open-telemetry/opentelemetry-js

packages/opentelemetry-types/LICENSE, packages/opentelemetry-types/README.md, packages/opentelemetry-types/package.json, packages/opentelemetry-types/src/index.ts, packages/opentelemetry-types/tsconfig.json
=> Add package: opentelemetry-types

packages/tsconfig.base.json
This PR updates the TypeScript compilation target to the latest possible ECMAScript standard to ensure that the JavaScript output is not altered by the compiler. This will ensure that the generated JavaScript code is the same as the TypeScript code minus types.
The reasoning behind this has been discussed previously, but the short version is to avoid being unable to test certain features because they have been transpiled to something else.
=> update target to ensure compilation does not alter generated code

.gitignore, CONTRIBUTING.md, package.json, packages/opentelemetry-types/package.json, packages/opentelemetry-types/src/trace/link.ts, packages/opentelemetry-types/src/trace/span.ts, packages/opentelemetry-types/src/trace/span_context.ts, packages/opentelemetry-types/tsconfig.json
This PR adds [typedoc](https://typedoc.org/) support for generating API documentation.
Example:
You can build the html docs from this branch as:
```
yarn install
yarn run docs
```
=> Add typedoc docs

packages/opentelemetry-types/src/context/propagation/Propagation.ts, packages/opentelemetry-types/src/context/propagation/Propagator.ts, packages/opentelemetry-types/src/index.ts
This PR adds `Propagator` interface.
=> Add Propagator interface

packages/opentelemetry-core/src/trace/TraceState.ts, packages/opentelemetry-core/test/tracestate.test.ts, packages/opentelemetry-types/src/trace/trace_state.ts
Specs: https://w3c.github.io/trace-context/#tracestate-field
Originates from https://github.com/open-telemetry/opentelemetry-js/pull/31#discussion_r294313856
> This would be easier to interact with by using an actual object than can then be serialized to a string by some formatter/encoder. Of course this could be done with a getter and a corresponding _traceState private property to hold the object, but then every vendor will have to replicate this logic.
=> Add TraceState

.circleci/config.yml, codecov.yml, packages/opentelemetry-core/package.json
~This is still work in progress (Draft), comments are welcome!~
Fixes #12 
Codecov link: 
https://codecov.io/gh/open-telemetry/opentelemetry-js/commit/3e91703b4528c55be22c2f001b2c957456b23ce9
=> 🤖Add codecov

packages/opentelemetry-types/src/trace/Event.ts
This PR is split up from https://github.com/open-telemetry/opentelemetry-js/pull/63 (Add LocalContext and Event interfaces). I think decision on `LocalContext` is still pending/ongoing and don't want to block `Event` interface.
=> Add Event interface

packages/opentelemetry-core/src/common/NoopLogger.ts, packages/opentelemetry-types/src/common/Logger.ts
This PR contains `Logger` interface and `NoopLogger`  implementation. 
I think we can extend this base interface to add `ConsoleLogger` (or somthing else) with config options like logLevel, strictMode(https://github.com/open-telemetry/opentelemetry-js/issues/92) etc.
=> Add Logger interface

packages/opentelemetry-core/src/context/propagation/BinaryTraceContext.ts, packages/opentelemetry-core/test/context/BinaryTraceContext.test.ts, packages/opentelemetry-core/test/context/propagation/binarytracecontext.test.ts, packages/opentelemetry-types/src/context/propagation/BinaryFormat.ts, packages/opentelemetry-types/src/index.ts
Specs: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/propagators-api.md#binary-format
=> Add BinaryFormat interface and implementation

packages/opentelemetry-core/package.json, packages/opentelemetry-scope-base/package.json
Fixes #97 
[Sample Generated Report](https://codecov.io/gh/markwolff/opentelemetry-js/tree/a8a1a3d1ad73f66c78dd179de0cd8871a9324e20) - only core has a non-empty report for now
5e7b244 removes the publishing of the report of `opentelemetry-scope-base` because it was an empty report. Codecov seems to error out every report if any are empty, so this should be added back in (with `-p ../../`) when there is code to be coverage checked.
Opting to use method proposed [here](https://github.com/open-telemetry/opentelemetry-js/issues/97#issuecomment-510788353) so that all script logic is located in each `package.json`, instead of scanning for (non-empty) coverage reports in circleCI yaml.
It might also be a good idea to separate generation and publishing of reports as in …
=> Codecov: Fix file path prefixes

packages/opentelemetry-core/src/internal/validators.ts, packages/opentelemetry-core/src/trace/TraceState.ts, packages/opentelemetry-core/test/internal/validators.test.ts, packages/opentelemetry-core/test/trace/tracestate.test.ts
Based on https://w3c.github.io/trace-context/#tracestate-field
limits:
**Key** is opaque string up to 256 characters printable. It MUST begin with a lowercase letter, and can only contain lowercase letters `a-z`, digits `0-9`, underscores `_`, dashes `-`, asterisks `*`, and forward slashes `/`.
**Value** is opaque string up to 256 characters printable ASCII RFC0020 characters (i.e., the range 0x20 to 0x7E) except comma `,` and `=`.
=> TraceState: Add validators

packages/opentelemetry-core/src/context/propagation/NoopBinaryFormat.ts, packages/opentelemetry-core/src/context/propagation/NoopHttpTextFormat.ts, packages/opentelemetry-core/src/index.ts, packages/opentelemetry-core/src/trace/NoopTracer.ts, packages/opentelemetry-core/src/trace/spancontext-utils.ts, packages/opentelemetry-core/test/trace/NoopTracer.test.ts, packages/opentelemetry-types/src/index.ts
Closes #86 
~This is still work in progress as some dependencies are not yet merged (especially ~`BinaryFormat` (merged now)~ and ~`HttpTraceContext`(merged now)~ PRs) but it should provide a starting point and avoid blocking other work. Comments are welcome.~
=> Add no-op implementations of Tracer API

packages/opentelemetry-core/README.md
=> Update readme for opentelemetry-core

packages/opentelemetry-types/src/trace/tracer.ts
Change return type "unknow" to HttpTextFormat for getHttpTextFormat
Change return type "unknow" to BinaryFormat for getBinaryFormat
Close #124 
Close #123 
=> Update tracer interface

packages/opentelemetry-core/src/index.ts
This is required in `basic-tracer` and `node-tracer` package.
=> Export NoopLogger and BinaryTraceContext

packages/opentelemetry-basic-tracer/README.md, packages/opentelemetry-core/README.md, packages/opentelemetry-node-tracer/README.md, packages/opentelemetry-types/README.md
=>  docs: add dependencies badge

packages/opentelemetry-core/src/trace/NoopTracer.ts, packages/opentelemetry-core/src/trace/TracerDelegate.ts, packages/opentelemetry-core/test/trace/NoopTracer.test.ts, packages/opentelemetry-core/test/trace/TracerDelegate.test.ts, packages/opentelemetry-core/test/trace/globaltracer-utils.test.ts
Fixes `@todo`
https://github.com/open-telemetry/opentelemetry-js/blob/a15ccb9d25193367dafb4dee9bac2bcbc20952fb/packages/opentelemetry-core/src/trace/NoopTracer.ts#L41
=> fix(core): tracer should never throw exception

packages/opentelemetry-core/src/trace/TracerDelegate.ts, packages/opentelemetry-core/test/trace/TracerDelegate.test.ts
One of the leftovers from https://github.com/open-telemetry/opentelemetry-js/pull/118#discussion_r308255830 (Private properties should always start with an underscore).
=> fix: minor fix

packages/opentelemetry-basic-tracer/src/BasicTracer.ts, packages/opentelemetry-basic-tracer/src/Span.ts, packages/opentelemetry-basic-tracer/test/BasicTracer.test.ts, packages/opentelemetry-basic-tracer/test/Span.test.ts, packages/opentelemetry-core/src/index.ts
=> refactor: move traceId generation in Tracer instead of Span

packages/opentelemetry-scope-async-hooks/src/AsyncHooksScopeManager.ts
=> chore: replace arguments per spread array to fix lint issue

packages/opentelemetry-basic-tracer/src/Span.ts, packages/opentelemetry-basic-tracer/src/export/ReadableSpan.ts, packages/opentelemetry-basic-tracer/test/Span.test.ts
Split from https://github.com/open-telemetry/opentelemetry-js/pull/149 with tests.
In SIG meeting, we have decided not to use `object.freeze` on `ReadableSpan` when constructing from `Span` object.
=> feat(sdk): add ReadableSpan

.nycrc, packages/opentelemetry-core/test/context/BinaryTraceContext.test.ts, packages/opentelemetry-core/test/context/HttpTraceContext.test.ts, packages/opentelemetry-core/test/trace/TracerDelegate.test.ts, packages/opentelemetry-core/test/trace/tracestate.test.ts, packages/opentelemetry-node-tracer/test/instrumentation/PluginLoader.test.ts, packages/opentelemetry-scope-async-hooks/test/AsyncHooksScopeManager.test.ts, packages/opentelemetry-scope-base/test/NoopScopeManager.test.ts
This PR contains,
1. Rename test files to match the actual file name/location.
2. Exclude karma and index files.
=> refactor: unit tests

packages/opentelemetry-basic-tracer/src/Span.ts, packages/opentelemetry-basic-tracer/src/export/ReadableSpan.ts, packages/opentelemetry-basic-tracer/test/Span.test.ts, packages/opentelemetry-types/src/index.ts
Closes https://github.com/open-telemetry/opentelemetry-js/issues/191
originates from https://github.com/open-telemetry/opentelemetry-js/pull/192/files#diff-08ba7b60ae6ed103fba2d7664cff8c92R88
=> fix(basic-tracer): add timestamp for event

packages/opentelemetry-basic-tracer/src/BasicTracer.ts, packages/opentelemetry-basic-tracer/test/BasicTracer.test.ts, packages/opentelemetry-core/src/trace/NoopTracer.ts, packages/opentelemetry-core/src/trace/TracerDelegate.ts, packages/opentelemetry-core/test/trace/NoopTracer.test.ts, packages/opentelemetry-core/test/trace/TracerDelegate.test.ts, packages/opentelemetry-node-tracer/test/NodeTracer.test.ts, packages/opentelemetry-types/src/trace/tracer.ts
As discussed in #161, we need the tracer to expose the `bind` method from the scope manager to allow plugins to use it.
see https://github.com/open-telemetry/opentelemetry-js/pull/161#discussion_r311027170
I've also updated `getCurrentSpan` on the basic tracer to actually return a `NoopSpan` when no span is set in the current scope (otherwise we will have some crash if the context is loss).
=> feat(tracer): expose bind method from scope manager

packages/opentelemetry-scope-async-hooks/src/AsyncHooksScopeManager.ts, packages/opentelemetry-scope-async-hooks/test/AsyncHooksScopeManager.test.ts
Making a new PR for event emitters support with async hooks.
Link to initial PR issue with the current implementation: https://github.com/open-telemetry/opentelemetry-js/pull/103#discussion_r303908136
I was saying that i would expect this behavior:
```
let ee = new EventEmitter()
ee = scopeManager.bind(ee, { test: 1 })
ee.on('test', () => {
// i would expect that scopeManager.active() would be { test: 1 } here.
})
```
@rochdev is the implementation using the scope at the `.on` moment would have the same behavior ? I'm not sure.
=> feat(ah-scope): add scope propagation for event emitters

packages/opentelemetry-basic-tracer/src/SpanProcessor.ts, packages/opentelemetry-basic-tracer/src/index.ts
Idea: The `SpanProcessor` interface allows users to build frameworks like exporter/z-pages/etc. The `SpanProcessor` interface should allow intercepting `Span`s immediately after start and immediately after end.
OpenCensus contains the same kind of interface: 
https://github.com/census-instrumentation/opencensus-node/blob/056523d83d21449e3bd888fec624d33c129951cc/packages/opencensus-core/src/trace/model/types.ts#L261-L266
This exist in [java](https://github.com/open-telemetry/opentelemetry-java/blob/cd06daa70eca1223c1c78a1ed7daee620d311dc5/sdk/src/main/java/io/opentelemetry/sdk/trace/SpanProcessor.java) but aren't yet included in the [spec](https://github.com/open-telemetry/opentelemetry-specification/issues/54).
=> feat: add span processor

.github/CODEOWNERS
=> chore: tag more reviewers

packages/opentelemetry-core/src/context/propagation/B3Format.ts, packages/opentelemetry-core/src/index.ts, packages/opentelemetry-core/test/context/B3Format.test.ts
- Fixes #204 
- This PR adds B3 propagator that converts SpanContext to/from **x-b3-*** Headers. 
- Based on https://github.com/openzipkin/b3-propagation
=> feat: Add B3format propagator

packages/opentelemetry-node-tracer/src/NodeTracer.ts, packages/opentelemetry-node-tracer/test/NodeTracer.test.ts
=> fix: enable async hooks manager in node tracer close #226

packages/opentelemetry-core/src/trace/instrumentation/BasePlugin.ts, packages/opentelemetry-node-tracer/src/instrumentation/PluginLoader.ts, packages/opentelemetry-node-tracer/src/instrumentation/utils.ts, packages/opentelemetry-node-tracer/test/instrumentation/PluginLoader.test.ts, packages/opentelemetry-node-tracer/test/instrumentation/node_modules/@opentelemetry/plugin-notsupported-module/index.js, packages/opentelemetry-node-tracer/test/instrumentation/node_modules/@opentelemetry/plugin-notsupported-module/package.json, packages/opentelemetry-node-tracer/test/instrumentation/node_modules/@opentelemetry/plugin-notsupported-module/simple-module.js, packages/opentelemetry-node-tracer/test/instrumentation/node_modules/@opentelemetry/plugin-supported-module/index.js, packages/opentelemetry-node-tracer/test/instrumentation/node_modules/@opentelemetry/plugin-supported-module/package.json, packages/opentelemetry-node-tracer/test/instrumentation/node_modules/@opentelemetry/plugin-supported-module/simple-module.js, packages/opentelemetry-node-tracer/test/instrumentation/node_modules/notsupported-module/index.js, packages/opentelemetry-node-tracer/test/instrumentation/node_modules/notsupported-module/package.json, packages/opentelemetry-node-tracer/test/instrumentation/node_modules/supported-module/index.js, packages/opentelemetry-node-tracer/test/instrumentation/node_modules/supported-module/package.json, packages/opentelemetry-node-tracer/test/instrumentation/utils.test.ts, packages/opentelemetry-types/src/trace/instrumentation/Plugin.ts
It's backward compatible. supportedVersion is optional in plugins. If not defined, all versions are supported. See related tests.
Closes #132
=> feat(plugin): add supportedVersions property

packages/opentelemetry-basic-tracer/package.json, packages/opentelemetry-basic-tracer/src/BasicTracer.ts, packages/opentelemetry-basic-tracer/src/config.ts, packages/opentelemetry-basic-tracer/src/types.ts, packages/opentelemetry-basic-tracer/src/utility.ts, packages/opentelemetry-basic-tracer/test/BasicTracer.test.ts
- Add functionality to hold global trace parameters (like `Attributes`, `Link`s, `Event`s etc.). Limits will be enforced on each span in order to prevent an unbounded memory increase for long-running spans.
- Limits are taken from OpenCensus specs: https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/TraceConfig.md#limits
- These are the default values (**recommended by the SDK**), users/vendors are allowed to override the globals per-span values.
- I planned to enforce these limits on per-span in next PR.
=> feat: add TraceParams config

packages/opentelemetry-basic-tracer/src/BasicTracer.ts, packages/opentelemetry-basic-tracer/src/MultiSpanProcessor.ts, packages/opentelemetry-basic-tracer/src/NoopSpanProcessor.ts, packages/opentelemetry-basic-tracer/src/Span.ts, packages/opentelemetry-basic-tracer/src/export/InMemorySpanExporter.ts, packages/opentelemetry-basic-tracer/test/MultiSpanProcessor.test.ts, packages/opentelemetry-basic-tracer/test/export/InMemorySpanExporter.test.ts
- This PR is a follow up of #218 and based on the specs https://github.com/open-telemetry/opentelemetry-specification/pull/205
- This PR introduces the `InMemorySpanExporter`, it can be used for testing purposes, especially in the plugins. It stores the exported spans in a list in memory. 
- SDK Usage (example):
```
const memoryExporter = new InMemorySpanExporter();
const tracer = new BasicTracer({
scopeManager: new NoopScopeManager(),
});
// register simple processor with InMemoryExporter
tracer.addSpanProcessor(new SimpleSpanProcessor(memoryExporter));
// register batch processor with Jaeger Exporter
// tracer.addSpanProcessor(new BatchSpanProcessor(jaegerExporter));
```
- I will open another PR to add Batching processor (BatchSpanProcessor).
=> feat: add InMemorySpanExporter, MultiSpanProcessor

packages/opentelemetry-exporter-jaeger/package.json, packages/opentelemetry-exporter-zipkin/package.json, packages/opentelemetry-plugin-grpc/package.json, packages/opentelemetry-plugin-http/package.json, packages/opentelemetry-plugin-http2/package.json, packages/opentelemetry-plugin-https/package.json, packages/opentelemetry-plugin-mongodb/package.json, packages/opentelemetry-plugin-redis/package.json
closes #242
- Remove posttest script in package.json
=> chore: remove script posttest

packages/opentelemetry-core/src/trace/instrumentation/BasePlugin.ts, packages/opentelemetry-node-tracer/src/instrumentation/PluginLoader.ts, packages/opentelemetry-node-tracer/test/instrumentation/PluginLoader.test.ts, packages/opentelemetry-types/src/trace/instrumentation/Plugin.ts
- Resolves #214
- This is based on **OPTION 1** mentioned in the #214.
- Per SIG,  **OPTION 1** is more superior because it allows individual config. 
- Note (per this implementation): only the individual config will get passed to the respective plugin.
=> feat: add plugin config options

packages/opentelemetry-plugin-http2/package.json, packages/opentelemetry-plugin-https/package.json, packages/opentelemetry-plugin-mongodb/package.json, packages/opentelemetry-plugin-redis/package.json
- This is to avoid publishing non-ready (work-in-progress) packages (`https`, `http2`, `redis`, `mongodb`).
- Once packages/instrumentations are ready will remove this flag.
=> chore: add 'private: true' for non ready packages

README.md
Quick PR to add target release dates to the README following [@tedsuo's comment](https://gitter.im/open-telemetry/community?at=5d6fe5da08973a793cad5dae) on gitter.
> My request: We’d like to start communicating more clearly about the state of each implementation. Please update the README to have section at the top with the following:
Current state of the project, with a focus on the items listed in the alpha description
Installation and super basic quick start guide.
=> chore: add release schedule

packages/opentelemetry-node-tracer/test/NodeTracer.test.ts, packages/opentelemetry-plugin-grpc/test/grpc.test.ts, packages/opentelemetry-plugin-http/package.json, packages/opentelemetry-plugin-http/test/functionals/http-disable.test.ts, packages/opentelemetry-plugin-http/test/functionals/http-enable.test.ts, packages/opentelemetry-plugin-http/test/functionals/http-package.test.ts, packages/opentelemetry-plugin-http/test/integrations/http-enable.test.ts
It was still failling simply because the scopeManager wasn't still enabled in the test code, so i switched to use the one created by the `NodeTracer` which is automatically enabled. Note that we shouldn't create async hooks scope manager to test default behavior.
close #226
=> tests: use node-tracer scope manager instead of creating one #226

examples/node-basic/index.js
- With Jaeger Exporter, users can easily visualize the spans data on UI.
=> feat: update example with Jaeger exporter

packages/opentelemetry-node-tracer/src/NodeTracer.ts, packages/opentelemetry-node-tracer/src/config.ts, packages/opentelemetry-node-tracer/test/NodeTracer.test.ts
- Closes #199 
- With `Node-Tracer` will load all the default supported plugins.
=> feat(Node-Tracer): initialize plugin loader

packages/opentelemetry-exporter-jaeger/src/jaeger.ts
- Added an optimistic flush before shutting down the Jaeger exporter to ensure all the spans are flushed properly. I faced this issue when running the [node basic tracer](https://github.com/open-telemetry/opentelemetry-js/blob/master/examples/node-basic/index.js) example with Jaeger exporter.
=> feat(exporter-jaeger): flush data before shutdown

packages/opentelemetry-basic-tracer/src/BasicTracer.ts, packages/opentelemetry-basic-tracer/test/BasicTracer.test.ts, packages/opentelemetry-core/src/trace/NoopTracer.ts, packages/opentelemetry-core/src/trace/TracerDelegate.ts, packages/opentelemetry-core/test/trace/NoopTracer.test.ts, packages/opentelemetry-core/test/trace/TracerDelegate.test.ts, packages/opentelemetry-core/test/trace/globaltracer-utils.test.ts, packages/opentelemetry-node-sdk/test/NodeTracer.test.ts, packages/opentelemetry-plugin-http/test/functionals/http-disable.test.ts, packages/opentelemetry-types/src/trace/tracer.ts
Remove all references to SpanDat per the specification update in https://github.com/open-telemetry/opentelemetry-specification/pull/215
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-telemetry/opentelemetry-js/286)
=> chore: remove all references to SpanData

packages/opentelemetry-plugin-http/src/http.ts, packages/opentelemetry-plugin-http/src/types.ts, packages/opentelemetry-plugin-http/src/utils.ts, packages/opentelemetry-plugin-http/test/functionals/http-enable.test.ts, packages/opentelemetry-plugin-http/test/functionals/utils.test.ts, packages/opentelemetry-plugin-http/test/integrations/http-enable.test.ts, packages/opentelemetry-plugin-http/test/utils/httpRequest.ts
Ensure exceptions are properly handled. 
- closes #222
- refactor(test): remove unnecessary code
- add tests
=> fix(http-plugin): ensure exceptions are handled

packages/opentelemetry-plugin-http/src/http.ts, packages/opentelemetry-plugin-http/src/utils.ts, packages/opentelemetry-plugin-http/test/functionals/utils.test.ts
- closes #316
- rename getUrlFromIncomingRequest to getAbsoluteUrl (since we use it for outgoing and incoming requests)
- improve formatting
- add test
=> fix(plugin-http): improve formatting for url attribute

packages/opentelemetry-plugin-http/package.json
`node-sdk` is only used in tests and should be in `devDependencies`
/cc @OlivierAlbertini
=> fix(http-plugin): move node-sdk to dev deps

packages/opentelemetry-basic-tracer/test/export/BatchSpanProcessor.test.ts
- Resolves #350.
- Increasing timeout number, this should give enough time to report spans collected by `BatchSpanProcessor`.
=> fix: increase timeout for BatchSpanProcessor test

packages/opentelemetry-exporter-zipkin/src/zipkin.ts
- Remove out-of-date `@todo` tag, `BatchSpanProcessor` is responsible for doing the span batching.
=> chore: remove todo tag

examples/grpc/client.js, examples/grpc/setup.js
=> fix(example): add flushInterval to report spans to Jaeger exporter

README.md, packages/opentelemetry-node-sdk/README.md, packages/opentelemetry-node-sdk/src/config.ts
- With this, `HTTPS` plugin will be loaded automatically when you use `node-sdk`.
=> chore: add HTTPS to default instrumented plugins list

.github/ISSUE_TEMPLATE/plugin_request.md
=> chore: add plugin request issue template

packages/opentelemetry-tracing/src/Span.ts
- Calculate `span`'s duration ONLY at the end of the span instead of each `get duration()` call.
- This will also set `_duration` immediately. See below snap, `_duration` is still pointing to invalid value even after a `span` is ended.
=> refactor: cal duration once instead of each get duration call

packages/opentelemetry-base/package.json, packages/opentelemetry-core/package.json, packages/opentelemetry-core/test/trace/fixtures/test-package/package.json, packages/opentelemetry-exporter-jaeger/package.json, packages/opentelemetry-exporter-prometheus/package.json, packages/opentelemetry-exporter-zipkin/package.json, packages/opentelemetry-metrics/package.json, packages/opentelemetry-node/package.json, packages/opentelemetry-plugin-grpc/package.json, packages/opentelemetry-plugin-http/package.json, packages/opentelemetry-plugin-http2/package.json, packages/opentelemetry-plugin-https/package.json, packages/opentelemetry-plugin-mongodb/package.json, packages/opentelemetry-plugin-postgres/package.json, packages/opentelemetry-plugin-redis/package.json, packages/opentelemetry-scope-async-hooks/package.json, packages/opentelemetry-scope-base/package.json, packages/opentelemetry-shim-opentracing/package.json, packages/opentelemetry-tracing/package.json, packages/opentelemetry-types/package.json, packages/opentelemetry-web/package.json
- Fixes #426 
- The [package.json's "main"](https://github.com/open-telemetry/opentelemetry-js/blob/master/packages/opentelemetry-types/package.json#L5) key points to "`build/src/index.js`", which means we should compile the packages before publishing to `npm`. The `prepare` script will run BEFORE the package is packed and published.
- Bump the version to `0.1.1`, we can cut a new release.
=> chore: add prepare script and bump the version

.gitignore, CONTRIBUTING.md, RELEASING.md, lerna.json, package.json
- closes #372
- add docs related to lerna-changelog
- add `lerna-changelog` package
- modify lerna.json
=> chore(lerna): add lerna-changelog

packages/opentelemetry-metrics/src/Handle.ts, packages/opentelemetry-metrics/src/Meter.ts, packages/opentelemetry-metrics/src/Metric.ts, packages/opentelemetry-metrics/src/Utils.ts, packages/opentelemetry-metrics/src/types.ts, packages/opentelemetry-metrics/test/Meter.test.ts, packages/opentelemetry-types/src/metrics/Meter.ts, packages/opentelemetry-types/src/metrics/Metric.ts
- Updates #402 
- First take on metrics SDK. In order to keep short PR, only `Counter` metric support is added.
- The monotonic concept is based on https://github.com/open-telemetry/opentelemetry-specification/pull/250/files.
i.e. `Counter`s are defined as monotonic by default, meaning that positive values are expected and `Gauge`s are defined as non-monotonic by default, meaning that any value (positive or negative) is allowed.
- Record call is still missing, will do it in the follow-up PR.
**Update 1**: Added support for `Gauge` Metric.
**Update 2**: Added `MeterConfig` with `Logger` option.
=> feat: implement metrics sdk

examples/grpc_dynamic_codegen/README.md, examples/grpc_dynamic_codegen/capitalize_client.js, examples/grpc_dynamic_codegen/capitalize_server.js, examples/grpc_dynamic_codegen/package.json, examples/grpc_dynamic_codegen/protos/defs.proto, examples/grpc_dynamic_codegen/setup.js
- This is the dynamic code generation variant of the gRPC examples. Code in these examples is generated at runtime using Protobuf.js.
- Dependency on #384
=> gRPC example using proto-loader

packages/opentelemetry-tracing/test/export/BatchSpanProcessor.test.ts
- Resolves #350
- This has been verified locally by running regression test, with and w/o the change.
=> fix: batchSpanProcessor test failing intermittently

packages/opentelemetry-core/src/trace/NoopSpan.ts, packages/opentelemetry-core/test/trace/NoopSpan.test.ts, packages/opentelemetry-core/test/trace/NoopTracer.test.ts, packages/opentelemetry-node/test/NodeTracer.test.ts, packages/opentelemetry-tracing/src/BasicTracer.ts, packages/opentelemetry-tracing/src/Span.ts, packages/opentelemetry-tracing/src/SpanProcessor.ts, packages/opentelemetry-tracing/test/BasicTracer.test.ts, packages/opentelemetry-tracing/test/Span.test.ts, packages/opentelemetry-tracing/test/export/BatchSpanProcessor.test.ts, packages/opentelemetry-types/src/trace/SpanOptions.ts, packages/opentelemetry-types/src/trace/span.ts
- Closes #448 
- Rename span flag IsRecordingEvents -> IsRecording
=> fix(span): rename span recording flag

packages/opentelemetry-shim-opentracing/src/shim.ts, packages/opentelemetry-tracing/src/BasicTracer.ts, packages/opentelemetry-tracing/src/Span.ts, packages/opentelemetry-tracing/test/Span.test.ts, packages/opentelemetry-types/src/trace/SpanOptions.ts, packages/opentelemetry-types/src/trace/span.ts
- Resolves #446
- Links will be recorded only during the start `Span` operation, because:
- Link's `SampledFlag` can be used in the sampling decision.
- OpenTracing supports adding references only during the `Span` creation.
- OpenCensus supports adding links at any moment, but this was mostly used to record child Links which are not supported in OpenTelemetry.
- Allowing links to be recorded after the sampling decision is made will cause samplers to not work correctly and unexpected behaviors for sampling.
=> fix: allow recording links only at Span creation time

packages/opentelemetry-core/src/context/propagation/B3Format.ts, packages/opentelemetry-core/src/context/propagation/BinaryTraceContext.ts, packages/opentelemetry-core/src/context/propagation/HttpTraceContext.ts, packages/opentelemetry-core/test/context/B3Format.test.ts, packages/opentelemetry-core/test/context/BinaryTraceContext.test.ts, packages/opentelemetry-core/test/context/HttpTraceContext.test.ts, packages/opentelemetry-types/src/trace/span_context.ts
- Closes #450 
- Add optional `isRemote` to `SpanContext`
- Set it to true when extracting a propagated SpanContext
=> feat: add IsRemote field to SpanContext, set by propagators

.github/CODEOWNERS, README.md
- Based on open-telemetry/community#233
=> chore: move members list out of community repo

packages/opentelemetry-types/src/distributed_context/EntryValue.ts, packages/opentelemetry-types/src/metrics/Handle.ts, packages/opentelemetry-types/src/trace/SpanOptions.ts, packages/opentelemetry-types/src/trace/link.ts, packages/opentelemetry-types/src/trace/span_context.ts, packages/opentelemetry-types/src/trace/tracer.ts
- Add missing JSDoc comments.
- Add known default values.
=> chore: update API docs

packages/opentelemetry-metrics/src/Meter.ts, packages/opentelemetry-metrics/test/Meter.test.ts
- Fixes #465 
- Ensure metric names are valid according to the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-metrics-user.md#metric-names)
- Invalid metric names return noop implementations (per SIG meeting)
=> feat: validate metric names

packages/opentelemetry-core/package.json
#471 
- add missing semver dependency
=> fix(core): add missing semver dependency

packages/opentelemetry-metrics/src/Handle.ts, packages/opentelemetry-metrics/src/Meter.ts, packages/opentelemetry-metrics/src/Metric.ts, packages/opentelemetry-metrics/src/export/types.ts, packages/opentelemetry-metrics/src/index.ts, packages/opentelemetry-metrics/src/types.ts, packages/opentelemetry-metrics/test/Meter.test.ts, packages/opentelemetry-types/src/metrics/Metric.ts
- Updates #402
- Continuation of Metrics SDK #415.
- Added methods (`registerMetric` and `getMetrics`)  to collect recorded values in the format of [ReadableMetric](https://github.com/open-telemetry/opentelemetry-js/blob/master/packages/opentelemetry-metrics/src/export/types.ts#L28), which can be used by metric exporters to transform and send to the backend.
- Pending stuff for next PRs:
- Add option to register metric exporter.
- Send data to registered exporter via `meter.getMetrics()`
- Implement `MeasureHandle`.
TODO:
- ~Decide which `MetricDescriptorType` to assign in case of Gauge (two options are `MetricDescriptorType.GAUGE_INT64` and `MetricDescriptorType.GAUGE_DOUBLE`) and in case of counter (two options are `MetricDescriptorType.COUNTER_INT64` and …
=> feat(metrics): add registerMetric and getMetrics

package.json, packages/opentelemetry-base/package.json, packages/opentelemetry-core/package.json, packages/opentelemetry-exporter-jaeger/package.json, packages/opentelemetry-exporter-prometheus/package.json, packages/opentelemetry-exporter-zipkin/package.json, packages/opentelemetry-metrics/package.json, packages/opentelemetry-node/package.json, packages/opentelemetry-plugin-dns/package.json, packages/opentelemetry-plugin-document-load/package.json, packages/opentelemetry-plugin-grpc/package.json, packages/opentelemetry-plugin-http/package.json, packages/opentelemetry-plugin-http2/package.json, packages/opentelemetry-plugin-https/package.json, packages/opentelemetry-plugin-mongodb/package.json, packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/package.json, packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/package.json, packages/opentelemetry-plugin-redis/package.json, packages/opentelemetry-scope-async-hooks/package.json, packages/opentelemetry-scope-base/package.json, packages/opentelemetry-shim-opentracing/package.json, packages/opentelemetry-tracing/package.json, packages/opentelemetry-types/package.json, packages/opentelemetry-web/package.json
- Attempt one to fix the build.
=> chore: upgrade typescript to 3.6.4

.gitignore, package.json, packages/opentelemetry-base/package.json, packages/opentelemetry-core/package.json, packages/opentelemetry-exporter-jaeger/package.json, packages/opentelemetry-exporter-prometheus/package.json, packages/opentelemetry-exporter-zipkin/package.json, packages/opentelemetry-metrics/package.json, packages/opentelemetry-node/package.json, packages/opentelemetry-plugin-dns/package.json, packages/opentelemetry-plugin-dns/test/integrations/dnspromise-lookup.test.ts, packages/opentelemetry-plugin-document-load/package.json, packages/opentelemetry-plugin-grpc/package.json, packages/opentelemetry-plugin-grpc/src/grpc.ts, packages/opentelemetry-plugin-http/package.json, packages/opentelemetry-plugin-http2/package.json, packages/opentelemetry-plugin-https/package.json, packages/opentelemetry-plugin-mongodb/package.json, packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/package.json, packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/package.json, packages/opentelemetry-plugin-redis/package.json, packages/opentelemetry-scope-async-hooks/package.json, packages/opentelemetry-scope-base/package.json, packages/opentelemetry-shim-opentracing/package.json, packages/opentelemetry-tracing/package.json, packages/opentelemetry-types/package.json, packages/opentelemetry-web/package.json
- Fix build failures on latest typescript
- Bump to latest typescript
1. Update typescript version to `^3.7.2` in all `package.json` files
2. Remove unreachable code from dns plugin test
3. Remove always-true if-statement from grpc plugin
=> chore: bump typescript version to ^3.7.2

.github/CODEOWNERS, README.md
- @obecny has showed strong interest and commitment in the OpenTelemetry Web SDKs and Plugins. Currently, he is the main contributor for Web SDKs. We really appreciate his work! Thank you for all the contributions.
- Notable PRs #334, #461, #477, #433, #455, #447, #435, #438.
- Involved in SIG meetings.
=> Propose to add @obecny as the CODEOWNERS.

packages/opentelemetry-types/package.json
- Updates #481 
- Remove redundant `compile` and `gts check` inside test script.
=> chore: remove test script from types package

.circleci/config.yml, packages/opentelemetry-plugin-document-load/src/documentLoad.ts, packages/opentelemetry-plugin-grpc/src/grpc.ts, packages/opentelemetry-plugin-http/src/http.ts, packages/opentelemetry-plugin-http/src/types.ts, packages/opentelemetry-plugin-http/src/utils.ts, packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/src/pg.ts
- #498 
This installs only the bare minimum required to run `yarn run check` and `yarn run docs`. The reason for the odd `lerna exec` symlinking is because `gts` looks for rules packages in the local node modules, and does not look in the global directory.
=> ci: install minimal lint & doc deps

packages/opentelemetry-types/README.md, packages/opentelemetry-types/tsconfig.json
- Updates #440, based on https://github.com/open-telemetry/opentelemetry-js/issues/440#issuecomment-546466773
=> chore: minor name change

packages/opentelemetry-metrics/package.json, packages/opentelemetry-metrics/src/export/ConsoleMetricExporter.ts, packages/opentelemetry-metrics/src/index.ts, packages/opentelemetry-metrics/test/export/ConsoleMetricExporter.test.ts
=> feat: add ConsoleMetricExporter

packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/package.json
- Move codecov report inside the `packages` folder. Earlier: https://codecov.io/gh/open-telemetry/opentelemetry-js/tree/39732fabe85b1bca064b91c3d84a101998e71d1b, Now: https://codecov.io/gh/open-telemetry/opentelemetry-js/pull/520/tree/packages
=> chore: fix codecov path

.circleci/config.yml
- Updates #481
- We can save ~25secs during each build
- Compile step is already part of `prepare` script, which runs on `yarn install`.
=> chore(circleci): remove duplicate compile step

packages/opentelemetry-exporter-prometheus/README.md
- Add USAGE instructions.
/cc @dyladan
=> chore: update prometheus exporter readme with usage and links

packages/opentelemetry-plugin-http/package.json, packages/opentelemetry-plugin-http/test/utils/assertSpan.ts, packages/opentelemetry-plugin-https/package.json, packages/opentelemetry-plugin-https/test/utils/assertSpan.ts
fixes https://github.com/open-telemetry/opentelemetry-js/issues/541
Adapt http/https plugin to @types/node 12.12.9
Refs: https://github.com/open-telemetry/opentelemetry-js/pull/545
=> fix(plugin-http): adapt to current @types/node

examples/basic-tracer-node/README.md, examples/basic-tracer-node/multi_exporter.js, examples/basic-tracer-node/package.json
=> examples(tracing): add multi exporter example

packages/opentelemetry-plugin-redis/README.md
OptenTelemetry -> OpenTelemetry
=> chore: fix minor typo

packages/opentelemetry-metrics/README.md
=> chore: update metrics README

packages/opentelemetry-shim-opentracing/package.json
- Add missing `main` to `package.json`
- Missing `main` in `package.json` makes developer unable to do `require("@opentelemetry/shim-opentracing");`
=> fix: add missing `main` in package.json

packages/opentelemetry-plugin-http/src/utils.ts, packages/opentelemetry-plugin-http/test/utils/assertSpan.ts
closes #579
- add assertion in tests
- fix copy/paste error
=> fix(plugin-http): http.url attribute

doc/exporter-guide.md
- OpenTelemetry exporters can be contributed by anyone, this guide will provide a means for developers/vendors/users to create their own.
=> Add exporter guide

.github/ISSUE_TEMPLATE/discussion.md
- Issues like #591 create feature requests where they would prefer to open discussions
=> chore: add discussion issue type

packages/opentelemetry-plugin-http/src/http.ts, packages/opentelemetry-plugin-http/src/utils.ts, packages/opentelemetry-plugin-http/test/functionals/http-enable.test.ts, packages/opentelemetry-plugin-http/test/functionals/utils.test.ts, packages/opentelemetry-plugin-http/test/integrations/http-enable.test.ts, packages/opentelemetry-plugin-http/test/utils/httpRequest.ts
fixes https://github.com/open-telemetry/opentelemetry-js/issues/583
Add parsing and conversion of WHATWG URL objects for client http
requests to ensure semantics of HTTP request are not modifed and
tracestate header is correctly added.
=> fix(plugin-http): correct handling of WHATWG urls

packages/opentelemetry-exporter-jaeger/src/transform.ts, packages/opentelemetry-exporter-jaeger/test/transform.test.ts
- Fixes #594 
- Jaeger exporter doesn't have direct support for `kind` attribute, this PR will set `SpanKind` as `Tags` similar to `Status` field.
=> fix(jaeger-exporter): set Span Kind as Tags

packages/opentelemetry-plugin-http/package.json, packages/opentelemetry-plugin-http/test/functionals/http-enable.test.ts, packages/opentelemetry-plugin-http/test/functionals/http-package.test.ts, packages/opentelemetry-plugin-http/test/integrations/http-enable.test.ts, packages/opentelemetry-plugin-https/README.md, packages/opentelemetry-plugin-https/package.json, packages/opentelemetry-plugin-https/src/https.ts, packages/opentelemetry-plugin-https/test/functionals/https-disable.test.ts, packages/opentelemetry-plugin-https/test/functionals/https-enable.test.ts, packages/opentelemetry-plugin-https/test/functionals/https-package.test.ts, packages/opentelemetry-plugin-https/test/integrations/https-enable.test.ts, packages/opentelemetry-plugin-https/test/utils/assertSpan.ts, packages/opentelemetry-plugin-https/test/utils/httpsRequest.ts
fixes https://github.com/open-telemetry/opentelemetry-js/issues/590
Sync http and https tests.
I have omitted `should have 1 ended span when request doesn't listening response` as it fails for https. Not sure here but I think it passes for http only because there is some service running on port 80 on CI servers.
=> chore(plugin-https): sync https tests with http

packages/opentelemetry-plugin-mongodb-core/package.json, packages/opentelemetry-plugin-mongodb-core/src/mongodb.ts, packages/opentelemetry-scope-async-hooks/src/AsyncHooksScopeManager.ts, packages/opentelemetry-scope-async-hooks/test/AsyncHooksScopeManager.test.ts, packages/opentelemetry-scope-base/src/NoopScopeManager.ts, packages/opentelemetry-scope-base/test/NoopScopeManager.test.ts
- Add missing `codecov` script
- Bump up `@opentelemetry/node` => `^0.2.0`
- Bump up `@opentelemetry/tracing` => `^0.2.0`
=> chore(plugin-mongodb-core): add missing codecov script

packages/opentelemetry-node/src/config.ts, packages/opentelemetry-plugin-dns/README.md
- closes #612
- remove dns plugin from the default list
- add doc for Zipkin until with find a solution that let's us ignore http call without specifying in plugin option
=> fix(plugin-dns): remove from default plugin list

examples/basic-tracer-node/multi_exporter.js, examples/dns/setup.js, examples/grpc/setup.js, examples/grpc_dynamic_codegen/setup.js, examples/http/setup.js, examples/https/setup.js, examples/mysql/setup.js, examples/redis/setup.js, packages/opentelemetry-exporter-jaeger/src/jaeger.ts, packages/opentelemetry-exporter-jaeger/src/types.ts, packages/opentelemetry-exporter-jaeger/test/jaeger.test.ts, packages/opentelemetry-tracing/src/export/BatchSpanProcessor.ts
- #608 
- Remove the interval that periodically flushes the jaeger exporter. The exporter already flushes on every export and should depend on the span processor for batching
=> Jaeger no flush interval

packages/opentelemetry-plugin-grpc/src/grpc.ts, packages/opentelemetry-plugin-grpc/test/grpc.test.ts
- Fixes #630 and #384 
- Related to https://github.com/open-telemetry/opentelemetry-js/pull/400
- The [client constructor in the grpc module](https://github.com/grpc/grpc-node/blob/9d36d8d5c76adbd6f4159e64e41eab2a9f16b6da/packages/grpc-js/src/make-client.ts#L140-L143) creates a method alias using the **originalName** (if present). We didn't patch/trace these methods before, so this PR resolves this problem.
- Original issue https://github.com/grpc/grpc/issues/12135
- I have verified the solution with [grpc example with dynamic codegen](https://github.com/open-telemetry/opentelemetry-js/tree/master/examples/grpc_dynamic_codegen) and been confirmed to be working.
/cc @markwolff
=> fix(grpc): patch original client methods

packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/package.json
- Some of the `package.json` dependencies from plugin-pg module are not necessary for running this module (only for development).
/cc @markwolff
=> chore(plugin-pg): move dev dependencies out of `dependencies` in package.json

packages/opentelemetry-node/src/config.ts, packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/package.json
- add pg-pool to default list of instrumented plugins
/cc @xiao-lix
=> feat: add pg-pool to default list of instrumented plugins

packages/opentelemetry-base/package.json, packages/opentelemetry-core/package.json, packages/opentelemetry-exporter-collector/package.json, packages/opentelemetry-exporter-jaeger/package.json, packages/opentelemetry-exporter-prometheus/package.json, packages/opentelemetry-exporter-zipkin/package.json, packages/opentelemetry-metrics/package.json, packages/opentelemetry-node/package.json, packages/opentelemetry-plugin-dns/package.json, packages/opentelemetry-plugin-document-load/package.json, packages/opentelemetry-plugin-grpc/package.json, packages/opentelemetry-plugin-http/package.json, packages/opentelemetry-plugin-https/package.json, packages/opentelemetry-plugin-mongodb/package.json, packages/opentelemetry-plugin-mysql/package.json, packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/package.json, packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/package.json, packages/opentelemetry-plugin-redis/package.json, packages/opentelemetry-plugin-xml-http-request/package.json, packages/opentelemetry-scope-async-hooks/package.json, packages/opentelemetry-scope-base/package.json, packages/opentelemetry-scope-zone-peer-dep/package.json, packages/opentelemetry-scope-zone/package.json, packages/opentelemetry-shim-opentracing/package.json, packages/opentelemetry-test-utils/package.json, packages/opentelemetry-tracing/package.json, packages/opentelemetry-web/package.json
- `ts-node` old versions is no longer work on Node V8, because `yn` is enforcing Node V10 compatibility. Caused by: https://github.com/sindresorhus/yn/pull/266
=> chore: upgrade ts-node version to ^8.6.2

packages/opentelemetry-types/package.json
- https://david-dm.org/ services (both website and badges) are generally fine, but it occasionally suffers. It causes our CircleCI builds to fail, this PR will skip checking the david urls from docs-test job.
=> chore: skip david-dm.org url from docs-test

packages/opentelemetry-plugin-dns/package.json
dns plugin was missing a dev dependency. This hasn't caused a problem before because it is in the root `node_modules`.
=> chore: add missing semver type dependency

packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/test/pg-pool.test.ts
- Solves an issue where the build is broken due to a typing update for pg-pool
=> chore: fix compilation

README.md
=> docs: typo in Ville de Montréal

packages/opentelemetry-plugin-ioredis/src/ioredis.ts
=> fix: return module exports from ioredis

README.md
=> fix: package links in README

CHANGELOG.md
=> Post Release: update CHANGELOG.md

README.md
- The line above this says the same thing.
/cc @dyladan
=> chore: remove redundant statement

.circleci/config.yml
As discussed with @mayurkale22 this change makes it so that docs will publish on any new version.
Previously, it ignored patch versions. Because we are changing so quickly, we are not following typical semver patterns and it is important that the docs always represent the latest version.
=> chore: publish docs on all tags

packages/opentelemetry-plugin-http/README.md, packages/opentelemetry-plugin-http/src/types.ts, packages/opentelemetry-plugin-http/src/utils.ts, packages/opentelemetry-plugin-http/test/functionals/http-enable.test.ts, packages/opentelemetry-plugin-http/test/functionals/utils.test.ts
- closes #642 
- Synchronise HTTP status code with `CanonicalCode` according to specs.
I try to use the benchmark system we have, see my sample code here : https://gist.github.com/OlivierAlbertini/9505254b713b9db5f60168ed3fa4e437
But the result is a bit random (on my macbook pro 2016). I would like to know which one is faster. Any insight ?
If we want to share this code with the web, I think we should discuss it and resolve it in a separate PR.
=> feat(plugin-http): sync. specs for statuscode

packages/opentelemetry-plugin-grpc/README.md, packages/opentelemetry-plugin-http/README.md, packages/opentelemetry-plugin-https/README.md, packages/opentelemetry-plugin-ioredis/README.md, packages/opentelemetry-plugin-mongodb/README.md, packages/opentelemetry-plugin-mysql/README.md, packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/README.md, packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/README.md, packages/opentelemetry-plugin-redis/README.md
- Closes #539 
- Add usage instruction for pg-pool plugin.
=> chore: add instruction for pg-pool plugin

examples/postgres/package.json, examples/stackdriver-trace/index.js
- Based on `0.3.3` release.
/cc @dyladan
=> Update Stackdriver exporter example

scripts/version-update.js
On windows (with git config core.autocrlf=true as recommended for cross os projects)
the version-update script created unix files (LF only). This caused that git sees a
lot modified files after bootstrap.
Use `os.EOL` to ensure line endings match the os used.
=> chore: use os specific line endings for version updates

.circleci/config.yml, CONTRIBUTING.md, doc/development-guide.md, lerna.json, package.json, packages/opentelemetry-api/package.json, packages/opentelemetry-base/package.json, packages/opentelemetry-core/package.json, packages/opentelemetry-exporter-collector/package.json, packages/opentelemetry-exporter-jaeger/package.json, packages/opentelemetry-exporter-prometheus/package.json, packages/opentelemetry-exporter-stackdriver-trace/package.json, packages/opentelemetry-exporter-zipkin/package.json, packages/opentelemetry-metrics/package.json, packages/opentelemetry-node/package.json, packages/opentelemetry-plugin-dns/package.json, packages/opentelemetry-plugin-grpc/package.json, packages/opentelemetry-plugin-http/package.json, packages/opentelemetry-plugin-https/package.json, packages/opentelemetry-plugin-ioredis/package.json, packages/opentelemetry-plugin-mongodb/package.json, packages/opentelemetry-plugin-mysql/package.json, packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/package.json, packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/package.json, packages/opentelemetry-plugin-redis/package.json, packages/opentelemetry-propagator-jaeger/package.json, packages/opentelemetry-scope-async-hooks/package.json, packages/opentelemetry-scope-base/package.json, packages/opentelemetry-shim-opentracing/package.json, packages/opentelemetry-tracing/package.json
~Fixes an issue that prevented lerna from being used on node 8.~
- Switch from yarn to npm. This will install lerna even on node 8. note: technically we are installing a devDependency that is incompatible with node 8 (lerna), but it is ok because we don't use the feature which uses the broken module.
- Skip checking the broken link so build will pass.
todo: create a follow up PR that removes the skip of the broken link after it is published to npm #751
=> chore: fix build errors

examples/tracer-web/examples/xml-http-request/index.js, package.json
[#688](https://github.com/open-telemetry/opentelemetry-js/issues/688)
Upgraded the @commitlint/cli and @commitlint/config-conventional packages to fix the warnings. The old versions were using core-js@2 and hence the warning messages
=> fix: upgraded commitlint to fix warnings

packages/opentelemetry-api/src/context/propagation/HttpTextFormat.ts, packages/opentelemetry-api/src/context/propagation/NoopHttpTextFormat.ts, packages/opentelemetry-api/src/context/propagation/carrier.ts, packages/opentelemetry-api/src/index.ts, packages/opentelemetry-core/src/context/propagation/B3Format.ts, packages/opentelemetry-core/src/context/propagation/HttpTraceContext.ts, packages/opentelemetry-plugin-http/src/http.ts, packages/opentelemetry-propagator-jaeger/src/JaegerHttpTraceFormat.ts, packages/opentelemetry-shim-opentracing/src/shim.ts
- Adds typing where there was none before :)
=> chore: add typing to propagator carrier

packages/opentelemetry-base/tsconfig-release.json, packages/opentelemetry-core/tsconfig-release.json, packages/opentelemetry-exporter-collector/tsconfig-release.json, packages/opentelemetry-plugin-xml-http-request/tsconfig-release.json, packages/opentelemetry-propagator-jaeger/tsconfig-release.json, packages/opentelemetry-web/tsconfig-release.json
- Cleanup
- We removed `compile:release` script in [opentelemetry-js/pull/53](https://github.com/open-telemetry/opentelemetry-js/pull/53), but pay no heed to corresponding `tsconfig-release.json` and somehow it got copied to few other packages.
=> cleanup: remove unused tsconfig-release.json

packages/opentelemetry-api/src/trace/instrumentation/Plugin.ts, packages/opentelemetry-core/src/trace/instrumentation/BasePlugin.ts, packages/opentelemetry-node/src/instrumentation/PluginLoader.ts, packages/opentelemetry-node/test/instrumentation/PluginLoader.test.ts, packages/opentelemetry-node/test/instrumentation/node_modules/@opentelemetry/plugin-http-module/http-module.js, packages/opentelemetry-node/test/instrumentation/node_modules/@opentelemetry/plugin-notsupported-module/simple-module.js, packages/opentelemetry-node/test/instrumentation/node_modules/@opentelemetry/plugin-simple-module/simple-module.js, packages/opentelemetry-node/test/instrumentation/node_modules/@opentelemetry/plugin-supported-module/simple-module.js, packages/opentelemetry-node/test/instrumentation/node_modules/random-module/index.js, packages/opentelemetry-node/test/instrumentation/node_modules/random-module/package.json, packages/opentelemetry-web/test/WebTracer.test.ts
we needed to avoid loading a plugin if the module name in the config was different than the one that the plugin instrument. 
It requires that every package expose `moduleName` as the name of the module they instrument so i changes the `BasePlugin` interface and `Plugin` type.
=> Prevent loading plugins for incorrect module #626

packages/opentelemetry-exporter-stackdriver-trace/src/trace.ts
=> fix: prevent crash when SDT exporter constructed without options

packages/opentelemetry-core/src/internal/validators.ts, packages/opentelemetry-core/test/internal/validators.test.ts
`TraceState` doesn't allow keys holding '@' char even W3C specifies them for multi tenant vendor scenarios.
Improve checking of TraceState keys to allow '@' char used in multi tenant vendor scenarios.
See https://www.w3.org/TR/trace-context/#key for details
=> fix: allow multi tenant vendor keys in TraceState

packages/opentelemetry-api/package.json, packages/opentelemetry-base/package.json, packages/opentelemetry-core/package.json, packages/opentelemetry-exporter-collector/package.json, packages/opentelemetry-exporter-jaeger/package.json, packages/opentelemetry-exporter-prometheus/package.json, packages/opentelemetry-exporter-stackdriver-trace/package.json, packages/opentelemetry-exporter-zipkin/package.json, packages/opentelemetry-metrics/package.json, packages/opentelemetry-node/package.json, packages/opentelemetry-plugin-dns/package.json, packages/opentelemetry-plugin-ioredis/package.json, packages/opentelemetry-plugin-mongodb/package.json, packages/opentelemetry-plugin-mysql/package.json, packages/opentelemetry-plugin-redis/package.json, packages/opentelemetry-propagator-jaeger/package.json, packages/opentelemetry-scope-async-hooks/package.json, packages/opentelemetry-scope-base/package.json, packages/opentelemetry-shim-opentracing/package.json, packages/opentelemetry-tracing/package.json
The previous glob failed on windows machines.
=> change testing glob to be windows compatible

README.md
According to [Launch Plan](https://docs.google.com/document/d/1eviggoIguOS89dgKL-8ntUOCfPP6FLWAoQkGoBDsld0/edit) and [Beta Readiness Tracker](https://github.com/open-telemetry/opentelemetry-js/issues/782).
=> chore: move Beta v1 release date target to 3/16

packages/opentelemetry-tracing/src/BasicTracerProvider.ts, packages/opentelemetry-tracing/src/config.ts
=> Remove Leftover configs

examples/redis/package.json
I doubt it's the cause of any trouble but I saw that otel-api is
importend twice in package.json
=> fix: removed pkg otel-api because imported twice

packages/opentelemetry-web/src/StackContextManager.ts
Stack scope manager was calling `fn.apply(context, args)` which causes the `this` in `fn` to be set to `context` rather than what it would have been normally. It appears not to affect the working of the Context Manager
=> Remove unnecessary `this` overwrite in stack context manager

README.md, packages/opentelemetry-api/README.md, packages/opentelemetry-core/README.md, packages/opentelemetry-exporter-prometheus/README.md, packages/opentelemetry-node/README.md, packages/opentelemetry-tracing/README.md, packages/opentelemetry-web/README.md
~TODO: add prometheus and collector exporter in [OpenTelemetry registry](https://opentelemetry.io/registry/). Similar to https://github.com/open-telemetry/opentelemetry.io/pull/107~ Will do it later
=> chore: update module names and fix typo

packages/opentelemetry-api/src/trace/SpanOptions.ts, packages/opentelemetry-tracing/src/Tracer.ts, packages/opentelemetry-tracing/test/BasicTracerProvider.test.ts
=> feat: start a root span with spanOptions.parent = null

packages/opentelemetry-tracing/src/export/BatchSpanProcessor.ts, packages/opentelemetry-tracing/test/export/BatchSpanProcessor.test.ts
=> Do not export empty span lists

packages/opentelemetry-core/src/context/propagation/B3Propagator.ts, packages/opentelemetry-core/src/context/propagation/HttpTraceContext.ts, packages/opentelemetry-core/test/context/B3Propagator.test.ts, packages/opentelemetry-core/test/context/HttpTraceContext.test.ts, packages/opentelemetry-propagator-jaeger/src/JaegerHttpTracePropagator.ts, packages/opentelemetry-propagator-jaeger/test/JaegerHttpTracePropagator.test.ts
=> fix: add type checking in propagators

packages/opentelemetry-exporter-prometheus/src/prometheus.ts, packages/opentelemetry-metrics/src/export/Aggregator.ts, packages/opentelemetry-metrics/src/export/ConsoleMetricExporter.ts, packages/opentelemetry-metrics/src/export/types.ts, packages/opentelemetry-metrics/test/Meter.test.ts
- Based on the specs: https://github.com/open-telemetry/opentelemetry-specification/blob/4e7cd5a7d13e09674d0c7cc8b5932ada367c4d2b/specification/api-metrics.md#time
- Feel free to add comments.
=> Metrics: Add lastUpdateTimestamp associated with point

packages/opentelemetry-tracing/src/Tracer.ts
A Tracer is always created by a TracerProvider and this one always passes it's config
therefore no need to default in constructor.
=> chore: remove unused default argument in Tracer

packages/opentelemetry-propagator-jaeger/README.md
=> fix: Jaeger propagator example of usage"

packages/opentelemetry-metrics/src/Meter.ts, packages/opentelemetry-metrics/src/types.ts, packages/opentelemetry-metrics/test/Meter.test.ts
From the spec [here](https://github.com/jmacd/opentelemetry-specification/blob/jmacd/draft_metric_sdk_spec/specification/sdk-metric.md#L289), there are different type of `Integrator` (which is our `Batcher`), we should allow to define a custom one for a given meter and use `UngroupedBatcher` if none is provided.
It will also allow user (like me) to implement their own aggregator :)
=> feat(meter): allow custom batcher #932

packages/opentelemetry-exporter-prometheus/src/prometheus.ts, packages/opentelemetry-exporter-prometheus/test/prometheus.test.ts, packages/opentelemetry-metrics/src/export/Batcher.ts, packages/opentelemetry-metrics/test/Batcher.test.ts
Originally reported by @obecny in gitter:
The following code:
```javascript
'use strict';
const { PrometheusExporter } = require('@opentelemetry/exporter-prometheus');
const { MeterProvider } = require('@opentelemetry/metrics');
const exporter = new PrometheusExporter(
{
startServer: true,
},
() => {
console.log('prometheus scrape endpoint: http://localhost:9464/metrics');
},
);
const meter = new MeterProvider({
interval: 5000,
exporter: exporter,
}).getMeter('foo');
const counter = meter.createCounter('foo', {
monotonic: true,
labelKeys: ['name'],
description: 'foo',
});
const boundCounter1 = counter.bind({ name: 'foo1' });
const boundCounter2 = counter.bind({ name: 'foo2' });
boundCounter1.add(12);
boundCounter2.add(15);
```
Gave the following prometheus export:
```
foo{name="foo2"} 15 …
```
=> fix: do not clear other labelsets when updating metrics

packages/opentelemetry-plugin-http/src/utils.ts
=> Remove bad null check

packages/opentelemetry-exporter-jaeger/README.md, packages/opentelemetry-exporter-jaeger/src/jaeger.ts, packages/opentelemetry-exporter-jaeger/test/jaeger.test.ts
~note: I was unable to add a test as this depends on an env var. running `JAEGER_AGENT_HOST=foo npm run test` showed me that it works though by failing the host checking tests hereby added.~
- It helpes solve open-telemetry/opentelemetry-specification#172 but does not solve it entirely.
- Allowing the user to set env var `JAEGER_AGENT_HOST` in their app and the exporter will pick it up and use it as a value for host. setting `host` in the exporter config would trump this. Let me know if you would like the env var to take precedence.
=> [Jaeger-Exporter] host default env var

packages/opentelemetry-api/src/metrics/BoundInstrument.ts, packages/opentelemetry-api/src/metrics/NoopMeter.ts, packages/opentelemetry-metrics/src/BoundInstrument.ts
The callback return type should be `void` not `{}`
=> chore: fixing wrong return type for metric observer callback

packages/tsconfig.base.json
Without a declaration map, jumping through packages in the repo by definition will target generated .d.ts files.
Like in `opentelemetry-exporter-prometheus`, `MetricExporter` is imported from `@opentelemetry/metrics`. If there is no declaration map, in vscode 'Go to definition' on `MetricExporter` will navigate to file `packages/opentelemetry-exporter-prometheus/node_modules/@opentelemetry/metrics/build/src/export/types.d.ts`.
With this patch, we can jump by definition across packages boundaries in the repo to its original source files. 
Take the example above, 'Go to definition' of `MetricExporter` in  `opentelemetry-exporter-prometheus` can navigate to `packages/opentelemetry-metrics/src/export/types.ts`.
=> chore: enable declaration map to allow jumping through packages

packages/opentelemetry-api/README.md, packages/opentelemetry-api/src/api/context.ts, packages/opentelemetry-api/src/api/global-utils.ts, packages/opentelemetry-api/src/api/metrics.ts, packages/opentelemetry-api/src/api/propagation.ts, packages/opentelemetry-api/src/api/trace.ts, packages/opentelemetry-api/test/api/api.test.ts, packages/opentelemetry-api/test/api/global.test.ts, packages/opentelemetry-node/test/NodeTracerProvider.test.ts, packages/opentelemetry-node/test/registration.test.ts, packages/opentelemetry-plugin-grpc/test/grpc.test.ts, packages/opentelemetry-plugin-http/test/functionals/http-enable.test.ts, packages/opentelemetry-plugin-http/test/functionals/http-package.test.ts, packages/opentelemetry-plugin-http/test/integrations/http-enable.test.ts, packages/opentelemetry-plugin-https/test/functionals/https-enable.test.ts, packages/opentelemetry-plugin-https/test/functionals/https-package.test.ts, packages/opentelemetry-plugin-https/test/integrations/https-enable.test.ts, packages/opentelemetry-plugin-xml-http-request/test/xhr.test.ts, packages/opentelemetry-tracing/test/BasicTracerProvider.test.ts, packages/opentelemetry-web/test/WebTracerProvider.test.ts, packages/opentelemetry-web/test/registration.test.ts
As discussed in the SIG and on issue #885, this uses the `global` object to store references to the global APIs. When an API method is called, it tries to get the global API instance by calling a method with its API version. If the version matches, the call is properly proxied through to the API, else it calls a no-op version.
=> Use global API instances

examples/opentracing-shim/client.js, examples/opentracing-shim/server.js
A previous update to the opentracing-shim example had modified to this to incorrectly use a setter method to set the global tracer. A similar method exists on the OpenTelemetry API but not the OpenTracing API. This was causing JavaScript errors when attempting to run the example.
Update to call the correct method on the OpenTracing API to initialise the global tracer.
Fixes #988
=> fix(opentracing-shim): update opentracing shim example

examples/opentracing-shim/shim.js
Traces generated by the opentracing shim example were incomplete. One trace was generated per service instead of a single trace containing all spans from both services for the remote calls.
The registration of the provider appeared to have been done in the other examples but not this one. After adding the same change a single trace is generated as expected.
Fixes #999
=> fix(opentracing-shim): register tracer provider for complete traces

.gitmodules
When running `npm install` a permission denied error would occur preventing Git submodules from being cloned into your local repository.
Changing this to use a https url and clone anonymously allows these to be retrieved as expected.
Fixes #1000
=> fix: permission denied error when cloning submodules

packages/opentelemetry-plugin-grpc/src/grpc.ts
- Fixes #1004 
- Adds a missing error status handler. Confused on why existing unit tests didn't pick this up until nodejs14. Will investigate separately...
=> fix: add missing error status handler

packages/opentelemetry-plugin-xml-http-request/src/xhr.ts, packages/opentelemetry-plugin-xml-http-request/test/xhr.test.ts
The `xml-http-request` plugin does not correctly set the span kind to `CLIENT` when creating the span on the open method. This makes all spans that represent XHR requests having the default span kind of `INTERNAL`. 
Per spec `INTERNAL -> Default value. Indicates that the span is used internally.`, which in this case is not true and should be `CLIENT -> Indicates that the span covers the client-side wrapper around an RPC or other remote request.`.
One-liner to set the span kind to `CLIENT`.
=> fix(opentelemetry-plugin-xml-http-request): define span kind as CLIENT for xmlhttprequests

.circleci/config.yml, README.md
=> chore: test on node 14

packages/opentelemetry-metrics/src/Metric.ts, packages/opentelemetry-metrics/src/export/Batcher.ts, packages/opentelemetry-metrics/test/Meter.test.ts
Currently the batcher interface define the following:
```ts
export abstract class Batcher {
// [ ... ]
abstract aggregatorFor(metricKind: MetricKind): Aggregator;
// [ ... ]
}
```
Which is spec compliant but from a user perspective it only possible to use a specific aggregator for each kind of metricKind. Some might want to configure that on a more granular level using the metric name or labels for example.
The go implementation already use `MetricDescriptor` instead of `MetricKind` i believe for the same reason: https://github.com/open-telemetry/opentelemetry-go/blob/master/sdk/export/metric/metric.go#L100
More details here: https://github.com/open-telemetry/opentelemetry-js/issues/989#issuecomment-622970316
=> feat(metrics): use MetricDescriptor to determine aggregator #989

packages/opentelemetry-core/src/common/time.ts, packages/opentelemetry-core/src/trace/TraceState.ts, packages/opentelemetry-core/test/common/time.test.ts, packages/opentelemetry-exporter-jaeger/src/types.ts, packages/opentelemetry-exporter-jaeger/test/jaeger.test.ts, packages/opentelemetry-exporter-jaeger/test/transform.test.ts, packages/opentelemetry-exporter-prometheus/src/export/types.ts, packages/opentelemetry-exporter-prometheus/src/prometheus.ts, packages/opentelemetry-exporter-zipkin/src/transform.ts, packages/opentelemetry-exporter-zipkin/src/types.ts, packages/opentelemetry-exporter-zipkin/src/zipkin.ts, packages/opentelemetry-exporter-zipkin/test/transform.test.ts, packages/opentelemetry-exporter-zipkin/test/zipkin.test.ts, packages/opentelemetry-metrics/src/BoundInstrument.ts, packages/opentelemetry-metrics/src/Meter.ts, packages/opentelemetry-metrics/src/MeterProvider.ts, packages/opentelemetry-metrics/test/Batcher.test.ts, packages/opentelemetry-metrics/test/Meter.test.ts, packages/opentelemetry-plugin-https/test/functionals/https-disable.test.ts, packages/opentelemetry-plugin-xml-http-request/src/types.ts, packages/opentelemetry-plugin-xml-http-request/test/xhr.test.ts, packages/opentelemetry-tracing/src/Span.ts, packages/opentelemetry-web/src/utils.ts
- Address comment on https://github.com/open-telemetry/opentelemetry-js/pull/1001#discussion_r419612373
- Renamed all namespace import of @opentelemetry/api variable name to `api`.
=> refactor: normalize namespace import name for @opentelemetry/api

packages/opentelemetry-core/src/context/propagation/B3Propagator.ts, packages/opentelemetry-core/test/context/B3Propagator.test.ts
=> fix: left pad short b3 trace identifiers

packages/opentelemetry-metrics/src/MeterProvider.ts, packages/opentelemetry-metrics/test/MeterProvider.test.ts, packages/opentelemetry-tracing/src/BasicTracerProvider.ts, packages/opentelemetry-tracing/test/BasicTracerProvider.test.ts
- According to https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/resource/sdk.md#resource-sdk, resource in MeterProvider/TracerProvider should be propagated to its meter and tracer.
- Prevent default resource re-creation in Meter/Tracer by propagating default resource in MeterProvider/TracerProvider.
=> fix: prevent duplicated resource creation

packages/opentelemetry-api/src/metrics/BoundInstrument.ts, packages/opentelemetry-api/src/metrics/Meter.ts, packages/opentelemetry-api/src/metrics/Metric.ts, packages/opentelemetry-api/src/metrics/NoopMeter.ts, packages/opentelemetry-metrics/src/BoundInstrument.ts, packages/opentelemetry-metrics/src/Meter.ts, packages/opentelemetry-metrics/src/Metric.ts, packages/opentelemetry-metrics/test/Batcher.test.ts
- Fixes #997 
- `@opentelemetry/api`: Add new interface UnboundMetric, with bind/unbind method, which extends Metric.
- `@opentelemetry/metrics`: Removed problematic setCallback method from BoundObserver. BoundObsever now acts as merely an instrument hold values, should not be exposed as public API.
=> fix: observers should not expose bind/unbind method

packages/opentelemetry-tracing/src/MultiSpanProcessor.ts, packages/opentelemetry-tracing/test/MultiSpanProcessor.test.ts
- MultiSpanProcessor doesn't propagate `forceFlush` action to its child processors.
=> fix: multi span processor should flush child span processors

.circleci/config.yml, README.md
Continue testing on node 13 until it is officially out of support.
=> Reintroduce node 13 tests

packages/opentelemetry-plugin-grpc/test/grpc.test.ts
- fixing failing build
```
test/grpc.test.ts:440:11 - error TS7027: Unreachable code detected.
440           return; // return so typechecking passes for rootSpan.end()
~~~~~~~
```
=> chore: fixing build

packages/opentelemetry-exporter-zipkin/test/transform.test.ts, packages/opentelemetry-plugin-http/test/functionals/utils.test.ts, packages/opentelemetry-tracing/src/MultiSpanProcessor.ts, packages/opentelemetry-tracing/src/NoopSpanProcessor.ts, packages/opentelemetry-tracing/src/Span.ts, packages/opentelemetry-tracing/src/SpanProcessor.ts, packages/opentelemetry-tracing/src/export/BatchSpanProcessor.ts, packages/opentelemetry-tracing/src/export/SimpleSpanProcessor.ts, packages/opentelemetry-tracing/test/MultiSpanProcessor.test.ts, packages/opentelemetry-tracing/test/Span.test.ts
- Make SpanProcessor accepts ReadableSpan as parameters in accordance with [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#onstartspan).
- Fixes #1028
- Removed `tracing.Span.toReadableSpan` as `tracing.Span`s are already implements ReadableSpan.
=> fix(tracing): span processor should receive a readable span as parameters

packages/opentelemetry-plugin-http/src/http.ts, packages/opentelemetry-plugin-http/src/utils.ts, packages/opentelemetry-plugin-http/test/functionals/http-enable.test.ts
see https://github.com/open-telemetry/opentelemetry-js/issues/983 and https://github.com/open-telemetry/opentelemetry-js/pull/965#discussion_r415143475 for context
=> fix(http-plugin): strip otel custom http header #983

packages/opentelemetry-metrics/src/Metric.ts, packages/opentelemetry-metrics/src/export/types.ts, packages/opentelemetry-metrics/test/Meter.test.ts
- Fixes #1022 
- This completes the process of piping the `Resource` assigned to a `MetricProvider` to the `MetricRecord`s so that it is available in the export pipeline.
=> chore: pipe resource through to MetricRecord

packages/opentelemetry-exporter-collector/package.json
=> fix: include proto files in deployment package

packages/opentelemetry-exporter-prometheus/README.md
- Readme from "OpenTelemetry Prometheus Metric Exporter" was not working
- setting labelKeys when creating the counter
- using pid as a nicer example for the label
=> fix readme: setting labelKeys when creating the counter

metapackages/plugins-node-core/package.json, metapackages/plugins-web-core/package.json
This is required to publish npm packages publicly
=> chore: mark metapackages as public

.github/workflows/docs.yml
The API doc deploy action failed because the token used was incorrect
=> chore: change personal access token to github token

packages/opentelemetry-api/package.json, packages/opentelemetry-api/src/api/global-utils.ts, packages/opentelemetry-api/src/platform/browser/globalThis.ts, packages/opentelemetry-api/src/platform/browser/index.ts, packages/opentelemetry-api/src/platform/index.ts, packages/opentelemetry-api/src/platform/node/globalThis.ts, packages/opentelemetry-api/src/platform/node/index.ts
- Fixes https://github.com/open-telemetry/opentelemetry-js/issues/1066
- Add fallbacks for `global` accessing.
=> fix: missing `global` in browser environments

.circleci/config.yml, README.md, packages/opentelemetry-api/package.json, packages/opentelemetry-context-async-hooks/package.json, packages/opentelemetry-context-base/package.json, packages/opentelemetry-context-zone-peer-dep/package.json, packages/opentelemetry-context-zone/package.json, packages/opentelemetry-core/package.json, packages/opentelemetry-exporter-collector/package.json, packages/opentelemetry-exporter-jaeger/package.json, packages/opentelemetry-exporter-prometheus/package.json, packages/opentelemetry-exporter-zipkin/package.json, packages/opentelemetry-metrics/package.json, packages/opentelemetry-node/package.json, packages/opentelemetry-plugin-grpc/package.json, packages/opentelemetry-plugin-http/package.json, packages/opentelemetry-plugin-https/package.json, packages/opentelemetry-plugin-xml-http-request/package.json, packages/opentelemetry-resources/package.json, packages/opentelemetry-shim-opentracing/package.json, packages/opentelemetry-tracing/package.json, packages/opentelemetry-web/package.json
=> chore: test build

doc/batcher-api.md
I don't think we got a specific folder where we document how to extend the SDK to customise its behavior so i've wrote it inside the `doc` the folder, happy to move it if you think this is more of an example !
closes #989
=> docs(batcher): document how to configure custom aggregators #989

packages/opentelemetry-context-async-hooks/src/AsyncHooksContextManager.ts, packages/opentelemetry-context-async-hooks/test/AsyncHooksContextManager.test.ts
~~This one was kinda hard to debug and fix but it finally works !~~
~~I had to remove different test cases that were working in the past:~~
~~- cases where we expected that `.bind` of a function will propagate the context across async operations, which is essentially leaking because `.bind` is only synchronous.~~
~~- cases where we wanted to use `withAsync` inside of a `with` which doesn't work because as said above, `with` is only sync.~~
~~Started this refactor for #1013 but considering the bug in #1101 (that this refactor fixes) as discussed at the SIG, we should merge that first and then try to fix `withAsync`~~
Lot of edit for this one but its worth, i found a way to fix the initial issue #752 without using `await` so i removed `withAsync` which should fixes #1013 and it works with …
=> fix(asynchooks-scope): fix context loss using .with() #1101

.github/CODEOWNERS, README.md
Given his regular contribution to OpenTelemetry JS, propose that @naseemkullah is granted Approver status.
=> Add @naseemkullah to approvers / CODEOWNERS

.circleci/config.yml, README.md
-remove node 13 tests
-removed node 13 tests.
=> remove node 13 tests

examples/metrics/metrics/observer.js, examples/prometheus/index.js, getting-started/README.md, getting-started/monitored-example/monitoring.js, getting-started/ts-example/README.md, getting-started/ts-example/monitoring.ts
- n/a
- Rather than hardcode the default endpoint in prometheus examples, interpolate them  from where they are defined.
=> chore: template prometheus endpoint in examples rather than hardcode

packages/opentelemetry-api/src/metrics/Meter.ts, packages/opentelemetry-api/src/metrics/Metric.ts, packages/opentelemetry-api/src/metrics/NoopMeter.ts, packages/opentelemetry-exporter-prometheus/src/prometheus.ts, packages/opentelemetry-exporter-prometheus/test/prometheus.test.ts, packages/opentelemetry-metrics/src/BoundInstrument.ts, packages/opentelemetry-metrics/src/Meter.ts, packages/opentelemetry-metrics/src/Metric.ts, packages/opentelemetry-metrics/src/UpDownCounterMetric.ts, packages/opentelemetry-metrics/src/export/Batcher.ts, packages/opentelemetry-metrics/src/export/types.ts, packages/opentelemetry-metrics/src/index.ts, packages/opentelemetry-metrics/src/types.ts, packages/opentelemetry-metrics/test/Meter.test.ts, packages/opentelemetry-metrics/test/export/ConsoleMetricExporter.test.ts
- Fixes #1111 
- Added new API endpoint and default SDK implementation.
- The `Counter` and `SumObserver` instruments are defined as monotonic (by default) and `UpDown-` variations of these two instruments are non-monotonic. So no need to have `monotonic` flag separately. 
- Updated Prometheus export to export `UpDownCounter` as `Gauge` type.
- I will take care of examples and remaining documentation in subsequent PR.
=> feat: add the UpDownCounter instrument

packages/opentelemetry-context-zone-peer-dep/src/ZoneContextManager.ts, packages/opentelemetry-context-zone-peer-dep/test/ZoneContextManager.test.ts
- This will fix partly the bug mentioned here
https://github.com/open-telemetry/opentelemetry-js/issues/1206
Another PR will be in contrib
=> chore: fixing zone from which to fork a new zone

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/plugin_request.md, .markdownlint.json, examples/tracer-web/README.md, metapackages/plugins-node-all/README.md, package.json, packages/opentelemetry-exporter-collector/README.md, packages/opentelemetry-plugin-fetch/README.md, packages/opentelemetry-plugin-grpc-js/README.md
Unblocks some open PRs including #1216 which are failing the lint check.
=> chore: fix markdown linting and add npm script

renovate.json
- The default value is **conflicted**, which means Renovate will rebase only if the branch is conflicted. See: https://docs.renovatebot.com/configuration-options/#rebasewhen
- This is to reduce noise (too many emails from renovate-bot).
- It was my bad, I added this config in first place. :(
=> chore(renovate): remove rebaseWhen config

packages/opentelemetry-exporter-jaeger/README.md
The documentation didn't show that the URL for the `endpoint` config option should include `/api/traces`
I added an extra option to the usage documentation example
=> docs: add note about endpoint config option

.github/CODEOWNERS, README.md
- This is based on offline discussion with @rochdev.
- (apparently) Roch is very eager to resume the contribution soon, but for now we have decided to remove him from the approvers list.
- Many thanks to @rochdev for your contributions and valuable reviews on the many PRs at early stage.
=> Remove @rochdev from @open-telemetry/js-approvers

.github/CODEOWNERS, README.md
- This is based on offline discussion with @bg451.
- @bg451 was in the original team to kick off this project
- Many thanks to @bg451 for your [contributions](https://github.com/open-telemetry/opentelemetry-js/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Abg451+is%3Aclosed) and [valuable reviews](https://github.com/open-telemetry/opentelemetry-js/pulls?q=is%3Apr+sort%3Aupdated-desc+reviewed-by%3Abg451+is%3Aclosed) on the many PRs especially OpenTracing-shim and Metrics-API work.
/cc @dyladan @obecny
=> Remove @bg451 from @open-telemetry/js-approvers

packages/opentelemetry-exporter-collector/src/platform/browser/CollectorTraceExporter.ts, packages/opentelemetry-exporter-collector/src/platform/browser/types.ts, packages/opentelemetry-exporter-collector/src/platform/node/CollectorTraceExporter.ts, packages/opentelemetry-exporter-collector/src/platform/node/types.ts, packages/opentelemetry-exporter-collector/src/types.ts, packages/opentelemetry-exporter-collector/test/browser/CollectorTraceExporter.test.ts
This PR addresses Issue #1109.
Currently, the Collector Exporter only sends traces to the collector. In Python, Java, and Go, for example, metric exporting already exists for the collector. This PR adds that feature. I created two versions, one for Node and the other for browser. The node version uses gRPC, and the browser uses Beacon or XHR. It's up to date with all previous collector exporter commits.
This is the 3rd part of this long [PR](https://github.com/open-telemetry/opentelemetry-js/pull/1248).
This PR just creates types based off the [OpenTelemetry Proto](https://github.com/open-telemetry/opentelemetry-proto/blob/master/opentelemetry/proto/metrics/v1/metrics.proto).
The next diffs will be as follows 
1. Add transform functions and tests
2. E2E Metric exporter for Browser with …
=> feat: Add types for Collector Metric Exporter

packages/opentelemetry-plugin-fetch/src/fetch.ts, packages/opentelemetry-plugin-fetch/test/fetch.test.ts
=> fix: do not crash on fetch(new Request(url))

packages/opentelemetry-api/src/metrics/Metric.ts, packages/opentelemetry-api/src/metrics/NoopMeter.ts, packages/opentelemetry-metrics/README.md, packages/opentelemetry-metrics/src/BaseObserverMetric.ts, packages/opentelemetry-metrics/src/Meter.ts, packages/opentelemetry-metrics/src/MonotonicObserverResult.ts, packages/opentelemetry-metrics/src/ObserverResult.ts, packages/opentelemetry-metrics/src/SumObserverMetric.ts, packages/opentelemetry-metrics/test/Meter.test.ts
- #1114
- Introduces the sum observer metric type.
=> feat: added sum observer metric

examples/README.md
=> fix: Typo in example README

metapackages/plugins-node-core/README.md, metapackages/plugins-node-core/package.json, packages/opentelemetry-node/README.md, packages/opentelemetry-node/src/config.ts
- Enable grpc-js plugin by default
=> feat(grpc-js): enable autoinstrumentation by default

packages/opentelemetry-tracing/README.md, packages/opentelemetry-tracing/src/utility.ts, packages/opentelemetry-tracing/test/Tracer.test.ts
Allows user to configure tracer's sampling probability via env var
- JS implementation of open-telemetry/opentelemetry-specification#567
- `Tracer.ts` looks to see if `process.env.OTEL_SAMPLING_PROBABILITY` is set and if so determines the sampling probability by converting its contents to a number and passing it to the `ProbabilitySampler` constructor. If unset it defaults to passing in a probability of 1.
=> feat: add OTEL_SAMPLING_PROBABILITY env var

packages/opentelemetry-plugin-grpc-js/src/index.ts
EMERGENCY BUGFIX. grpc-js plugin is broken right now.
=> fix: add missing grpc-js index

packages/opentelemetry-api/tsconfig.json, packages/opentelemetry-context-base/tsconfig.json, packages/tsconfig.es5.json
- Fixes #902 
- Downgrade compile target of `@opentelemetry/api` & `@opentelemetry/context-base` (dependency of /api) `es2017` ... `es5`
=> feat(api/context-base): change compile target to es5

metapackages/plugins-node-all/package.json
Holding https://github.com/open-telemetry/opentelemetry-js/pull/1382 release for this.
=> chore: bump metapackage dependencies

packages/opentelemetry-sdk-node/package.json, packages/opentelemetry-sdk-node/test/sdk.test.ts
Disable loading of plugins during sdk tests, which was the cause of the flaky test.
=> Fix flaky sdk test

.github/workflows/canary.yaml
The publish action failed because by default the setup-node github action uses the github registry. Set to npmjs specifically.
=> chore: set registry and scope for canary publish

README.md
[README.md](https://github.com/open-telemetry/opentelemetry-js/blob/master/README.md) file contains two broken links to `pg` and `pg-pool` plugins respectively due to changes in repository directories.
This PR solves those broken links.
=> docs: fix broken links to pg and pg-pool plugins

doc/batcher-api.md
for [https://github.com/open-telemetry/opentelemetry-js/issues/1314](https://github.com/open-telemetry/opentelemetry-js/issues/1314)
=> Fix typo in document.

packages/opentelemetry-exporter-jaeger/README.md
- Fixes https://github.com/open-telemetry/opentelemetry-js/issues/1433
- Add "for Node.js" to make it more clear.
=> docs(exporter-jaeger): add "for Node.js"

.github/workflows/canary.yaml
Pull full git history to fix canary publish
=> Fix canary builds

packages/opentelemetry-resource-detector-aws/src/detectors/AwsBeanstalkDetector.ts, packages/opentelemetry-resource-detector-aws/src/detectors/index.ts, packages/opentelemetry-resource-detector-aws/test/detectors/AwsBeanstalkDetector.test.ts
Like In [Java repository](https://github.com/open-telemetry/opentelemetry-java/tree/master/sdk_extensions/aws_v1_support/src/main/java/io/opentelemetry/sdk/extensions/trace/aws/resource), we add AWS Beanstalk plugin resource detector to JS repository
1. Add main function of AWS Beanstalk resource detector
2. Add corresponding unit test of AWS Beanstalk resource detector
If you would like to review this @anuraaga
=> feat: added AWS Beanstalk Plugins Resource Detector

packages/opentelemetry-metrics/src/export/aggregators/Histogram.ts, packages/opentelemetry-metrics/test/export/aggregators/Histogram.test.ts
- Proper sort of histogram boundaries
- Well known javascript behaviour, when array sort is being implemented by lexicographical order, not number,
so [200, 1000, 300, 1500] instead of [200, 300, 1000, 1500] becomes [1000, 1500, 200, 300]
=> fix: proper histogram boundaries sort

packages/opentelemetry-exporter-collector-proto/README.md, packages/opentelemetry-exporter-collector-proto/test/CollectorTraceExporter.test.ts, packages/opentelemetry-exporter-collector/README.md
- [Early pull request](https://github.com/open-telemetry/opentelemetry-js/pull/1256) has renamed `CollectorExporter` to `CollectorTraceExporter`, this corrects the doc wrong API.
- change CollectorExporter to CollectorTraceExporter
=> docs: change CollectorExporter to CollectorTraceExporter

examples/tracer-web/examples/zipkin/index.html, examples/tracer-web/examples/zipkin/index.js, examples/tracer-web/package.json, examples/tracer-web/webpack.config.js, packages/opentelemetry-exporter-zipkin/.eslintrc.js, packages/opentelemetry-exporter-zipkin/README.md, packages/opentelemetry-exporter-zipkin/karma.conf.js, packages/opentelemetry-exporter-zipkin/package.json, packages/opentelemetry-exporter-zipkin/src/platform/browser/index.ts, packages/opentelemetry-exporter-zipkin/src/platform/browser/util.ts, packages/opentelemetry-exporter-zipkin/src/platform/index.ts, packages/opentelemetry-exporter-zipkin/src/platform/node/index.ts, packages/opentelemetry-exporter-zipkin/src/platform/node/util.ts, packages/opentelemetry-exporter-zipkin/src/types.ts, packages/opentelemetry-exporter-zipkin/src/zipkin.ts, packages/opentelemetry-exporter-zipkin/test/browser/index-webpack.ts, packages/opentelemetry-exporter-zipkin/test/browser/zipkin.test.ts, packages/opentelemetry-exporter-zipkin/test/common/transform.test.ts, packages/opentelemetry-exporter-zipkin/test/helper.ts, packages/opentelemetry-exporter-zipkin/test/node/zipkin.test.ts
- Fixes #1265
- Adding possibility of using Zipkin Exporter in web
- Added example too
=> chore: refactoring zipkin to be able to use it in web

package.json
Seems like the main package.json version was missed when I released the latest version
=> chore: fixing released version in main package.json

.github/ISSUE_TEMPLATE/bug_report.md
We have found that many issues are a result of improper setup. This adds a section to the issue template which asks users to provide their setup code.
=> Request setup code in template

packages/opentelemetry-plugin-fetch/test/fetch.test.ts, packages/opentelemetry-plugin-xml-http-request/test/xhr.test.ts
Addresses #1499 
Remove non-inclusive language from tests
=> Remove non-inclusive language from tests

packages/opentelemetry-exporter-collector-grpc/package.json, packages/opentelemetry-exporter-collector-proto/package.json
#1538 
#1524
proto files from build directory of `@opentelemetry/exporter-collector-proto` and `@opentelemetry/exporter-collector-grpc` are not published to npm in v0.11.0, causing error message about missing files to be logged when package is used, and exporter to not work.
Added the protos folder to the `"files"` section of `package.json`.
Validated the fix with `npm publish --dry-run`:
```
npm notice 304B   build/protos/opentelemetry/proto/collector/README.md                       
npm notice 2.9kB  build/protos/opentelemetry/proto/common/v1/common.proto                    
npm notice 1.9kB  build/protos/opentelemetry/proto/collector/metrics/v1/metrics_service.proto
npm notice 19.2kB build/protos/opentelemetry/proto/metrics/v1/metrics.proto                  
npm notice 1.3kB …
```
=> fix: include missing proto files in npm distribution

packages/opentelemetry-api/src/trace/attributes.ts, packages/opentelemetry-api/src/trace/span.ts, packages/opentelemetry-tracing/src/Span.ts, packages/opentelemetry-tracing/test/Span.test.ts
=> chore: disallow null attribute values

packages/opentelemetry-resource-detector-aws/src/detectors/AwsEc2Detector.ts, packages/opentelemetry-resources/src/constants.ts, packages/opentelemetry-resources/test/resource-assertions.test.ts, packages/opentelemetry-resources/test/util/resource-assertions.ts
- Fixes #1580 
- There were two host name attributes: `host.name` and `host.hostname`. This PR removes the latter as per: https://github.com/open-telemetry/opentelemetry-specification/pull/838.
=> chore: remove duplicate hostname resource attribute

packages/opentelemetry-api/src/context/context.ts, packages/opentelemetry-api/src/trace/NoopTracer.ts, packages/opentelemetry-core/test/context/B3MultiPropagator.test.ts, packages/opentelemetry-core/test/context/B3Propagator.test.ts, packages/opentelemetry-core/test/context/B3SinglePropagator.test.ts, packages/opentelemetry-core/test/context/HttpTraceContext.test.ts, packages/opentelemetry-core/test/context/composite.test.ts, packages/opentelemetry-plugin-http/src/http.ts, packages/opentelemetry-plugin-http/test/utils/DummyPropagation.ts, packages/opentelemetry-plugin-https/test/utils/DummyPropagation.ts, packages/opentelemetry-shim-opentracing/src/shim.ts
- Fixes #1558
This PR simplifies the active span logic by only storing a span in the active context. Instead of storing plain span contexts in a context, they are wrapped in a NoopSpan on extract.
- The `setExtractedSpanContext` API method was updated to wrap the extracted span context in a NoopSpan before storing it in a context.
- The `getExtractedSpanContext` method was removed, as this should now be done by accessing the context of the current span.
- Logic in the http plugin had to be adjusted to preserve the require parent behavior.
cc: @vmarchaud - This work might be a prerequisite for #1552.
=> feat: simplify active span logic

packages/opentelemetry-plugin-xml-http-request/test/unmocked.test.ts, packages/opentelemetry-tracing/src/MultiSpanProcessor.ts, packages/opentelemetry-tracing/src/NoopSpanProcessor.ts, packages/opentelemetry-tracing/src/SpanProcessor.ts, packages/opentelemetry-tracing/src/export/BatchSpanProcessor.ts, packages/opentelemetry-tracing/src/export/SimpleSpanProcessor.ts, packages/opentelemetry-tracing/test/Span.test.ts
Fixes #1620 
Also adds tests to guarantee onStart and onEnd are called synchronously when spans are started and ended as required by specification.
=> chore: ensure onStart is called with a writeable span

examples/collector-exporter-node/docker/docker-compose.yaml, packages/opentelemetry-exporter-collector-grpc/test/helper.ts, packages/opentelemetry-exporter-collector-proto/test/helper.ts, packages/opentelemetry-exporter-collector/src/platform/browser/CollectorTraceExporter.ts, packages/opentelemetry-exporter-collector/src/platform/node/CollectorTraceExporter.ts, packages/opentelemetry-exporter-collector/src/transform.ts, packages/opentelemetry-exporter-collector/test/common/transform.test.ts, packages/opentelemetry-exporter-collector/test/helper.ts
- Fixes #1623 
- For proto and grpc the ids is converted from hex to base64
- For json the id are kept as hex
=> chore: fixing conversion of id to hex and base64

packages/opentelemetry-api/src/trace/Sampler.ts, packages/opentelemetry-core/src/trace/sampler/ParentBasedSampler.ts, packages/opentelemetry-core/src/trace/sampler/TraceIdRatioBasedSampler.ts, packages/opentelemetry-core/test/trace/ParentBasedSampler.test.ts, packages/opentelemetry-tracing/src/Tracer.ts
=> chore: sampler gets a full context

packages/opentelemetry-exporter-zipkin/test/common/transform.test.ts, packages/opentelemetry-plugin-http/test/functionals/utils.test.ts, packages/opentelemetry-tracing/src/BasicTracerProvider.ts, packages/opentelemetry-tracing/src/MultiSpanProcessor.ts, packages/opentelemetry-tracing/src/NoopSpanProcessor.ts, packages/opentelemetry-tracing/src/Span.ts, packages/opentelemetry-tracing/src/SpanProcessor.ts, packages/opentelemetry-tracing/src/Tracer.ts, packages/opentelemetry-tracing/test/Span.test.ts, packages/opentelemetry-tracing/test/export/SimpleSpanProcessor.test.ts
=> feat: span processor onstart recieves context

eslint.config.js, package.json, packages/opentelemetry-api/src/context/propagation/NoopTextMapPropagator.ts, packages/opentelemetry-api/src/metrics/NoopMeter.ts, packages/opentelemetry-api/src/trace/NoopLogger.ts, packages/opentelemetry-api/src/trace/NoopSpan.ts, packages/opentelemetry-api/src/trace/NoopTracer.ts, packages/opentelemetry-context-base/src/NoopContextManager.ts, packages/opentelemetry-core/src/common/ConsoleLogger.ts, packages/opentelemetry-core/src/common/NoopLogger.ts, packages/opentelemetry-core/src/platform/browser/timer-util.ts, packages/opentelemetry-core/src/trace/sampler/AlwaysOffSampler.ts, packages/opentelemetry-core/src/trace/sampler/AlwaysOnSampler.ts, packages/opentelemetry-exporter-collector/src/platform/node/CollectorExporterNodeBase.ts, packages/opentelemetry-metrics/src/export/Controller.ts, packages/opentelemetry-metrics/src/export/NoopExporter.ts, packages/opentelemetry-plugin-grpc/src/grpc.ts, packages/opentelemetry-plugin-http/src/http.ts, packages/opentelemetry-shim-opentracing/src/shim.ts, packages/opentelemetry-tracing/src/NoopSpanProcessor.ts, packages/opentelemetry-tracing/src/export/BatchSpanProcessor.ts, packages/opentelemetry-tracing/src/export/SimpleSpanProcessor.ts
- This PR removes warnings regarding  unused vars (https://github.com/open-telemetry/opentelemetry-js/issues/1093)
- Stub classes methods arguments were prefixed with "_". Unused vars - deleted. Now this rule will throw error
Also, precommit lint hook introduced
=> chore: eslint - fix unused vars warnings, add precommit lint - part 1

packages/opentelemetry-core/src/ExportResult.ts, packages/opentelemetry-exporter-collector-proto/test/CollectorMetricExporter.test.ts, packages/opentelemetry-exporter-collector-proto/test/CollectorTraceExporter.test.ts, packages/opentelemetry-exporter-collector/src/CollectorExporterBase.ts, packages/opentelemetry-exporter-collector/src/platform/browser/util.ts, packages/opentelemetry-exporter-collector/test/browser/CollectorMetricExporter.test.ts, packages/opentelemetry-exporter-collector/test/browser/CollectorTraceExporter.test.ts, packages/opentelemetry-exporter-collector/test/common/CollectorMetricExporter.test.ts, packages/opentelemetry-exporter-collector/test/common/CollectorTraceExporter.test.ts, packages/opentelemetry-exporter-collector/test/node/CollectorMetricExporter.test.ts, packages/opentelemetry-exporter-collector/test/node/CollectorTraceExporter.test.ts, packages/opentelemetry-exporter-jaeger/src/jaeger.ts, packages/opentelemetry-exporter-jaeger/test/jaeger.test.ts, packages/opentelemetry-exporter-prometheus/src/PrometheusExporter.ts, packages/opentelemetry-exporter-zipkin/src/platform/browser/util.ts, packages/opentelemetry-exporter-zipkin/src/platform/node/util.ts, packages/opentelemetry-exporter-zipkin/src/zipkin.ts, packages/opentelemetry-exporter-zipkin/test/node/zipkin.test.ts, packages/opentelemetry-metrics/src/export/ConsoleMetricExporter.ts, packages/opentelemetry-metrics/src/export/Controller.ts, packages/opentelemetry-metrics/test/export/Controller.test.ts, packages/opentelemetry-tracing/src/export/BatchSpanProcessor.ts, packages/opentelemetry-tracing/src/export/ConsoleSpanExporter.ts, packages/opentelemetry-tracing/src/export/InMemorySpanExporter.ts, packages/opentelemetry-tracing/src/export/SimpleSpanProcessor.ts, packages/opentelemetry-tracing/test/export/BatchSpanProcessor.test.ts, packages/opentelemetry-tracing/test/export/InMemorySpanExporter.test.ts, packages/opentelemetry-tracing/test/export/SimpleSpanProcessor.test.ts
There is 2 goals for this PR:
- Remove `FAILED_RETRYABLE` result since it has been removed from the spec and we expect exporter to handle this.
- Add an optional `error` inside the result so the error is correctly handled at one place (on the `Controller` for metrics and `SpanProcessor` for spans). Previously every exporter had to use the `globalErrorHandler` to report the error which made multiple errors appears (one from the exporter and one for the upstream component that called it)
The design is the same as the Golang implementation: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#go-spanexporter-interface
Fixes #1569
=> refactor: new interface for ExportResult #1569

.github/ISSUE_TEMPLATE/request_for_instrumentation.md
Per the Maintainers meeting, this modifies the instrumentation request issue template to apply the `instrumentation` label.
=> chore: apply instrumentation label to plugin requests

packages/opentelemetry-api/README.md, packages/opentelemetry-api/src/trace/span.ts, packages/opentelemetry-api/src/trace/status.ts, packages/opentelemetry-api/test/noop-implementations/noop-span.test.ts, packages/opentelemetry-exporter-collector-grpc/test/helper.ts, packages/opentelemetry-exporter-collector-proto/test/helper.ts, packages/opentelemetry-exporter-collector/test/helper.ts, packages/opentelemetry-exporter-jaeger/src/transform.ts, packages/opentelemetry-exporter-jaeger/test/jaeger.test.ts, packages/opentelemetry-exporter-jaeger/test/transform.test.ts, packages/opentelemetry-exporter-zipkin/src/transform.ts, packages/opentelemetry-exporter-zipkin/test/common/transform.test.ts, packages/opentelemetry-exporter-zipkin/test/helper.ts, packages/opentelemetry-exporter-zipkin/test/node/zipkin.test.ts, packages/opentelemetry-grpc-utils/test/utils/assertionUtils.ts, packages/opentelemetry-plugin-grpc-js/src/client/utils.ts, packages/opentelemetry-plugin-grpc-js/src/server/clientStreamAndUnary.ts, packages/opentelemetry-plugin-grpc-js/src/server/serverStreamAndBidi.ts, packages/opentelemetry-plugin-grpc-js/src/utils.ts, packages/opentelemetry-plugin-grpc/src/grpc.ts, packages/opentelemetry-plugin-grpc/src/utils.ts, packages/opentelemetry-plugin-http/src/http.ts, packages/opentelemetry-plugin-http/src/types.ts, packages/opentelemetry-plugin-http/src/utils.ts, packages/opentelemetry-plugin-http/test/functionals/http-enable.test.ts, packages/opentelemetry-plugin-http/test/functionals/utils.test.ts, packages/opentelemetry-plugin-https/test/functionals/https-enable.test.ts, packages/opentelemetry-shim-opentracing/src/shim.ts, packages/opentelemetry-tracing/src/Span.ts, packages/opentelemetry-tracing/test/Span.test.ts
=> fix!: change status codes from grpc status codes

examples/tracer-web/examples/user-interaction/index.js, packages/opentelemetry-exporter-collector-grpc/src/CollectorExporterNodeBase.ts, packages/opentelemetry-exporter-collector-proto/src/CollectorExporterNodeBase.ts, packages/opentelemetry-exporter-collector/src/platform/browser/CollectorExporterBrowserBase.ts, packages/opentelemetry-exporter-collector/src/platform/node/CollectorExporterNodeBase.ts
- Fixes #1601
- Fixes #1610
- The problem was that the promise was not yet resolved before it has been already removed from the Promise.all. So after it is resolved now can be removed
- During testing it turn out that the example for web hasn't been updated with B3 Propagator
=> fix: do not access promise before resolve

packages/opentelemetry-core/src/utils/environment.ts, packages/opentelemetry-core/test/utils/environment.test.ts, packages/opentelemetry-tracing/src/config.ts, packages/opentelemetry-tracing/src/utility.ts, packages/opentelemetry-tracing/test/BasicTracerProvider.test.ts, packages/opentelemetry-tracing/test/Span.test.ts
- PR one of many for Environment Variable Configuration Spec #1392
- respect span limit env vars
- new defaults conforming to the spec
- invalid numbers now matched to closest equivalent instead of the default for a given var
=> chore: env vars for span limit as per specification

getting-started/README.md
Making the text more clear, concise, readable, and consistent.
Wording changes, capitalization, rewording third-party speech, "we" speech, and forward-looking statements
=> Updates to getting started page

packages/opentelemetry-tracing/src/config.ts, packages/opentelemetry-tracing/src/types.ts
Remove obsolete code.
Graceful shutdown support was removed via https://github.com/open-telemetry/opentelemetry-js/pull/1522
Remove the corresponding configuration because it is not used anymore.
Refs: https://github.com/open-telemetry/opentelemetry-js/pull/1321
=> chore: remove unused tracer config gracefulShutdown

packages/opentelemetry-context-zone-peer-dep/README.md, packages/opentelemetry-context-zone/README.md, packages/opentelemetry-instrumentation-xml-http-request/README.md
I didn't make an issue, as it seemed simple enough. A few packages were using `WebTracer` as opposed to `WebTracerProvider` in their examples. It seems like this may have been removed from the exports in `@opentelemetry/web` (please correct me if wrong), so these examples are out of date. Regardless, there is some inconsistency.
Update examples to use `WebTracerProvider` and specify `contextManager` in the `register()` method as opposed to on instantiation of provider.
=> chore: use WebTracerProvider instead of WebTracer in docs

packages/opentelemetry-resource-detector-aws/src/detectors/AwsEksDetector.ts, packages/opentelemetry-resource-detector-aws/src/detectors/index.ts, packages/opentelemetry-resource-detector-aws/test/detectors/AwsEksDetector.test.ts
- Added AWS EKS Resource Detector
- This is similar to the AWS EKS Resource Detector in [Java](https://github.com/open-telemetry/opentelemetry-java/blob/master/sdk-extensions/aws-v1-support/src/main/java/io/opentelemetry/sdk/extension/trace/aws/resource/EksResource.java)
- Added functionality of AWS EKS resource detector
- Added corresponding unit tests for AWS EKS detector
If you can review @dyladan, @anuraaga, thanks a lot!
=> Feat: Added Amazon EKS Resource Detector

packages/opentelemetry-instrumentation-xml-http-request/src/xhr.ts
- Fixes #1719 
- Check for `PerformanceResourceTiming` support in `@opentelemetry/instrumentation-xml-http-request`
=> fix(xhr): check for resource timing support

packages/opentelemetry-instrumentation-http/test/functionals/http-enable.test.ts, packages/opentelemetry-instrumentation-http/test/functionals/http-package.test.ts, packages/opentelemetry-plugin-http/test/functionals/http-package.test.ts
Fixes #1745 
Update:
the 2nd link (info.cern.ch) used in test is not valid anymore
http instrumentation and http plugin was using the same port
=> feat: fixing failing test

packages/opentelemetry-exporter-jaeger/src/transform.ts, packages/opentelemetry-exporter-jaeger/test/transform.test.ts
Jaeger exporter set error tag when span status is Unset as discribed in issue #1757 
Changed error flag setting logic
Added test for this
=> fix(@opentelemetry/exporter-jaeger): fixed issue #1757

.github/workflows/docs.yml
During a previous PR the workflow `run` line was accidentally removed.
=> chore: fix docs workflow

packages/opentelemetry-instrumentation-http/test/integrations/http-enable.test.ts, packages/opentelemetry-instrumentation-http/test/integrations/https-enable.test.ts, packages/opentelemetry-plugin-http/test/functionals/http-package.test.ts, packages/opentelemetry-plugin-http/test/integrations/http-enable.test.ts, packages/opentelemetry-plugin-https/test/functionals/https-package.test.ts, packages/opentelemetry-plugin-https/test/integrations/https-enable.test.ts
I believe the flakiness of the http test comes down to its dependence on making requests to google.fr. I have replaced this functionality in the tests with a local dev server. Making these requests locally means they are faster and more reliable.
=> chore: use local server for http integration tests

packages/opentelemetry-api/src/trace/SpanOptions.ts
Fixes #1793 
SDK already accepted `api.TimeInput` so only the API needs to be changed.
=> chore: change SpanOptions startTime to TimeInput

packages/opentelemetry-exporter-collector-proto/test/CollectorMetricExporter.test.ts, packages/opentelemetry-exporter-collector-proto/test/CollectorTraceExporter.test.ts
Fixes #1811 
The collector exporter proto tests had a race condition. They were waiting 20ms for the exporter to lazy-load the proto files. If it took longer than 20ms, the tests failed. This removes the race.
=> chore: remove race from tests

README.md
I wanted to propose @Flarna as js approver. He is contributing in this project for quite long time and has done many contributions. Thx for your hard work.
https://github.com/open-telemetry/opentelemetry-js/commits?author=Flarna
https://github.com/open-telemetry/opentelemetry-js-contrib/commits?author=Flarna
=> chore: adding flarna to js approvers

README.md
I wanted to propose @johnbley as js approver. He is contributing to this project with web related stuff and I believe it would be great to have him as an approver too.
https://github.com/open-telemetry/opentelemetry-js-contrib/commits?author=johnbley
https://github.com/open-telemetry/opentelemetry-js/commits?author=johnbley
=> chore: adding johnbley to js approvers

.github/CODEOWNERS
=> Add @johnbley to codeowners

packages/opentelemetry-instrumentation-http/src/http.ts, packages/opentelemetry-instrumentation-http/test/functionals/http-enable.test.ts, packages/opentelemetry-instrumentation-http/test/functionals/https-enable.test.ts, packages/opentelemetry-plugin-http/src/http.ts, packages/opentelemetry-plugin-http/test/functionals/http-enable.test.ts, packages/opentelemetry-plugin-https/test/functionals/https-enable.test.ts
=> improv(instrumentation-http): supressInstrumentation when we get a request on ignoredPath [#1831]

.github/workflows/canary.yaml, .github/workflows/lint.yml, .github/workflows/unit-test.yml, .github/workflows/w3c-integration-test.yml
Prepare to rename `master` branch to `main` by adding `main` to the github action triggers. After the branch is renamed, `master` will be removed from the list.
See [this post](https://github.com/github/renaming) for more information
=> chore: prepare for branch rename

packages/opentelemetry-exporter-jaeger/README.md
- Clearing up a misunderstanding someone might have in understanding the [opentelemetry-exporter-jaeger](https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/opentelemetry-exporter-jaeger/) package
- Added info that the package is only supported in Node.js applications
=> Add info that the project only works with Node.js

packages/opentelemetry-api/src/index.ts
This will fix the currently-failing lint workflow.
An update to typedoc means that only classes which are exported are included in the documentation. Here, the API singletons are exported as type only. This means they can't be used directly, but are included in the typedoc documentation and the following code will compile successfully:
```typescript
import { context, ContextAPI } from "@opentelemetry/api";
let ctx: ContextAPI = context;
```
The following code will still fail:
```typescript
import { ContextAPI } from "@opentelemetry/api";
const ctx = new ContextAPI() // this will fail
const ctx2 = ContextAPI.getInstance() // this will also fail
```
=> chore: export API singleton types

packages/opentelemetry-instrumentation-http/README.md
- Typo in `instrumentation-http` README example code.
- current example: `require('@opentelemetry/instrumentation-graphql')`
- should be: `require('@opentelemetry/instrumentation-http')`
=> docs(instrumentation-http): fix typo in README

packages/opentelemetry-instrumentation-fetch/src/fetch.ts, packages/opentelemetry-instrumentation-fetch/test/fetch.test.ts
- PerformanceObserver entries are not actually used due to several bugs. performance.getEntriesByType fallback is used so things are not that broken.
- Move `observer.disconnect` to the setTimeout so it is not disconnected before the 300ms timeout. XHR instrumentation seems to work fine.
- Don't shadow `entries` variable inside perf observer callback, currently empty entry list is always returned.
- Normalize spanUrl check inside perf observer callback as it can be relative but entry.name is always absolute. The same is already done in web.getResource. Same issue in XHR instrumentation, will fix it there also.
- Added mock perf observer(not sure if this is the right way but couldn't come up with anything better) so that unit tests actually use it instead of fallback getEntries. …
=> fix(instrumentation-fetch): perf observer bugs

README.md
- Following #1863, and due to the fact that two public attributes were removed from the node's collector exporter implementation
- Added a new section `0.15.0 to 0.16.0` under `Upgrade guidelines` in general README, which mentions this breaking change.
=> docs(exporter-collector): document breaking change in README

.github/workflows/canary.yaml
https://github.com/lerna/lerna/issues/2788
The automation tokens we were using do not support the verification step in lerna. I switched to a more permissive token to fix the canary release automation for now but as a longer-term fix I would like to go back to using a regular automation token.
=> chore: no verify access on publish

packages/opentelemetry-instrumentation-http/src/utils.ts, packages/opentelemetry-instrumentation-http/test/functionals/utils.test.ts, packages/opentelemetry-instrumentation-http/test/integrations/http-enable.test.ts, packages/opentelemetry-instrumentation-http/test/utils/rawRequest.ts, packages/opentelemetry-plugin-http/src/utils.ts, packages/opentelemetry-plugin-http/test/functionals/utils.test.ts, packages/opentelemetry-plugin-http/test/integrations/http-enable.test.ts, packages/opentelemetry-plugin-http/test/utils/rawRequest.ts
Fixes #1377 
@blumamir and I investigated this issue and were able to reproduce it. 
It happens if client uses the same TCP connection to send multiple requests (in keep-alive mode for example), so that there are multiple active requests on the same socket.
In this scenario, there is one socket for two request/response pairs and this socket is attached only to a single response on every given time.
So it may happen, that the instance of [OutgoingMessage](https://github.com/nodejs/node/blob/75fd447/lib/_http_outgoing.js#L83) (response in our case), will not have a socket attached when handler calls the `response.end` function. In this case, the data will be pushed into an internal buffer https://github.com/nodejs/node/blob/75fd447/lib/_http_outgoing.js#L334. 
But in http plugin we try to …
=> fix: use socket from the request

README.md
1. `@opentelemetry/instrumentation-http` was pointing to old plugin link.
2. We actually don't have `@opentelemetry/instrumentation-https` because new `@opentelemetry/instrumentation-http` will handle both HTTP and HTTPs, so remove that not used link.
=> docs(readme): fix @opentelemetry/instrumentation-http link

README.md, packages/opentelemetry-resources/src/Resource.ts, packages/opentelemetry-resources/test/Resource.test.ts
[Resource Merge Spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/sdk.md#merge)
> The resulting resource MUST have all attributes that are on any of the two input resources. If a key exists on both the old and updating resource, the value of the updating resource MUST be picked (even if the updated value is empty).
This commit updates the resource collision precedence.
=> fix: specification compliant resource collision precedence

packages/opentelemetry-semantic-conventions/src/trace/rpc.ts
- Adding 2 missing attributes to `rpc` semantic conventions, according to the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/rpc.md). I need them to update the aws-sdk instrumentation according to [these](https://github.com/open-telemetry/opentelemetry-specification/pull/1422/files) conventions
-
=> feat(semantic-conventions): add missing RpcAttributes from spec

packages/opentelemetry-instrumentation-http/src/http.ts, packages/opentelemetry-instrumentation-http/test/functionals/https-enable.test.ts
- Fixes https://github.com/open-telemetry/opentelemetry-js/issues/2008
- Safely access `constructor.name`, in case object doesn't have a custructor.
=> fix(http-instrumentation): crash fix

packages/opentelemetry-instrumentation/test/node/InstrumentationNodeModuleFile.test.ts
- Fixes #1990
- fixing path of instrumentation file for different systems
=> chore: fixing path of instrumentation file for different systems

packages/opentelemetry-core/README.md
- Some of links about samplers are dead in [packages/opentelemetry-core/README.md](https://github.com/open-telemetry/opentelemetry-js/blob/2f169a57f5bf2f737ff4a6a15256c60aef15d4d9/packages/opentelemetry-core/README.md#built-in-implementations).
- Make them links to existing headings.
- Change the heading text to add ` Sampler` like about Propagator section.
=> docs: fix links & headings about built-in samplers

packages/opentelemetry-semantic-conventions/src/trace/general.ts
Adds missing NET_TRANSPORT IPC semantic convention attributes. Came up as a comment on another PR: https://github.com/open-telemetry/opentelemetry-js-contrib/pull/389#discussion_r596982199
* Add `pipe` and `Unix` IPC attributes. (From https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/span-general.md#general-network-connection-attributes)
=> feat: add NET_TRANSPORT IPC attributes

eslint.config.js, packages/opentelemetry-metrics/src/export/ConsoleMetricExporter.ts, packages/opentelemetry-metrics/test/Meter.test.ts, packages/opentelemetry-metrics/test/export/ConsoleMetricExporter.test.ts, packages/opentelemetry-tracing/src/export/ConsoleSpanExporter.ts, packages/opentelemetry-tracing/test/export/BatchSpanProcessor.test.ts, packages/opentelemetry-tracing/test/export/ConsoleSpanExporter.test.ts, packages/opentelemetry-web/src/WebTracerProvider.ts, packages/opentelemetry-web/test/WebTracerProvider.test.ts
Adds ESLint rule for avoiding any console log statements in the codebase
Fixes #2007 and #1861
=> chore(eslint): no-console error rule

packages/opentelemetry-instrumentation-fetch/src/fetch.ts, packages/opentelemetry-web/src/utils.ts
Running opentelemetry-web in a javascript application that's being server side renderedwill throw an error.  This PR fixes that issue as documented here https://github.com/open-telemetry/opentelemetry-js/issues/1575
-
- moves the url normalization done with an anchor tag under a function so it will not be run on import
=> Server side rendering support

packages/opentelemetry-exporter-zipkin/src/platform/browser/util.ts
Unblock #1825 by fixing its compilation error. Also a stricter and safer check anyways.
=> Check type of navigator.sendBeacon

packages/opentelemetry-propagator-jaeger/src/JaegerHttpTracePropagator.ts, packages/opentelemetry-propagator-jaeger/test/JaegerHttpTracePropagator.test.ts
Fixes #1983
Ensures the Jaeger propagator context extraction conforms to the [Jaeger trace context specification](https://www.jaegertracing.io/docs/1.21/client-libraries/#propagation-format). Specifically, when received trace id shorter that 32 characters, it will now be zero-padded to 32 characters.
=> fix(propagator-jaeger): zero pad extracted trace id to 32 characters

packages/opentelemetry-tracing/src/Span.ts, packages/opentelemetry-tracing/test/Span.test.ts
By [Semantic Conventions for Exceptions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/exceptions.md#Attributes) - `exception.type` should be a string.
Cast to string for numeric exception codes.
=> fix: exception.type should always be a string

packages/opentelemetry-core/src/context/propagation/HttpTraceContext.ts, packages/opentelemetry-core/test/context/HttpTraceContext.test.ts
=> fix: do not inject invalid span context

packages/opentelemetry-core/src/baggage/propagation/HttpBaggage.ts, packages/opentelemetry-core/src/context/propagation/HttpTraceContext.ts, packages/opentelemetry-core/test/context/HttpTraceContext.test.ts, packages/opentelemetry-propagator-b3/src/B3MultiPropagator.ts, packages/opentelemetry-propagator-b3/src/B3Propagator.ts, packages/opentelemetry-propagator-b3/src/B3SinglePropagator.ts, packages/opentelemetry-propagator-b3/test/B3MultiPropagator.test.ts, packages/opentelemetry-propagator-b3/test/B3Propagator.test.ts, packages/opentelemetry-propagator-b3/test/B3SinglePropagator.test.ts, packages/opentelemetry-propagator-jaeger/src/JaegerHttpTracePropagator.ts, packages/opentelemetry-propagator-jaeger/test/JaegerHttpTracePropagator.test.ts
=> chore: do not inject span context when instrumentation is suppressed

packages/opentelemetry-resource-detector-aws/src/detectors/AwsEksDetector.ts, packages/opentelemetry-resource-detector-aws/test/detectors/AwsEksDetector.test.ts
- Initially, I was just trying to run the test suite, and happened to be using node 15. Uncovered a couple issues with the EKS detector/test
- Fixes #1776
- test suite was failing on node 15 because it no longer allows unhandled promise rejections
- this was due to not awaiting a promise response from `_isEks` in the detector, so the if block was never evaluating the result of the call
- "unsuccessful" test cases were noop (error assertions never executed), because `detect` wraps itself in a try/catch, and never throws
- updated those test cases to document current behavior
- fixed the flipped test names
=> fix: await http response in AWS EKS detector

packages/opentelemetry-instrumentation-fetch/src/fetch.ts, packages/opentelemetry-instrumentation-fetch/test/fetch.test.ts, packages/opentelemetry-instrumentation-xml-http-request/src/xhr.ts, packages/opentelemetry-instrumentation-xml-http-request/test/xhr.test.ts
- fixes #2044
- It will debug information whenever adding headers was prevented because origin didn't match the config property `propagateTraceHeaderCorsUrls`
=> chore: adding info to debug whenever headers are being skipped due to cors policy

packages/opentelemetry-instrumentation-fetch/README.md, packages/opentelemetry-instrumentation-fetch/src/fetch.ts, packages/opentelemetry-instrumentation-fetch/test/fetch.test.ts
This PR adds an `applyCustomAttributesOnSpan`  function on the `instrumentation-fetch` package. similar to the API of [http(s) plugins](https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/opentelemetry-plugin-https/README.md#https-plugin-options).
Fixes #1287
Happy to make changes in tests or implementation if needed
=> feat(instrumentation-fetch): Add applyCustomAttributesOnSpan option

eslint.config.js, packages/opentelemetry-exporter-collector-grpc/src/util.ts, packages/opentelemetry-metrics/src/export/Controller.ts, packages/opentelemetry-tracing/src/export/BatchSpanProcessor.ts
Signed-off-by: Naseem <naseem@transit.app>
- solves #1492
- added  https://palantir.github.io/tslint/rules/no-floating-promises/ and configured accordingly
It was mostly tests that had floating promises (if there's been any test flakiness it could possibly be attributed to that), but there were a few floating promises in non-test code.
=> chore: no-floating-promises

packages/opentelemetry-semantic-conventions/src/resource/ResourceAttributes.ts, packages/opentelemetry-semantic-conventions/src/trace/SemanticAttributes.ts, scripts/semconv/generate.sh, scripts/semconv/templates/SemanticAttributes.ts.j2
Updated the generated semantic convention attributes to the one defined
in v1.2.0 of the Opentelemetry specification.
Changed `generate.sh` to ensure it uses v1.2.0 of the spec
=> feat: upgrade semantic conventions to v1.2.0 of spec

README.md, packages/opentelemetry-core/src/index.ts, packages/opentelemetry-core/src/utils/environment.ts, packages/opentelemetry-core/src/utils/sampling.ts, packages/opentelemetry-core/test/utils/environment.test.ts, packages/opentelemetry-tracing/README.md, packages/opentelemetry-tracing/src/config.ts, packages/opentelemetry-tracing/src/utility.ts, packages/opentelemetry-tracing/test/BasicTracerProvider.test.ts, packages/opentelemetry-tracing/test/Tracer.test.ts, packages/opentelemetry-tracing/test/config.test.ts, packages/opentelemetry-tracing/test/export/ConsoleSpanExporter.test.ts
Adds support for OTEL_TRACES_SAMPLER and OTEL_TRACES_SAMPLER_ARG, in favor of
OTEL_SAMPLING_PROBABILITY.
- Fixes #1675 
- removes support for `OTEL_SAMPLING_PROBABILITY`
- adds support for `OTEL_TRACES_SAMPLER` and `OTEL_TRACES_SAMPLER_ARG`
=> feat: handle OTEL_TRACES_SAMPLER env var

packages/opentelemetry-instrumentation/src/platform/node/instrumentation.ts
Fixes #2119 
For the detailed problem description refer to the linked issue.
In short: don't iterate over all module definitions at `onRequire` hook when checking for supported library versions. The hook already has the module definition. `isSupported` might otherwise find another module and report the supported status back falsely.
=> fix(instrumentation): support multiple module definitions with different versions

packages/opentelemetry-exporter-prometheus/src/PrometheusSerializer.ts, packages/opentelemetry-exporter-prometheus/test/PrometheusSerializer.test.ts
Sanitises the attribute names to match the naming convention enforced by
Prometheus
If you have a label name with `-` then Prometheus will fall over this issue with an error like:
`error while linting: text format parsing error in line 282: expected '=' after label name, found '-'`
The change is to also sanitise the label name and not only the metric names
=> feat: ensure the label names are sanitised

packages/opentelemetry-instrumentation/src/platform/node/instrumentation.ts
#2131 
Instrumentations need access to the enabled flag, this is to avoid defining it multiple times.
=> fix: add isEnabled to InstrumentationBase

packages/opentelemetry-core/src/trace/sampler/ParentBasedSampler.ts, packages/opentelemetry-core/test/trace/ParentBasedSampler.test.ts
- Fixes #2164
- Add a check for invalid parent `SpanContext`
- Add unit tests
=> [sampler] treat invalid SpanContext as no SpanContext

README.md
Feature status was very out of date and included API and context which is no longer in this repo.
=> chore: update feature status in readme

packages/opentelemetry-instrumentation-grpc/src/grpc/index.ts
There were two problems that i've fixed:
- sometime a client method (that is generated by grpc client) do not have a path, as i don't know the grpc internal i'm don't know why
- there was a race between instrumentation files patch and the global one, which sometimes would not set the `grpcClient` variable (which is used to retrieve grpc constants).
Fxies #2160
=> chore(grpc-instrumentation): fix grpc example #2160

packages/opentelemetry-sdk-node/package.json
This PR moves `nock` from `dependencies` to `devDependencies` since the library is only required during development.
=> fix(opentelemetry-sdk-node): move nock to dev dependencies

packages/opentelemetry-instrumentation/src/instrumentation.ts, packages/opentelemetry-instrumentation/src/types.ts, packages/opentelemetry-instrumentation/test/common/Instrumentation.test.ts
Plugins should be able to modify configuration at run time; many plugins implement this. There is no reason this shouldn't be in the base class, so all plugins have this functionality.  
Added `getConfig` and `setConfig` to `InstrumentationAbstract` and `Instrumentation`
Fixes #2174
=> feat(opentelemetry-instrumentation): getConfig and setConfig

packages/opentelemetry-core/src/index.ts, packages/opentelemetry-core/src/trace/rpc-metadata.ts, packages/opentelemetry-instrumentation-http/src/http.ts, packages/opentelemetry-instrumentation-http/src/utils.ts, packages/opentelemetry-instrumentation-http/test/functionals/http-enable.test.ts, packages/opentelemetry-instrumentation-http/test/functionals/utils.test.ts
- https://github.com/open-telemetry/opentelemetry-js-contrib/issues/464: We previously had a implicit dependency between http instrumentation and some http framework instrumentation, specially express one where both http was using express metadata to assign a attribute and express was using the http one to rename the main span it creates.
- This PR introduces a new context api to store "RPC Metadata" which is for now only for HTTP but might later on be completed with specific metadata for GRPC or any other RPC system so instrumentations "works" together to have the maximum data available. For now the http metadata only contains a span (which is the root span that the http instrumentation creates for each new request) and a optional `route` that might be set by other instrumentation later …
=> feat(core): add specific context key to store rpc metadata

packages/opentelemetry-api-metrics/package.json, packages/opentelemetry-context-zone-peer-dep/package.json, packages/opentelemetry-context-zone/package.json, packages/opentelemetry-core/package.json, packages/opentelemetry-exporter-collector/package.json, packages/opentelemetry-exporter-zipkin/package.json, packages/opentelemetry-instrumentation-fetch/package.json, packages/opentelemetry-instrumentation-xml-http-request/package.json, packages/opentelemetry-instrumentation/package.json, packages/opentelemetry-propagator-jaeger/package.json, packages/opentelemetry-tracing/package.json, packages/opentelemetry-web/package.json, renovate.json
On MacOS the most recent version of karma-webpack is broken
Fixes #2231
=> chore: downgrade karma-webpack

packages/opentelemetry-node/test/registration.test.ts, packages/opentelemetry-sdk-node/test/sdk.test.ts, packages/opentelemetry-web/test/registration.test.ts
Only references from the production API package were changed. The metrics API can be handled at a later time. They were only used in tests so this is pretty straightforward.
=> chore: remove references to Noop classes from API

packages/opentelemetry-instrumentation-http/src/http.ts, packages/opentelemetry-instrumentation-http/test/functionals/http-disable.test.ts, packages/opentelemetry-instrumentation-http/test/functionals/https-disable.test.ts, packages/opentelemetry-instrumentation/test/common/autoLoader.test.ts, packages/opentelemetry-tracing/src/Tracer.ts
Only references from the production API package were changed. The metrics API can be handled at a later time.
=> chore: remove references to NOOP singletons

README.md, RELEASING.md
Creating a JS versioning proposal as requested in https://github.com/open-telemetry/opentelemetry-specification/issues/1267
/cc @tedsuo
=> chore: Link to spec versioning doc

packages/opentelemetry-sdk-node/README.md
Fixes a broken link to BatchSpanProcessor in sdk node README.md
=> chore(README): update link to BatchSpanProcessor in sdk node

.github/workflows/unit-test.yml
Hopefully this will fix the node 16 issues
=> chore: use setup-node

renovate.json
Prevent bad upgrades like those pointed out by @Flarna in #2236
=> chore: do not upgrade backwards compatibility

packages/opentelemetry-exporter-collector-grpc/src/CollectorExporterNodeBase.ts, packages/opentelemetry-exporter-collector-grpc/src/CollectorMetricExporter.ts, packages/opentelemetry-exporter-collector-grpc/src/CollectorTraceExporter.ts, packages/opentelemetry-exporter-collector-grpc/test/CollectorMetricExporter.test.ts, packages/opentelemetry-exporter-collector-grpc/test/CollectorTraceExporter.test.ts
- OTLP-gRPC exporter needs to honor the OTEL_EXPORTER_OTLP(*)HEADERS env var
- from spec:
> Key-value pairs to be used as headers associated with gRPC or HTTP requests.
- fixes #2303 
- Merge headers into gRPC exporters' metadata
=> feat: otlp-grpc exporter uses headers environment variables

getting-started/README.md, website_docs/_index.md, website_docs/getting_started/browser.md, website_docs/getting_started/nodejs.md
=> chore: update the website getting started docs

packages/template/package.json
- The [packages template](https://github.com/jonchurch/opentelemetry-js/blob/main/packages/template/package.json#L22) lists Node.js >=8.0.0 under supported engines in the default package.json. OTLP JS lists v8.5.0 as the min supported Node.js version. New packages that copy the template may fail to update the current default.
- Bump the engines field in package.json to `>=8.5.0` to be in line with Node.js version support of the project.
closes #2318
=> chore: update package template engines version

examples/tracer-web/webpack.config.js
- Closes #2325 
- Webpack config for the examples included bundling a file that was not in the examples dir, preventing the example from running as per the instructions.
- Removed offending line from webpack config
=> chore: fix tracer-web example webpack config

CHANGELOG.md, packages/opentelemetry-exporter-collector-proto/src/CollectorMetricExporter.ts, packages/opentelemetry-exporter-collector-proto/src/CollectorTraceExporter.ts
Fixes: #2330 
- Changes default HTTP exporter port to be `55681` instead of `4317` because `4317` is reserved for gRPC [in the specs](https://github.com/open-telemetry/opentelemetry-specification/blob/2a712f7626cb62b21ae210ef3175612e7744f285/specification/protocol/otlp.md#otlpgrpc-default-port)
- `55681` is [used by](https://github.com/open-telemetry/opentelemetry-collector/blob/f3784a92def81ae9b5c770c97ac2d5bed4f9b804/receiver/otlpreceiver/factory.go#L33-L34) `opentelemetry-collector` so it should be a good choice
=> Change default HTTP exporter port to 55681

website_docs/getting_started/browser.md
- website_docs , consistency in using words plugin versus instrumentation. Replaced the word plugin with instrumentation 
- The package for instrumentation of `document load` is named @opentelemetry/instrumentation-document-load . But the website_docs use often the word `plugin` in order to reference this instrumentation, e.g by informing the user to install the @opentelemetry/plugin-document-load . It should actually be:  @opentelemetry/instrumentation-document-load
=> replaced word plugin with instrumentation

renovate.json
Yet another crack at updating renovate so it will not do #2236 
This version comes from a suggestion from the folks at renovate so it should work.
=> chore: ignore backcompat in renovate

packages/opentelemetry-web/src/enums/PerformanceTimingNames.ts, packages/opentelemetry-web/src/types.ts, packages/opentelemetry-web/src/utils.ts, packages/opentelemetry-web/test/utils.test.ts
Add capturing [decodedBodySize from resource timings](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceResourceTiming/decodedBodySize). [As per spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#common-attributes) it should be only included if content encoding (eg. gzip, brotli) is being used (in which case encoded and decoded sizes are different)
Past related: https://github.com/open-telemetry/opentelemetry-js/pull/1262#discussion_r448697119
=> feat(opentelemetry-web): capture decodedBodySize / http.response_content_length_uncompressed

packages/opentelemetry-instrumentation-http/src/http.ts, packages/opentelemetry-instrumentation-http/src/utils.ts, packages/opentelemetry-instrumentation-http/test/functionals/http-enable.test.ts, packages/opentelemetry-instrumentation-http/test/utils/assertSpan.ts
Fixes https://github.com/open-telemetry/opentelemetry-js/issues/1255
Fixes #2320 
And fix an HTTP instrumentation test: `'should have 1 ended span when request throw on bad "options" object'`
For HTTP instrumentation, the span for outgoing request is currently started (`startSpan`) without any attributes. Only later when response arrives, request and response attributes are calculated and set on it. This is problematic in 2 situations:
- if exception is thrown before the response arrives (for example, if the parameters are not valid), then the span is closed and there are no attributes on it for user to understand the context (no URL, method).
- sampler can only take decisions based on attributes that are available during `startSpan` function call (on the options). Request attributes are …
=> fix(instrumentation-http): set outgoing request attributes on start span

.github/CODEOWNERS, README.md
I wanted to promote @Rauno56 to js approver. He has been contributing for this project for a while and is quite active in otel as well.
PRs:
https://github.com/open-telemetry/opentelemetry-js-contrib/commits?author=Rauno56
https://github.com/open-telemetry/opentelemetry-js/commits?author=Rauno56
https://github.com/open-telemetry/opentelemetry-js-api/commits?author=Rauno56
Thx @Rauno56 for all of you contributions so far.
=> chore: adding Rauno56 to js approvers

packages/opentelemetry-resource-detector-aws/README.md, packages/opentelemetry-resource-detector-aws/src/detectors/AwsEc2Detector.ts
- the code example in README is not valid.
=> fix: fixup aws detector readme

packages/opentelemetry-instrumentation-http/README.md, packages/opentelemetry-instrumentation-http/src/http.ts, packages/opentelemetry-instrumentation-http/src/types.ts, packages/opentelemetry-instrumentation-http/src/utils.ts, packages/opentelemetry-instrumentation-http/test/functionals/http-enable.test.ts
- support adding custom attributes before a span is started for opentelemetry-instrumentation-http
- help to use  some custom fields to make the sample decision
- help to report some custom fields before a request/response
- add startIncomingSpanHook，startOutgoingSpanHook and corresponding test for opentelemetry-instrumentation-http
=> feat(@opentelemetry-instrumentation-http): support adding custom attributes before a span is started

.github/CODEOWNERS
This will mean we don't have to make a PR every time an approver is changed.
=> chore: change codeowners to point to team

packages/opentelemetry-exporter-collector-grpc/tsconfig.json, packages/opentelemetry-exporter-collector-proto/tsconfig.json, packages/opentelemetry-exporter-collector/tsconfig.json, packages/opentelemetry-exporter-jaeger/tsconfig.json, packages/opentelemetry-exporter-zipkin/tsconfig.json, packages/opentelemetry-instrumentation-fetch/tsconfig.json, packages/opentelemetry-instrumentation-grpc/tsconfig.json, packages/opentelemetry-instrumentation-http/tsconfig.json, packages/opentelemetry-instrumentation-xml-http-request/tsconfig.json, packages/opentelemetry-sdk-node/tsconfig.json, packages/opentelemetry-sdk-trace-node/tsconfig.json, packages/opentelemetry-sdk-trace-web/tsconfig.json, packages/opentelemetry-shim-opentracing/tsconfig.json, tsconfig.json
Seems the entried in tsconfig.json files needs to be sorted otherwise I end up with
modified files after npm install.
Refs: #2340
=> chore: sort entries in tsconfig

packages/opentelemetry-core/src/baggage/propagation/HttpBaggagePropagator.ts, packages/opentelemetry-core/src/baggage/utils.ts, packages/opentelemetry-core/src/common/attributes.ts, packages/opentelemetry-core/src/common/global-error-handler.ts, packages/opentelemetry-core/src/common/time.ts, packages/opentelemetry-core/src/common/types.ts, packages/opentelemetry-core/src/propagation/composite.ts, packages/opentelemetry-core/src/trace/HttpTraceContextPropagator.ts, packages/opentelemetry-core/src/utils/wrap.ts
related to #1093,
- This PR fixes lint warnings in `core` package.
=> chore: Fix lint warnings in core package

packages/opentelemetry-instrumentation-fetch/src/fetch.ts, packages/opentelemetry-instrumentation-fetch/test/fetch.test.ts
tl;dr: Fetch instrumentation drops request body when using `Request` object.
Currently fetch instrumentation forwards calls via 2 parameter signature regardless if 'fetch(Request)` or `fetch(url, object)` signature is being used:
https://github.com/open-telemetry/opentelemetry-js/blob/90ea0fed52f406005550862f9b645803f89e36a9/packages/opentelemetry-instrumentation-fetch/src/fetch.ts#L299
This however is causing a bug where passing request object as 2nd parameter drops request body: https://jsfiddle.net/t2t2/bc53reqf/
(confirmed with both Firefox 90.0.2 & Chrome 92.0.4515.131)
In quick research found that while [Request.body](https://developer.mozilla.org/en-US/docs/Web/API/Request/body) should return a `ReadableStream` none of the browsers actually do it right now. `fetch(url, object)` is …
=> fix(instrumentation-fetch): `fetch(string, Request)` silently drops request body

website_docs/getting_started/nodejs.md, website_docs/instrumentation.md
Like https://github.com/open-telemetry/opentelemetry-js-api/pull/116 this fixes the examples in the website docs to work properly again.
=> docs: fix examples in website_docs/instrumentation.md

packages/opentelemetry-propagator-b3/src/B3MultiPropagator.ts, packages/opentelemetry-propagator-b3/src/B3Propagator.ts, packages/opentelemetry-propagator-b3/src/B3SinglePropagator.ts, packages/opentelemetry-propagator-jaeger/src/JaegerPropagator.ts, packages/opentelemetry-resources/src/platform/browser/default-service-name.ts, packages/opentelemetry-resources/src/platform/node/default-service-name.ts, packages/opentelemetry-sdk-metrics-base/src/BaseObserverMetric.ts, packages/opentelemetry-sdk-metrics-base/src/BatchObserverResult.ts, packages/opentelemetry-sdk-metrics-base/src/CounterMetric.ts, packages/opentelemetry-sdk-metrics-base/src/MeterProvider.ts, packages/opentelemetry-sdk-metrics-base/src/Metric.ts, packages/opentelemetry-sdk-metrics-base/src/SumObserverMetric.ts, packages/opentelemetry-sdk-metrics-base/src/UpDownCounterMetric.ts, packages/opentelemetry-sdk-metrics-base/src/ValueRecorderMetric.ts
- This PR fixes lint warnings in `propagator-jaeger`, `propagator-b3`, `resources`, and `sdk-metrics-base` packages (related to #1093)
=> chore: Fix lint warnings in propagator-jaeger, propagator-b3, resources, and sdk-metrics-base packages

.github/workflows/canary.yaml, .github/workflows/docs.yaml, .github/workflows/lint.yml, .github/workflows/unit-test.yml, examples/basic-tracer-node/package.json, examples/collector-exporter-node/package.json, examples/grpc-js/package.json, examples/grpc/package.json, examples/http/package.json, examples/https/package.json, package.json, packages/opentelemetry-core/package.json, packages/opentelemetry-exporter-collector-grpc/package.json, packages/opentelemetry-exporter-collector-proto/package.json, packages/opentelemetry-instrumentation-http/package.json, packages/opentelemetry-sdk-trace-node/package.json
Similar to what @blumamir did in contrib
Also update dependencies which didn't match the hoisted versions in order to speed up the hoist.
Tests now run in under 5 minutes in CI with a cache miss
=> chore: hoist dependencies to speed up ci

.github/workflows/lint.yml, .github/workflows/unit-test.yml
Now that we are hoisting modules, the caching step is significantly more efficient than it used to be. Combined with the latest version of the caching action supporting multiple paths properly, this drastically simplifies the caching part of our action and speeds up the tests.
~2-3 minutes
~3-4 minutes
=> chore: simplify unit test cache

examples/README.md
- fixes: #2391 
- updated examples readme to remove express example link which is moved to opentelemetry-js-contrib/examples
- and added additional examples link to point opentelemetry-js-contrib
=> docs(examples): updated examples readme links

README.md, benchmark/propagator.js, integration-tests/propagation-validation-server/validation-server.js, packages/opentelemetry-core/README.md, packages/opentelemetry-core/src/baggage/propagation/W3CBaggagePropagator.ts, packages/opentelemetry-core/src/index.ts, packages/opentelemetry-core/src/trace/W3CTraceContextPropagator.ts, packages/opentelemetry-core/test/baggage/W3CBaggagePropagator.test.ts, packages/opentelemetry-core/test/propagation/composite.test.ts, packages/opentelemetry-core/test/trace/W3CTraceContextPropagator.test.ts, packages/opentelemetry-instrumentation-grpc/test/helper.ts, packages/opentelemetry-sdk-trace-base/src/BasicTracerProvider.ts, packages/opentelemetry-shim-opentracing/test/Shim.test.ts
Fixes #2428
Renames:
- `HttpTraceContextPropagator` to `W3CTraceContextPropagator`
- `HttpBaggagePropagator` to `W3CBaggagePropagator`
This is a breaking change
Fix in the contrib repo: https://github.com/open-telemetry/opentelemetry-js-contrib/pull/644. I didn't find any places that need updating in `opentelemetrry-js-api` or `opentelemetry.io` repos.
=> fix!: remove 'Http' from W3C propagator names

packages/opentelemetry-exporter-prometheus/src/PrometheusExporter.ts, packages/opentelemetry-exporter-prometheus/src/PrometheusLabelsBatcher.ts, packages/opentelemetry-exporter-zipkin/src/platform/browser/util.ts, packages/opentelemetry-exporter-zipkin/src/platform/node/util.ts, packages/opentelemetry-exporter-zipkin/src/transform.ts, packages/opentelemetry-exporter-zipkin/src/types.ts, packages/opentelemetry-exporter-zipkin/src/zipkin.ts, packages/opentelemetry-exporter-zipkin/test/common/transform.test.ts, packages/opentelemetry-shim-opentracing/src/shim.ts
- This PR fixes lint warnings in `exporter-prometheus` and `exporter-zipkin` packages.
- The warnings regarding the deprecation of `url.parse` haven't been fixed because they need more manual work. I will tackle them in a different PR if needed.
- I have renamed `statusCodeTagName` and `statusDescriptionTagName` exported variables to fix the name shadowing issue in `transform.ts`, but I am not sure this doesn't have any side effects. Let me know if I should revert them.
=> chore(exporter): fix lint warnings

packages/opentelemetry-sdk-trace-base/src/BasicTracerProvider.ts, packages/opentelemetry-sdk-trace-base/src/Span.ts, packages/opentelemetry-sdk-trace-base/src/Tracer.ts, packages/opentelemetry-sdk-trace-base/src/config.ts, packages/opentelemetry-sdk-trace-base/src/export/InMemorySpanExporter.ts, packages/opentelemetry-sdk-trace-base/src/utility.ts, packages/opentelemetry-sdk-trace-base/test/common/BasicTracerProvider.test.ts, packages/opentelemetry-sdk-trace-base/test/common/MultiSpanProcessor.test.ts, packages/opentelemetry-sdk-trace-node/src/NodeTracerProvider.ts
- This PR fixes lint warnings in `sdk-trace-base` and `sdk-trace-node` packages.
=> chore(sdk-trace): fix lint warnings

packages/opentelemetry-exporter-collector/src/platform/browser/CollectorMetricExporter.ts, packages/opentelemetry-exporter-collector/src/platform/node/CollectorExporterNodeBase.ts, packages/opentelemetry-exporter-collector/src/platform/node/CollectorMetricExporter.ts, packages/opentelemetry-exporter-collector/src/types.ts
- This PR fixes lint warnings in `exporter-collector` package.
=> chore(exporter-collector): fix lint warnings

packages/opentelemetry-instrumentation-http/src/http.ts, packages/opentelemetry-instrumentation-http/src/utils.ts, packages/opentelemetry-instrumentation-http/test/functionals/http-package.test.ts, packages/opentelemetry-instrumentation-http/test/functionals/https-package.test.ts
- This PR fixes lint warnings in `instrumentation-http` package.
=> chore(instrumentation-http): fix lint warnings

packages/opentelemetry-instrumentation-fetch/src/fetch.ts
- This PR fixes lint warnings in `instrumentation-fetch` package.
- Fix lint warnings.
=> chore(instrumentation-fetch): fix lint warnings

packages/opentelemetry-semantic-conventions/src/resource/SemanticResourceAttributes.ts, packages/opentelemetry-semantic-conventions/src/trace/SemanticAttributes.ts, scripts/semconv/generate.sh
Regenerated the `@opentelemetry-js/semantic-conventions`-package to use
the latest definitions from the Opentelemetry specification
- Resolves issue #2407 
- Update semantic conventions to the latest version of the spec
=> feat: upgrade semantic conventions to the latest 1.6.1 version

packages/opentelemetry-instrumentation/src/platform/node/instrumentation.ts, packages/opentelemetry-instrumentation/test/node/InstrumentationBase.test.ts
- In some cases (typically, AWS lambda; but can potentially happen in other cases) the `package.json` file may be missing at runtime for a certain module. Currently OTEL crashes in this case, unnecessarily.
- See discussion - https://github.com/open-telemetry/opentelemetry-js/issues/2193
- In case the module's version is missing (due to a missing `package.json` file), we patch the module/file if and only if the supported versions contain a wildcard (`*`). Until now, an exception was thrown, crashing the app.
- Added tests that cover these scenarios/
=> fix: handle missing package.json file when checking for version

doc/instrumentation-guide.md
These links were broken in the doc
I found in git log that the referenced packages were moved. So here are the links to point to their new location.
The line numbers referenced in the links aren't all quite right anymore, but at least the links take you into the right file now.
=> Update links to packages moved to experimental

packages/opentelemetry-exporter-otlp-http/test/node/CollectorMetricExporter.test.ts, packages/opentelemetry-exporter-otlp-http/test/node/CollectorTraceExporter.test.ts
- resolves #2278 
- removes incorrect usage of `serviceName` property from tests in opentelemetry-exporter-otlp-http package
- Two test cases in package opentelemetry-exporter-otlp-http are using the `serviceName` property for configuration of OTLPTraceExporter and OTPLMetricExporter.`serviceName` is not a valid property of the config object (OTLPExporterNodeConfigBase), this PR removes the usage of this property in the test cases.
=> fix: remove usage of serviceName property in tests for otel collector

.github/workflows/unit-test.yml, .github/workflows/w3c-integration-test.yml
=> chore: fix cache paths for backcompat tests

CHANGELOG.md, integration-tests/propagation-validation-server/package.json, lerna.json, packages/opentelemetry-context-async-hooks/package.json, packages/opentelemetry-context-zone-peer-dep/package.json, packages/opentelemetry-context-zone/package.json, packages/opentelemetry-core/package.json, packages/opentelemetry-exporter-jaeger/package.json, packages/opentelemetry-exporter-zipkin/package.json, packages/opentelemetry-propagator-b3/package.json, packages/opentelemetry-propagator-jaeger/package.json, packages/opentelemetry-resources/package.json, packages/opentelemetry-sdk-trace-base/package.json, packages/opentelemetry-sdk-trace-node/package.json, packages/opentelemetry-sdk-trace-web/package.json, packages/opentelemetry-semantic-conventions/package.json, packages/opentelemetry-shim-opentracing/package.json, packages/template/package.json
There are no changes from 0.26.0
Huge thank you to all involved who helped get us this far! 🎉 
- @aabmass
- @adamegyed
- @alisabzevari
- @amanbrar1999
- @AndrewGrachov
- @antoniomrfranco
- @anuraaga
- @aphelionz
- @aravinsiva
- @Asafb26
- @astorm
- @austinlparker
- @banothurameshnaik
- @BlumAmir
- @bradfrosty
- @brunoluiz
- @carolinee21
- @chalin
- @confiq
- @connorlindsey
- @CptSchnitz
- @danielmbarlow
- @DarkPurple141
- @davidwitten
- @debagger
- @dengliming
- @dobesv
- @drexler
- @dyladan
- @echoontheway
- @EdZou
- @flands
- @Flarna
- @hermanbanken
- @Hongbo
- @ivansenic
- @JamesJHPark
- @JapuDCret
- @jessitron
- @johanneswuerbach
- @johnbley
- @jonahrosenblum
- @jonchurch
- @jordanworner
- @jtmalinowski
- @jufab
- @justinwalz
- @kanikashah90
- @KKelvinLo
- @kkruk
- @kudlatyamroth
- …
=> chore: v1.0.0 proposal

experimental/backwards-compatability/node10/package.json, experimental/backwards-compatability/node12/package.json, experimental/backwards-compatability/node8/package.json, experimental/packages/opentelemetry-exporter-otlp-grpc/package.json, experimental/packages/opentelemetry-exporter-otlp-http/package.json, experimental/packages/opentelemetry-exporter-otlp-proto/package.json, experimental/packages/opentelemetry-exporter-prometheus/package.json, experimental/packages/opentelemetry-instrumentation-fetch/package.json, experimental/packages/opentelemetry-instrumentation-grpc/package.json, experimental/packages/opentelemetry-instrumentation-http/package.json, experimental/packages/opentelemetry-instrumentation-xml-http-request/package.json, experimental/packages/opentelemetry-sdk-metrics-base/package.json, experimental/packages/opentelemetry-sdk-node/package.json
Update stable dependencies of all experimental packages. This is just a number since the code for 0.26 packages is identical to the 1.0 packages.
=> chore: update stable dependencies to 1.0

experimental/packages/opentelemetry-exporter-prometheus/test/PrometheusExporter.test.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/MeterProvider.ts, experimental/packages/opentelemetry-sdk-metrics-base/test/Meter.test.ts, experimental/packages/opentelemetry-sdk-metrics-base/test/MeterProvider.test.ts
API doesn't allow to pass a meter config to `getMeter`.
Related: #2546
Related: #2547
Removes per-meter config on `MeterProvider.getMeter`.
=> feat(sdk-metrics-base): remove per-meter config on MeterProvider.getMeter

README.md
- Updates main README.md with new URLs of repositories that have been moved
- Updates URLs for plugins (master -> main)
Dup of #2503 with CLA signed and some more fixes.
=> docs: fix URLs in README post-experimental move

experimental/packages/opentelemetry-exporter-trace-otlp-grpc/README.md, experimental/packages/opentelemetry-exporter-trace-otlp-http/README.md, experimental/packages/opentelemetry-exporter-trace-otlp-proto/README.md, experimental/packages/opentelemetry-sdk-metrics-base/README.md, packages/opentelemetry-sdk-trace-base/README.md, packages/opentelemetry-sdk-trace-node/README.md, packages/opentelemetry-sdk-trace-web/README.md
The npm badges on the README page links to the correct npm package but display an incorrect version.
=> chore: update npm badge image links

experimental/packages/opentelemetry-instrumentation/src/autoLoaderUtils.ts, experimental/packages/opentelemetry-instrumentation/test/common/autoLoader.test.ts
preventing double enable for instrumentation that has been already enabled during startup based on default config value
=> fix: preventing double enable for instrumentation that has been already enabled

experimental/packages/opentelemetry-instrumentation/src/autoLoaderUtils.ts, experimental/packages/opentelemetry-instrumentation/src/instrumentation.ts, experimental/packages/opentelemetry-instrumentation/src/platform/node/instrumentation.ts, experimental/packages/opentelemetry-instrumentation/src/platform/node/types.ts, experimental/packages/opentelemetry-instrumentation/src/types.ts, experimental/packages/opentelemetry-instrumentation/src/utils.ts, experimental/packages/opentelemetry-instrumentation/test/common/autoLoader.test.ts
related to #1093,
- This PR fixes lint warnings in `instrumentation` package.
- Note all warnings are resolved. The following warnings are still unresolved since they need better understanding about the code and its usage. I hope I can fix them later when I gain more knowledge about the project.
```
/home/asabzevari/projects/opentelemetry/opentelemetry-js/packages/opentelemetry-instrumentation/src/instrumentation.ts
32:51  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
/home/asabzevari/projects/opentelemetry/opentelemetry-js/packages/opentelemetry-instrumentation/src/platform/node/instrumentation.ts
28:47  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any …
```
=> chore: Fix lint warnings in instrumentation package

experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/tsconfig.json, experimental/packages/opentelemetry-exporter-metrics-otlp-http/tsconfig.esm.json, experimental/packages/opentelemetry-exporter-metrics-otlp-http/tsconfig.json, experimental/packages/opentelemetry-exporter-metrics-otlp-proto/tsconfig.json, experimental/packages/opentelemetry-exporter-trace-otlp-grpc/tsconfig.json, experimental/packages/opentelemetry-exporter-trace-otlp-http/tsconfig.esm.json, experimental/packages/opentelemetry-exporter-trace-otlp-http/tsconfig.json, experimental/packages/opentelemetry-exporter-trace-otlp-proto/tsconfig.json, experimental/packages/opentelemetry-sdk-metrics-base/src/MeterProvider.ts, experimental/tsconfig.esm.json, experimental/tsconfig.json
Now that the core dependencies have been updated, remove the `@ts-ignore` directives. They are actually causing the build to fail now as can be seen here: https://github.com/open-telemetry/opentelemetry-js/runs/4179375965?check_suite_focus=true
=> chore: fix compilation errors

experimental/packages/opentelemetry-instrumentation-xml-http-request/src/types.ts, tsconfig.base.json
Looks like updating to typescript 4.4 caused the compilation to break due to errors being recognized as unknown types. This disables that option temporarily and in a follow-up PR I will update the repo to take advantage of the new default behavior.
=> chore: fix the compilation for typescript 4.4

experimental/packages/opentelemetry-api-metrics/package.json, experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/tsconfig.json, experimental/packages/opentelemetry-exporter-metrics-otlp-http/tsconfig.esm.json, experimental/packages/opentelemetry-exporter-metrics-otlp-http/tsconfig.json, experimental/packages/opentelemetry-exporter-metrics-otlp-proto/tsconfig.json, experimental/packages/opentelemetry-exporter-prometheus/tsconfig.json, experimental/packages/opentelemetry-instrumentation-grpc/tsconfig.json, experimental/packages/opentelemetry-instrumentation/tsconfig.esm.json, experimental/packages/opentelemetry-instrumentation/tsconfig.json, experimental/packages/opentelemetry-sdk-metrics-base/package.json, experimental/packages/opentelemetry-sdk-node/tsconfig.json
This solves the issue where the WIP metrics API and SDK cause problems with existing packages by giving them a version number that does not match the dependencies of the existing packages. This means the released 0.27.0 versions will be used when bootstrapping those packages.
=> chore: rename metrics packages to prevent lerna linking

experimental/packages/opentelemetry-sdk-metrics-base/src/InstrumentDescriptor.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/Instruments.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/Measurement.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/Meter.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/MeterProvider.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/state/MultiWritableMetricStorage.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/state/WritableMetricStorage.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/view/AttributesProcessor.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/view/Predicate.ts, experimental/packages/opentelemetry-sdk-metrics-base/test/view/ViewRegistry.test.ts
In #2629 the metrics API and SDK packages were renamed and made private to prevent them from being linked with other packages by lerna. This PR cleans up some references that were missed and still point to the released API.
=> chore: Update wip metrics references

.github/workflows/peer-api.yaml, experimental/packages/opentelemetry-api-metrics/package.json, experimental/packages/opentelemetry-api-metrics/src/types/Meter.ts, experimental/packages/opentelemetry-api-metrics/src/types/Metric.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/Meter.ts
- Update `MetricOptions` to remove unspecified options
- Update metric creation methods to use new type
- Add optional context to synchronous instruments
- Fixes #2548 
- Fixes #2549 
- Fixes #2552
=> feat: spec compliant metric creation and sync instruments

examples/tracer-web/.eslintrc, examples/tracer-web/README.md, examples/tracer-web/examples/fetch/index.js, examples/tracer-web/examples/fetchXhr/index.html, examples/tracer-web/examples/fetchXhr/index.js, examples/tracer-web/examples/fetchXhrB3/index.html, examples/tracer-web/examples/fetchXhrB3/index.js, examples/tracer-web/examples/metrics/index.js, examples/tracer-web/examples/xml-http-request/index.js, examples/tracer-web/examples/zipkin/index.js, examples/tracer-web/package.json, examples/tracer-web/webpack.dev.config.js, examples/tracer-web/webpack.prod.config.js
fix: Lint issues
Updating to package versions
- webpack to v5
- sdk-trace-xxx to v1.0.1
- instrumentation to v0.27.0
- exporters to v0.27.0
And adds a few additional examples and execution modes to help identify how to use and the resulting bundles sizes based on different configurations
=> chore: update and fix tracer-web examples

examples/tracer-web/examples/fetchXhr/index.js, examples/tracer-web/examples/fetchXhrB3/index.js
Fixing some minor issues in the new combined fetch plus xhr tracer-web examples that was stopping the click event from actually being executed.
=> fix: tracer typo in fetchxhr examples

CONTRIBUTING.md, doc/development-guide.md
This PR addresses some documentation issues
- removes outdated information about the use of Circle CI, as it has been replaced by GitHub Actions in #1711
- updates the link to the `nvm` repository which has been moved to the nvm-sh organization.
- fixes a typo in `CONTRIBUTING.md`
=> docs: remove circle-ci from development guide, update link, and fix typo.

README.md, renovate.json
Since he has stepped down from his responsibilities, @obecny is removed from the list.
He will retain his approver rights for now.
/cc @open-telemetry/javascript-maintainers
=> chore: remove @obecny as maintainer

style.md
This should be considered a living document. Please make suggestions for additional rules if you feel there is something important that has been missed.
=> chore: start a style guide

experimental/packages/opentelemetry-instrumentation-fetch/src/fetch.ts, experimental/packages/opentelemetry-instrumentation-xml-http-request/src/xhr.ts, packages/opentelemetry-exporter-zipkin/src/platform/browser/util.ts, packages/opentelemetry-sdk-trace-web/src/utils.ts, packages/opentelemetry-sdk-trace-web/test/utils.test.ts
Fix the dependencies on window and document API in web packages for WebWorker compatibility.
Related: https://github.com/open-telemetry/opentelemetry-js/issues/1575
- We don't need to access web APIs from window (window === globalThis).
- `parseURL` with URL constructor and fallback to anchor element if possible.
- No longer exposes a document element in sdk-trace-web as public API.
This should be web main frame compatible and worker tests should be introduced in https://github.com/open-telemetry/opentelemetry-js/pull/2659.
=> fix: remove window and document dependencies in web packages

package.json
There are chances that link checks get code 429 on github action. Allow the linkinator to retry with respecting the 'retry-after' header to suppress the "too many requests" code.
Links: https://github.com/open-telemetry/opentelemetry-js/runs/4653698160?check_suite_focus=true
=> chore: retry link checks on code 429 with 'retry-after' header

README.md, renovate.json
Propose Rauno Viskus as maintainer of OpenTelemetry Javascript in recognition of his work on the project. Rauno has shown good judgement in all areas of the project including the API, SDK, and contrib respositories, and has been particularly helpful with maintenance of the contrib repository.
=> chore: add Rauno Viskus as maintainer

README.md, renovate.json
Propose Amir Blum as maintainer of OpenTelemetry Javascript in recognition of his work on the project. Amir has been a long time contributor and has shown good judgement in all areas of the project including the API, SDK, and contrib repositories. He has been particularly helpful in the areas of tracing and instrumentation.
=> chore: add Amir Blum as maintainer

README.md, renovate.json
Propose Chengzhong Wu as maintainer of OpenTelemetry Javascript in recognition of his work on the project. Chengzhong has show good judgement in all areas of the project, and has been especially helpful in development the API and the metrics SDK.
=> chore: add Chengzhong Wu as maintainer

packages/opentelemetry-propagator-jaeger/src/JaegerPropagator.ts, packages/opentelemetry-propagator-jaeger/test/JaegerPropagator.test.ts
0-pad Span ID received from Carrier to 16-characters format according to [Jaeger Propagation Format](https://www.jaegertracing.io/docs/1.29/client-libraries/#propagation-format)
- [*] Bug fix (non-breaking change which fixes an issue)
- [*] Can be verified by using [Jaeger Python Client](https://github.com/jaegertracing/jaeger-client-python) to generate _parent_ spans. Sometimes Python library generates 15-character-length Span ID so OpenTelemetry doesn't create reference to Parent Span
- [*] Followed the style guidelines of this project
- [*] Unit tests have been added
- [-] …
=> fix(propagator-jaeger): 0-pad span-id to match 16-symbol validation

packages/exporter-trace-otlp-grpc/tsconfig.json, packages/exporter-trace-otlp-http/src/OTLPExporterBase.ts, packages/exporter-trace-otlp-http/src/platform/browser/OTLPExporterBrowserBase.ts, packages/exporter-trace-otlp-http/src/platform/node/OTLPExporterNodeBase.ts, packages/exporter-trace-otlp-http/tsconfig.json, packages/exporter-trace-otlp-proto/tsconfig.json, packages/opentelemetry-core/src/index.ts, packages/opentelemetry-core/src/utils/callback.ts, packages/opentelemetry-core/src/utils/promise.ts, packages/opentelemetry-core/test/test-utils.ts, packages/opentelemetry-core/test/utils/callback.test.ts, packages/opentelemetry-core/test/utils/promise.test.ts, packages/opentelemetry-exporter-jaeger/src/jaeger.ts, packages/opentelemetry-sdk-trace-base/src/export/BatchSpanProcessorBase.ts, packages/opentelemetry-sdk-trace-base/src/export/SimpleSpanProcessor.ts
The procedure of shutdown once is implemented at several places. It may be good to have them all to share an abstract BindOnce structure.
=> refactor: unifying shutdown once with BindOnceFuture

.github/workflows/w3c-integration-test.yml, integration-tests/propagation-validation-server/package.json
In the latest changes, one of the package.json is changed and triggered cache invalidations at https://github.com/open-telemetry/opentelemetry-js/blob/main/.github/workflows/w3c-integration-test.yml#L28 and installed @opentelemtry/api with different versions for private package propagation-validation-server (^1.0.3) and lerna package @opentelemtry/sdk-trace-base (~1.0.3 in dev dependencies). Lerna treats this inconsistent semver mark as incompatible semvers and installs different versions for each package.
This leads to the failure of registration of BasicTracerProvider for https://github.com/open-telemetry/opentelemetry-js-api/blob/main/src/internal/global-utils.ts#L53.
- Pin the @opentelemetry/api version in private package `propagation-validation-server` to `~1.0.3`. 
- Hoist all …
=> test(integration-w3c): fix inconsistent api versions loaded

packages/opentelemetry-sdk-trace-base/package.json, packages/opentelemetry-sdk-trace-node/package.json, packages/opentelemetry-sdk-trace-web/package.json
Fixes #2755
Use API 1.1 in SDKs to avoid that SDKs register a TracerProvider,... using an older API then other OTel components.
This avoids the version check in API rejecting the use of API 1.1 but a peer may still use 1.0.x.
CI was failing before
=> fix: use api 1.1 in SDKs

experimental/packages/opentelemetry-sdk-metrics-base/src/Instruments.ts, experimental/packages/opentelemetry-sdk-metrics-base/test/Instruments.test.ts, experimental/packages/opentelemetry-sdk-metrics-base/test/util.ts
Trunc floating-point values if the ValueType is INT for synchronous instruments.
=> feat(sdk-metrics-base): add ValueType support for sync instruments

packages/opentelemetry-sdk-trace-base/src/Tracer.ts, packages/opentelemetry-sdk-trace-base/test/common/Tracer.test.ts
Currently `Sampler` gets a different context then `SpanProcessor` in case `option.root` is set to `true`. This is inconsistent and besides that the `SpanProcessor` might end up in a wrong conclusion regarding parent span which is not intended.
If `options.root` is set the behavior is like no parent span is on context.
Delete a potential span from context and pass this new context to `onStart()` and `shouldSample()`.
- see added tests
=> fix: pass same context to Sampler and SpanProcessor in root span case

README.md
Removed the contrib version column from compatibility matrix because contrib packages
no longer use a common version and release happens quite independent of core.
Therefore having this at a single place in this repo would result in mostly
incomplete/outdated information.
Removed links to individual contrib packages as the list was outdated already and it's
a maintenance pain to keep core repo up to date with unrelated contrib changes.
=> docs: simplify contrib part in readme

packages/exporter-trace-otlp-grpc/package.json, packages/exporter-trace-otlp-http/package.json, packages/exporter-trace-otlp-proto/package.json
This will prevent the exporters from being released when a stable release is cut. They can then be moved to experimental.
=> chore: mark trace exporters private to prevent publish

packages/opentelemetry-core/src/baggage/propagation/W3CBaggagePropagator.ts, packages/opentelemetry-core/test/baggage/W3CBaggagePropagator.test.ts
Solves the problem of extracting the baggage header when it is set inside an array.
Fixes #2831
=> fix(opentelemtry-core): fix header extraction

CHANGELOG.md, integration-tests/propagation-validation-server/package.json, lerna.json, packages/exporter-trace-otlp-grpc/package.json, packages/exporter-trace-otlp-http/package.json, packages/exporter-trace-otlp-proto/package.json, packages/opentelemetry-context-async-hooks/package.json, packages/opentelemetry-context-zone-peer-dep/package.json, packages/opentelemetry-context-zone/package.json, packages/opentelemetry-core/package.json, packages/opentelemetry-exporter-jaeger/package.json, packages/opentelemetry-exporter-zipkin/package.json, packages/opentelemetry-propagator-b3/package.json, packages/opentelemetry-propagator-jaeger/package.json, packages/opentelemetry-resources/package.json, packages/opentelemetry-sdk-trace-base/package.json, packages/opentelemetry-sdk-trace-node/package.json, packages/opentelemetry-sdk-trace-web/package.json, packages/opentelemetry-semantic-conventions/package.json, packages/opentelemetry-shim-opentracing/package.json, packages/template/package.json, selenium-tests/package.json
* [#2588](https://github.com/open-telemetry/opentelemetry-js/pull/2588) feat: spec compliant metric creation and sync instruments ([@dyladan](https://github.com/dyladan))
* [#2569](https://github.com/open-telemetry/opentelemetry-js/pull/2569) feat(api-metrics): async instruments spec compliance ([@legendecas](https://github.com/legendecas))
* [#2707](https://github.com/open-telemetry/opentelemetry-js/pull/2707) feat(sdk-metrics-base): update metric exporter interfaces ([@srikanthccv](https://github.com/srikanthccv))
* [#2776](https://github.com/open-telemetry/opentelemetry-js/pull/2776) feat(sdk-metrics-base): add ValueType support for sync instruments ([@legendecas](https://github.com/legendecas))
* [#2686](https://github.com/open-telemetry/opentelemetry-js/pull/2686) …
=> chore: release proposal 1.1.0

experimental/packages/opentelemetry-sdk-metrics-base/src/MeterProvider.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/index.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/state/MetricStorageRegistry.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/view/Predicate.ts, experimental/packages/opentelemetry-sdk-metrics-base/test/MeterProvider.test.ts, experimental/packages/opentelemetry-sdk-metrics-base/test/util.ts
This PR simplifies the the public API for `MeterProvider.addView()` as mentioned in #2592 and makes `addView()` adhere to the following spec statement:
> In order to avoid conflicts, views which specify a name SHOULD have an instrument selector that selects at most one instrument.
=> feat(views): Update addView() to disallow named views that select more than one instrument.

CHANGELOG.md, README.md
OTLP exporters have been moved back to experimental therefore the corresponding breaking change will be in 0.28.0.
Corrected compat matrix as SDK 1.0 uses API 1.0 and SDK 1.1 use API 1.1.
=> fix: correct changelog and compat matrix for 1.1 release

experimental/CHANGELOG.md, experimental/packages/exporter-trace-otlp-http/src/platform/node/util.ts, experimental/packages/exporter-trace-otlp-http/test/node/CollectorTraceExporter.test.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-http/test/node/CollectorMetricExporter.test.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-proto/test/OTLPMetricExporter.test.ts
Signed-off-by: Svetlana Brennan <svetlana.svn@gmail.com>
OTLP/HTTP and OLTP/PROTO trace exporters are unable to export when gzip compression is used. 
Fixes #2876
Removed `content-length` header when gzip is used. Content-length header was setting the uncompressed length which was causing a timeout export issue. 
Updated existing unit test
=> fix(otlp-http-exporter): remove content length header

CHANGELOG.md, CONTRIBUTING.md, experimental/CHANGELOG.md
Refs: https://github.com/open-telemetry/opentelemetry-js/pull/2881#discussion_r841922681
Simplify the changelog entry format, so that it can be easier for people to manually fill in the entry.
=> docs: simplify changelog entry format

package.json
Fixes #2078 
Remove husky and commitlint. Now that we're using manual changelogs, we don't need to enforce conventional commits so strictly in this repository. I still think we should strive to use them in PR titles, but I have found myself being mostly annoyed by the enforced hooks and using `--no-verify` flag most of the time.
=> chore: remove husky hooks

experimental/CHANGELOG.md, experimental/packages/opentelemetry-sdk-metrics-base/src/MeterProvider.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/export/MetricReader.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/state/MetricCollector.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/types.ts, experimental/packages/opentelemetry-sdk-metrics-base/test/MeterProvider.test.ts, experimental/packages/opentelemetry-sdk-metrics-base/test/export/MetricReader.test.ts
Refs: https://github.com/open-telemetry/opentelemetry-js/issues/2593
- Passthrough ReaderOptions on MeterProvider.shutdown and MeterProvider.forceFlush.
- MeterProvider.shutdown and MeterProvider.forceFlush short-circuit promise rejections by `Promise.all`
- MetricReader throws on bound to a MeterProvider if it is already bound.
=> feat(sdk-metrics-base): shutdown and forceflush on MeterProvider

experimental/CHANGELOG.md, experimental/packages/opentelemetry-sdk-metrics-base/src/Meter.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/MeterProvider.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/state/MeterProviderSharedState.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/state/MeterSharedState.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/state/MetricCollector.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/utils.ts, experimental/packages/opentelemetry-sdk-metrics-base/test/Meter.test.ts, experimental/packages/opentelemetry-sdk-metrics-base/test/MeterProvider.test.ts
As spec defines:
> https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#get-a-meter
> Meters are identified by all of these fields. When more than one Meter of the same name, version, and schema_url is created, it is unspecified whether or under which conditions the same or different Meter instances are returned. The term identical applied to Meters describes instances where all identifying fields are equal. The term distinct applied to Meters describes instances where at least one identifying field has a different value.
Also said:
> https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/datamodel.md#opentelemetry-protocol-data-model-producer-recommendations
> Producers SHOULD prevent the presence of …
=> feat(sdk-metrics-base): meter identity

experimental/packages/opentelemetry-api-metrics/package.json, experimental/packages/opentelemetry-exporter-prometheus/package.json, experimental/packages/opentelemetry-sdk-metrics-base/package.json
Metrics packages were left out of the release on friday because they were marked private
=> Include metrics in release

CHANGELOG.md, experimental/packages/opentelemetry-instrumentation/src/platform/node/instrumentation.ts
A common pitfall for OTEL JS is modules that are `required` before the require-in-the-middle hook is set. In many cases, the end users don't understand why certain instrumentations aren't working, while others do.
Check the require cache when initializing each instrumentation, and alert if the module was already loaded. In case it was - log a warning.
Manually
=> feat: warn when hooked module is already loaded

CHANGELOG.md, experimental/packages/opentelemetry-instrumentation/src/types.ts
Removed the unused field `InstrumentationConfig#path` as it seems it's not used anywhere. The comment there is also outdated so can't tell if it was ever used.
CI
=> chore: remove unused InstrumentationConfig#path

README.md
Marc has done exceptional work on OTel JS and has been very helpful during the push to release metrics.
=> Add pichlermarc to approvers

CHANGELOG.md, experimental/CHANGELOG.md, experimental/packages/opentelemetry-exporter-metrics-otlp-http/test/browser/CollectorMetricExporter.test.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-http/test/metricsHelper.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-http/test/node/CollectorMetricExporter.test.ts, experimental/packages/opentelemetry-exporter-prometheus/src/PrometheusSerializer.ts, experimental/packages/opentelemetry-exporter-prometheus/test/PrometheusSerializer.test.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/export/MetricData.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/state/MeterProviderSharedState.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/state/MeterSharedState.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/state/MetricCollector.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/state/TemporalMetricProcessor.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/utils.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/view/ViewRegistry.ts, experimental/packages/opentelemetry-sdk-metrics-base/test/Instruments.test.ts, experimental/packages/opentelemetry-sdk-metrics-base/test/Meter.test.ts, experimental/packages/opentelemetry-sdk-metrics-base/test/MeterProvider.test.ts, experimental/packages/opentelemetry-sdk-metrics-base/test/export/PeriodicExportingMetricReader.test.ts, experimental/packages/opentelemetry-sdk-metrics-base/test/state/MeterSharedState.test.ts, experimental/packages/opentelemetry-sdk-metrics-base/test/state/MetricCollector.test.ts, experimental/packages/opentelemetry-sdk-metrics-base/test/util.ts, experimental/packages/opentelemetry-sdk-metrics-base/test/view/ViewRegistry.test.ts, experimental/packages/otlp-transformer/src/metrics/internal.ts, experimental/packages/otlp-transformer/test/metrics.test.ts, packages/opentelemetry-core/src/common/types.ts
The spec renamed `InstrumentationLibrary` to `InstrumentationScope`. This PR renames `InstrumentationLibrary` to `InstrumentationScope` to match the spec (**Metrics ONLY**)
- breaking change for experimental packages
=> refactor(metrics-sdk): rename InstrumentationLibrary -> InstrumentationScope

experimental/CHANGELOG.md, experimental/packages/otlp-transformer/README.md, experimental/packages/otlp-transformer/package.json
Previously the esm and esnext files were not included in the `otlp-transformer` package even though their corresponding entry points were defined `package.json`.
This PR also updates the `README.md` file of this package to drop information about not implemented features.
=> fix(otlp-transformer): include esm and esnext in package files and update README

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation/src/platform/node/instrumentation.ts, experimental/packages/opentelemetry-instrumentation/test/node/InstrumentationBase.test.ts
Otherwise, disabling the instrumentation module before actually
requiring the to-be-instrumented module doesn't work, and the module is
patched.
=> fix(instrumentation): only patch core modules if enabled

experimental/CHANGELOG.md, experimental/packages/opentelemetry-sdk-metrics-base/src/Instruments.ts, experimental/packages/opentelemetry-sdk-metrics-base/test/Instruments.test.ts
Currently, Histograms allow for negative values to be recorded. However, the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#record) states this for parameters of the Histogram `record()` function:
> Parameters:
>  - **The amount of the Measurement, which MUST be a non-negative numeric value.**
>  - Optional [attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/README.md#attribute).
This PR changes the Histogram Implementation to drop negative values and to log when they are passed to `record()`. This behavior is in line with the [Python](https://github.com/open-telemetry/opentelemetry-python/blob/741389585b5d6d1af808a8939c5348113158f969/opentelemetry-sdk/src/opentelemetry/sdk/me …
=> fix(sdk-metrics-base): only record non-negative histogram values.

experimental/CHANGELOG.md, experimental/packages/otlp-transformer/src/common/types.ts
Fixes https://github.com/open-telemetry/opentelemetry-js/issues/3020
We have no usage on types of Long and its implementation. Removing the references in types should not break any usage.
=> fix(otlp-transformer): remove type dependency on Long

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation-http/src/utils.ts, experimental/packages/opentelemetry-instrumentation-http/test/functionals/http-enable.test.ts, experimental/packages/opentelemetry-instrumentation-http/test/functionals/utils.test.ts, experimental/packages/opentelemetry-instrumentation-http/test/utils/assertSpan.ts
When an error is captured, it is now recorded as an event using [recordException()](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#record-exception).
Added the `recordException` call right after the status setup in `setSpanWithError()`.
Updated the helper that compares spans so it supports errors being passed and checks if they've been recorded.
=> feat: record exceptions in http instrumentation

experimental/CHANGELOG.md, experimental/packages/opentelemetry-exporter-prometheus/src/PrometheusSerializer.ts, experimental/packages/opentelemetry-exporter-prometheus/src/index.ts, experimental/packages/opentelemetry-exporter-prometheus/test/PrometheusSerializer.test.ts
Fixes #3033
Exports PrometheusSerializer from opentelemetry-exporter-prometheus
The existing test has been switched to include PrometheusSerializer from the package-level export.
=> feat(opentelemetry-exporter-prometheus): export PrometheusSerializer

experimental/CHANGELOG.md, experimental/packages/opentelemetry-sdk-node/README.md, experimental/packages/opentelemetry-sdk-node/src/sdk.ts, experimental/packages/opentelemetry-sdk-node/src/types.ts, experimental/packages/opentelemetry-sdk-node/test/sdk.test.ts, experimental/packages/opentelemetry-sdk-node/test/util/resource-assertions.ts
Fixes #2799
configure service name directly in the node SDK config
add optional serviceName option in node SDK constructor, which behind the scenes creates another resource that is merged with any one that may have been passed in. this occurs after autoDetectResources so that the in code config set service name trumps any env set service name
=> feat(node-sdk): add serviceName config option

.github/workflows/close-stale.yml
There are bugs being closed as stale that are still bugs. IMO a bug should never be stale
=> chore: do not mark bugs stale

experimental/examples/prometheus/index.js, experimental/packages/opentelemetry-sdk-metrics-base/README.md, experimental/packages/opentelemetry-sdk-metrics-base/src/InstrumentDescriptor.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/MeterProvider.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/export/MetricData.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/export/MetricExporter.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/export/MetricProducer.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/export/MetricReader.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/export/PeriodicExportingMetricReader.ts
Part of https://github.com/open-telemetry/opentelemetry-js/issues/3026
=> docs(sdk-metrics): update document on public interfaces

examples/http/README.md
=> typo on example link

experimental/CHANGELOG.md, experimental/packages/opentelemetry-sdk-metrics-base/src/aggregator/Histogram.ts, experimental/packages/opentelemetry-sdk-metrics-base/test/aggregator/Histogram.test.ts
`HistogramAggregator` incorrectly assumes positive-only values, and therefore produces wrong `max` values on export when only negative values are provided (e.g. when `ExplicitBucketHistogramAggregation` is used with `UpDownCounter` via `View` configuration).
This PR fixes this by replacing the default `max` with `-Infinity`
Fixes #3085
=> fix(histogram): fix maximum when only values < -1 are provided

.github/workflows/unit-test.yml
There have been several test failures on node 18 related to lerna running the version command in the wrong directory. This issue may be fixed by the latest version of npm. We should always make sure we are running the latest version when possible.
=> Use latest npm after setup node

experimental/CHANGELOG.md, experimental/packages/exporter-trace-otlp-proto/test/OTLPTraceExporter.test.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-proto/test/OTLPMetricExporter.test.ts, experimental/packages/otlp-proto-exporter-base/.gitignore, experimental/packages/otlp-proto-exporter-base/package.json, experimental/packages/otlp-proto-exporter-base/scripts/protos.js, experimental/packages/otlp-proto-exporter-base/src/OTLPProtoExporterNodeBase.ts, experimental/packages/otlp-proto-exporter-base/src/util.ts, experimental/packages/otlp-proto-exporter-base/tsconfig.json, package.json
Precompile proto files to JS source code and get rid of runtime code generation. Also, this allows exporting traces and metrics in one process simultaneously by not caching the `ExportRequestProto` type.
This doesn't change how otlp-grpc-exporter loads proto files as https://github.com/grpc/grpc-node/tree/master/packages/proto-loader requires raw proto files to load service definitions. 
Fixes https://github.com/open-telemetry/opentelemetry-js/issues/515
The existing tests should cover this change.
=> feat(otlp-proto): pre-compile proto files

experimental/CHANGELOG.md, experimental/packages/opentelemetry-sdk-metrics-base/src/export/PeriodicExportingMetricReader.ts
`PeriodicExportingMetricReader` currently keeps the Node.js process from exiting when not doing an explicit shutdown.
=> fix: don't let PeriodicExportingMetricReader block process exit

experimental/CHANGELOG.md, experimental/packages/opentelemetry-exporter-prometheus/src/PrometheusSerializer.ts, experimental/packages/opentelemetry-exporter-prometheus/test/PrometheusSerializer.test.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/aggregator/Histogram.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/aggregator/types.ts, experimental/packages/opentelemetry-sdk-metrics-base/src/export/MetricData.ts, experimental/packages/opentelemetry-sdk-metrics-base/test/Instruments.test.ts, experimental/packages/opentelemetry-sdk-metrics-base/test/aggregator/Histogram.test.ts, experimental/packages/otlp-transformer/src/metrics/internal.ts, experimental/packages/otlp-transformer/test/metrics.test.ts
With a Histogram Aggregation, `sum` was collected even when using it with instruments like `UpDownCounter` or `ObservableGauge`, which allow negative measurements. However, the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/0b8aa6a375c60d7ed0a5cd4f99263f4800faca3a/specification/metrics/sdk.md?plain=1#L418-L419) states this:
>Arithmetic sum of `Measurement` values in population. This SHOULD NOT be collected when used with
instruments that record negative measurements (e.g. `UpDownCounter` or `ObservableGauge`).
This PR changes the Aggregation so that `sum` is only exported when used with instruments that only allow non-negative values. With the previous approach this would be indicated with a flag. This approach became unwieldy, so instead the type for …
=> feat(histogram): align collection of optional `Histogram` properties with spec

experimental/CHANGELOG.md
This is simply updating the changelog to reflect that a bug was fixed while implementing another feature.
=> chore: update changelog to reflect #3098 fixed #2791

experimental/packages/opentelemetry-instrumentation-fetch/src/fetch.ts
This `spanResponse` object is not used for anything, and I can't figure out its purpose:
https://github.com/open-telemetry/opentelemetry-js/blob/0213d829dc6ab4f7181212bb6f99ebb6538aaabb/experimental/packages/opentelemetry-instrumentation-fetch/src/fetch.ts#L324-L334
The override doesn't make sense, as it sets the same value already present in the initialised object:
https://github.com/open-telemetry/opentelemetry-js/blob/0213d829dc6ab4f7181212bb6f99ebb6538aaabb/experimental/packages/opentelemetry-instrumentation-fetch/src/fetch.ts#L330-L334
I have amended the code to what I think makes sense and was the original intention. Opening a PR to have a discussion.
=> refactor(fetch): revert to original code in endSpanOnSuccess

CHANGELOG.md, experimental/packages/opentelemetry-instrumentation-grpc/src/enums/AttributeValues.ts, experimental/packages/opentelemetry-instrumentation-grpc/src/grpc-js/clientUtils.ts, experimental/packages/opentelemetry-instrumentation-grpc/src/grpc-js/index.ts, experimental/packages/opentelemetry-instrumentation-grpc/src/grpc/clientUtils.ts, experimental/packages/opentelemetry-instrumentation-grpc/src/grpc/index.ts, experimental/packages/opentelemetry-instrumentation-grpc/src/utils.ts, experimental/packages/opentelemetry-instrumentation-grpc/test/utils/extractMethodAndServiceUtils.ts
This PR is extending [**old one**](https://github.com/open-telemetry/opentelemetry-js/pull/3089). Feel free to check it if needs comments
Opentelemtry grpc instrumentation is not consistent in terms of creating grpc attributes in requests.
For example in Java/Python instrumentations it contains necessary attributes for grpc connection:
- rpc.method
- rpc.service
- rpc.system
But these attributes are missed in js grpc instrumentation. It doesn't set attributes. 
Additionally, if compare Python/Java and Nodejs attributes.
Already existing attribute `rpc.method` is implemented incorrectly in Nodejs.
https://github.com/open-telemetry/opentelemetry-js/blob/747c404fb1295d54eb628a434ebf782d2f180bfb/experimental/packages/opentelemetry-instrumentation-grpc/src/grpc-js/clientUtils.ts#L131
Fixes # …
=> GRPC instrumentation. Added new attributes according to the OpenTelemetry rpc convention

experimental/packages/otlp-proto-exporter-base/scripts/protos.js
Fixes https://github.com/open-telemetry/opentelemetry-js/issues/3121
The scripts in `node_modules/.bin` can be a script wrapper on Windows. Run the executable directly instead of running it with node to circumvent the problem.
=> fix(otlp-proto-exporter-base): spawn pbjs without node

CHANGELOG.md, packages/opentelemetry-context-async-hooks/src/AbstractAsyncHooksContextManager.ts, packages/opentelemetry-context-async-hooks/test/AsyncHooksContextManager.test.ts
Fixes https://github.com/open-telemetry/opentelemetry-js/issues/2971
This is an alternative solution to https://github.com/open-telemetry/opentelemetry-js/pull/3132
=> Prevent double wrapping event emitter listeners

.github/workflows/docs.yaml, .github/workflows/lint.yml
Docs deployment has failed for a while. We were also missing some of the packages now that we are back to a single monorepo.
=> Fix docs deployment

CHANGELOG.md, examples/https/README.md, examples/https/client.js, examples/https/docker/docker-compose.yml, examples/https/package.json, examples/https/server.js, lerna.json
Versions on the `https` example were outdated. The example server needed to be run as root, as it was using port `443`. This PR
- changes the port used to `8443` so it can be used with non-root users
- also adds `npm` scripts to easily start Zipkin and Jaeger via docker and docker-compose.
=> chore: update `https` example

CHANGELOG.md, experimental/CHANGELOG.md, experimental/packages/opentelemetry-sdk-node/package.json, experimental/packages/otlp-transformer/package.json, packages/opentelemetry-context-async-hooks/package.json, packages/opentelemetry-context-zone-peer-dep/package.json, packages/opentelemetry-core/package.json, packages/opentelemetry-propagator-b3/package.json, packages/opentelemetry-propagator-jaeger/package.json, packages/opentelemetry-resources/package.json, packages/opentelemetry-sdk-trace-base/package.json, packages/opentelemetry-sdk-trace-node/package.json, packages/opentelemetry-sdk-trace-web/package.json, packages/opentelemetry-shim-opentracing/package.json
Update to reflect most recent API release
=> deps: update API max version

CHANGELOG.md, packages/opentelemetry-core/src/platform/node/hex-to-base64.ts, packages/opentelemetry-core/test/platform/hex-to-base64.test.ts
Improve `hexToBase64` which is used in OTLP exporters to convert span and trace IDs. The previous implementation created a lot of garbage which had to be cleaned up by the GC. Besides the GC overhead, the old version was slow (see the table).
Why not use `Buffer.from(hexStr, 'hex')` instead? It turned out the handwritten one is faster (500k random inputs, Node 16.15):
| Version  | Avg (ns) | diff |
| --- | --- | --- |
| hexToBase64 - new | 1349 | 1.0
| `Buffer.from(str, 'hex').toString('base64')`  | 1995  | 1.48
| hexToBase64 - old  | 3759  | 2.78
=> perf: improve hexToBase64

README.md
Svetlana Brennan (@svetlanabrennan) has been contributing to the OpenTelemetry JavaScript projects actively in a variety of areas, especially OTLP exporters. I believe it would be valuable to have her on the team, and I would like to nominate Svetlana as an approver for the OpenTelemetry JavaScript project.
(@Rauno56 is an incumbent maintainer, delisting the duplicated entry)
=> Add svetlanabrennan as an approver

experimental/CHANGELOG.md, experimental/packages/opentelemetry-sdk-metrics/src/export/MetricData.ts, experimental/packages/opentelemetry-sdk-metrics/src/index.ts, experimental/packages/opentelemetry-sdk-metrics/test/ObservableResult.test.ts, experimental/packages/opentelemetry-sdk-metrics/test/state/MeterSharedState.test.ts, experimental/packages/opentelemetry-sdk-metrics/test/state/MetricCollector.test.ts
`@opentelemetry/sdk-metrics` exports some classes and functions that are intended for internal use. In an effort to reduce the API surface before declaring metrics GA, this PR replaces the existing wildcard exports with explicit exports.
Related: #3158 
Replaces the existing wildcard exports with explicit exports and removes export for:
- AccumulationRecord
- Aggregator
- AggregatorKind 
- Accumulation
- ~~CollectionResult~~
- createInstrumentDescriptor
- createInstrumentDescriptorWithView
- isDescriptorCompatibleWith
- ~~TimeoutError~~
=> chore(sdk-metrics): clean up exports

eslint.config.js
`eslint` rules `@typescript-eslint/no-shadow` (for `*.ts`) and `@typescript-eslint/no-floating-promises` (for `test/**/*.ts`)  were duplicated. 
This PR removes the duplicated `@typescript-eslint/no-shadow` rule and uses the newer entry for `@typescript-eslint/no-floating-promises`.
=> chore: cleanup eslint

experimental/CHANGELOG.md, experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/test/OTLPMetricExporter.test.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/test/metricsHelper.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-http/test/browser/CollectorMetricExporter.test.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-http/test/metricsHelper.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-http/test/node/CollectorMetricExporter.test.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-proto/test/OTLPMetricExporter.test.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-proto/test/metricsHelper.ts, experimental/packages/opentelemetry-exporter-prometheus/src/PrometheusExporter.ts, experimental/packages/opentelemetry-exporter-prometheus/test/PrometheusExporter.test.ts, experimental/packages/opentelemetry-exporter-prometheus/test/PrometheusSerializer.test.ts, experimental/packages/opentelemetry-sdk-metrics/src/export/AggregationSelector.ts, experimental/packages/opentelemetry-sdk-metrics/src/export/MetricReader.ts, experimental/packages/opentelemetry-sdk-metrics/src/export/PeriodicExportingMetricReader.ts, experimental/packages/opentelemetry-sdk-metrics/src/index.ts, experimental/packages/opentelemetry-sdk-metrics/src/state/MeterProviderSharedState.ts, experimental/packages/opentelemetry-sdk-metrics/src/state/MeterSharedState.ts, experimental/packages/opentelemetry-sdk-metrics/src/state/MetricCollector.ts, experimental/packages/opentelemetry-sdk-metrics/src/state/MetricStorage.ts, experimental/packages/opentelemetry-sdk-metrics/src/state/MetricStorageRegistry.ts, experimental/packages/opentelemetry-sdk-metrics/src/view/ViewRegistry.ts, experimental/packages/opentelemetry-sdk-metrics/test/Instruments.test.ts, experimental/packages/opentelemetry-sdk-metrics/test/export/MetricReader.test.ts, experimental/packages/opentelemetry-sdk-metrics/test/export/PeriodicExportingMetricReader.test.ts, experimental/packages/opentelemetry-sdk-metrics/test/export/TestMetricProducer.ts, experimental/packages/opentelemetry-sdk-metrics/test/export/TestMetricReader.ts, experimental/packages/opentelemetry-sdk-metrics/test/state/MeterSharedState.test.ts, experimental/packages/opentelemetry-sdk-metrics/test/state/MetricCollector.test.ts, experimental/packages/opentelemetry-sdk-metrics/test/state/MetricStorageRegistry.test.ts, experimental/packages/opentelemetry-sdk-metrics/test/view/ViewRegistry.test.ts
Add support for per-metric-reader aggregation support
**sdk-metrics-base**
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#metricreader
The spec requires the SDK to allow constructing a MetricReader with an optional aggregation selector and an optional aggregation temporality selector. These selectors are only applicable to the specific metric reader, and should not cause side effects on other metric readers.
=> feat(sdk-metrics-base): per metric-reader aggregation

experimental/CHANGELOG.md, experimental/examples/prometheus/package.json
Update outdated prometheus example
Fixes #3165 
Updated dependencies from 0.28.0 to the latest (0.32.0)
Using the demo app that is included, which demonstrates basic metrics collection and exports those metrics to a Prometheus endpoint
=> chore(deps): update prometheus example dependencies to 0.32

experimental/CHANGELOG.md, experimental/packages/opentelemetry-api-metrics/src/NoopMeter.ts, experimental/packages/opentelemetry-api-metrics/src/index.ts, experimental/packages/opentelemetry-api-metrics/test/api/api.test.ts, experimental/packages/opentelemetry-api-metrics/test/api/global.test.ts, experimental/packages/opentelemetry-api-metrics/test/noop-implementations/noop-meter.test.ts, experimental/packages/opentelemetry-instrumentation/test/common/autoLoader.test.ts, experimental/packages/opentelemetry-sdk-metrics/src/MeterProvider.ts, experimental/packages/opentelemetry-sdk-metrics/test/MeterProvider.test.ts, experimental/packages/opentelemetry-sdk-node/test/sdk.test.ts
`@opentelemetry/api-metrics` exports some classes and constants that are intended for internal use. In an effort to reduce the API surface before declaring metrics GA, this PR replaces the existing wildcard exports with explicit exports.
Related: https://github.com/open-telemetry/opentelemetry-js/issues/3158
Replaces the existing wildcard exports with explicit exports and removes export for:
- `NoopMeter`
- `NoopMetric`
- `NoopCounterMetric`
- `NoopUpDownCounterMetric`
- `NoopHistogramMetric`
- `NoopObservableMetric`
- `NoopObservableCounterMetric`
- `NoopObservableGaugeMetric`
- `NoopObservableUpDownCounterMetric`
- `NOOP_COUNTER_METRIC`
- `NOOP_HISTOGRAM_METRIC`
- `NOOP_UP_DOWN_COUNTER_METRIC`
- `NOOP_OBSERVABLE_COUNTER_METRIC`
- `NOOP_OBSERVABLE_GAUGE_METRIC`
- …
=> chore(api-metrics): clean up exports

package.json
Hypothesis: For some reason it looks like the type definitions for `responselike` are missing and this is failing the build while compiling. `linkinator` depends on this package, and rolling it back to `3.0.3` seems to fix the issue. This issue also only seems to happen in CI and I could not reproduce it on my machine or in docker.
Re-running builds on commits that previously passed now also fail. So this might also be related to caching. 
See this week-old commit as an example: 
- [first attempt from 7 days ago](https://github.com/open-telemetry/opentelemetry-js/actions/runs/2951643982/attempts/1)
- [second attempt from today](https://github.com/open-telemetry/opentelemetry-js/actions/runs/2951643982/attempts/2)
=> fix(build): rollback linkinator to 3.0.3

experimental/packages/opentelemetry-sdk-node/README.md, experimental/packages/opentelemetry-sdk-node/src/sdk.ts
The `@opentelemetry/node-sdk` package's documentation was outdated. This PR updates the metrics documentation of this package.
Related #3224
=> docs(node-sdk): update outdated metric documentation.

experimental/CHANGELOG.md, experimental/packages/opentelemetry-sdk-metrics/src/index.ts, experimental/packages/opentelemetry-sdk-metrics/test/MeterProvider.test.ts, experimental/packages/opentelemetry-sdk-metrics/test/state/MeterSharedState.test.ts
Looks like I missed the export of the SDKs `Meter` during the SDK clean up in #3197. This PR removes the export for `Meter` as the API's `Meter` interface is supposed to be used instead.
Related #3158
=> chore(sdk-metrics): remove accidental export of the SDK Meter class

experimental/CHANGELOG.md, experimental/packages/opentelemetry-api-metrics/src/types/Meter.ts, experimental/packages/opentelemetry-api-metrics/src/types/Metric.ts, experimental/packages/opentelemetry-api-metrics/src/types/ObservableResult.ts, experimental/packages/opentelemetry-api-metrics/test/types/Metric.test.ts
Fixes #3151 
Added generic to `create{metricType}` methods a the types or the metrics.
=> feat(opentelemetry-api-metrics): Adding generics to `create{metricType}`

package.json
We previously rolled back `linkinator` to `3.0.3` due to some typing issues (#3231) that were introduced by the newer version. `4.0.3` of linkinator fixes this issue by dropping the dependency to `update-notifier` which used `responselike` down the chain.
Additional info:
- https://github.com/JustinBeckwith/linkinator/pull/519
- https://github.com/JustinBeckwith/linkinator/releases/tag/4.0.3
=> chore: upgrade linkinator to 4.0.3

CHANGELOG.md, package.json
`markdownlint-cli` was outdated, and `npm audit` complained about it. This PR updates the package to `0.32.2`. :slightly_smiling_face:
- ran the new version of `markdownlint` with the `npm lint:markdown` script included in `package.json` which prompted the changes in #3252
=> deps: update markdownlint-cli to 0.32.2

experimental/CHANGELOG.md, experimental/packages/exporter-trace-otlp-proto/package.json, experimental/packages/opentelemetry-exporter-metrics-otlp-proto/package.json, experimental/packages/otlp-proto-exporter-base/package.json, experimental/packages/otlp-transformer/package.json
`protobufjs` was oudated and unused in some packages. This PR: 
- Moves the dependency on `protobufjs` from `@opentelemetry/exporter-trace-otlp-proto` and `@opentelemetry/exporter-metrics-otlp-proto` to `@opentelemetry/otlp-proto-exporter-base`.
- Removes the dependency on `protobufjs` from `@opentelemetry/otlp-transformer` as it is not used there.
- Adds a dev dependency on `protobufjs-cli` to `@opentelemetry/otlp-proto-exporter-base`, as the CLI has been moved to its own package in https://github.com/protobufjs/protobuf.js/releases/tag/protobufjs-v7.0.0
- Updates all dependencies to `protobufjs` to `7.1.1`
Supersedes #3164
=> deps: remove unused protobufjs and update used ones to 7.1.1

renovate.json
Renovate Bot often tries to bump `@opentelemetry/api` to new versions and lumps that in together with other package updates. This makes renovate bot's PRs hard to impossible to merge. For most packages in this repository, `@opentelemetry/api` is kept at an older version on purpose to ensure maximum compatibility. Any updates should most likely be a conscious decision. 
See #3156
=> chore: ignore @opentelemetry/api in renovate config

CHANGELOG.md, experimental/packages/exporter-trace-otlp-http/README.md, experimental/packages/opentelemetry-instrumentation-fetch/README.md, experimental/packages/opentelemetry-instrumentation-http/README.md, experimental/packages/opentelemetry-instrumentation-xml-http-request/README.md, packages/opentelemetry-context-zone-peer-dep/README.md, packages/opentelemetry-context-zone/README.md, packages/opentelemetry-sdk-trace-base/README.md, packages/opentelemetry-sdk-trace-node/src/index.ts, packages/opentelemetry-sdk-trace-web/README.md, packages/opentelemetry-sdk-trace-web/src/index.ts
Re-export sdk-trace-base members from sdk-trace-node and sdk-trace-web so that people using the platform SDK don't need to depends on the `sdk-trace-base` again.
Fixes https://github.com/open-telemetry/opentelemetry-js/issues/3318
=> feat(sdk-trace): re-export sdk-trace-base in sdk-trace-node and web

.github/workflows/unit-test.yml
This PR pins [`actions/checkout`](https://github.com/actions/checkout/) to `v3.0.2` in the web builds, as `v3.1.0` broke our pipeline.  
Our pipeline uses the `circleci/node:16-browsers` image, which sets the default user to a non-root `circleci` user. This is an unsupported path according to [GitHub Actions documentation](https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions#user). It causes files to be not writable, as they are owned by another user (see https://github.com/actions/checkout/issues/956), thus failing the build on checkout. 
This PR is NOT a permanent solution as we won't be able to update `actions/checkout` without switching to another image, but it will unblock other PRs with failing builds for now.
=> fix(build): pin checkout actions for web build to 3.0.2

.github/workflows/unit-test.yml, CHANGELOG.md, karma.base.js
The circle ci image we've been using for testing was causing permissions issues in github actions. This was the original reason for the permission setting in the action run. Chrome has since been added to the default runner so we actually don't need the image at all.
=> ci: run browser tests without circle

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation/src/platform/node/instrumentation.ts
Fixes https://github.com/open-telemetry/opentelemetry-js/issues/3304
=> fix(instrumentation): debug log on no modules defined for instrumentation

experimental/CHANGELOG.md, experimental/packages/exporter-trace-otlp-grpc/package.json, experimental/packages/exporter-trace-otlp-proto/package.json, experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/package.json, experimental/packages/opentelemetry-exporter-metrics-otlp-proto/package.json, experimental/packages/opentelemetry-instrumentation-grpc/package.json, experimental/packages/otlp-grpc-exporter-base/package.json, experimental/packages/otlp-proto-exporter-base/package.json
* Remove unused `@grpc/proto-loader` dependencies or move them to dev deps where possible.
* Update grpc-js and proto-loader versions: most of the packages contain `grpc-js` with `^1.5.9` versioning, which might install (currently) up to grpc-js 1.7, which depends on proto-loader 0.7.x. However proto-loader dependencies were pinned to patch versions, this would cause duplicate proto-loader package installs.
* Remove exact grpc-js and proto-loader versions from `opentelemetry-instrumentation-grpc`.
=> chore: fix grpc and proto-loader deps

README.md, api/README.md, doc/context.md, doc/sdk-registration.md, doc/tracing.md, packages/opentelemetry-context-async-hooks/README.md
Just removes the link to the deprecated repo. ~~I'll have it archived shortly.~~ 
edit: repo has been archived. PR extended to clean up API readme
=> Update API readme and doc links

packages/sdk-metrics/README.md, packages/sdk-metrics/package.json
sdk-metrics is GA therefore readme should no longer tell it's experimental. Besides that the link to the repo is updated in package.json.
=> chore: remove experimental note in sdk-metrics

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation-http/src/http.ts, experimental/packages/opentelemetry-instrumentation-http/test/functionals/http-enable.test.ts, experimental/packages/opentelemetry-instrumentation-http/test/functionals/https-enable.test.ts
Related: https://github.com/open-telemetry/opentelemetry-js/issues/225
As support for Node.js versions lower than v12 are dropped, `error` events can be monitored without side-effects with `events.errorMonitor`.
=> feat(instrumentation-http): monitor error events with events.errorMonitor

CHANGELOG.md, experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/test/metricsHelper.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-proto/test/metricsHelper.ts, experimental/packages/opentelemetry-exporter-prometheus/package.json, experimental/packages/opentelemetry-exporter-prometheus/test/PrometheusExporter.test.ts, experimental/packages/opentelemetry-exporter-prometheus/test/PrometheusSerializer.test.ts, experimental/packages/opentelemetry-exporter-prometheus/test/util.ts, experimental/packages/opentelemetry-exporter-prometheus/tsconfig.json, packages/sdk-metrics/src/MeterProvider.ts, packages/sdk-metrics/test/util.ts
Currently the Metrics SDK does not comply with the resource semantic conventions (see #3410). 
This PR changes `MeterProvider` to use `Resource.default()` (which already contains the required/recommended attributes), which is then merged with the user-provided resource.
Fixes #3410
=> fix(sdk-metrics): use default Resource to comply with semconv

api/CHANGELOG.md, api/test/tree-shaking/tree-shaking.test.ts
Fixes CI failures in https://github.com/open-telemetry/opentelemetry-js/pull/3208#issuecomment-1312384503.
When small modules are concatenated, variable names are mangled, which fails the matching in the tree-shaking test.
=> test(api): disable module concatenation in tree-shaking test

api/CHANGELOG.md, api/src/metrics/Metric.ts
~~Just a small fix to the metrics API comment I spotted when reviewing https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1281~~
~~Probably it's a missed copy-paste mistake~~
deprecate `MetricAttribute` and `MetricAttributeValue` to align with `SpanAttributes` and `SpanAttributeValue`.
I wonder if it should also be replaced in the api package where it is used (I think yes)
=> fix(api): deprecate MetricAttributes and MetricAttributeValue

CHANGELOG.md, experimental/packages/opentelemetry-instrumentation-grpc/src/grpc-js/index.ts, experimental/packages/opentelemetry-instrumentation-grpc/src/grpc/index.ts, experimental/packages/opentelemetry-instrumentation-grpc/src/utils.ts, experimental/packages/opentelemetry-instrumentation-grpc/test/helper.ts, experimental/packages/opentelemetry-instrumentation-grpc/test/utils/assertionUtils.ts
Set net.peer.name and net.peer.port span attribute on gRPC client spans as a hint to APMs to look for service dependencies. This is a requirement of [OTEL gRPC span conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/span-general.md#common-attributes).
Fixes #3429 
* decode grpc destination URI (typically dns:host:port)
* set as net.peer.name and net.peer.port
* verified net.peer.name and net.peer.port exists as a span attribute in grpc client spans using otel collector
* passes unit tests
=> feat(instrumentation-grpc): set net.peer.name and net.peer.port on client spans

scripts/update-ts-configs-constants.js, scripts/update-ts-configs.js
Change update-ts-config script to generate posix path also on windows to avoid that tsconfig.json files are wrongly modified.
=> chore: improve windows compatibility of update-ts-config

experimental/CHANGELOG.md, experimental/packages/opentelemetry-exporter-prometheus/src/PrometheusSerializer.ts, experimental/packages/opentelemetry-exporter-prometheus/test/PrometheusSerializer.test.ts, integration-tests/propagation-validation-server/package.json
Fixes (issue): https://github.com/open-telemetry/opentelemetry-js/issues/3465
Corrects the string used for NaN in the `PrometheusSerializer` from 'Nan' to 'NaN'.
=> Correct NaN String in the Prometheus Exporter

experimental/CHANGELOG.md, experimental/packages/api-logs/README.md, experimental/packages/api-logs/src/types/LogRecord.ts, experimental/packages/api-logs/test/noop-implementations/noop-logger.test.ts
Our company is also using OpenTelemetry standard for observability. I have been paying attention to the construction of OpenTelemetry, but I found that the Logs capability is not provided. so we developed the implementation of Logs by referring to the design standard. Recently, the community started developing Logs after the Metric stable release was completed. so I want to contribute the code that has been done with reference to the community's latest specifications and style, as well as the recent implementation of Logs in java, to build on and improve the capability of Logs. Accelerate the building of Logs capability so that developers like me can use the stable version of OpenTelemetry capability sooner rather than later. Welcome to participate in the CR and discussion.
We've done …
=> feat(api-logs): add the SeverityNumber enumeration

experimental/CHANGELOG.md, experimental/packages/opentelemetry-sdk-node/README.md, experimental/packages/opentelemetry-sdk-node/src/sdk.ts, experimental/packages/opentelemetry-sdk-node/test/sdk.test.ts, packages/opentelemetry-core/src/utils/environment.ts, packages/opentelemetry-core/test/utils/environment.test.ts
Support for the `OTEL_SDK_DISABLED` env variable. 
In the case of a truthy value, the SDK functions(`start`, `detectResources`) that might create side effects are set to be no-op.
Parsing of boolean env variables. 
=> Feat support otel sdk disabled env

api/CHANGELOG.md, api/src/metrics/ObservableResult.ts
Fixes https://github.com/open-telemetry/opentelemetry-js/issues/3293
Declare the this parameter types for the observable callbacks.
This should not be a breaking change as usages without `this` parameter to be the expected one are not working anyways.
=> fix(api): declare this parameter type in observable callbacks

CHANGELOG.md, packages/sdk-metrics/src/state/MetricStorageRegistry.ts, packages/sdk-metrics/test/state/MetricStorageRegistry.test.ts
Fixes https://github.com/open-telemetry/opentelemetry-js/issues/3472
- Fixes that `MetricStorageRegistry.findOrUpdateCompatibleCollectorStorage` always returns `undefined`, which leads to duplicated registration of metric storage for a collector.
=> fix(sdk-metrics): fix duplicated registration of metrics for collectors

CHANGELOG.md, packages/opentelemetry-core/src/common/time.ts, packages/opentelemetry-core/test/common/time.test.ts
Fixes https://github.com/open-telemetry/opentelemetry-js/issues/3459
Avoid unnecessary stringify of number values as the precision loss is inevitable with `toFixed` too. This also fixes precision loss on numbers without fractional parts.
=> fix(core): fix precision loss in numberToHrtime

.github/repository-settings.md
Following the new guidance at https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md#collaborators-and-teams:
> If requested, `foo-maintainers` will be granted `Admin` permissions, and in return they must document any changes they make to the repository settings in a file named `.github/repository-settings.md` in their repository (other than temporarily disabling "Do not allow bypassing the above settings", see branch protection rules below).
=> Document repo settings

CHANGELOG.md, packages/sdk-metrics/src/export/PeriodicExportingMetricReader.ts, packages/sdk-metrics/test/export/PeriodicExportingMetricReader.test.ts
Fixes https://github.com/open-telemetry/opentelemetry-js/issues/3278
Related spec issue: https://github.com/open-telemetry/opentelemetry-specification/issues/2983
- Collect immediately when the PeriodicExportingMetricReader flushes.
=> fix(sdk-metrics): collect metrics when periodic exporting metric reader flushes

CHANGELOG.md, package.json
Fixes `docs:test` failure in PRs like https://github.com/open-telemetry/opentelemetry-js/pull/3514 and https://github.com/open-telemetry/opentelemetry-js/pull/3517.
- Add plugin `typedoc-plugin-missing-exports` to generate docs for implicitly exported types.
- Add plugin `typedoc-plugin-resolve-crossmodule-references` to generate links between projects in the monorepo.
Tested locally with `NODE_OPTIONS=--max-old-space-size=6144 npm run docs` and verified that the docs are generated as expected.
=> chore: fix cross project links and missing implicitly exported types

packages/opentelemetry-resources/src/Resource.ts
A meaningless typo in `Resource.default` docstring that bothered me.
- [V] Bug fix (non-breaking change which fixes an issue)
Using my browser spellchecker.
- [V] Followed the style guidelines of this project
=> fix(typo): Fix typo in Resource.default docstring

CHANGELOG.md, experimental/packages/otlp-proto-exporter-base/src/platform/browser/OTLPProtoExporterBrowserBase.ts
The protobuf exporter currently sends 'content-type' header as protobuf but 'accept' header as json. Otel collector ignores the accept header and sends the response with protobuf. However, this is an issue with other backends.
Match Accept header with Content-Type in the proto exporter
- [x ] Bug fix (non-breaking change which fixes an issue)
Tested using the opentelemetry-web example.
=> Match Accept header with Content-Type in the proto exporter

experimental/packages/otlp-proto-exporter-base/scripts/protos.js
Seems protobufjs 7.2.0 requires to include a search path.
=> chore: fix proto generation

CHANGELOG.md, experimental/CHANGELOG.md, experimental/packages/otlp-transformer/src/trace/internal.ts, experimental/packages/otlp-transformer/test/trace.test.ts, packages/opentelemetry-sdk-trace-base/src/export/ConsoleSpanExporter.ts, packages/opentelemetry-sdk-trace-base/test/common/export/ConsoleSpanExporter.test.ts
fix: include TraceState in trace exports
Include TraceState in OTEL spans and links.
Print span.traceState in ConsoleSpanExporter.
=> fix: include TraceState in trace exports

experimental/CHANGELOG.md, experimental/packages/exporter-trace-otlp-proto/tsconfig.esm.json, experimental/packages/exporter-trace-otlp-proto/tsconfig.esnext.json, experimental/packages/otlp-proto-exporter-base/tsconfig.esm.json, experimental/packages/otlp-proto-exporter-base/tsconfig.esnext.json, tsconfig.esm.json, tsconfig.esnext.json
Regenerated some tsconfig.json file because they are shown as modified by git after `npm install`.
Refs: https://github.com/open-telemetry/opentelemetry-js/pull/3208
=> fix: remove JSON syntax error and regenerate tsconfig files

CHANGELOG.md, packages/sdk-metrics/test/aggregator/LastValue.test.ts
This PR fixes the flaky test described in #3572 by using fake timers instead of setting and awaiting timeouts.
Fixes #3572 
=> fix(sdk-metrics): fix flaky LastValueAggregator test by using fake timer

.github/repository-settings.md
On advice of @legendecas consider merge queues. This can help in the case that many PRs are ready to be merged but have to each be manually merged and updated.
=> chore: enable merge queues

.github/workflows/lint.yml, .github/workflows/peer-api.yml, .github/workflows/unit-test.yml, .github/workflows/w3c-integration-test.yml
Currently, all queued items are pending for check status to be reported: https://github.com/open-telemetry/opentelemetry-js/queue/main
Refs: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions
=> chore: enable merge queue checks

experimental/CHANGELOG.md, experimental/packages/opentelemetry-sdk-node/README.md, experimental/packages/opentelemetry-sdk-node/src/sdk.ts, experimental/packages/opentelemetry-sdk-node/test/sdk.test.ts
Register diag logger with environ `OTEL_LOG_LEVEL`.
Fixes https://github.com/open-telemetry/opentelemetry-js/issues/3312
=> feat(sdk-node): install diag logger with OTEL_LOG_LEVEL

experimental/packages/opentelemetry-instrumentation-http/src/http.ts
Noticed while working on #3625.
Fixes # n/a
Just removing an unused argument
n/a
=> chore: remove unused argument

api/src/internal/global-utils.ts, api/test/common/internal/global.test.ts
The logging when api versions don't match in `registerGlobal` is not very helpful.  This adds all the relevant information to debug problems with this scenario.
Add the type and the two mismatched version numbers to the mismatched version log message.
The previous unit test attempting to cover this case was not actually covering it because context global registration is
`!allowOverride` (the default), so I switched the test to use `diag` instead.  Now the `if (api.version !== VERSION)` block is actually hit by the unit test.
- [ x ] Followed the style guidelines of this project
- [ x ] Unit tests have been added
=> chore: improve logging for api registration mismatches

CHANGELOG.md, packages/opentelemetry-core/src/utils/environment.ts, packages/opentelemetry-sdk-trace-web/test/NodeGlobalsFoolProofing.test.ts
Fixes [#3613](https://github.com/open-telemetry/opentelemetry-js/issues/3613)
Some customers of ours are using webpack where they had set all node globals to false (https://webpack.js.org/migrate/5/), as suggested by Stack overflow responses such as https://stackoverflow.com/questions/64557638/how-to-polyfill-node-core-modules-in-webpack-5 where best voted answers suggest devs to set Node Globals as false as a fallback. Current check on `process` was doing a plain type check to see equality with undefined however typeof false is boolean & typeof null is object.
To ensure that OTEL works with any config having undefined/null/false, this PR was raised.
Added falsy checks while using `process` in browser environment to ensure that the OTEL can work with projects where webpack config has …
=> fix(core): added falsy check to make otel core work with browser where webpack config had process as false or null

packages/opentelemetry-sdk-trace-base/test/browser/export/BatchSpanProcessor.test.ts
The BatchSpanProcessor.test.ts is using the type `VisibilityState`, this was removed from TypeScript v4.6.0+
As part of merging the JS and Contrib repo's to the web js sandbox, which is using a later version of TypeScript this test fails to build. The sandbox also attempts to run all tests in node, browser and web worker automatically as part of merging.
This change is required so that the code can be successfully merged to the sandbox.
=> fix: batchspanprocessor.test for TS > 4.6.0

CHANGELOG.md, packages/opentelemetry-resources/src/platform/node/HostDetectorSync.ts, packages/opentelemetry-resources/src/platform/node/machine-id/execAsync.ts, packages/opentelemetry-resources/src/platform/node/machine-id/getMachineId-bsd.ts, packages/opentelemetry-resources/src/platform/node/machine-id/getMachineId-darwin.ts, packages/opentelemetry-resources/src/platform/node/machine-id/getMachineId-linux.ts, packages/opentelemetry-resources/src/platform/node/machine-id/getMachineId-unsupported.ts, packages/opentelemetry-resources/src/platform/node/machine-id/getMachineId-win.ts, packages/opentelemetry-resources/src/platform/node/machine-id/getMachineId.ts, packages/opentelemetry-resources/test/detectors/node/HostDetector.test.ts, packages/opentelemetry-resources/test/detectors/node/machine-id/getMachineId-bsd.test.ts, packages/opentelemetry-resources/test/detectors/node/machine-id/getMachineId-darwin.test.ts, packages/opentelemetry-resources/test/detectors/node/machine-id/getMachineId-linux.test.ts, packages/opentelemetry-resources/test/detectors/node/machine-id/getMachineId-win.test.ts
This PR adds `host.id` resource attribute collection to the HostDetector. The `host.id` is currently collected by the cloud provider Detectors (AWS EC2, GCP, etc), but not collected for non-cloud environments. See [the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/host.md#host) and description (copied) below:
> Unique host ID. For Cloud, this must be the instance_id assigned by the cloud provider. For non-containerized Linux systems, the machine-id located in /etc/machine-id or /var/lib/dbus/machine-id may be used.
This PR includes code to collect the `host.id` based on this pending spec work: https://github.com/open-telemetry/opentelemetry-specification/pull/3173.
The tl;dr is that the following sources should be …
=> feat: detect host id for non-cloud environments

.nycrc, CHANGELOG.md
Windows tests are currently running out of heap space, which seems to be related to source map merging. As far as I can tell, we're already generating source maps for the browser/webworker tests, and using ts-mocha already provides us with source-maps. While investigating #3628, I found that the merging of source maps (persumably merging the existing ones and the ones generated by nyc/istanbul) is what allocates a lot of memory. This PR disables the generation of source maps and reduces the amount of memory used significantly from >3.9GB to 174MB
Fixes #3628 
Prevent source map generation by `nyc`
=> fix(test): fix failing tests by preventing source-map generation

CHANGELOG.md, experimental/packages/opentelemetry-instrumentation-http/src/utils.ts, experimental/packages/opentelemetry-instrumentation-http/test/functionals/utils.test.ts
According [to the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#http-server-semantic-conventions), `http.target` attribute should include path + query params, current implementation sets the path without query params.
Attribute | Type | Description | Examples | Requirement Level
-- | -- | -- | -- | --
http.target | string | The full request target as passed in a HTTP request line or equivalent. | /path/12314/?q=ddds | Required
Fix `http.target` to use [urlObject.path](https://nodejs.org/docs/latest-v19.x/api/url.html#urlobjectpath) and not [urlObject.pathname](https://nodejs.org/docs/latest-v19.x/api/url.html#urlobjectpathname) which is the value the includes the query params.
Bug fix
Created a new unit test …
=> fix(instrumentation-http): include query params in http.target

api/CHANGELOG.md, api/src/diag/types.ts
Conflicting type name `LoggerOptions` in API and experimental logs API
Fixes #3640 
Renaming `LoggerOptions` to `DiagLoggerOptions`
N/A
=> Rename Diag/LoggerOptions to DiagLoggerOptions

api/CHANGELOG.md, api/src/index.ts
- `DiagLoggerApi.setLogger` has two overrides. One of them has `options: DiagLoggerOptions` parameter. However, `DiagLoggerOptions` is not exported through `index.ts`. 
Fixes #3638 
Exporting `DiagLoggerOptions` interface in index.ts
N/A
=> Export DiagLoggerOptions Type

experimental/CHANGELOG.md, experimental/packages/opentelemetry-sdk-node/src/sdk.ts, experimental/packages/opentelemetry-sdk-node/src/types.ts, experimental/packages/opentelemetry-sdk-node/test/sdk.test.ts
Add ability to override `idGenerator` when using NodeSDK
Fixes #3435 
Add 'idGenerator' to the configuration of NodeSDK
I added a test that creates NodeSDK with a custom idGenerator object, then I created span and verified it has the id that my custom generator generates. (a constant id just for testing)
=> feat(sdk-node): override IdGenerator when using NodeSDK

experimental/CHANGELOG.md
When this [retry pr ](https://github.com/open-telemetry/opentelemetry-js/pull/3207)was merged, the changelog was in the wrong place. This retry feature hasn't been released yet so the changelog needs to be under Unreleased. 
=> fix(otlp-exporter-base): fix changelog for merged retry pr

CHANGELOG.md, examples/http/client.js, examples/http/package.json, examples/http/server.js, lerna.json
The `http` example had outdated dependencies, and were still using older functions for getting active spans when newer convenience APIs are available now.
- Updates dependencies in `package.json`
- It seems like these are usually updated with each release now, but this was further behind than the others so it probably wasn't as obvious with a Find/Replace
- Uses newer `startActiveSpan()` and `getActiveSpan()`
=> chore: update http example

experimental/CHANGELOG.md, experimental/packages/opentelemetry-sdk-node/src/sdk.ts, experimental/packages/opentelemetry-sdk-node/src/utils.ts
In `@opentelemetry/sdk-node` instrumentations are registered before the SDK `MeterProvider` is registered, causing the instrumentations to be left with a `NoopMeterProvider`, and subsequently `NoopMeter` and then no-op instruments, which causes all metrics data provided to these instruments to be dropped.
This is only the case for metrics, as the Trace API implements a delegating no-op instead. Once we implement a delegating no-op for the Metrics API (#3622), the workaround proposed by this PR will become obsolete.
Fixes #3609 
Updates instrumentations once MeterProvider is registered to avoid no-ops being used.
=> fix(sdk-node): update instrumentations once MeterProvider is initialized

scripts/update-ts-configs.js
`npm install` fails on `update-ts-configs`
```
> node scripts/update-ts-configs.js
node:internal/fs/utils:346
throw err;
^
Error: ENOENT: no such file or directory, open '/workspaces/opentelemetry-js/examples/http/tsconfig.json'
at Object.openSync (node:fs:585:3)
at Object.readFileSync (node:fs:453:35)
at readJSON (/workspaces/opentelemetry-js/scripts/update-ts-configs.js:281:26)
at readAndMaybeMergeTsConfig (/workspaces/opentelemetry-js/scripts/update-ts-configs.js:250:20)
at writeSingleTargetTsConfig (/workspaces/opentelemetry-js/scripts/update-ts-configs.js:148:14)
at generateTsConfig (/workspaces/opentelemetry-js/scripts/update-ts-configs.js:95:3)
at main (/workspaces/opentelemetry-js/scripts/update-ts-configs.js:76:5)
at Object.<anonymous> …
```
=> fix(build): add `example/http` to ignore list in `update-ts-configs`

experimental/packages/opentelemetry-instrumentation-fetch/src/fetch.ts, packages/opentelemetry-context-zone-peer-dep/src/util.ts, packages/opentelemetry-sdk-trace-web/src/utils.ts
The web sandbox is using a later version of TypeScript and these fixes are just typing updates to allow the sandbox to merge and compile.
Tested locally (on windows) and by duplicating the changed in a local sandbox branch
=> fix: Minor typing issues for web sandbox

CONTRIBUTING.md
Following a conversation with @martinkuba, I realized the `CONTRIBUTING.md` did not reflect the policies most recently agreed to in the SIG meetings and implemented in the repository settings. This PR is meant to clarify the merge requirements and who should merge PRs when they are ready.
=> docs: update CONTRIBUTING.md merge requirements

CHANGELOG.md, packages/opentelemetry-resources/src/Resource.ts, packages/opentelemetry-resources/test/Resource.test.ts, packages/opentelemetry-resources/test/regression/existing-detectors-1-9-1.test.ts, packages/opentelemetry-sdk-trace-base/src/export/SimpleSpanProcessor.ts
See #3676, existing detectors that previously worked with `1.9.1` do not compile anymore. This PR fixes this, but will break the use of `resource.waitForAsyncAttributes()` that was introduced in the most recent version. Looks like this is the only way to restore compatibility. I'm open to any suggestions to improve this. 
Fixes #3676
Fixes open-telemetry/opentelemetry-js-contrib#1429
- make properties for async resource resolution optional
> **What do I do if I accidentally release a backwards incompatible change as a minor version?**
> 
> As soon as you realize that you’ve broken the Semantic Versioning spec, fix the problem and release a new minor version that corrects the problem and restores backwards compatibility. Even under this circumstance, it is unacceptable to modify versioned …
=> fix(resource): make properties for async resource resolution optional

CHANGELOG.md, packages/opentelemetry-resources/src/platform/node/machine-id/getMachineId-bsd.ts, packages/opentelemetry-resources/src/platform/node/machine-id/getMachineId-linux.ts, packages/opentelemetry-resources/test/detectors/node/machine-id/getMachineId-bsd.test.ts, packages/opentelemetry-resources/test/detectors/node/machine-id/getMachineId-linux.test.ts
This PR changes the import according to https://github.com/nodejs/node/issues/35740#issuecomment-713778857 to make the default detectors work again with Node.js v12. 
**Note: Node.js <14 remains unsupported by this project.**
Fixes #3673 
**Note: CI does not run for Node 12**
=> fix(resources): change fs/promises import to be node 12 compatible

CHANGELOG.md, experimental/packages/opentelemetry-sdk-node/README.md
The start() method in the NodeSDK class has been recently updated to be synchronous (in https://github.com/open-telemetry/opentelemetry-js/pull/3460) - it no longer returns a promise. This is a minor update to the example in the corresponding README.
=> Updated Node SDK example in README

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation-xml-http-request/src/xhr.ts, experimental/packages/opentelemetry-instrumentation-xml-http-request/test/xhr.test.ts
Fix span name on package instrumentation-xml-http-request after pull #3603  
Remove `HTTP` on span name
Unit test
=> fix!: span name on instrumentation-xml-http-request

CHANGELOG.md, packages/opentelemetry-sdk-trace-web/src/utils.ts, packages/opentelemetry-sdk-trace-web/test/window/utils.test.ts
Noticed that [fetch instrumentation](https://github.com/open-telemetry/opentelemetry-js/tree/main/experimental/packages/opentelemetry-instrumentation-fetch) breaks web apps that provide relative urls to `window.fetch` and have URL base explicitly set via a [base element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base). The root cause seems to be `parseUrl`, which resolves absolute URL using `location.href` as URL base when it should use [document.baseURI](https://www.w3schools.com/jsref/prop_doc_baseuri.asp). 
Makes `parseUrl` use `document.baseURI` when available and fall back to `location.href` when not (web workers). 
I'm attempting to instrument [Grafana](https://github.com/grafana/grafana) frontend with tracing. If fetch …
=> fix(sdk-trace-web): make parseUrl respect document.baseURI

experimental/packages/opentelemetry-exporter-metrics-otlp-http/README.md
Just a small fix in the code in the readme. Based on the context, it should be `metricExporter` instead of not existing `exporter`. 😃
=> docs(readme): exporter should be metricExporter

README.md, experimental/examples/prometheus/README.md, experimental/packages/opentelemetry-exporter-prometheus/README.md
Fix broken links to OpenTelemetry Metrics documentation
=> docs: fix links to OpenTelemetry Metrics documentation

experimental/CHANGELOG.md, experimental/packages/opentelemetry-sdk-node/src/sdk.ts, experimental/packages/opentelemetry-sdk-node/test/sdk.test.ts
Since #3627 `DiagConsoleLogger` is instantiated and set even when `OTEL_LOG_LEVEL` is unset, which can cause unintended logs to appear on the console.
This PR changes it, so the environment is used before it is merged with the default values.  
Related #3683
=> fix(sdk-node): only set DiagConsoleLogger when OTEL_LOG_LEVEL is set

.github/workflows/unit-test.yml
`api-eol-node-test` is failing as it uses typescript 5.0.2 to compile tests.
This PR changes the job to use the typescript version from package.json to compile the API & tests.
=> fix(ci): use npx to run tsc 4.4.4 in api-eol-node-test

experimental/packages/opentelemetry-instrumentation-http/test/functionals/https-enable.test.ts, packages/opentelemetry-context-async-hooks/test/AsyncHooksContextManager.test.ts
Extracted from #3689.
Fixes # N/A
CI only runs on Node 14+, so this is dead code
Housekeeping
CI
=> chore: remove handling of node versions 8, 9 and 10 in tests

CHANGELOG.md, experimental/packages/opentelemetry-instrumentation-http/src/http.ts, experimental/packages/opentelemetry-instrumentation-http/test/functionals/http-metrics.test.ts
Updates description for HTTP auto instrumentation metrics to match [semantic conventions.](https://github.com/open-telemetry/opentelemetry-specification/blob/main/semantic_conventions/metrics/http.yaml#LL5C10-L5C10)
If the proper description is not provided the Prometheus exporter from the OpenTelemetry Collector will report an error on the `http.server.duration` metric.
Fixes [this issue](https://github.com/open-telemetry/opentelemetry-demo/issues/737) in the Demo repo.
=> fix(instrumentation-http): use semantic convention metric descriptions

CHANGELOG.md, packages/opentelemetry-sdk-trace-web/src/utils.ts, packages/opentelemetry-sdk-trace-web/test/utils.test.ts
Fetch autoinstrumentation currently always pulls in opentelemetry-sdk-trace-web, where it calls into code that tries to access `location.href`
This is fine in browser contexts, but in server runtimes where `location` isn't defined (e.g. Node, Deno) this crashes.
https://github.com/open-telemetry/opentelemetry-js/issues/3413 tracks the broader work to make Fetch autoinstrumentation isomorphic, but I figured getting this one piece fixed for Deno couldn't hurt.
Fixes a subpiece of #3413 
Checks if `location` exists before accessing it
- [ x] Bug fix (non-breaking change which fixes an issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test …
=> fix(opentelemetry-sdk-trace-web): don't crash in runtimes where location isn't defined

README.md, experimental/CHANGELOG.md, experimental/packages/opentelemetry-sdk-node/src/types.ts
`NodeSDKConfiguration.defaultAttributes` was unused, this PR removes it and adds upgrade guidelines to `README.md`
Fixes #3717 
- `@opentelemetry/sdk-node` is still experimental
- causes compilation errors when upgrading, and `NodeSDKConfiguration.defaultAttributes` is still used
=> fix(sdk-node)!: remove unused defaultAttributes option

experimental/CHANGELOG.md, experimental/examples/logs/package.json, experimental/packages/sdk-logs/package.json
After merging the release I noticed the new logs SDK didn't get its version bumped
=> Logs version fixup

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation/package.json
This includes a RITM feature to allow reloading (and re-run of
the RITM hook) of non-core modules when deleting them from
'require.cache'.
Fixes: #3655
=> fix(instrumentation): update dep require-in-the-middle to 7.0.1

experimental/packages/sdk-logs/test/browser/export/BatchLogRecordProcessor.test.ts, packages/opentelemetry-sdk-trace-base/test/browser/export/BatchSpanProcessor.test.ts
This is the same fix as for BatchSpanProcessor tests in https://github.com/open-telemetry/opentelemetry-js/pull/3636, but for logs.
The VisibilityState type was renamed to DocumentVisibilityState in typescript 4.6. Once typescript is updated, we should change this temporary type to DocumentVisibilityState. The reason for adding this now is because packages from this repo are merged into the [sandbox repo](https://github.com/open-telemetry/opentelemetry-sandbox-web-js) which uses a newer version of typescript.
=> fix: VisibilityState type for typescript >4.6

CHANGELOG.md, experimental/packages/opentelemetry-sdk-node/src/TracerProviderWithEnvExporter.ts, packages/opentelemetry-exporter-jaeger/README.md
The JaegerExporter currently does not support running in bundled environments, as requiring jaeger-client loads .thrift files from the file system. This causes problems in @opentelemetry/sdk-node as the JaegerExporter is required even though it is unused, see https://github.com/open-telemetry/opentelemetry-js/issues/3521).
To circumvent this problem, this PR changes the approach of always requiring `'@opentelemetry/exporter-jaeger'` to do it once before the constructor is actually called. Further added documentation to clarify that bundling is not supported with this package.
**This PR does not add support for running the JaegerExporter in a bundled environment.**
Fixes #3521
Supersedes #3728 
- Pulling in relevant code from `jaeger-client` and pre-generating JS code from the `.thrift` …
=> fix(sdk-node): lazy require @opentelemetry/exporter-jaeger

experimental/CHANGELOG.md, experimental/packages/otlp-transformer/src/metrics/internal.ts
As the types in metrics expand, it is better using switch cases than multiple `if-else`s.
Also fixed a "`scopeMetrics` is already declared in the upper scope" warning.
This is a follow-up of https://github.com/open-telemetry/opentelemetry-js/pull/3712#discussion_r1169754148.
=> refactor(otlp-transformer): refine metrics transformer

experimental/packages/opentelemetry-shim-opencensus/package.json, experimental/packages/opentelemetry-shim-opencensus/src/propagation.ts, experimental/packages/opentelemetry-shim-opencensus/src/transform.ts, experimental/packages/opentelemetry-shim-opencensus/test/propagation.test.ts, experimental/packages/opentelemetry-shim-opencensus/test/transform.test.ts
Part of #3749 [PR 2 of 5]
**Finished state of this feature: https://github.com/open-telemetry/opentelemetry-js/pull/3778**
Adds some of the basic mapping logic between OpenCensus <-> OpenTelemetry interfaces. This will be used in the next PR (https://github.com/open-telemetry/opentelemetry-js/pull/3756) which adds the Shim tracer and span implementations. As before, I'll update the changelog in the final PR of the series.
=> feat(opencensus-shim) add mapping logic and propagation shim

experimental/CHANGELOG.md, experimental/packages/opentelemetry-sdk-node/src/types.ts
~~contrib repo currently fails to build because of issue with `@opentelemetry/resource-detector-instana`:~~ (sorry that was not correct, I needed to update the branch, but the fix is relevant regardless).
```
test/InstanaAgentDetectorIntegrationTest.test.ts:62:7 - error TS2322: Type 'import("/Users/amirblum/repos/opentelemetry-js-contrib/node_modules/@opentelemetry/resources/build/src/Resource").Resource' is not assignable to type 'import("/Users/amirblum/repos/opentelemetry-js-contrib/node_modules/@opentelemetry/sdk-node/node_modules/@opentelemetry/resources/build/src/Resource").Resource'.
Types have separate declarations of a private property '_syncAttributes'.
62       resource: globalResource,
~~~~~~~~
test/InstanaAgentDetectorIntegrationTest.test.ts:101:7 - error TS2322: Type …
```
=> fix(sdk-node): use resource interface instead of concrete class

experimental/CHANGELOG.md, experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/src/OTLPMetricExporter.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/test/OTLPMetricExporter.test.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-http/src/platform/node/OTLPMetricExporter.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-http/test/node/CollectorMetricExporter.test.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-proto/src/OTLPMetricExporter.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-proto/test/OTLPMetricExporter.test.ts
Updates #3291 
- add user agent to otlp grpc metric exporter
- add user agent to otlp http/json metric exporter
- add user agent to otlp http/proto metric exporter
- add unit tests for the above changes
=> feat(otlp-metric-exporters): Add User-Agent header to OTLP metric exporters

.github/workflows/label-releases.yml, package.json
The release label will be used in the next step which is to actually release the packages to NPM
=> Add scripts to prepare releases automatically

experimental/CHANGELOG.md, experimental/packages/sdk-logs/src/Logger.ts, experimental/packages/sdk-logs/src/LoggerProvider.ts, experimental/packages/sdk-logs/src/index.ts, experimental/packages/sdk-logs/src/types.ts, experimental/packages/sdk-logs/test/common/Logger.test.ts, experimental/packages/sdk-logs/test/common/LoggerProvider.test.ts
=> [sdk-logs] remove includeTraceContext configuration and use LogRecord context when available

README.md
Adding @hectorhdzg to the approvers list in recognition of his ongoing work in OpenTelemetry JS.
=> Add Hector to approvers

experimental/packages/exporter-logs-otlp-http/package.json
Remove unused `rimraf` dependency, see #3738 #3737
=> deps(exporter-logs-otlp-http): remove unused rimraf devDependency

packages/opentelemetry-semantic-conventions/README.md
This PR fixes the OpenTelemetry Semantic Conventions URL used in the readme file of the `opentelemetry-semantic-conventions` package. In the last release (`v1.21.0`) of the [Opentelemetry Specification](https://github.com/open-telemetry/opentelemetry-specification) the [Semantic Conventions](https://github.com/open-telemetry/semantic-conventions) section was moved to a separate repository.
Fix URL in readme file.
=> fix(opentelemetry-semantic-conventions): update trace semantic conventions url

experimental/packages/exporter-logs-otlp-grpc/test/OTLPLogExporter.test.ts
The test server in the logs gRPC exporter module are currently using port 1501, which is the same as the test server used in the trace exporter tests, which causes tests to fail when they're run in parallel with lerna.
This PR changes the port in the gRPC logs exporter tests to use port 1503 (1502 is already used by the metrics exporter tests) instead. 
=> fix(exporter-logs-otlp-grpc): make test server use port 1503

examples/esm-http-ts/package.json, experimental/packages/otlp-transformer/package.json
Some versions are not aligned with the most recent version of the `@opentelemetry/*` packages. This PR aligns these versions in preparation for #3894, as `npm` workspaces do not allow multiple versions of a locally linked package.
=> chore: fix misaligned dependency versions

experimental/CHANGELOG.md, experimental/packages/exporter-logs-otlp-http/package.json, experimental/packages/exporter-logs-otlp-http/src/platform/browser/OTLPLogExporter.ts, experimental/packages/exporter-logs-otlp-http/src/platform/node/OTLPLogExporter.ts, experimental/packages/exporter-logs-otlp-http/test/browser/OTLPLogExporter.test.ts, experimental/packages/exporter-logs-otlp-http/test/logHelper.ts, experimental/packages/exporter-logs-otlp-http/test/node/OTLPLogExporter.test.ts, experimental/packages/exporter-logs-otlp-http/tsconfig.json
When we use the `OTLPLogExporter` to send logs to a collector I face this issue:
```
readLog.traceId: parse trace_id:invalid length for ID, error found
```
When I look at what the exporter send, traceId look like this `x+wKeY+LpUblmgFbiqXBwQ==` which is base64. that a bug we should have an hex.
When I look at `OTLPTraceExporter` i notice it adds an extra parameter `true` to this function `createExportLogsServiceRequest` which disable the mapping to base64.
This PR replicate this behavior to `OTLPLogExporter`
`createExportLogsServiceRequest` function used in OTLPLogExporter now have an extra parameter `true` to use hex format
Has been tested in TDD and i had a single new test
=> fix(exporter-logs-otlp-http): set useHex to true

experimental/CHANGELOG.md, experimental/packages/otlp-proto-exporter-base/src/platform/util.ts
See #3921, a type import is missing that causes compilation to fail when using any proto exporters.
Fixes #3921
=> fix(otlp-proto-exporter-base): add missing type import

experimental/CHANGELOG.md, experimental/examples/opencensus-shim/package.json, experimental/examples/opencensus-shim/setup.js
Currently the opencensus-shim example imports `@opencensus/nodejs` which also imports `@opencensus/instrumentation-all` and `grpc` and causes build fails on many platforms.
Changed `@opencensus/nodejs` to `@opencensus/nodejs-base` which does not include instrumentations. 
=> fix(example-opencensus-shim): avoid OpenCensus auto instrumentations

CHANGELOG.md, experimental/packages/opentelemetry-exporter-prometheus/src/PrometheusExporter.ts, experimental/packages/opentelemetry-exporter-prometheus/src/PrometheusSerializer.ts, experimental/packages/opentelemetry-exporter-prometheus/test/PrometheusExporter.test.ts, experimental/packages/opentelemetry-exporter-prometheus/test/PrometheusSerializer.test.ts
This PR amends the Prometheus Exporter to be in line with the [text based exposition format](https://github.com/prometheus/docs/blob/main/content/docs/instrumenting/exposition_formats.md#text-based-format).
Fixes #3463 
Updates the default mode of the Prometheus Exporter to not append timestamp.
=> Update the Prometheus Exporter to by Default not Append Timestamp

experimental/packages/opentelemetry-sdk-node/tsconfig.json
Retrospectively update tsconfig dependencies with `scripts/update-ts-config.js`.
Refs: https://github.com/open-telemetry/opentelemetry-js/pull/3969
=> chore: apply update-ts-configs

CHANGELOG.md, experimental/packages/exporter-logs-otlp-http/package.json
This PR is adding the opentelemetry-api as a dev dependency to the exporter-logs-otlp-http as the tests are directly importing the otel-api and this is breaking when importing into the web-sandbox as the used dependency is not listed.
THe web-sandbox is using rollup for is packaging / bundling which requires all direct used dependencies to be listed
Tested in a local web-sandbox repo adding the dev dependency and by adding and running all tests in the js repo
=> fix: Add otel-api as dev dep for sandbox tests

CHANGELOG.md, packages/opentelemetry-core/src/common/time.ts, packages/opentelemetry-shim-opentracing/test/Shim.test.ts
Fixes https://github.com/open-telemetry/opentelemetry-js/issues/3986
Remove `Math.round()` calls from `hrTimeTo{Milli,Micro}seconds()` functions in order to preserve higher precision from floating point parts.
- Existing tests are all passing
- Would like to test this against contrib repo but not sure how to do that
=> fix(core): stop rounding to nearest int in hrTimeTo*seconds() functions

.github/workflows/unit-test.yml, api/package.json
`nyc` requires `istanbul-lib-report`, which silently dropped support for Node.js v8 when going from
`3.0.0` to `3.0.1` by requiring make-dir@^4.0.0 to fix https://github.com/advisories/GHSA-c2qf-rxjj-qqgw. `make-dir@4.0.0` does not support Node.js v8 anymore, which causes the eol tests to fail.
As we don't report the coverage in these tests, I opted to run the tests without `nyc` instead of pinning the package (as pinning would mean we're stuck with that version, which may prevent us from updating in the future, even though we don't use it).
- Introduced `test:eol` script which runs tests, but does not run them with `nyc`
- adapted the github workflow to use that script instead
=> fix(ci): don't collect coverage for eol tests

experimental/packages/exporter-logs-otlp-http/tsconfig.esm.json, experimental/packages/exporter-logs-otlp-http/tsconfig.esnext.json, experimental/packages/exporter-logs-otlp-http/tsconfig.json
Running `npm install && npm run compile` in the repo at HEAD is missing some generated changes.
Ran `git clean -fdx && npm install && npm run compile` at HEAD in the repo to re-generate files. This must have been missed from a previous commit.
- chore
N/A
=> chore(exporter-logs-otlp-http): commit missing generated changes to tsconfig.json

README.md
Currently, browser support of the packages in this repo is not considered production-ready, we should set expectations in the `README.md` accordingly.  
Fixes #4035 
See also https://github.com/open-telemetry/opentelemetry.io/pull/3125
Adds a not based on https://github.com/open-telemetry/opentelemetry.io/pull/3125 to the README under `Browser Support`. Removes the checkmark for `Browser Support` in the supported runtimes
=> docs(README): clarify browser support

experimental/CHANGELOG.md
Looks like I made a typo while creating the latest release. This PR fixes that, sorry for the noise.
=> fix(changelog): fix incorrect version for latest experimental release

CHANGELOG.md, packages/opentelemetry-exporter-zipkin/src/transform.ts, packages/opentelemetry-exporter-zipkin/test/common/transform.test.ts
exporter-zipkin export traces correctly to zipkin.
Fixes #4056
Round the duration for zipkin.
=> fix(zipkin-exporter): round duration for zipkin

README.md
This PR moves @johnbley, @markwolff, and @OlivierAlbertini to emeritus to accurately reflect the number of active approvers in the OTel JS SIG. 
Thank you for your contributions!
cc @open-telemetry/javascript-maintainers
=> chore: move inactive approvers to emeritus

doc/GUIDELINES.md
I accidentally broke a link when I moved GUIDELINES.md
=> docs: fix broken link to renovate.json

api/src/metrics/Meter.ts, api/src/metrics/Metric.ts, api/src/metrics/ObservableResult.ts, experimental/packages/exporter-logs-otlp-http/test/node/OTLPLogExporter.test.ts, experimental/packages/exporter-logs-otlp-proto/test/logHelper.ts, experimental/packages/exporter-trace-otlp-http/test/node/nodeHelpers.ts, experimental/packages/exporter-trace-otlp-proto/test/traceHelper.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-http/src/OTLPMetricExporterBase.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-http/test/node/nodeHelpers.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-proto/test/metricsHelper.ts, experimental/packages/opentelemetry-instrumentation-http/src/http.ts, experimental/packages/otlp-exporter-base/src/OTLPExporterBase.ts, experimental/packages/otlp-exporter-base/src/platform/browser/OTLPExporterBrowserBase.ts, experimental/packages/otlp-exporter-base/src/platform/node/OTLPExporterNodeBase.ts, experimental/packages/otlp-grpc-exporter-base/src/OTLPGRPCExporterNodeBase.ts, experimental/packages/otlp-proto-exporter-base/src/platform/browser/OTLPProtoExporterBrowserBase.ts, experimental/packages/otlp-proto-exporter-base/src/platform/node/OTLPProtoExporterNodeBase.ts, experimental/packages/sdk-logs/src/export/BatchLogRecordProcessorBase.ts, package.json, packages/opentelemetry-core/src/utils/callback.ts, packages/opentelemetry-core/test/utils/merge.test.ts, packages/opentelemetry-sdk-trace-base/src/export/BatchSpanProcessorBase.ts, packages/sdk-metrics/src/aggregator/ExponentialHistogram.ts, packages/sdk-metrics/src/state/MeterSharedState.ts, packages/sdk-metrics/src/view/Aggregation.ts
`prettier` and `prettier-plugin-eslint` were outdated. This PR updates them and applies style rules.
Supersedes #3978
=> chore(deps): update prettier to v3 and prettier-plugin-eslint to v5

renovate.json
Looks like the `@types/node` rule that was intended for `experimental/backwards-compatibility` only was applied to `@types/node` for the whole repo. As we do not want to update `@types/node` anyway (to ensure we dont accidentally use newer features that are unsupported by older runtimes), this PR moves '@types/node' to the `ignoreDeps` array instead.
This PR should not have any impact how the config is applied, as we were mistakingly using `matchPaths` which is not a valid config option ('includePaths' would be the right one).
=> fix(renovate): remove faulty '@types/node' rule and explicitly apply it to the whole repo

doc/tracing.md
**_This PR just update typo on docs._**
- **add comma**
=> docs(guidelines) tiny fix, add comma on docs

experimental/CHANGELOG.md, experimental/packages/opentelemetry-sdk-node/README.md, experimental/packages/opentelemetry-sdk-node/package.json
`@opentelemetry/sdk-node` depends on `@opentelemetry/exporter-jaeger` despite never using it directly.
This increases the number of dependencies required to install `@opentelemetry/sdk-node` even if
`@opentelemetry/exporter-jaeger` is not used.
Fixes #3759
The change moves `@opentelemetry/exporter-jaeger` to the dev dependencies to resolve it in tests
but avoid requiring it for general usage of `@opentelemetry/sdk-node`. This is consistent with the
`@opentelemetry/sdk-node` [documentation](https://github.com/open-telemetry/opentelemetry-js/blob/main/experimental/packages/opentelemetry-sdk-node/README.md#installation) which states
that exporters must be explicit dependencies. 
Locally building and testing the package after running `npm install` in …
=> fix(sdk-node): move @opentelemetry/exporter-jaeger to dev dependencies

CHANGELOG.md, packages/sdk-metrics/src/InstrumentDescriptor.ts, packages/sdk-metrics/test/util.ts
Fixes #4141
Allows the `/` character in metric instrument name validation.
- Updated existing test case
=> fix(sdk-metrics): allow instrument names to contain '/'

.github/workflows/benchmark.yml, .gitignore, packages/opentelemetry-sdk-trace-base/package.json
Benchmark workflow is currently failing because individual benchmark results are not written to file. This PR makes it so that benchmark results are written to `.benchmark-results.txt` and adds `.benchmark-results.txt` to `.gitignore`.
Related #4171
=> fix(benchmark): write benchmark results to file

benchmarks/index.html
Part of https://github.com/open-telemetry/opentelemetry-js/issues/4171
The benchmarks charts are currently available at
https://open-telemetry.github.io/opentelemetry-js/benchmarks/
This is an update to the HTML page to use the OTel layout/theme, which will make it consistent with the [Collector perf tests](https://open-telemetry.github.io/opentelemetry-collector-contrib/benchmarks/loadtests/) and [Java benchmarks tests](https://open-telemetry.github.io/opentelemetry-java/).
=> Update benchmarks page theme

CHANGELOG.md, doc/contributing/benchmark-tests.md, doc/metrics.md, doc/tracing.md
Part of https://github.com/open-telemetry/opentelemetry-js/issues/4171
This PR adds a doc with instructions on how to add new benchmark tests.
=> Added performance benchmarking doc

experimental/CHANGELOG.md, experimental/packages/opentelemetry-sdk-node/package.json
The `@opentelemetry/exporter-jaeger` explicit dependency isn't removed despite what the last [changelog says](https://github.com/open-telemetry/opentelemetry-js/blob/main/experimental/CHANGELOG.md#0440)
This PR removes the dependency.
=> fix(sdk-node) Remove @opentelemetry/exporter-jaeger explicit dependency

CHANGELOG.md, packages/sdk-metrics/src/InstrumentDescriptor.ts
Older versions of `@opentelemetry-api` do not contain the `MetricAdvice` type. As it's used in the public interface, this type is needed at compile time. This PR hand-rolls the type again in the SDK, so that we can maintain backwards compatibility with older API versions.
In 2.0 we'll be able to bump the minimum API version and remove this workaround. Also in 2.0 `InstrumentDescriptor` will become an intnernal interface, so additions to it will not be part of the public interface anymore.
=> fix(sdk-metrics): hand-roll MetricAdvice type as older API versions do not include it

CHANGELOG.md, lerna.json, package.json, scripts/update-ts-configs.js
With lerna@6 and "useWorkspaces" it will use "workspaces" from
package.json.
See request for this at https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1771#discussion_r1385900274
=> chore: no need for 'packages' in "lerna.json"

CHANGELOG.md, packages/opentelemetry-context-zone-peer-dep/src/ZoneContextManager.ts, packages/opentelemetry-context-zone-peer-dep/tsconfig.esm.json, packages/opentelemetry-context-zone-peer-dep/tsconfig.esnext.json, packages/opentelemetry-context-zone-peer-dep/tsconfig.json
Avoid hardcoding the `node_modules` path in `tsconfig.json` as packages may be hoisted by package managers.
[Type references](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-types-) resolves these package names in the similar process of resolving module names in an `import` statement.
=> chore: type reference on zone.js

experimental/examples/prometheus/README.md, experimental/examples/prometheus/docker-compose.yaml, experimental/examples/prometheus/prometheus.docker.yml
Make it way easier to visualise metrics scraping by prometheus with a docker-compose file. 
- Add a docker-compose.yaml to the [experimental prometheus example](https://github.com/open-telemetry/opentelemetry-js/tree/main/experimental/examples/prometheus)
- Update the [related README.md documentation](https://github.com/Lp-Francois/opentelemetry-js/blob/docs-add-docker-compose-to-run-prometheus-for-experiemental-example/experimental/examples/prometheus/README.md).
1. run `npm run install` and `npm run start` to start the web server from the directory.
2.  start prometheus with `docker compose up`
3. Go to `http://localhost:9090` and observe the prometheus UI with graphs
=> docs: add docker-compose to run prometheus for the experimental example

CHANGELOG.md, packages/opentelemetry-exporter-zipkin/test/common/transform.test.ts, packages/opentelemetry-sdk-trace-base/src/Span.ts, packages/opentelemetry-sdk-trace-base/src/Tracer.ts, packages/opentelemetry-sdk-trace-base/test/common/Span.test.ts
This PR fixes issue https://github.com/open-telemetry/opentelemetry-js/issues/4188 in which the span processor on start method lacks attributes since they are set after with an accessor method (setAttributes) and not on the constructor itself.
This is a follow up of #4206. I will address any review asap as I'm need of this fix with urgency.
Fixes #4188
The PR adds constructor attributes to the span which are optional and if they are added from this layer the spanProcessor.onStart method will have context of attributes whenever it is called, this doest not break compatibility since setAttributes is still a valid public method and also the changes needed on wrappers like the Tracer are done.
Please describe the tests that you ran to verify your …
=> fix(sdk-trace-base): processor onStart called with a span having empty attributes

scripts/generate-protos.js
=> Execute binaries from root node modules

README.md
In recognition of his great work and valuable insights, I propose to add @trentm to the list of JS approvers.
=> Add Trent Mick to approvers

.npmrc
This change has been causing trouble in #4271. It not used in any of the automations.
I've been meaning to use it for releases, but there are other ways to do it.
=> fix(ci): remove token setup via environment variable from .npmrc

CHANGELOG.md, experimental/CHANGELOG.md, package.json, scripts/update-changelog.js
Currently I'm manually updating the changelogs on each release, which can be a somewhat tedious process. This PR adds a script to automate that process, hopefully moving us a step closer to have the release process fully automated.
- adds script to clean up and update changelogs when preparing releases
- run that script in the existing release preparation scripts
- changes an old entry that used a header with no sub-entries so that it is not auto-removed by the script.
=> feat: add script to update changelogs on release preparation

.github/workflows/changelog.yml, CHANGELOG_NEXT.md
I'm adding a changelog file specifically for `next` changes so we can put together a reasonable changelog for the release.
=> Require changelog entries for next branch

benchmarks/data.js
Our docs deploy workflow deleted some benchmark data on every release. This PR brings back the old data - I went trough the commit history and manually added the entries back. This should be merged before #4376 as merging any PR will mean that there will be merge conflicts.  #4376 will fix the workflow problem.
Thanks to @martinkuba for initially noticing this.
=> fix(benchmark): bring back accidentally deleted data

.github/workflows/docs.yaml
Currently out docs deploy workflow deletes the pre-existing benchmark data from the `benchmarks/` directory from the `gh-pages` branch (see 6cf6b679820f780675ddb78c50683f434f34bc27, b3a3d45f4d93666d4df76e5ab8c8146e31120311). 
To fix this, this PR:
- adds the `clean-exclude` option with `benchmarks/**` to ensure they are not deleted when the other docs data is `rsync`ed by the action.
- updates the deploy action to v4 (at least v4.2.0 is needed for wildcard matching in clean-exclude)
- updates the node version used in the workflow to v20 (so that we can use v4 of the deploy action)
=> fix(ci): ensure deploy workflow does not override benchmark data

experimental/packages/opentelemetry-instrumentation/package.json, package-lock.json
Bump import-in-the-middle to 1.7.2.
Fixes the issue: https://github.com/DataDog/import-in-the-middle/issues/31
=> fix(instrumentation): bump import-in-the-middle to 1.7.2

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation/package.json, package-lock.json
`import-in-the-middle` is having a lot of changes right now to keep up with changes in Node.js. This PR unpins `import-in-the-middle` to ensure our users can also keep up without requiring a new `@opentelemetry/instrumentation` release each time.
This PR is intended as more of a discussion-starter. There are a few pros and cons to both sides (keeping it pinned vs. unpinning it)
=> fix(instrumentation): use caret range on import-in-the-middle

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation/src/instrumentationNodeModuleFile.ts, experimental/packages/opentelemetry-instrumentation/src/platform/browser/index.ts, experimental/packages/opentelemetry-instrumentation/src/platform/browser/noop-normalize.ts, experimental/packages/opentelemetry-instrumentation/src/platform/browser/throwing-normalize.ts, experimental/packages/opentelemetry-instrumentation/src/platform/index.ts, experimental/packages/opentelemetry-instrumentation/src/platform/node/normalize.ts, experimental/packages/opentelemetry-instrumentation/test/browser/noop-normalize.test.ts, experimental/packages/opentelemetry-instrumentation/test/browser/throwing-normalize.test.ts
Since we now export `InstrumentationNodeModuleDefinition` even if  `@opentelemetry/instrumentation` is used in a browser context. This PR changes it so that it does not import `'path'` anymore which is part of the nodejs core library. As only the `normalize` function is used, I replaced it with a function that throws on runtime should someone use `InstrumentationNodeModuleDefinition` in the browser for some reason.
Fixes #4373 
=> fix(instrumentation): do not import 'path' in browser runtimes

CHANGELOG.md, packages/opentelemetry-sdk-trace-base/src/Span.ts, packages/opentelemetry-sdk-trace-base/test/common/Span.test.ts
The attribute value length limit was not enforced when a span was created with attributes
Fixes #4416 
Set the length limit before setting the attributes.
=> fix(sdk-trace-base): ensure attribute value length limit is enforced on span creation

api/CHANGELOG.md, api/package.json, api/src/experimental/index.ts, api/src/experimental/trace/SugaredOptions.ts, api/src/experimental/trace/SugaredTracer.ts, api/src/index.ts, api/test/common/experimental/trace/SugaredTracer.test.ts, packages/opentelemetry-sdk-trace-base/test/common/Tracer.test.ts
Early draft of a SugaredTracer, intended as basis for discussions and implementation ideas.
Ref https://github.com/open-telemetry/opentelemetry-js/issues/3250
cc @cartermp
cd @legendecas
Supersedes https://github.com/open-telemetry/opentelemetry-js-api/pull/173
Signed-off-by: secustor [sebastian@poxhofer.at](mailto:sebastian@poxhofer.at)
=> feat(SugaredTracer): add draft of sugaredTracer

CHANGELOG.md, packages/opentelemetry-core/src/platform/node/environment.ts
We currently try to assign `os.hostname()` as the default, but we override it with the emtpy string from `DEFAULT_ENVIRONMENT`. This PR removes that assignment of `HOSTNAME` as it's not doing anything.
While we don't use `HOSTNAME` anywhere other than in tests, `getEnv()` may be used by consumers of the `@opentelemetry/core` library and they might depend on the default for that value being the empty string. Also since `getEnv()` indicates us getting environment variables, I think we should not fall back to anything that's not a static default (as is the case for all other variables).
Fixes #4405
=> refactor(core): drop unnecessary assignment of HOSTNAME

CHANGELOG.md, examples/opentelemetry-web/package.json, experimental/packages/exporter-logs-otlp-grpc/package.json, experimental/packages/exporter-logs-otlp-http/package.json, experimental/packages/exporter-logs-otlp-proto/package.json, experimental/packages/exporter-trace-otlp-grpc/package.json, experimental/packages/exporter-trace-otlp-http/package.json, experimental/packages/exporter-trace-otlp-proto/package.json, experimental/packages/opentelemetry-browser-detector/package.json, experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/package.json, experimental/packages/opentelemetry-exporter-metrics-otlp-http/package.json, experimental/packages/opentelemetry-exporter-metrics-otlp-proto/package.json, experimental/packages/opentelemetry-instrumentation-fetch/package.json, experimental/packages/opentelemetry-instrumentation-xml-http-request/package.json, experimental/packages/opentelemetry-instrumentation/package.json, experimental/packages/otlp-exporter-base/package.json, experimental/packages/otlp-grpc-exporter-base/package.json, experimental/packages/otlp-proto-exporter-base/package.json, experimental/packages/sdk-logs/package.json, karma.webpack.js, package-lock.json, packages/opentelemetry-context-zone-peer-dep/package.json, packages/opentelemetry-context-zone-peer-dep/test/ZoneContextManager.test.ts, packages/opentelemetry-context-zone/package.json, packages/opentelemetry-exporter-zipkin/package.json, packages/opentelemetry-sdk-trace-web/package.json, packages/sdk-metrics/package.json
Test with zone.js' default export entry rather than specifying `'zone.js/dist/index'`
Zone.js' default export entry that is picked by the bundler contains new syntax that needs to be transpiled.
=> test: transpile zone.js products in test

CHANGELOG_NEXT.md, package-lock.json, packages/opentelemetry-resources/package.json, packages/opentelemetry-resources/src/Resource.ts, packages/opentelemetry-resources/src/types.ts
- Updates #4175 
- Update minimum API version to 1.1.0 in opentelemetry-resources
- Replace deprecated `SpanAttributes` with `Attributes`
=> chore(otel-resources): replace deprecated spanAttributes

CHANGELOG.md, experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/test/metricsHelper.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-http/test/metricsHelper.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-proto/test/metricsHelper.ts, experimental/packages/opentelemetry-exporter-prometheus/test/PrometheusExporter.test.ts, experimental/packages/opentelemetry-exporter-prometheus/test/PrometheusSerializer.test.ts, experimental/packages/opentelemetry-instrumentation-http/test/functionals/http-metrics.test.ts, experimental/packages/opentelemetry-sdk-node/src/sdk.ts, packages/sdk-metrics/src/MeterProvider.ts, packages/sdk-metrics/test/Instruments.test.ts, packages/sdk-metrics/test/MeterProvider.test.ts, packages/sdk-metrics/test/export/ConsoleMetricExporter.test.ts, packages/sdk-metrics/test/export/InMemoryMetricExporter.test.ts, packages/sdk-metrics/test/export/MetricReader.test.ts, packages/sdk-metrics/test/regression/cumulative-exponential-histogram.test.ts, packages/sdk-metrics/test/regression/two-metric-readers-async-instrument.test.ts, packages/sdk-metrics/test/state/MeterSharedState.test.ts, packages/sdk-metrics/test/state/MetricCollector.test.ts
Currently a MetricReader is added to a MeterProvider via addMetricReader(). As Meters (and through it instruments) can be created before adding a MetricReader. This gives the false impression that the order of calls does not matter. This PR deprecates the addMetricReader() method in favor of a constructor option as it is the case for most SDKs:
- see [Java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProvider.java#L42)
- does not allow adding a MetricReader after building the MeterProvider
- see [Python](https://github.com/open-telemetry/opentelemetry-python/blob/975733c71473cddddd0859c6fcbd2b02405f7e12/opentelemetry-sdk/src/opentelemetry/sdk/metrics/_internal/__init__.py#L304)
- does not allow adding a …
=> feat(sdk-metrics): deprecate MeterProvider.addMetricReader() in favor of 'readers' constructor option

CHANGELOG_NEXT.md, experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/test/metricsHelper.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-http/test/metricsHelper.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-proto/test/metricsHelper.ts, experimental/packages/opentelemetry-exporter-prometheus/test/PrometheusExporter.test.ts, experimental/packages/opentelemetry-exporter-prometheus/test/PrometheusSerializer.test.ts, experimental/packages/opentelemetry-instrumentation-http/test/functionals/http-metrics.test.ts, experimental/packages/opentelemetry-sdk-node/src/sdk.ts, packages/sdk-metrics/src/MeterProvider.ts, packages/sdk-metrics/test/Instruments.test.ts, packages/sdk-metrics/test/MeterProvider.test.ts, packages/sdk-metrics/test/export/ConsoleMetricExporter.test.ts, packages/sdk-metrics/test/export/InMemoryMetricExporter.test.ts, packages/sdk-metrics/test/export/MetricReader.test.ts, packages/sdk-metrics/test/regression/cumulative-exponential-histogram.test.ts, packages/sdk-metrics/test/regression/two-metric-readers-async-instrument.test.ts, packages/sdk-metrics/test/state/MeterSharedState.test.ts, packages/sdk-metrics/test/state/MetricCollector.test.ts
Currently a `MetricReader` is added to a `MeterProvider` via `addMetricReader()`. As Meters (and through it instruments) can be created before adding a `MetricReader`. This gives the false impression that the order of calls does not matter. This PR removes the addMetricReader() method in favor of a constructor option as it is the case for most SDKs:
- see [Java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProvider.java#L42)
- does not allow adding a `MetricReader` after building the `MeterProvider`
- see [Python](https://github.com/open-telemetry/opentelemetry-python/blob/975733c71473cddddd0859c6fcbd2b02405f7e12/opentelemetry-sdk/src/opentelemetry/sdk/metrics/_internal/__init__.py#L304)
- does not allow …
=> feat(sdk-metrics)!: remove MeterProvider.addMetricReader() in favor of constructor option

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation/package.json, package-lock.json
import-in-the-middle@1.7.2 and later includes a bug (https://github.com/DataDog/import-in-the-middle/issues/57) where a property we use to distinguish ESM from CJS modules is not present, causing instrumentation to crash end-user apps.
This drops support for ESM instrumentation again for Node.js 18.19 and later.
pin import-in-the-middle@1.7.1
=> fix(instrumentation)!: pin import-in-the-middle@1.7.1

experimental/CHANGELOG.md, experimental/packages/exporter-logs-otlp-grpc/src/OTLPLogExporter.ts, experimental/packages/exporter-logs-otlp-grpc/test/OTLPLogExporter.test.ts, experimental/packages/exporter-logs-otlp-http/src/platform/node/OTLPLogExporter.ts, experimental/packages/exporter-logs-otlp-http/test/node/OTLPLogExporter.test.ts, experimental/packages/exporter-logs-otlp-proto/src/platform/node/OTLPLogExporter.ts, experimental/packages/exporter-logs-otlp-proto/test/node/OTLPLogExporter.test.ts
The User-Agent header is set for all log exporters by default 
Fixes #4397
Adds the header to node exporters for:
* exporter-logs-otlp-proto
* exporter-logs-otlp-http
* exporter-logs-otlp-grpc
The headers have been updated. The headers are overridden by using the spread operator instead of `Object.assign` to achieve consistency with exporters of other signals.
=> fix(exporter-logs-otlp-*): set User-Agent header

doc/metrics.md, experimental/CHANGELOG.md, experimental/packages/opentelemetry-exporter-prometheus/src/PrometheusExporter.ts, experimental/packages/opentelemetry-exporter-prometheus/test/PrometheusExporter.test.ts, experimental/packages/opentelemetry-sdk-node/README.md
Promisify prometheus tests and avoid zalgo problem with the constructor callback.
=> refactor(exporter-prometheus): promisify prometheus tests

experimental/CHANGELOG.md, experimental/packages/opentelemetry-sdk-node/README.md, experimental/packages/opentelemetry-sdk-node/src/sdk.ts, experimental/packages/opentelemetry-sdk-node/src/types.ts, experimental/packages/opentelemetry-sdk-node/test/sdk.test.ts
Since registered span processors are chained together via that active multispanprocessor, it makes sense to expose the option as an array of span processors. As such this change also deprecates the `spanProcessor` option in favor of the new, more flexible`spanProcessors` option.
use case: suppose you are happy with the default batchspan processor, but rather not override any of its hooks and just add a subsequent processor that does something e.g. extracts baggage and adds the baggage entries to spans (side note: an off the shelf baggage extractor span processor might be nice!).
add a spanProcessors config option. convert the original/deprecated spanProcessor config to an array of one if used. we now loop over the spanProcessors and register them to the tracer provider. …
=> feat(node-sdk): add spanProcessors option

CHANGELOG.md, packages/sdk-metrics/src/aggregator/ExponentialHistogram.ts, packages/sdk-metrics/test/aggregator/ExponentialHistogram.test.ts
This PR fixes a bug in the exponential histogram merge operation where the source histogram has empty bucket counts. The bucket index was not being set properly in this case, and depending on the histogram being merged, it can lead to corrupted counts in the resulting histogram.
Fixes #4450 
Added special case handling for the zero-length bucket counts case in the `_incrementIndexBy` method.
Added a unit test that replicates a real world failure that exhibits this issue. If you comment out the changes added to `_incrementIndexBy` you will see the newly added test fail.
=> fix: handle zero bucket counts in ExponentialHistogram merge

experimental/CHANGELOG.md, experimental/packages/otlp-transformer/src/common/index.ts
On older, *unsupported* browser runtimes the use of `BigInt` is causing some issues. (#4482, #4350)
We guard against the use of `BigInt` in the same file by falling back to to encoding the timestamp as a string if it is not defined, so this PR attempts to follow this pattern.
Fixes #4350
=> fix(otlp-transformer): only use BigInt inside hrTimeToNanos()

README.md
Adds @david-luna to triagers and adds the triager role to the `README.md`, also fixes some wrong team-names on the way.
Welcome @david-luna :slightly_smiling_face:
=> Add @david-luna to triagers

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation-fetch/README.md, experimental/packages/opentelemetry-instrumentation-fetch/src/fetch.ts
A side issue from https://github.com/open-telemetry/opentelemetry-js/issues/4496 was the mistaken use of instrumentation-fetch for *Node.js's* `fetch()`. instrumentation-fetch does not intend to handle Node.js's fetch. 
This change makes it so instrumentation-fetch will noop when used in Node.js.
Refs: https://github.com/open-telemetry/opentelemetry-js/issues/4496
* * *
Theoretically I think instrumentation-fetch *should* be able instrument Node.js fetch, but currently it is written with dependencies on a web otel package and its tests assume web/browser. See https://github.com/open-telemetry/opentelemetry-js/issues/4333 for discussion on instrumenting Node.js' `fetch()`.
=> fix(instr-fetch): do not enable in Node.js; clarify in docs this instr is for web fetch only

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation/package.json, package-lock.json
we added `@opentelemetry/api-logs` as a `peerDependency` when it should've been a `dependency`, requiring everyone using the package to install an old `@opentelemetry/api-logs` package.
fixes #4516
=> fix(instrumentation): remove peer-dependency on @opentelemetry/api-logs

CHANGELOG.md, packages/sdk-metrics/src/export/ConsoleMetricExporter.ts
Changed the depth of which the ConsoleMetricExporter will log such that values on metrics like attributes, startTime, endTime, and value will be logged entirely.
Example:
Fixes #4061 
Change the console.dir depth to `null` to ensure objects part of the output metrics are fully serialized in the console.
Create a sample application that logs metrics to the console using the `ConsoleMetricExporter`. Observe the output metrics for correctness.
=> fix: ConsoleMetricExporter Should Not Export Shallowly

experimental/CHANGELOG.md, experimental/packages/exporter-logs-otlp-http/src/platform/node/OTLPLogExporter.ts, experimental/packages/exporter-logs-otlp-proto/src/platform/node/OTLPLogExporter.ts, experimental/packages/exporter-trace-otlp-http/src/platform/node/OTLPTraceExporter.ts, experimental/packages/exporter-trace-otlp-proto/src/platform/node/OTLPTraceExporter.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/src/OTLPMetricExporter.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-http/src/platform/node/OTLPMetricExporter.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-proto/src/OTLPMetricExporter.ts, experimental/packages/otlp-exporter-base/src/util.ts, experimental/packages/otlp-exporter-base/test/common/util.test.ts
When passing an options object like `{ headers: { foo: undefined } }` to the http/json and http/protobuf exporters, the headers will not be validated and that will cause 
https://github.com/open-telemetry/opentelemetry-js/blob/abfe059d72d2a50d993ee7fb5ea50a1c29851a31/experimental/packages/otlp-exporter-base/src/platform/node/util.ts#L89
to throw, as we're passing an `undefined` header value. While this alone will not cause an application crash, trying to access `req` at
https://github.com/open-telemetry/opentelemetry-js/blob/abfe059d72d2a50d993ee7fb5ea50a1c29851a31/experimental/packages/otlp-exporter-base/src/platform/node/util.ts#L62
will cause the end-user's application to crash within typically 10s after the first export (when using defaults).
This PR fixes this by sanitizing these …
=> fix(exporters): use parseHeaders() to ensure header-values are not 'undefined'

experimental/CHANGELOG.md
moves an unreleased changelog entry that accidentally ended up on an already released version.
=> chore(changelog): move entry that accidentally ended up in a previous version

experimental/CHANGELOG.md, experimental/packages/sdk-logs/README.md, experimental/packages/sdk-logs/src/LoggerProvider.ts, experimental/packages/sdk-logs/test/common/LoggerProvider.test.ts
Before this, Resource.default() attributes would only be used if *no*
resource was given to LoggerProvider. That would mean that
'service.name' and others could be missing, e.g. when called from
NodeSDK.
* * *
Here is where, for example, NodeSDK passes in a resource to LoggerProvider:
https://github.com/open-telemetry/opentelemetry-js/blob/aabd1a9b001ae9c8190bf2ddc1f3c8fe3a94a74d/experimental/packages/opentelemetry-sdk-node/src/sdk.ts#L360-L362
=> fix(sdk-logs): ensure default resource attributes are used as fallbacks when a resource is passed to LoggerProvider

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation-http/src/http.ts, experimental/packages/opentelemetry-instrumentation-http/src/utils.ts, experimental/packages/opentelemetry-instrumentation-http/test/functionals/http-enable.test.ts, experimental/packages/opentelemetry-instrumentation-http/test/functionals/http-metrics.test.ts, experimental/packages/opentelemetry-instrumentation-http/test/functionals/https-enable.test.ts, experimental/packages/opentelemetry-instrumentation-http/test/functionals/utils.test.ts, experimental/packages/opentelemetry-instrumentation-http/test/integrations/http-enable.test.ts, experimental/packages/opentelemetry-instrumentation-http/test/integrations/https-enable.test.ts, experimental/packages/opentelemetry-instrumentation-http/test/utils/assertSpan.ts
Updates #4567 
- Replace `SemanticAttributes.*`, `NetTransportValues.*`, and `HttpFlavorValues.*` with specific exported strings for http instrumentation package.
Not quite sure; chore to replace deprecated fields but feature to improve minification?
=> refactor(instr-http): use exported strings for semconv

CHANGELOG.md, packages/opentelemetry-sdk-trace-base/src/export/BatchSpanProcessorBase.ts
OpenTelemetry is producing too much overhead for scenarios with significant load. One of the example is BatchSpanExporter, that is allocating array of batch size only to check is it has any pending attributes. 
Replaced map & filter with a simple loop.
Benchmarks:
Before 
create spans (10 attributes) x 689,041 ops/sec ±1.54% (92 runs sampled)
BatchSpanProcessor process span x 660,065 ops/sec ±1.08% (95 runs sampled)
After:
create spans (10 attributes) x 688,731 ops/sec ±1.15% (94 runs sampled)
BatchSpanProcessor process span x 673,550 ops/sec ±1.01% (93 runs sampled)
=> perf(export): do not allocate arrays if resource has no pending async attributes

experimental/CHANGELOG.md, experimental/packages/api-events/README.md, experimental/packages/api-events/src/NoopEventEmitterProvider.ts, experimental/packages/api-events/src/api/events.ts, experimental/packages/api-events/src/types/EventEmitterProvider.ts, experimental/packages/api-events/test/api/api.test.ts, experimental/packages/api-events/test/noop-implementations/noop-event-emitter-provider.test.ts, experimental/packages/api-events/test/noop-implementations/noop-event-emitter.test.ts
`event domain` was removed from the specification in this PR https://github.com/open-telemetry/opentelemetry-specification/pull/3749.
Fixes # https://github.com/open-telemetry/opentelemetry-specification/issues/2994
=> Remove domain from the Events API

experimental/CHANGELOG.md, experimental/packages/opentelemetry-sdk-node/src/sdk.ts, experimental/packages/opentelemetry-sdk-node/test/sdk.test.ts
Host resources were not being set by default when initializing node SDK with `NodeSDK`.
Fixes #4282
- Add `HostDetector` to the list of default resource detectors
- Add test to make sure host and process values are being set by default
- Update from deprecated `sdk.detectResources()` to `sdk.start()` on tests
- Update from deprecated `SemanticResourceAttributes.SERVICE_NAME` to `SEMRESATTRS_SERVICE_NAME` on SDK file
=> feat(sdk-node): add `HostDetector` as default resource detector

experimental/CHANGELOG.md, experimental/packages/api-events/README.md, experimental/packages/api-events/src/NoopEventLogger.ts, experimental/packages/api-events/src/NoopEventLoggerProvider.ts, experimental/packages/api-events/src/api/events.ts, experimental/packages/api-events/src/index.ts, experimental/packages/api-events/src/internal/global-utils.ts, experimental/packages/api-events/src/types/EventLogger.ts, experimental/packages/api-events/src/types/EventLoggerOptions.ts, experimental/packages/api-events/src/types/EventLoggerProvider.ts, experimental/packages/api-events/test/api/api.test.ts, experimental/packages/api-events/test/internal/global.test.ts, experimental/packages/api-events/test/noop-implementations/noop-event-logger-provider.test.ts, experimental/packages/api-events/test/noop-implementations/noop-event-logger.test.ts
As discussed in https://github.com/open-telemetry/opentelemetry-specification/pull/3869, the decision has been made in the Specification SIG meeting on 3/2/24 to rename EventEmitter to EventLogger in the API.
Technically this is a breaking change. But the API is in very early experimental stage without a default SDK implementation.
=> Rename EventEmitter to EventLogger in the Events API

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation-xml-http-request/README.md, experimental/packages/opentelemetry-instrumentation-xml-http-request/src/xhr.ts, experimental/packages/opentelemetry-instrumentation-xml-http-request/test/xhr.test.ts
PR https://github.com/open-telemetry/opentelemetry-js/pull/3028 added a `ignoreNetworkEvents` boolean to the `experimental/opentelemetry-instrumentation-fetch` package. This PR adds the same behaviour + flag to the `experimental/opentelemetry-instrumentation-xml-http-request` package. 
Quoting from that PR
> Summary: This PR allows to optionally disable adding network events as span events to control the total volume of telemetry data produced.
> 
> Some of the modern vendors treat spans and span events (annotations) equally – both are counted towards the overall retained events volume. Similarly, vendors that charge for the overall size of data retained will count span annotations as part of the data. Typically, span produced by the @opentelemetry-instrumentation-fetch includes 9 network …
=> feat(opentelemetry-instrumentation-xhr): optionally ignore network events

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation-http/README.md
I didn't see a specific issue for this, so realizing there should probably be another issue similar to https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1778 in this repo, for the instrumentations within.
This is intended to let folks know what version of semantic conventions are in use as well as the attributes exported in the instrumentation. This will make it easier to update to later versions when ready (see tracking issue #4572).
- In the README for http instrumentation, add version of Semantic Conventions used as well as a table of keys and values. I kept the "`1.22+`" because even though the numbered version will change with each release, right now it's effective in 1.22+ that contains the exported string keys. When we have a new semantic convention package with new …
=> docs(instr-http): document semantic conventions and attributes in use

experimental/CHANGELOG.md, experimental/packages/opentelemetry-exporter-metrics-otlp-http/src/OTLPMetricExporterBase.ts, packages/sdk-metrics/src/InstrumentDescriptor.ts, packages/sdk-metrics/src/Instruments.ts, packages/sdk-metrics/src/Meter.ts, packages/sdk-metrics/src/aggregator/ExponentialHistogram.ts, packages/sdk-metrics/src/aggregator/Histogram.ts, packages/sdk-metrics/src/types.ts, packages/sdk-metrics/src/view/Aggregation.ts, packages/sdk-metrics/test/Meter.test.ts, packages/sdk-metrics/test/export/ConsoleMetricExporter.test.ts, packages/sdk-metrics/test/export/utils.ts
Split from #4528, relates to #4296
Added SDK for _synchronous_ gauge.
=> feat(sdk-metrics): added synchronous gauge to SDK

experimental/CHANGELOG.md, experimental/packages/otlp-transformer/src/common/internal.ts, experimental/packages/otlp-transformer/src/logs/index.ts, experimental/packages/otlp-transformer/src/metrics/internal.ts, experimental/packages/otlp-transformer/src/resource/internal.ts, experimental/packages/otlp-transformer/src/trace/index.ts, experimental/packages/otlp-transformer/test/logs.test.ts, experimental/packages/otlp-transformer/test/metrics.test.ts, experimental/packages/otlp-transformer/test/trace.test.ts
Resources and scopes creation are currently duplicated across all signals even though they're the same. This PR pulls them out into shared functions for all signals. 
Replaces #4429
=> feat(otlp-transformer): consolidate scope/resource creation in transformer

CHANGELOG.md, packages/opentelemetry-resources/src/detectors/BrowserDetectorSync.ts
=> fix(resources): ensure BrowserDetector does not think Node.js v21 is a browser

CHANGELOG.md, packages/opentelemetry-sdk-trace-base/src/export/ConsoleSpanExporter.ts, packages/opentelemetry-sdk-trace-base/test/common/export/ConsoleSpanExporter.test.ts
It's currently impossible to troubleshoot resource setup without explicitly logging the resource before setting up the SDK. 
This PR adds the span's resource to the output that's logged to the console to aid troubleshooting.
=> feat(sdk-trace-base): log resource attributes in ConsoleSpanExporter

experimental/packages/exporter-logs-otlp-grpc/test/OTLPLogExporter.test.ts, experimental/packages/exporter-trace-otlp-grpc/test/OTLPTraceExporter.test.ts, package-lock.json
New versions of `@grpc/grpc-js` add more info to the `Deadline Exceeded` error, making our tests fail. The error still starts with `Deadline Exceeded` so I switched the assertion from a `strictEqual()` to a `match()`
- Update `@grpc/grpc-js` to latest (package-lock.json only)
- Adapt tests
=> test(exporter-*-grpc): use RegExp to match Deadline Exceeded error

experimental/packages/opentelemetry-instrumentation-fetch/README.md
Now that instrumentation-undici exists, point to it for users that want
instrumentation of Node.js' fetch().
=> doc(instr-fetch): mention instr-undici for Node.js fetch()

renovate.json
Enables lock file maintenance via renovate bot so we don't have to do it manually every time.
=> chore(renovate): enable lock file maintainance

package.json
See discussion in #4621, when releasing the API is temporarily removed. This bleeds over into `package-lock.json` where it's never rectified by the `_restore:package-json` script.
This PR adds a `npm install --package-lock-only` to sync the `package-lock.json` again after incrementing versions.
=> fix: ensure api is not dropped from workspaces in package-lock.json

CHANGELOG.md, experimental/packages/opentelemetry-instrumentation-grpc/src/instrumentation.ts, experimental/packages/opentelemetry-instrumentation-http/src/http.ts, experimental/packages/opentelemetry-instrumentation/src/platform/node/instrumentation.ts
This PR introduces diag.debug message for `@opentelemetry/instrumentation` patch and unpatch function for nodejs.
It is a common practice for instrumentations that implement `InstrumentationBase` to define `patch` and `unpatch` functions for modules and module files, and emit a diag message on each invocation. Since we have dozens of instrumentations that does the same thing, the current practice introduces unnecessary repetitions, inconsistencies and degraded user and maintainer experience.
This PR hoists the diag printing to the `@opentelemetry/instrumentation` package where the diag message is written once and applied to all instrumentations.
Instrumentation implementors will need to remove the current diag.debug call in `patch` and `unpatch` if they apply any, so the message will only …
=> feat!(instrumentation): add patch and unpatch diag log messages

.github/workflows/unit-test.yml, CHANGELOG.md, README.md, api/CHANGELOG.md, experimental/CHANGELOG.md
Seeing if tests pass on node 22 [released this week](https://nodejs.org/en/blog/announcements/v22-release-announce)
=> Add node 22 support

.gitmodules
`experimental/packages/otlp-proto-exporter-base` no longer exists and its submodules shall be removed.
Follow-up of https://github.com/open-telemetry/opentelemetry-js/pull/4581.
=> chore: remove obsolete submodules

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation-grpc/src/instrumentation.ts, experimental/packages/opentelemetry-instrumentation-http/src/http.ts, experimental/packages/opentelemetry-instrumentation/src/platform/node/instrumentation.ts
This PR aims to cleanup code from instrumentations, that unwraps a patched function before attempting to patch it again.
For instrumentation implementations, there will be no need to `_unwrap` before calling `_wrap`, refactoring this:
```js
if (isWrapped(moduleExports.myFunc)) {
this._unwrap(moduleExports, 'myFunc');
}
this._wrap(moduleExports, 'myFunc', this._getMyFuncFunctionPatch());
```
to this shorter cleaner version:
```js
this._wrap(moduleExports, 'myFunc', this._getMyFuncFunctionPatch());
```
A common implementation of instrumnetation `patch` hook looks like this:
```js 
if (isWrapped(moduleExports.request)) {
this._unwrap(moduleExports, 'request');
}
this._wrap(
moduleExports,
'request',
this._getPatchOutgoingRequestFunction('http')
);
if (isWrapped(moduleExports.get)) { …
```
=> feat(instrumentation): apply unwrap before wrap in base class

renovate.json
We had `import-in-the-middle` on the all-patch ignore list due to the problems outlined in #4553
`import-in-the-middle` has since been updated and those concerns are now void, this PR is adding `import-in-the-middle` back to the all-patch group.
Closes #4553
=> chore(renovate): remove import-in-the-middle from the all-patch ignore list

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation-grpc/README.md, experimental/packages/opentelemetry-instrumentation-grpc/src/instrumentation.ts, experimental/packages/opentelemetry-instrumentation-http/README.md
This PR applies https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2196 to the node instrumentations in core repo
=> docs: align all supported versions to a common format

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation/src/types.ts
This PR improves the documentation of the `supportedVersions` option on `InstrumentationModuleDefinition` and `InstrumentationModuleFile`:
- explain that the array is ORed (one needs to match)
- add guidelines on the syntax that is supported in a way that is easy to consume
- document the effect of this function, copied from [here](https://github.com/open-telemetry/opentelemetry-js/blob/ca027b5eed282b4e81e098ca885db9ce27fdd562/experimental/packages/opentelemetry-instrumentation/src/types.ts#L61)
- Add documentation about empty array behavior
- Recommendation to bind the upper supported version to a major version to avoid breaking changes that we cannot anticipate, and guarantee support and stability.
This PR is only to document existing behavior, which is something we might want to …
=> docs(instrumentation): better docs for supportedVersions option

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation-fetch/src/fetch.ts, experimental/packages/opentelemetry-instrumentation-grpc/src/instrumentation.ts, experimental/packages/opentelemetry-instrumentation-http/src/http.ts, experimental/packages/opentelemetry-instrumentation-xml-http-request/src/xhr.ts, experimental/packages/opentelemetry-instrumentation/src/instrumentation.ts, experimental/packages/opentelemetry-instrumentation/src/platform/browser/instrumentation.ts, experimental/packages/opentelemetry-instrumentation/src/platform/node/instrumentation.ts
This PR makes the `config` object for base instrumentations (node + browser), required instead of optional with default value empty object.
The current implementation of instrumentation base classes requires a config object to be set. The 2 functions that accept a config object (constructor and `setConfig`) currently define the function parameter as optional, with default value `{}`. This creates the following problems:
- By making this property optional, we are unable to add additional parameters to the constructor function in a clean way, which is something I want to do soon.
- if the config object is not supplied, it is assumed to be empty object `{}`, but there is no typescript enforcement that the config object has only optional properties. Thus, this assumption may break and we …
=> feat(instrumentation): remove default value for config in base instrumentation constructor

README.md
Just updating my personal info in the README. The company I work for is called "Keyval" but we are changing it to "Odigos" to align with the name of the open-source project we maintain.
=> chore: fix personal info in README

packages/opentelemetry-sdk-trace-node/README.md
There is an issue in a package name in node sdk
=> docs: fix instrumentation-graphql package name in documentation

api/CHANGELOG.md, api/src/index.ts, api/src/metrics/Meter.ts, api/src/metrics/Metric.ts, api/src/metrics/NoopMeter.ts, api/test/common/noop-implementations/noop-meter.test.ts, packages/sdk-metrics/src/Instruments.ts, packages/sdk-metrics/src/Meter.ts, packages/sdk-metrics/src/types.ts, packages/sdk-metrics/test/Instruments.test.ts
=> feat(api): added synchronous gauge

CHANGELOG.md, package-lock.json, packages/opentelemetry-context-zone-peer-dep/package.json, packages/opentelemetry-context-zone/package.json, selenium-tests/package.json
Adding supplementary support for zone.js 0.12.x
Fixes #4729 
- addresses [https://github.com/open-telemetry/opentelemetry-js/issues/4729](https://github.com/open-telemetry/opentelemetry-js/issues/4729)
=> feat(context-zone*): support zone.js 0.12.x

CHANGELOG.md, packages/opentelemetry-core/src/platform/browser/sdk-info.ts, packages/opentelemetry-core/src/platform/node/sdk-info.ts
Updates #4567
Replace deprecated imports from “@opentelemetry/semantic-conventions” with new (tree-shakeable) string constants for core package. What I did:
- Search for “@opentelemetry/semantic-conventions” in package path.
- Add new imports and check that new and old strings match exactly.
- Use new imports and remove old ones.
- No new functionality
- I'm not sure if documentation, like described in https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1778, is wanted for this package at the moment. Please let me know, if I should add it.
=> refactor(core): Use (tree-shakeable) string constants for semconv

CHANGELOG.md, packages/opentelemetry-sdk-trace-base/src/Span.ts, packages/opentelemetry-sdk-trace-base/test/common/Span.test.ts
Updates #4567
Replace deprecated imports from `@opentelemetry/semantic-conventions` with new (tree-shakeable) string constants for package `@opentelemetry/sdk-trace-base`. What I did:
- Search for “@opentelemetry/semantic-conventions” in package path.
- Add new imports and check that new and old strings match exactly.
- Use new imports and remove old ones.
- No new functionality
=> refactor(sdk-trace-base): Use tree-shakeable string constants for semconv

CHANGELOG.md, packages/opentelemetry-sdk-trace-web/src/utils.ts, packages/opentelemetry-sdk-trace-web/test/WebTracerProvider.test.ts
Updates #4567
Replace deprecated imports from `@opentelemetry/semantic-conventions` with new (tree-shakeable) string constants for package `@opentelemetry/sdk-trace-web`. What I did:
- Search for “@opentelemetry/semantic-conventions” in package path.
- Add new imports and check that new and old strings match exactly.
- Use new imports and remove old ones.
- No new functionality
=> refactor(sdk-trace-web): Use tree-shakeable string constants for semconv

CHANGELOG.md, packages/opentelemetry-shim-opentracing/src/shim.ts, packages/opentelemetry-shim-opentracing/test/Shim.test.ts
Updates #4567
Replace deprecated imports from `@opentelemetry/semantic-conventions` with new (tree-shakeable) string constants for package `@opentelemetry/shim-opentracing`. What I did:
- Search for “@opentelemetry/semantic-conventions” in package path.
- Add new imports and check that new and old strings match exactly.
- Use new imports and remove old ones.
- No new functionality
=> refactor(shim-opentracing): Use tree-shakeable string constants for semconv

examples/http/tracer.js, examples/https/tracer.js
Updates https://github.com/open-telemetry/opentelemetry-js/issues/4567
Replaced deprecated import (SemanticResourceAttributes) from @opentelemetry/semantic-conventions with new string constants (SEMRESATTRS_SERVICE_NAME) for the example https package
=> refactor(examples/https): use new exported string constants for semconv

CHANGELOG.md, experimental/packages/opentelemetry-exporter-prometheus/test/util.ts, packages/opentelemetry-exporter-jaeger/src/jaeger.ts, packages/opentelemetry-exporter-jaeger/test/jaeger.test.ts, packages/opentelemetry-exporter-zipkin/src/zipkin.ts, packages/opentelemetry-exporter-zipkin/test/common/transform.test.ts, packages/opentelemetry-exporter-zipkin/test/node/zipkin.test.ts
Updates #4567 
Replace deprecated `SemanticResourceAttributes.*` usage with new exported attributes for:
- exporter-zipkin
- exporter-jaeger
- exporter-prometheus
I kept these in 1 PR because they are so small, happy to split into separate PRs if that's preferred.
=> chore(exporters): updated deprecated semconv to use exported strings

experimental/packages/opentelemetry-instrumentation-http/README.md
We decided the key column was [redundant and unnecessary](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1778#issuecomment-2042946387). My original PR added the whole table #4587 before we decided on this.
- remove key column from README in instrumentation-http 
n/a
=> docs(instrumentation-http): remove semconv key column from readme

CHANGELOG.md, packages/opentelemetry-resources/src/detectors/BrowserDetectorSync.ts, packages/opentelemetry-resources/src/detectors/platform/node/HostDetectorSync.ts, packages/opentelemetry-resources/src/detectors/platform/node/OSDetectorSync.ts, packages/opentelemetry-resources/src/detectors/platform/node/ProcessDetectorSync.ts, packages/opentelemetry-resources/test/Resource.test.ts, packages/opentelemetry-resources/test/detectors/node/HostDetector.test.ts, packages/opentelemetry-resources/test/detectors/node/OSDetector.test.ts, packages/opentelemetry-resources/test/resource-assertions.test.ts, packages/opentelemetry-resources/test/util/resource-assertions.ts, packages/opentelemetry-resources/test/util/sample-detector.ts
Updates #4567 
- Replace deprecated `SemanticResourceAttributes.*` usage with new exported attributes
- Update resource-assertions test util to match changes made in https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2210
Note some of the changes elsewhere in the package had already been made in a previous PR #4608 .
=> chore(resources): update deprecated semconv to use exported strings

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation/package.json, experimental/packages/opentelemetry-instrumentation/src/platform/node/instrumentation.ts, package-lock.json
`import-in-the-middle` v1.8.0 [has a lot of bug fixes](https://github.com/DataDog/import-in-the-middle/pull/91). 
Closes #4547
In one of those PRs I added a named `Hook` export which should work around the default export issue which closes #4691 and closes #4717.
Unfortunately when I added the export I forgot to add it to the types so the types need fudging until [this PR](https://github.com/DataDog/import-in-the-middle/pull/92) makes it into a release.
=> fix: Update `import-in-the-middle`

README.md
@open-telemetry/javascript-maintainers Please adapt the needed rights/groups/.... accordingly.
I'm still around but as of now I don't find enough time to really follow the project in the needed details to really fulfill the approver role.
=> chore: move flarna from approver to emeritus

CHANGELOG.md, examples/opentracing-shim/package.json, examples/opentracing-shim/shim.js
Updates https://github.com/open-telemetry/opentelemetry-js/issues/4567
Replaced deprecated import (SemanticResourceAttributes) from @opentelemetry/semantic-conventions with new string constants (SEMRESATTRS_SERVICE_NAME) for the example `opentracing-shim` package
=> refactor(examples/opentracing-shim): use new exported string constants for semconv

experimental/CHANGELOG.md, experimental/examples/opencensus-shim/setup.js
Updates https://github.com/open-telemetry/opentelemetry-js/issues/4567
Replaced deprecated import (SemanticResourceAttributes) from @opentelemetry/semantic-conventions with new string constants (SEMRESATTRS_SERVICE_NAME) for the experimental example `opencensus-shim` package
=> refactor(experimental/examples/opencensus-shim): use new exported string constants for semconv

CHANGELOG.md, examples/basic-tracer-node/index.js, examples/basic-tracer-node/package.json
Updates https://github.com/open-telemetry/opentelemetry-js/issues/4567
Replaced deprecated import (SemanticResourceAttributes) from @opentelemetry/semantic-conventions with new string constants (SEMRESATTRS_SERVICE_NAME) for the example `basic-tracer-node` package
=> refactor(examples/basic-tracer-node): use new exported string constants for semconv

experimental/packages/sdk-logs/package.json, package-lock.json
Versions in `@opentelemetry/sdk-logs` were not updated correctly in the release PR (ref #4677).
This PR fixes this before actually releasing.
=> fix(sdk-logs): adapt versions for release

README.md
To accurately reflect the number of active approvers in the OTel JS SIG, we need to periodically move inactive approvers to emeritus.
This PR moves @haddasbronfman from approver to emeritus. Thank you for your work on the project. 
If anything changes w.r.t. available time to work on the project, please feel free to reach out to the JS SIG's maintainers group. :slightly_smiling_face: 
cc @open-telemetry/javascript-maintainers
=> chore: move haddasbronfman from approver to emeritus

experimental/CHANGELOG.md, experimental/packages/otlp-transformer/src/index.ts
This PR changes the exports of the `@opentelemetry/otlp-transformer` package to be explicit over `export * from`. This will help us reduce the API surface of the `@opentelemetry/otlp-transformer` package now that #4581 and #4542 is merged in and many of these types are not needed anymore.
By first converting to explicit exports, it will be easier to review future PRs that will remove those exports.
Part of #4583
=>  refactor(otlp-transformer): use explicit exports

CHANGELOG.md, packages/opentelemetry-context-zone-peer-dep/src/index.ts
Changes all exports to be explicit.
Part of #4186
=> refactor(context-zone-peer-dep): use explicit exports

.github/ISSUE_TEMPLATE/bug_report.yaml, README.md, experimental/packages/opentelemetry-browser-detector/README.md
Refactoring some deprecated documentation around SemanticResourceAttributes:
* https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/opentelemetry-semantic-conventions/src/resource/SemanticResourceAttributes.ts#L575
=> docs: usage of SEMRESATTRS_XXXXX

packages/opentelemetry-sdk-trace-base/src/export/SimpleSpanProcessor.ts
Related: 
* https://github.com/open-telemetry/opentelemetry-js/issues/4741
=> docs: add SimpleSpanProcessor warning

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation/package.json, package-lock.json
Ref https://github.com/open-telemetry/opentelemetry-js/pull/4806#issuecomment-2178669926
`import-in-the-middle` is more stable and has tests to ensure otel usage won't get broken so this should mean less PRs/releases required.
=> feat(instrumentation): Use a caret version for `import-in-the-middle` dependency

package.json, scripts/extract-latest-release-notes.js
Adds a few more script for release-automation that I usually did by hand. Moving us closer to having a fully-automated solution.
**This adds:**
- scripts to auto-update release PRs with the latest changelog (I had to copy this to the body by hand before every time someone merged to main when the release PR was open, which was very cumbersome)
- scripts to update the release PR branch (now always titled `release/next-version` for simplicity) automatically
**Additional changes:**
- makes `scripts/extract-latest-release-notes.js` work with multiple changelog files so that we can list all changes in the PR body.
**Next steps:**
- script to automatically create the release PR
- tying everything together with a workflow that uses the @opentelemetrybot user to create and update PRs when main is …
=> feat: add release-pr update chores as scripts to package.json

CHANGELOG.md, experimental/CHANGELOG.md, experimental/packages/exporter-logs-otlp-http/src/platform/config.ts, experimental/packages/exporter-logs-otlp-proto/src/platform/browser/OTLPLogExporter.ts, experimental/packages/exporter-logs-otlp-proto/src/platform/node/OTLPLogExporter.ts, experimental/packages/exporter-trace-otlp-http/src/platform/browser/OTLPTraceExporter.ts, experimental/packages/exporter-trace-otlp-http/src/platform/node/OTLPTraceExporter.ts, experimental/packages/exporter-trace-otlp-proto/src/platform/browser/OTLPTraceExporter.ts, experimental/packages/exporter-trace-otlp-proto/src/platform/node/OTLPTraceExporter.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-http/src/platform/browser/OTLPMetricExporter.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-http/src/platform/node/OTLPMetricExporter.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-proto/src/OTLPMetricExporter.ts, packages/opentelemetry-sdk-trace-base/src/config.ts
* https://github.com/open-telemetry/opentelemetry-js/issues/4741
In most of the exporters, there is a function [`getEnv()`](https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/opentelemetry-core/src/platform/node/environment.ts#L27) that is called an unnecessary amount of times inside nested ternary operators. 
It looks as `getEnv()` calls `parseEnvironment()` that happens to iterate over a large static object parsing its values and performing other assertions. 
See extract from source: 
* https://github.com/open-telemetry/opentelemetry-js/blob/main/experimental/packages/exporter-trace-otlp-http/src/platform/node/OTLPTraceExporter.ts#L57
```ts
getDefaultUrl(config: OTLPExporterNodeConfigBase): string {
return typeof config.url === 'string'
? config.url
: …
```
=> refactor: reduce and simplify usage of getEnv()

README.md
Welcome @maryliag :slightly_smiling_face: :tada: 
Also orders the approvers alphabetically while we're at it :slightly_smiling_face:
=> chore: add @maryliag to triagers

README.md
In recognition of her contributions to the project, technical judgement and efforts around driving community topics, I propose we add @JamieDanielson to the list of JS Maintainers.
cc @open-telemetry/javascript-maintainers
=> chore: add @JamieDanielson to maintainers 

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation/src/types.ts
As we are talking about stabilizing the `@opentelemetry/instrumentation` package, I want to suggest removing the `description` property from `Instrumentation` interface which is not used anywhere in the codebase (core + contrib).
While this is technically a breaking change, it is very unlikly that someone actually uses it out there IMO.
- The instrumentation description is well documented in `package.json` https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2202 and one can pick it up from there.
- I don't think this data is relevant in runtime
- Even if we do want it in the future, I think it should be bundled into a proper interface with other metadata, so the current property will probably not be the final one we want to use anyway.
- …
=> fix(instrumentation)!:remove unused description property from interface

experimental/packages/opentelemetry-instrumentation/src/instrumentation.ts
Just a small typo I came across while browsing the code.
Correct a mixup between the jsdoc comment of the enabled and the disable function.
=> docs(opentelemtry-instrumentation): fix reversed jsdoc comment

CHANGELOG.md, experimental/packages/sdk-logs/src/export/ConsoleLogRecordExporter.ts, experimental/packages/sdk-logs/test/common/export/ConsoleLogRecordExporter.test.ts, packages/opentelemetry-sdk-trace-base/src/export/ConsoleSpanExporter.ts, packages/opentelemetry-sdk-trace-base/test/common/export/ConsoleSpanExporter.test.ts
The `ConsoleSpanExporter` prints many useful information to the console about a span, but it lacks the `instrumentationLibrary`. This info is present on the `ReadableSpan`, but it was probably forgotten, as the resource is included and the span info is included, but there is no way currently to view the library info for an output span:
```js
{
resource: {
attributes: {
'service.name': 'coupon',
'telemetry.sdk.language': 'nodejs',
'telemetry.sdk.name': 'opentelemetry',
'telemetry.sdk.version': '1.25.0',
'telemetry.distro.name': 'odigos',
'telemetry.distro.version': 'v1.0.76'
}
},
traceId: 'cd873e9e3f16df24a8e2ebfe83d00b9c',
parentId: '22ca73ebb95febbe',
traceState: undefined,
name: 'request handler - /apply-coupon',
id: 'cb7f45d392356f99',
kind: 0,
timestamp: 1720132143829000,
duration: …
```
=> feat: include instrumentation scope info in console span and log record exporters

CHANGELOG.md, experimental/packages/opentelemetry-instrumentation/package.json, package-lock.json
Bumps the shimmer package to a version that doesn't include an invasive type that breaks certain setups.
See PR for more details: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69966
Fixes https://github.com/getsentry/sentry-javascript/issues/12682
This PR supersedes https://github.com/open-telemetry/opentelemetry-js/pull/4835
I don't think tests are necessary here. Feel free to let me know though!
=> deps(opentelemetry-instrumentation): Bump shimmer types to 1.2.0

experimental/CHANGELOG.md, experimental/packages/api-logs/src/types/AnyValue.ts
Following [this PR in contrib](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2352) I noticed that the `AnyValue` type in `@opentelemetry/api-logs` is not accurate, as [the spec defined more allowed types](https://opentelemetry.io/docs/specs/otel/logs/data-model/#type-any). This PR aligns the `AnyValue` type to match the spec:
> Type any
> Value of type any can be one of the following:
> 
> - A scalar value: string, boolean, signed 64 bit integer, or double precision floating point (IEEE 754-1985)
> 
> - A byte array,
> 
> - An array (a list) of any values,
> 
> - A map<string, any>,
> 
> - [since 1.31.0] An empty value (e.g. null).
=> fix(api-logs): align AnyValue to spec

CHANGELOG.md, package-lock.json, packages/sdk-metrics/package.json
See #4834, `@types/lodash` are now not compatible with older typescript versions anymore, which makes it fail with Typescript 4.4.4, which we're using. I investigated why we need this dependency (and `lodash.merge`) and found that it was added some 4 years ago, before the Metrics SDK rewrite (see #1491). 
Since that rewrite, however, we don't use it anymore, so it can be safely removed.
=> deps(sdk-metrics): remove unused lodash.merge dependency

CHANGELOG.md, experimental/packages/opentelemetry-instrumentation/src/types.ts
Fix #4712, related to #3713.
TypeScript emits `InstrumentationNodeModuleDefinition` with ` | undefined` for some reason, making it incompatible with `InstrumentationModuleDefinition` under `exactOptionalPropertyTypes: true`.
I'm using OpenTelemetry indirectly via Sentry. I applied this patch locally to the latest version of `@opentelemetry/instrumentation` and it resolved the issue.
=> fix(instrumentation): Fix optional property types

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation/src/platform/node/instrumentation.ts
Closes: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2237
Refs: #3308
---
Back in #3308 a diag.warn `No modules instrumentation has been defined for {instr}, nothing with be patched` was reduced to being a diag.debug to avoid confusion for users. The aws-lambda instrumentation can reasonably not patching anything.
Another more recent case: instrumentation-undici uses InstrumentationBase but its `init()` doesn't return any modules to patch because it uses diagnostics-channels to do its instrumentation. This is a second example where it is totally reasonable for an instrumentation to not return any modules for patching from `init()`.  Given it is reasonable to do so, I don't think the `diag.debug()` is worth it. Sure, it theoretically might catch a programming error in …
=> fix(instrumentation): drop diag.debug on InstrumentationBase#init not returning any modules

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation/src/instrumentation.ts, experimental/packages/opentelemetry-instrumentation/test/common/Instrumentation.test.ts
Before this change an instrumentation instance's config, as returned
from .getConfig(), would include {enabled: true} after construction,
`new MyInstrumentation()`; but would not include 'enabled' after
`.setConfig({})`. That inconsistency could cause bugs in usage of
`this.getConfig().enabled`.
=> fix(instrumentation): ensure .setConfig() results in config.enabled defaulting to true

experimental/packages/exporter-logs-otlp-grpc/test/OTLPLogExporter.test.ts
Exporter tests are currently failing with the very recent Node.js 22.7.0. We believe the failures are due to a Node 22.x regression for which there is an issue/PR/discussion.
This PR is about improving the test failure to be more helpful.
Before this change the test failure output was:
```
% cd experimental/packages/exporter-logs-otlp-grpc
% npm test
...
1) OTLPLogExporter - node with TLS, without metadata, target https://localhost:1503
"before all" hook for "test certs are valid":
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/trentm/tm/opentelemetry-js4/experimental/packages/exporter-logs-otlp-grpc/test/OTLPLogExporter.test.ts)
at listOnTimeout (node:internal/timers:594:17)
at processTimers …
```
=> test(exporter-logs-otlp-grpc): improve error reporting in particular test failure

.github/workflows/unit-test.yml
Failing tests on grpc exporters for latest Node 22
There is a bug in node.js v22.7 with buffers that is causing grpc exporters to fail. Fix should be available in 22.8, pinning to 22.6 for now to keep development and releases moving.
=> chore: pin unit test to node 22.6 until 22.8 is available

api/package.json, api/test/tree-shaking/tree-shaking.test.ts, experimental/packages/api-events/package.json, experimental/packages/api-logs/package.json, experimental/packages/exporter-logs-otlp-http/package.json, experimental/packages/exporter-logs-otlp-proto/package.json, experimental/packages/exporter-trace-otlp-http/package.json, experimental/packages/exporter-trace-otlp-proto/package.json, experimental/packages/opentelemetry-browser-detector/package.json, experimental/packages/opentelemetry-exporter-metrics-otlp-http/package.json, experimental/packages/opentelemetry-instrumentation-fetch/package.json, experimental/packages/opentelemetry-instrumentation-xml-http-request/package.json, experimental/packages/opentelemetry-instrumentation/package.json, experimental/packages/otlp-exporter-base/package.json, experimental/packages/otlp-transformer/package.json, experimental/packages/sdk-events/package.json, experimental/packages/sdk-logs/package.json, package-lock.json, packages/opentelemetry-context-zone-peer-dep/package.json, packages/opentelemetry-core/package.json, packages/opentelemetry-exporter-zipkin/package.json, packages/opentelemetry-propagator-jaeger/package.json, packages/opentelemetry-resources/package.json, packages/opentelemetry-sdk-trace-base/package.json, packages/opentelemetry-sdk-trace-web/package.json, packages/propagator-aws-xray/package.json, packages/sdk-metrics/package.json, selenium-tests/package.json
Supersedes #4958 . 
Types are incorrect not only on `memfs` but also `unionfs`. The additional commit https://github.com/open-telemetry/opentelemetry-js/pull/4961/commits/b4c9a968b6786f0fb72c22a7bfb24b2b9997da11 applies the workaround from https://github.com/webpack/webpack/issues/18242#issuecomment-2018116985
=> chore(deps): update dependency webpack to v5.94.0

experimental/CHANGELOG.md, experimental/packages/sampler-jaeger-remote/src/JaegerRemoteSampler.ts, experimental/packages/sampler-jaeger-remote/test/JaegerRemoteSampler.test.ts
We need to catch errors otherwise this code throws unhandled promise rejections. These rejections can cause node processes to exit. Just using a try finally block does not suffice for catching these errors.
I created the test first to verify it fails. Then I added the catch statement to see that it now passes.
=> fix(jaeger-remote-sampler): Catch errors retrieving remote config

.github/workflows/unit-test.yml
Now that Node.js 22.8 is available with a workaround
(https://github.com/nodejs/node/pull/54565) for the bug in 22.7 that
caused 'RangeError: "length" is outside of buffer bounds' errors in
exporter tests (see https://github.com/open-telemetry/opentelemetry-js/pull/4953),
we can unpin the Node.js v22 used for unit tests.
This undoes the pinning from #4957.
=> chore: unpin unit-test from 22.6

experimental/CHANGELOG.md, experimental/packages/opentelemetry-browser-detector/src/BrowserDetector.ts
Replaces `ResourceAttributes` with `Attributes`
Refs #4175
Replace the interfaces internally. The changes are not affecting the public API of the detector so it's not marked as breaking change.
Ran the test suite for the detector
=> refactor(browser-detector): replace `ResourceAtrributes` with `Attributes`

experimental/CHANGELOG.md, experimental/packages/sdk-logs/test/common/export/BatchLogRecordProcessor.test.ts, experimental/packages/sdk-logs/test/common/export/SimpleLogRecordProcessor.test.ts
Replaces `ResourceAttributes` with `Attributes`
Refs #4175
Replace the interfaces in the tests.
Ran the test suite for the logs SDK
=> refactor(sdk-logs): replace ResourceAtrributes with Attributes

.github/workflows/unit-test.yml
Saw this earlier when working on #5010. 
We needed this when we were still using webpack 4, but we've fully migrated to webpack 5, so we can drop it :slightly_smiling_face:
=> chore: remove --openssl-legacy-provider option

experimental/CHANGELOG.md, experimental/packages/sdk-events/package.json, experimental/packages/sdk-logs/package.json, experimental/packages/sdk-logs/src/LogRecord.ts, package-lock.json
I saw that there's two `devDependency` entries old `@opentelemetry/api-events` and `@opentelemetry/api-logs` packages, which cause an old package to be present for these two packages.
The current version is actually specified as a `dependency` so removing the `devDependency` is safe.
Since the `devDependency` pulled in the local types, we had some type-mismatch with in `@opentelemetry/sdk-logs` where `null` was not an allowed input with the changed type.
=> fix(events,logs): drop outdated API from devDependencies and align types

CHANGELOG.md, packages/sdk-metrics/src/Instruments.ts, packages/sdk-metrics/src/ObservableResult.ts, packages/sdk-metrics/src/aggregator/types.ts, packages/sdk-metrics/src/exemplar/AlignedHistogramBucketExemplarReservoir.ts, packages/sdk-metrics/src/exemplar/AlwaysSampleExemplarFilter.ts, packages/sdk-metrics/src/exemplar/Exemplar.ts, packages/sdk-metrics/src/exemplar/ExemplarFilter.ts, packages/sdk-metrics/src/exemplar/ExemplarReservoir.ts, packages/sdk-metrics/src/exemplar/NeverSampleExemplarFilter.ts, packages/sdk-metrics/src/exemplar/SimpleFixedSizeExemplarReservoir.ts, packages/sdk-metrics/src/exemplar/WithTraceExemplarFilter.ts, packages/sdk-metrics/src/export/MetricData.ts, packages/sdk-metrics/src/state/DeltaMetricProcessor.ts, packages/sdk-metrics/src/state/HashMap.ts, packages/sdk-metrics/src/state/MultiWritableMetricStorage.ts, packages/sdk-metrics/src/state/SyncMetricStorage.ts, packages/sdk-metrics/src/state/WritableMetricStorage.ts, packages/sdk-metrics/src/types.ts, packages/sdk-metrics/src/utils.ts, packages/sdk-metrics/test/MeterProvider.test.ts, packages/sdk-metrics/test/state/HashMap.test.ts, packages/sdk-metrics/test/state/MultiWritableMetricStorage.test.ts, packages/sdk-metrics/test/util.ts, packages/sdk-metrics/test/utils.test.ts
Replaces `MetricsAttributes` with `Attributes`
Refs #4175
Replace the interfaces in sources & tests.
at the root folder
- npm run compile
- npm run test
=> refactor(sdk-metrics): replace `MetricsAttributes` with `Attributes`

CHANGELOG.md, experimental/packages/opentelemetry-instrumentation-http/src/http.ts, experimental/packages/opentelemetry-instrumentation-http/src/types.ts, experimental/packages/opentelemetry-instrumentation-http/src/utils.ts, experimental/packages/opentelemetry-instrumentation-http/test/functionals/http-enable.test.ts, experimental/packages/opentelemetry-instrumentation-http/test/functionals/utils.test.ts
Replaces `SpanAttributes` and `MetricsAttributes` with `Attributes`. Mote this is not marked as a breaking change since `@opentelemetry/api` dependency is already at `v1.3.0` and types do not break.
Refs #4175
compile and ran the test suite for instrumentation
=> refactor(instrumentation-http): replace `SpanAttributes` and `MetricAttributes` with `Attributes`

experimental/CHANGELOG.md, experimental/packages/opentelemetry-sdk-node/src/utils.ts
This PR addresses the issue #4882, which involves logging an unrecognized OTEL_NODE_RESOURCE_DETECTORS value. According to the OpenTelemetry specification, unrecognized enum values should generate a warning rather than an error. The current implementation uses diag.error to log this issue, but it should use diag.warn instead to align with the specification and avoid unnecessary error-level logging.
Fixes: #4882
Updated opentelemetry-sdk-node/src/utils.ts and auto-instrumentations-node/src/utils.ts to replace diag.error with diag.warn for handling unrecognized OTEL_NODE_RESOURCE_DETECTORS values.
This change ensures that unrecognized values generate a warning, as specified in the OpenTelemetry SDK environment variable guidelines.
Bug fix (non-breaking change which fixes an issue)
- Ran the …
=> fix(sdk-node): use warn instead of error on unknown OTEL_NODE_RESOURCE_DETECTORS values

CHANGELOG.md, packages/opentelemetry-exporter-zipkin/test/common/transform.test.ts
The Span constructor from ' @opentelemetry/sdk-trace-base` is planned for removal from the public API . This PR anticipates the possible breaking changes derived from it
Refs #3597
- Remove usage of `new Span` constructor in favour of `Tracer.startSpan`
=> chore(exporter-zipkin): remove usages of Span constructor

CONTRIBUTING.md
we still recommend using `npm install` in the docs, but we now include a `package-lock.json` so `npm ci` provides a better development experience.
=> docs: use npm ci in CONTRIBUTING.md

.github/workflows/unit-test.yml
Noticed that all the PR states that the coverage from `main` is behind. Looks like on main the permissions are not enough to create a new main commit in codecov. 
So I'm now passing the token to see if that makes a difference. This is what the Go SIG does:
https://github.com/open-telemetry/opentelemetry-go/blob/8fbaa970843f0899228bc19c1e45a31f5a5bb73e/.github/workflows/ci.yml#L124-L130
See:
- failing upload: https://github.com/open-telemetry/opentelemetry-js/actions/runs/11223167457/job/31197190624#step:9:52 
- comment on PR: https://github.com/open-telemetry/opentelemetry-js/pull/5031#issuecomment-2388633390
I've noticed the same happening on contrib, where we're hundreds of commits behind. We'll have to do the same there.
=> ci: use codecov token when uploading reports

experimental/CHANGELOG.md, experimental/packages/exporter-logs-otlp-proto/src/platform/node/OTLPLogExporter.ts
The `OTLPLogExporter` constructor doesn't specify the correct config type. This updates it from `OTLPExporterConfigBase` to `OTLPExporterNodeConfigBase`.
Fixes #5057
=> fix(exporter-logs-otlp-proto): Use correct config type in constructor

CONTRIBUTING.md
Fixes: #5046 
Packages that also run in browser have browser-specific tests. Adding this information in [Running tests](https://github.com/open-telemetry/opentelemetry-js/blob/main/CONTRIBUTING.md#running-tests) CONTRIBUTING.md.
=>  Added custom test instructions for browser-specific tests

.github/workflows/publish-to-npm.yml
We currently don't publish from a workflow, this PR adds a workflow so that we can release by dispatching it. This is not optimal yet, but it moves us closer towards a fully automated release pipeline.
I will update the `doc/contributing/releasing.md` when I've released with the new workflow at least once. I will then also remove the publish script from `package.json`.
Updates #4924
=> ci: add workflow to publish packages to npm

experimental/CHANGELOG.md, experimental/packages/otlp-grpc-exporter-base/test/configuration/otlp-grpc-configuration.test.ts
See test failure in #5068, after we updated the versions, the tests failed because they were hardcoded. This PR fixes this, and also moves some changelog entries to the correct spot (I had put them in bugfix but they belong in the breaking changes section).
=> test(otlp-grpc-exporter-base): do not use hard-coded version in tests, touch up changelog entries

integration-tests/tracecontext-integration-test.sh
Tests are currently failing (see [here](https://github.com/open-telemetry/opentelemetry-js/actions/runs/11345739893/job/31554085622?pr=5068), probably due to some changes that don't allow the use of `pip install` with an externally managed environment, like the global one that's supposed to be managed by the system and requires packages to be installed via `apt` on Ubuntu 24.04). This PR makes the test script use a `venv` instead to avoid this error.
=> test: use venv in w3c trace context test script

experimental/packages/opentelemetry-instrumentation-http/src/http.ts, experimental/packages/opentelemetry-instrumentation-http/src/utils.ts, experimental/packages/opentelemetry-instrumentation-http/test/functionals/http-enable.test.ts, experimental/packages/opentelemetry-instrumentation-http/test/functionals/http-metrics.test.ts
While reviewing #5079 I noticed that we don't set `http.route` and `http.response.status` code in the server duration metrics, so this PR addresses a few problems:
- We did not add `http.route` to the `Span` on "new" metrics
- We add the `http.route` only when `DUPLICATE` emission is turned on because 
- we also didn't add it to the Span for "new" metrics
- but we did add it for the "old" metrics and the attribute name happens to match
-  we never added the `http.response.status` code, because 
- it is not yet determined when we add it (before the request is handled)
**NOTE: skipping changelog because this is a bug in an unreleased feature**
Supersedes #5079
Related to #5026
=> fix(instrumentation-http): add server attributes after they become available

README.md
In recognition of her excellent work on the project, I propose to add @maryliag to the list of JS approvers.
=> chore: add @maryliag to approvers

.github/workflows/publish-to-npm.yml, doc/contributing/releasing.md
I added another workflow recently #5067 - this PR:
- adds some instructions for that new workflow, and replaces the old ones
- adds some extra comments to explain the added workflow from #5067, some things I figured out myself over time and some of the knowledge there was handed down to me a long time ago but never put into writing
- fixes a broken link for the workflow to create release PRs
=> docs: update releasing.md to mention npm publish workflow, fix a link to release PR workflow

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation-http/src/utils.ts, experimental/packages/opentelemetry-instrumentation-http/test/integrations/http-enable.test.ts
Skips malformed `forwarded` headers instead of throwing an uncaught exception.
Fixes #5095 
Introduce `parseForwardedHeader` in `experimental/packages/opentelemetry-instrumentation-http/src/utils.ts` which wraps `forwarded-parse` and returns an empty array on any caught exception.
First, wrote a test that broke the instrumentation in the expected way (throwing `ParseError: Unexpected end of input`).
Then, fixed it and confirmed the test passes.
=> fix(instrumentation-http): skip malformed forwarded headers

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation-http/src/http.ts
Issue: Setting the `OTEL_SEMCONV_STABILITY_OPT_IN` environment variable doesn't do anything.
Bug: In the `http.ts line 112` the for loop iterates through `getEnv().OTEL_SEMCONV_STABILITY_OPT_IN` but the since it's using `in` the value of `entry` would be the indice of the element in the array (0,1,..) not the value.
Fix: Using `of` instead iterates over the values themselves.
Please see https://www.typescriptlang.org/docs/handbook/iterators-and-generators.html#forof-vs-forin-statements for more information about the use of `in` vs `of`
Issue: Setting the `OTEL_SEMCONV_STABILITY_OPT_IN` environment variable doesn't do anything.
Bug: In the `http.ts line 112` the for loop iterates through `getEnv().OTEL_SEMCONV_STABILITY_OPT_IN` but the since it's using `in` the value of `entry` would be …
=> fix(instrumentation-http): iterating through the OTEL_SEMCONV_STABILITY_OPT_IN content instead of the entry indices

experimental/packages/opentelemetry-sdk-node/src/utils.ts
Hi
A grep across the whole codebase return now other impacted files.
=> fix(sdk-node): fix typo `FomEnv` → `FromEnv`

CHANGELOG.md, packages/opentelemetry-sdk-trace-base/src/Span.ts
=> fix(sdk-trace): performance.now() may return the same value for consecutive calls

semantic-conventions/CHANGELOG.md, semantic-conventions/src/resource/SemanticResourceAttributes.ts, semantic-conventions/src/trace/SemanticAttributes.ts
This updates the `@deprecated ...` message for some of the old constants
where they referred to constants that now no longer exist, because they
where themselves deprecated or removed.
This is a partial fix for https://github.com/open-telemetry/opentelemetry-js/issues/5025
=> fix(semantic-conventions): update deprecated messages for some old constants

CHANGELOG.md, packages/sdk-metrics/src/export/CardinalitySelector.ts, packages/sdk-metrics/src/export/MetricReader.ts, packages/sdk-metrics/src/state/AsyncMetricStorage.ts, packages/sdk-metrics/src/state/DeltaMetricProcessor.ts, packages/sdk-metrics/src/state/MeterSharedState.ts, packages/sdk-metrics/src/state/MetricCollector.ts, packages/sdk-metrics/src/state/SyncMetricStorage.ts, packages/sdk-metrics/src/view/View.ts, packages/sdk-metrics/test/MeterProvider.test.ts, packages/sdk-metrics/test/state/AsyncMetricStorage.test.ts, packages/sdk-metrics/test/state/DeltaMetricProcessor.test.ts, packages/sdk-metrics/test/state/MetricStorageRegistry.test.ts, packages/sdk-metrics/test/state/SyncMetricStorage.test.ts, packages/sdk-metrics/test/state/TemporalMetricProcessor.test.ts
implements Otel Cardinality Limit spec.
This change allows you to:
- configure View for custom aggregation cardinality limit. 
- allows specifying cardinality selector on metric reader
- also applies default 2000 limit if it's not set.
Link to the spec: https://opentelemetry.io/docs/specs/otel/metrics/sdk/#cardinality-limits
Updated PR to support both async and sync storage
References https://github.com/open-telemetry/opentelemetry-js/issues/4095
- added unit tests
- created a small app that uses this package via npm link
=> feat(sdk-metrics): add aggregation cardinality limit

experimental/CHANGELOG.md
I messed up the changelog formatting in one of my PRs, so the lint step is failing on `main` now, this PR fixes it
=> docs: fix changelog formatting

CHANGELOG_NEXT.md, experimental/packages/opentelemetry-sdk-node/test/sdk.test.ts, packages/opentelemetry-sdk-trace-base/src/BasicTracerProvider.ts, packages/opentelemetry-sdk-trace-base/src/Span.ts, packages/opentelemetry-sdk-trace-base/test/common/BasicTracerProvider.test.ts, packages/opentelemetry-sdk-trace-node/test/NodeTracerProvider.test.ts
After merging https://github.com/open-telemetry/opentelemetry-js/pull/5152 it is not necessary to have `_registeredSpanProcessors` private property to modify at runtime. This PR does remove the property and adapts the tests.
Fixes #5136 
- remove `_registeredSpanProcessors` from `BasicTracerProvider`
- wrap all processors in a MultiSpanProcessor to make sure `forceFlush` works in all situations.
- add a test for it
- update tests to not access the removed property
- compiled all packages
- tested all packages
=> refactor(sdk-trace-base): remove `_registeredSpanProcessors` from BasicTracerProvider

CHANGELOG_NEXT.md, experimental/packages/opentelemetry-sdk-node/test/sdk.test.ts, packages/opentelemetry-sdk-trace-base/src/BasicTracerProvider.ts, packages/opentelemetry-sdk-trace-base/src/Span.ts, packages/opentelemetry-sdk-trace-base/src/Tracer.ts, packages/opentelemetry-sdk-trace-base/test/common/BasicTracerProvider.test.ts, packages/opentelemetry-sdk-trace-base/test/common/MultiSpanProcessor.test.ts, packages/opentelemetry-sdk-trace-base/test/common/Span.test.ts, packages/opentelemetry-sdk-trace-base/test/common/Tracer.test.ts, packages/opentelemetry-sdk-trace-base/test/common/export/SimpleSpanProcessor.test.ts, packages/opentelemetry-sdk-trace-base/test/common/export/TestTracingSpanExporter.ts
Resource and active span processor should not be accessible once the tracer provider is constructed. This PR makes the necessary changes to have both as private properties and inject them into any tracer created via `getTracer` API.
Fixes #4791
Fixes #4792 
- made `resource` private in `BasicTracerProvider`
- remove `getActiveSpanProcessor` in `BasicTracerProvider`
- refactor `SpanImpl` constructor
- update `Tracer.startSpan` to use the new constructor
- refactor `Tracer` constructor to get only necessary deps (processor & resource) instead of the provider
- update tests
I've decided to change the constructor method signature for `SpanImpl`. This way we inject the necessary dependencies that are held in the `Tracer` class making unnecessary to have public properties or getters for span …
=> refactor(sdk-trace-base): make resource private and remove getActiveSpanProcessor API

experimental/CHANGELOG.md, experimental/packages/exporter-trace-otlp-http/test/browser/CollectorTraceExporter.test.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-http/test/browser/CollectorMetricExporter.test.ts, experimental/packages/otlp-exporter-base/src/transport/xhr-transport.ts, experimental/packages/otlp-exporter-base/test/browser/xhr-transport.test.ts
Skips creating a blob and passes the `Uint8Array` directly to `request.send()`, as it was done before `0.53.0`. Both are an acceptable input according to https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/send#parameters, but creating `Blob`s does not seem to work in React Native.
Fixes #5178
=> refactor(otlp-exporter-base): don't create blob before sending xhr

api/src/platform/browser/globalThis.ts, experimental/packages/api-events/src/platform/browser/globalThis.ts, experimental/packages/api-logs/src/platform/browser/globalThis.ts, experimental/packages/opentelemetry-instrumentation-grpc/test/helper.ts, package-lock.json, package.json, packages/opentelemetry-core/src/platform/browser/globalThis.ts, packages/opentelemetry-sdk-trace-web/src/utils.ts
Has the changes from #5190, plus `npm run lint:fix` to apply the new rules.
Supersedes #5190
- updates prettier to 3.3.3
- applies `lint:fix`
=> chore: update prettier to 3.3.3

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
The current link is broken https://github.com/open-telemetry/community/blob/main/CONTRIBUTING.md
Fixes the broken link for contribution processes which were moved in https://github.com/open-telemetry/community/pull/2051
=> fix(docs): broken link for community contribution lifecycle and processes

packages/opentelemetry-core/src/common/time.ts, packages/opentelemetry-sdk-trace-base/src/Span.ts
The [String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated.
This PR replaces `String.prototype.substr()` with [String.prototype.substring()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring)
=> chore: replace deprecated String.prototype.substr() with substring()

experimental/CHANGELOG.md, experimental/packages/exporter-logs-otlp-grpc/src/index.ts, experimental/packages/exporter-trace-otlp-grpc/src/index.ts, experimental/packages/exporter-trace-otlp-http/src/index.ts, experimental/packages/exporter-trace-otlp-http/src/platform/browser/index.ts, experimental/packages/exporter-trace-otlp-http/src/platform/index.ts, experimental/packages/exporter-trace-otlp-http/src/platform/node/index.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/src/index.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-proto/src/index.ts, experimental/packages/opentelemetry-sdk-node/src/index.ts
See #5218. Using `export *` in comments breaks some build tooling (specifically the tooling used by Nuxt) and breaks the build output. 
Note for reviewers: This is weird and this is difficult to test, please use the [reproducer I created](https://github.com/pichlermarc/repro-5218) for verifying that this actually fixes the problem. I also did not believe it at first when I narrowed it down to a comment. 😅 
Fixes #5218 
changes `export *` in comments to read `wildcard export` instead
=> fix: de-confuse Nuxt build tooling by not using  'export *' in comments

CHANGELOG.md, packages/opentelemetry-sdk-trace-base/src/config.ts
Right now `@opentelemetry/sdk-trace-base` loads `OTEL_*` env vars when it is loaded, regardless of if `loadDefaultConfig` is ever called. In runtimes with a permission model like Deno, this may cause a bunch of permission prompts right on startup. This PR changes the env vars to all be loaded when `loadDefaultConfig` is called.
Interestingly, previously only `buildSamplerFromEnv` used the "global" env vars. For all other options the env vars are re-read on every call to `loadDefaultConfig`.
I have tested locally that Deno does not prompt for env vars on startup anymore when `@opentelemetry/sdk-trace-base` is loaded.
=> fix(sdk-trace-base): don't load envs top level

.github/workflows/unit-test.yml
Some devDependencies for browser/webworker tests require Node.js 18+. Since Node.js Version for web tests only affects development, we can bump the version we use for testing browser/workers to Node.js 22. This will unblock some Renovate updates.
=> ci: run browser and worker tests on Node.js 22

CHANGELOG.md, experimental/packages/opentelemetry-exporter-metrics-otlp-http/test/node/OTLPMetricExporter.test.ts, packages/sdk-metrics/src/MeterProvider.ts, packages/sdk-metrics/src/export/PeriodicExportingMetricReader.ts, packages/sdk-metrics/test/MeterProvider.test.ts, packages/sdk-metrics/test/export/PeriodicExportingMetricReader.test.ts
Metric provider behave differently from traces and logs providers during shutdown process, being the only one that does not flush pending tasks.
Although it's not explicitly required ([yet](https://github.com/open-telemetry/opentelemetry-specification/issues/2983)) by the specs for [metrics](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#shutdown-1) and [logs](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/sdk.md#shutdown) as it is for [traces](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#shutdown-1), this PR adds flushing metrics on shutdown, with the intent of eliminating a not infrequent confusion and wrong assumption among users. …
=> feat(sdk-metrics): PeriodicExportingMetricReader now flushes pending tasks at shutdown

CHANGELOG.md
Changelog entry was misplaced in #5128, updating it to fit the correct category (I also edited the release before publishing 1.29.0 to avoid confusion)
=> docs: re-categoize misplaced changelog entry

semantic-conventions/CHANGELOG.md, semantic-conventions/README.md
It is recommended that users (typically instrumentation libraries) of *unstable* semconv create a local copy of relevant definitions, rather than pinning. Pinning of this package can easily lead to very many versions of the package being installed, which leads to heavy disk usage.
Refs: #5182
=> doc(semantic-conventions): clarify suggested usage of *unstable* semconv

.github/workflows/benchmark.yml, .github/workflows/unit-test.yml
- limit to npm@<11 on Node 18 as npm@11.0.0 dropped support for it via the engines field (README.md is not updated yet)
- Updates benchmark workflow to latest LTS Node.js version
- Updates Windows tests to run on Node.js v20
=> fix(ci): adapt workflow to use supported npm versions

CHANGELOG.md
I was reviewing the `v1.next` release PRs, caught one of the CHANGELOG entry pointing to the wrong issue number, which made it into #5274. Figured we could still get that fixed before the release goes out
=> Fix incorrect CHANGELOG entry on main (`v1.next`)

packages/opentelemetry-sdk-trace-base/src/BasicTracerProvider.ts
Removing a circular dependency in `opentelemetry-sdk-trace-base` `BasicTracerProvider.ts` which was causing an error on React Native/Babel:
`Cannot read property 'prototype' of undefined`
Simply changed it to direct import, should not be an issue on other platforms.
Changed the import from `'.'` to `'./Tracer'` and `'./SpanProcessor'`.
Retried getting a Tracer with the changes and the error was not there anymore, Tracer worked correctly.
=> chore: removed circular dependency from BasicTracerProvider

README.md
* Includes a cherry-pick for #5286
* Synced supported Node versions (for v2.0)
* Also deleted a very old comment about Node 8 being required. Node 8 was EOL in 2019, it seems extremely unlikely that the `perf_hook` is the _only_ thing preventing the SDK from working in extremely old versions at this point.
=> chore: update supported versions in 2.0 README

CHANGELOG.md, packages/sdk-metrics/src/InstrumentDescriptor.ts, packages/sdk-metrics/src/Meter.ts, packages/sdk-metrics/src/aggregator/ExponentialHistogram.ts, packages/sdk-metrics/src/aggregator/Histogram.ts, packages/sdk-metrics/src/export/AggregationSelector.ts, packages/sdk-metrics/src/export/CardinalitySelector.ts, packages/sdk-metrics/src/export/ConsoleMetricExporter.ts, packages/sdk-metrics/src/export/InMemoryMetricExporter.ts, packages/sdk-metrics/src/export/MetricData.ts, packages/sdk-metrics/src/export/MetricExporter.ts, packages/sdk-metrics/src/export/MetricReader.ts, packages/sdk-metrics/src/index.ts, packages/sdk-metrics/src/state/MeterProviderSharedState.ts, packages/sdk-metrics/src/state/MetricCollector.ts, packages/sdk-metrics/src/view/Aggregation.ts, packages/sdk-metrics/src/view/InstrumentSelector.ts, packages/sdk-metrics/src/view/View.ts, packages/sdk-metrics/test/InstrumentDescriptor.test.ts, packages/sdk-metrics/test/util.ts, packages/sdk-metrics/test/view/Aggregation.test.ts
Drop the `@deprecated` `InstrumentDescriptor` type export 
Note that this public `InstrumentDescriptor` has always been just an alias of `MetricDescriptor`, and does not actually point to the internal type with the same name.
Separately:
* Refactor the internal `InstrumentDescriptor` type to extend from the public `MetricDescriptor`, adding only the `advice` field
* Move the `InstrumentType` enum into `./src/export/MetricData.ts` as it is a public export, plus to avoid a circular dependency after the refactor (hence the big diff)
Fixes https://github.com/open-telemetry/opentelemetry-js/pull/5254#issuecomment-2541202896 (cc @pichlermarc)
=> feat(sdk-metrics)!: Drop deprecated `InstrumentDescriptor` export

experimental/packages/opentelemetry-instrumentation-fetch/test/fetch.test.ts
Refactor `fetch()` tests for improved clearity, type safety and realism (relative to the real-world `fetch` behavior).
I would like to propose something for #4888 to start a discussion, but in doing so I find that the current tests are quite confusing to work with, so I split out these refactors to the tests as a separate PR/proposal.
I think this represents a significant enough improvements to the tests that it makes sense as a PR, but ~~I may something else that I want to try/propose next week~~ in the longer term, I am also proposing that we further refactor these tests in #5282.
See the inline commits on the PR.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any …
=> [instrumentation-fetch] refactor fetch() tests for clarity, type safety and realism

experimental/packages/exporter-logs-otlp-http/package.json, experimental/packages/exporter-logs-otlp-proto/package.json, experimental/packages/exporter-trace-otlp-http/package.json, experimental/packages/exporter-trace-otlp-proto/package.json, experimental/packages/opentelemetry-browser-detector/package.json, experimental/packages/opentelemetry-exporter-metrics-otlp-http/package.json, experimental/packages/opentelemetry-instrumentation-fetch/package.json, experimental/packages/opentelemetry-instrumentation-xml-http-request/package.json, experimental/packages/opentelemetry-instrumentation/package.json, experimental/packages/otlp-exporter-base/package.json, experimental/packages/sdk-events/package.json, experimental/packages/sdk-logs/package.json, experimental/packages/web-common/package.json, package-lock.json, packages/opentelemetry-exporter-zipkin/package.json, packages/opentelemetry-resources/package.json, packages/opentelemetry-sdk-trace-web/package.json, packages/sdk-metrics/package.json
Just a quick clean-up. We don't use `webpack-merge` in these packages, so I'm removing the `devDependency`.
=> chore(deps): remove webpack-merge where it is not needed

examples/opentelemetry-web/package.json, package-lock.json, selenium-tests/package.json
Supersedes #5269
Here is [`git diff <mybranch> renovate-bot/renovate/webpack-dev-server-5.x`](https://gist.github.com/chancancode/8c6d3f08374a89714ba06fa586bc82c9) if anyone cares.
=> chore(deps): update dependency webpack-dev-server to v5

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation-fetch/src/fetch.ts, experimental/packages/opentelemetry-instrumentation-fetch/test/fetch.test.ts
Currently, the browser `fetch()` instrumentation unconditionally clones the response object for every request, in order to preserve the ability for the `applyCustomAttributes` to consume the response body. This cloned response doesn't get consumed/released until the body has been streamed and read entirely, which forces the browser to buffer and retain the entire response body, creating unnecessary memory pressure on large or long-running response streams. In extreme cases, this is effectively a memory leak and can cause the browser tab to crash.
Fixes #4888
The offending code was added in #2497. This commit effectively reverts that commit and breaks the feature. This is certainly a breaking change, and we can discuss the mitigations below. …
=> feat(instrumentation-fetch)! Passthrough original request to `applyCustomAttributes`

CHANGELOG.md, experimental/CHANGELOG.md, experimental/packages/opentelemetry-exporter-prometheus/src/PrometheusSerializer.ts, experimental/packages/opentelemetry-exporter-prometheus/test/PrometheusExporter.test.ts, experimental/packages/opentelemetry-exporter-prometheus/test/PrometheusSerializer.test.ts, experimental/packages/otlp-transformer/test/metrics.test.ts, experimental/packages/shim-opencensus/src/metric-transform.ts, experimental/packages/shim-opencensus/test/OpenCensusMetricProducer.test.ts, experimental/packages/shim-opencensus/test/metric-transform.test.ts, packages/sdk-metrics/src/InstrumentDescriptor.ts, packages/sdk-metrics/src/aggregator/ExponentialHistogram.ts, packages/sdk-metrics/src/aggregator/Histogram.ts, packages/sdk-metrics/src/aggregator/LastValue.ts, packages/sdk-metrics/src/aggregator/Sum.ts, packages/sdk-metrics/src/aggregator/types.ts, packages/sdk-metrics/src/export/MetricData.ts, packages/sdk-metrics/test/Instruments.test.ts, packages/sdk-metrics/test/aggregator/ExponentialHistogram.test.ts, packages/sdk-metrics/test/aggregator/Histogram.test.ts, packages/sdk-metrics/test/export/MetricReader.test.ts, packages/sdk-metrics/test/util.ts
Drop deprecated `type` field on `MetricDescriptor`
Fixes #3439
Fixes https://github.com/open-telemetry/opentelemetry-js/pull/5266#pullrequestreview-2514648591 (@pichlermarc)
Move the field to the internal `InstrumentDescriptor` type and keep it for internal use.
See also: https://github.com/open-telemetry/opentelemetry-js/pull/5266#issuecomment-2556564698
=> feat(sdk-metrics)!: drop deprecated `type` field on `MetricDescriptor`

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation-grpc/package.json, experimental/packages/opentelemetry-instrumentation-http/package.json, experimental/packages/opentelemetry-sdk-node/README.md, experimental/packages/opentelemetry-sdk-node/package.json, experimental/packages/opentelemetry-sdk-node/test/sdk.test.ts, experimental/packages/shim-opencensus/package.json, package-lock.json, packages/opentelemetry-sdk-trace-node/package.json
This re-applies some changes from #4341 that were dropped in
the merge from 'next' back to 'main'.
As a rider, it also corrects the sdk-node/README to indicate
the default context-manager is now the one based on AsyncLocalStorage.
=> chore(deps): remove unused 'semver' deps from some packages

experimental/CHANGELOG.md, experimental/packages/opentelemetry-exporter-metrics-otlp-http/src/platform/browser/OTLPMetricExporter.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-http/test/browser/OTLPMetricExporter.test.ts
Refs: #5031
---
This was pointed out in Slack here: https://cloud-native.slack.com/archives/C01NL1GRPQR/p1736535825217819
My PR copies some of the test blocks from "test/node/OTLPMetricExporter.test.ts" (those that were passing
config to `OTLPMetricExporter`) over to the platform test file.
/cc @pichlermarc
=> fix(exporter-metrics-otlp-http): browser OTLPMetricExporter was not passing config to OTLPMetricExporterBase super class

.github/workflows/changelog.yml, CHANGELOG.md
Refs https://github.com/open-telemetry/opentelemetry-js/pull/5284#discussion_r1891065431
Changelog workflow does only check `main` at the moment - this PR makes it check `v1.x` too.
Tested by adding a changelog entry - see #5337 for a PR that does have an entry, but the workflow fails.
=> [backport/v1.x] ci: make changelog workflow check v1.x

CHANGELOG.md, packages/sdk-metrics/src/export/PeriodicExportingMetricReader.ts, packages/sdk-metrics/test/export/PeriodicExportingMetricReader.test.ts
=> [backport/v1.x] fix(sdk-metrics): don't export from PeriodicExportingMetricReader with no metrics (#5288)

experimental/CHANGELOG.md, experimental/packages/opentelemetry-exporter-metrics-otlp-http/src/platform/browser/OTLPMetricExporter.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-http/test/browser/OTLPMetricExporter.test.ts
=> [backport/v1.x] fix(exporter-metrics-otlp-http): browser OTLPMetricExporter was not passing config to OTLPMetricExporterBase super class [#5331]

.github/workflows/create-or-update-release-pr.yml
Release PR automation is broken as `v1.x` does not exist on the fork, so this PR fixes that by checking out main first, then changing to v1.x and pushing it once we've fetched.
See https://github.com/open-telemetry/opentelemetry-js/actions/runs/12751711772/job/35539475261
=> [backport/v1.x] ci: make v1.x release PR workflow checkout correct branch

experimental/CHANGELOG.md, experimental/packages/opentelemetry-sdk-node/src/sdk.ts, experimental/packages/opentelemetry-sdk-node/src/utils.ts, experimental/packages/opentelemetry-sdk-node/test/sdk.test.ts
Fixes #5304
This commit lowers the diagnostic level to debug when exporters are not explicitly provided and the default is used.
(Note - there are a couple other similar logs like 'OTEL_TRACES_EXPORTER contains "none". SDK will not be initialized.' but I was not sure if they should be updated too.)
=> feat(sdk-node): lower diagnostic level

experimental/CHANGELOG.md, experimental/packages/otlp-exporter-base/src/configuration/shared-configuration.ts, experimental/packages/otlp-exporter-base/src/configuration/shared-env-configuration.ts, experimental/packages/otlp-exporter-base/test/common/configuration/shared-configuration.test.ts
This PR removes validation code that is not needed.
Fixes N/A
This commit removes two `Number.isNaN()` checks. These checks are not needed because the `Number.isFinite()` checks they are paired with also detect `NaN` values.
=> refactor(otlp-exporter-base): remove unnecessary `isNaN()` checks

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation-grpc/src/utils.ts
There is not a problem, but this appears to be unused code.
Fixes N/A
This commit removes the `findIndex()` function. This function appears to be unused and `findIndex()` is part of the language now.
=> chore(instrumentation-grpc): remove unused `findIndex()` function

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation-grpc/src/serverUtils.ts, experimental/packages/opentelemetry-instrumentation-grpc/test/helper.ts
`errorMonitor` should be preferred over `'error'` event handlers for instrumentation, as the latter alters the behavior of the server if the user has not added their own error handler.
Related to: https://github.com/open-telemetry/opentelemetry-js/issues/225. I'm not sure we want to close the issue based on this fix.
This commit updates instrumentation-grpc to utilize `errorMonitor` instead of `'error'` event handlers. This makes the instrumented server behave more like it would without instrumentation.
=> feat(instrumentation-grpc): monitor error events with events.errorMonitor

packages/sdk-metrics/src/state/DeltaMetricProcessor.ts
Fixes the following eslint warning in the sdk-metrics package:
```
/home/runner/work/opentelemetry-js/opentelemetry-js/packages/sdk-metrics/src/state/DeltaMetricProcessor.ts
96:32  warning  Forbidden non-null assertion  @typescript-eslint/no-non-null-assertion
```
Ref #5365
The assertion was intentional, base on the `.has()` check with the same inputs immediately prior. The surrounding code has the same patterns and used the eslint magic comment to disable the warning, this one was just missed.
=> refactor(sdk-metrics): fix eslint warning

experimental/packages/opentelemetry-instrumentation/src/types.ts
Fixes the following eslint warning:
```
/home/runner/work/opentelemetry-js/opentelemetry-js/experimental/packages/opentelemetry-instrumentation/src/types.ts
140:24  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
140:68  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
146:24  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
```
Ref #5365
The annotations weren't working because they were placed on the wrong lines.
=> refactor(instrumentation): fix eslint warnings

packages/opentelemetry-sdk-trace-web/src/utils.ts
```
/home/runner/work/opentelemetry-js/opentelemetry-js/packages/opentelemetry-sdk-trace-web/src/utils.ts
52:14  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
```
Ref #5365
The eslint comment wasn't working because it was placed on the wrong line. However, it also wasn't necessary anymore – `keyof any` was used to obtain the union of all possible object key types – `string | number | symbol`. TypeScript now provides an alias for this in the standard libaray that gives exactly the same result.
Also fixed what appears to be a TypeError on an un-annotated `let` binding, not sure why it wasn't caught by the type checker, maybe it was just missed on the version of TS we are using.
Please describe the tests …
=> refactor(sdk-trace-web): fix eslint warning

packages/opentelemetry-sdk-trace-node/test/registration.test.ts
Fix the following eslint warning:
```
/home/runner/work/opentelemetry-js/opentelemetry-js/packages/opentelemetry-sdk-trace-node/test/registration.test.ts
30:61  warning  Don't use `Function` as a type  @typescript-eslint/ban-types
```
Ref #5365
Here we are looking for a `AnyConstructor` type, and `Function` is a close enough approximation that exists in the standard library.
The potential foot gun of _calling_ the function resulting in an `any` value still exists, but this is a small function used in tests only, so that's probably acceptable.
=> refactor(sdk-trace-node): fix eslint warning

CHANGELOG.md, packages/opentelemetry-exporter-zipkin/src/platform/node/util.ts
Addresses the following deprecation/eslint warning:
```
/home/runner/work/opentelemetry-js/opentelemetry-js/packages/opentelemetry-exporter-zipkin/src/platform/node/util.ts
34:19  warning  'url.parse' was deprecated since v11.0.0. Use 'url.URL' constructor instead  node/no-deprecated-api
```
Ref #5365
`url.parse` is deprecated in favor of `new URL()`.
`url.parse` do not get CVEs so at minimum using it in production code a security liability, if not an outright vulnerability.
They do behave differently so it's often not a straightforward direct replacement. However, in this case, the only reason we are even calling `url.parse` is to extract a set of info to merge into the options we pass into `http(s).request`. `http(s).request` now takes a separate URL argument, so we can bypass that.
So …
=> fix(exporter-zipkin): remove deprecated `url.parse` usage

experimental/packages/opentelemetry-browser-detector/src/BrowserDetector.ts
Fixes the following eslint warning
```
/home/runner/work/opentelemetry-js/opentelemetry-js/experimental/packages/opentelemetry-browser-detector/src/BrowserDetector.ts
66:66  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
```
Ref #5365
Use an appropriate type for the task in place of `any`
=> refactor(browser-detector): fix eslint warning

packages/opentelemetry-core/src/utils/lodash.merge.ts
Fixes the following eslint warning in the `core` pacakge:
```
/home/runner/work/opentelemetry-js/opentelemetry-js/packages/opentelemetry-core/src/utils/lodash.merge.ts
44:24  warning  Don't use `Function` as a type  @typescript-eslint/ban-types
```
Ref #5365
This could have been addressed in various ways with no change to the code, but upon further inspection, we can probably shed some weight here.
This code was inherited from lodash, which defines:
```js
const getPrototype = overArg(Object.getPrototypeOf, Object);
```
`overArg` allows each argument of the passed in function to be transformed by a mapper function, in this case, effective it amounts to:
```js
const getPrototypeOf = Object.getPrototype;
function getPrototype(value) {
return getPrototypeOf(Object(value));
}
```
So at …
=> refactor(core): fix eslint warning

experimental/packages/exporter-logs-otlp-grpc/src/index.ts, experimental/packages/exporter-trace-otlp-grpc/src/index.ts, experimental/packages/exporter-trace-otlp-http/src/index.ts, experimental/packages/exporter-trace-otlp-http/src/platform/browser/index.ts, experimental/packages/exporter-trace-otlp-http/src/platform/index.ts, experimental/packages/exporter-trace-otlp-http/src/platform/node/index.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/src/index.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-proto/src/index.ts
Fix the following eslint warnings:
```
/home/runner/work/opentelemetry-js/opentelemetry-js/experimental/packages/exporter-trace-otlp-http/src/index.ts
20:1  warning  Using 'ExportAllDeclaration' is not allowed  no-restricted-syntax
/home/runner/work/opentelemetry-js/opentelemetry-js/experimental/packages/exporter-trace-otlp-http/src/platform/browser/index.ts
20:1  warning  Using 'ExportAllDeclaration' is not allowed  no-restricted-syntax
/home/runner/work/opentelemetry-js/opentelemetry-js/experimental/packages/exporter-trace-otlp-http/src/platform/index.ts
20:1  warning  Using 'ExportAllDeclaration' is not allowed  no-restricted-syntax
/home/runner/work/opentelemetry-js/opentelemetry-js/experimental/packages/exporter-trace-otlp-http/src/platform/node/index.ts
20:1  warning  Using …
```
=> refactor(exporter-*): remove `export * from ...`

experimental/packages/opentelemetry-exporter-metrics-otlp-http/src/OTLPMetricExporterBase.ts
Fixes the following eslint warning in exporter-metrics-otlp-http:
```
/home/runner/work/opentelemetry-js/opentelemetry-js/experimental/packages/opentelemetry-exporter-metrics-otlp-http/src/OTLPMetricExporterBase.ts
120:30  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
```
Ref #5365
The unused parameter can be explicitly typed as `InstrumentType`, but since this default selector doesn't actually care about it, it can also just be elided.
By adding an explicit return type, if someone in the future added the wrong parameter to the default selector function, TypeScript would reject it.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any …
=> refactor(exporter-metrics-otlp-http): fix eslint warning

experimental/packages/opentelemetry-instrumentation-fetch/src/utils.ts
Fix the following eslint warnings:
```
/home/runner/work/opentelemetry-js/opentelemetry-js/experimental/packages/opentelemetry-instrumentation-fetch/src/utils.ts
137:16  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
138:21  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
```
Ref #5365
This can be avoided by re-ordering the branches so that TypeScript can narrow the type of the value progressively.
=> refactor(instrumentation-fetch): fix eslint warnings

semantic-conventions/package.json
It had been bumped to >=18 along with most other packages in the 'next' branch. However, the semconv package (similar to the 'api' package) is staying on 1.x, so we don't want to drop support for older Node.js versions in a minor.
---
This should get merged before a next verison of the semconv package is released. The latest release (1.28.0) has `>=14`.
=> chore(semantic-conventions): restore min-supported node to >=14

experimental/packages/opentelemetry-instrumentation-grpc/src/clientUtils.ts, experimental/packages/opentelemetry-instrumentation-grpc/src/instrumentation.ts, experimental/packages/opentelemetry-instrumentation-grpc/src/serverUtils.ts, experimental/packages/opentelemetry-instrumentation-grpc/test/helper.ts
Fixes the following eslint warnings in the instrumentation-grpc package:
```
/home/runner/work/opentelemetry-js/opentelemetry-js/experimental/packages/opentelemetry-instrumentation-grpc/src/clientUtils.ts
105:42  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
/home/runner/work/opentelemetry-js/opentelemetry-js/experimental/packages/opentelemetry-instrumentation-grpc/src/instrumentation.ts
129:69  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
134:69  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
139:68  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
144:68  warning  Unexpected any. Specify a different type …
```
=> refactor(instrumentation-grpc): fix eslint warnings

doc/metrics.md
Accidental reversal of link text and target in [Markdown](https://spec.commonmark.org/0.31.2/#links) `[link](/uri)`.
=> docs: Fix Markdown typo

README.md
This adds the section next to the existing 'Triagers' section
These are separate 'teams', the new one just provides permissions
on the contrib repo.
This adds Jon and Florencia for now. There are others to add, but
I will follow-up separately.
Refs: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2600
=> docs: add 'Contrib Triagers' section to the README

experimental/packages/exporter-logs-otlp-grpc/src/index.ts
This TODO was handled in #5399.
/cc @chancancode
=> chore: remove obsolete comment

experimental/CHANGELOG.md, experimental/packages/exporter-logs-otlp-grpc/package.json, experimental/packages/exporter-trace-otlp-grpc/package.json, package-lock.json
#5031 was a large refactor for OTLP exporters, and a dependency that was previously listed as a dev dependency is now required as a production dependency. Upgrading to [experimental/v0.56.0](https://github.com/open-telemetry/opentelemetry-js/releases/tag/experimental/v0.56.0) caused an error in Yarn PnP:
```
2025-01-09T01:35:53.432Z   220 U Error: @opentelemetry/exporter-logs-otlp-grpc tried to access @opentelemetry/otlp-exporter-base, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```
- move `@opentelemetry/otlp-exporter-base` to be production dependency
- I am working on a separate PR to add knip to this repo (we have it on contrib already) and make the other changes suggested by knip. For this one specifically I confirmed before and after …
=> fix(exporter-logs/trace-otlp-grpc): fix error for missing dependency otlp-exporter-base

scripts/semconv/generate.sh, semantic-conventions/src/experimental_attributes.ts, semantic-conventions/src/experimental_metrics.ts, semantic-conventions/src/stable_attributes.ts, semantic-conventions/src/stable_metrics.ts
This updates the version of weaver used for semconv file generation to 0.12.0.
This includes fixes for trailing whitespace in multi-line comments.
---
Note: if you look at the diff ignoring whitespace, you can see the diff is tiny: https://github.com/open-telemetry/opentelemetry-js/pull/5427/files?w=1
=> chore(semantic-conventions): whitespace-only fixes in comments from weaver 0.12.0

semantic-conventions/CHANGELOG.md
This uses the recent changelog-gen.js script to backfill the changelog for the v1.28.0 release.
---
The rendered changelog looks like this:
https://github.com/trentm/opentelemetry-js/blob/tm-semconv-add-1.28-changelog/semantic-conventions/CHANGELOG.md#1280
=> doc(semantic-conventions): add generated changelog details for the previously released v1.28.0

package.json, scripts/update-changelog.js
This removes some vestigial lerna-changelog config.
It also tweaks the header names for our changelogs. Happy to discuss or revert these names. Mostly the parentheses seemed odd to me.  The wording changes (different words, pluralize) matches more closely the names being used for the changelogs in contrib repo (using release-please's default section names).
=> chore: tweak the section titles for changelogs

README.md
FYI: If you are a javascript-contrib-triagers member, I am listing you
here. If I have made an error in your name or you care to change or not list
your company, please reply on this PR in the next few days. Thanks.
/cc @aabmass, @abhee11, @obecny, @d4nyll, @facostaembrace, @JacksonWeber, @Ugzuzg, @jj22ee, @jpmunz, @kirrg001, @mhennoch, @MikeGoldsmith, @mottibec, @punya, @seemk, @trivikr, @t2t2,
=> doc: list all current javascript-contrib-triagers members

packages/opentelemetry-context-zone-peer-dep/src/util.ts
Fixed this eslint warning:
```
/home/runner/work/opentelemetry-js/opentelemetry-js/packages/opentelemetry-context-zone-peer-dep/src/util.ts
22:39  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
```
Ref #5365
=> refactor(context-zone-peer-dep): fix eslint warnings

experimental/CHANGELOG.md, experimental/packages/sdk-logs/karma.conf.js, experimental/packages/sdk-logs/src/config.ts, experimental/packages/sdk-logs/src/export/BatchLogRecordProcessorBase.ts, experimental/packages/sdk-logs/test/browser/index-webpack.ts, experimental/packages/sdk-logs/test/browser/index-webpack.worker.ts, experimental/packages/sdk-logs/test/common/LoggerProvider.test.ts, experimental/packages/sdk-logs/test/common/export/BatchLogRecordProcessor.test.ts, experimental/packages/sdk-logs/test/node/LoggerProvider.test.ts
Migrates from `getEnv()` to using the new `get*FromEnv()` methods added in #5443. Also inlines the defaults. This drops
"env var configuration" (via `window.OTEL_*` ) in browser environments. As such I had to move some tests to different places to ensure they only run in the correct context.
This breaking change now will enable us to split the env var config code completely in a non-breaking feature release later.
Refs #5217
=> feat(sdk-logs)!: do not read environment variables from window

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation-http/src/http.ts
Migrates away from `getEnv()` to the new functions and inline-defaults introduced in https://github.com/open-telemetry/opentelemetry-js/pull/5443. Since the HTTP instrumentation can only be used on Node.js, everything stays as-is for the end-user. This is a pure refactor.
Refs https://github.com/open-telemetry/opentelemetry-js/issues/5217
=> refactor(instrumentation-http): migrate away from getEnv()

experimental/CHANGELOG.md, experimental/packages/opentelemetry-exporter-metrics-otlp-http/src/OTLPMetricExporterBase.ts
Migrates from `getEnv()` to using the new `get*FromEnv()` methods added in #5443. Also inlines the defaults. This drops
"env var configuration" (via `window.OTEL_*` ) in browser environments.
This breaking change now will enable us to split the env var config code completely in a non-breaking feature release later.
Refs #5217
=> feat(exporter-metrics-otlp-http)!: do not read environment variables from window

CONTRIBUTING.md
The Contributing Guide refers to enforcement of Conventional Commits via commitlint and husky, which is no logner the case as of #2898.
Updating the Contributing Guide to reflect how Conventional Commits are now a recommendation that is not enforced.
Rendered the Markdown and ensured that it looks correct.
=> docs: update Contributing Guide

doc/metrics.md, examples/otlp-exporter-node/metrics.js, packages/sdk-metrics/README.md
Metrics SDK docs are out of date in a few places, this PR aligns them with the state on `main`.
Follows up on #4931
=> docs(sdk-metrics): align documentation with current state

experimental/packages/sampler-jaeger-remote/package.json, package-lock.json, packages/opentelemetry-resources/package.json
- a dev dependency for `@opentelemetry/api` was missing in `@opentelemetry/sampler-jaeger-remote`
- this may cause problems with new API versions
- a dependency to the now unused `@opentelemetry/resources@1.9.0` was still there
- does not cause any problems, but we can remove it since we don't need it anymore
=> deps: clean up dependencies

CHANGELOG.md, packages/opentelemetry-core/src/utils/configuration.ts
Using the `util` module in configuration.ts in opentelemetry-core prevents using sdk-trace-base and other packages in the browser. Removing it and relying on string interpolation, allows using the packages again in the browser.
=> fix(core): avoid using util in configuration.ts for browser compatibility

doc/upgrade-to-2.x.md
Rendered version of the added migration guide section: https://github.com/trentm/opentelemetry-js/blob/tm-doc-sdk2-resource-detector-impl/doc/upgrade-to-2.x.md#-opentelemetryresources-changes-for-implementors-of-resource-detectors
=> doc: add section to SDK 2.x migration guide for implementors of resource detectors

packages/opentelemetry-resources/src/Resource.ts
It's not clear that `Resource` is not intended to be implemented by the end-user. This adds a comment on how to obtain a `Resource`.
refs #5540
=> docs: clarify that Resource is not user-implementable

CHANGELOG.md, experimental/packages/opentelemetry-sdk-node/test/sdk.test.ts, packages/opentelemetry-resources/src/detect-resources.ts
This removes the logResources call which was triggering a warning that asynchronous resources were accessed before being resolved. Alternative to #5545 
---
> From offline discussion, I'd vote for just dropping the `logResources` call.
> 
> - I cannot imagine there is a spec requirement or breaking concern over `diag.verbose()` output.
> - Side note: You commented on the `logResources()` (for a different reason) in the PR where this was added: https://github.com/open-telemetry/opentelemetry-js/pull/3460#discussion_r1040096977
> - There is already a `diag.debug` that dumps the raw Resource:
> 
> ```
> % cd metapackages/auto-instrumentation-node
> % OTEL_LOG_LEVEL=debug node -r ./build/src/register.js test/test-app/app.js
> ...
> ContainerDetector found resource. ResourceImpl {
> …
```
=> Do not log detected resource

experimental/CHANGELOG.md, experimental/packages/opentelemetry-sdk-node/src/sdk.ts
Migrated away from using `process.env` to use the `getStringFromEnv`-function
Fixes #5563
=> refactor: use get*FromEnv() for logging setup

packages/opentelemetry-resources/src/detectors/platform/node/HostDetector.ts, packages/opentelemetry-resources/src/detectors/platform/node/OSDetector.ts, packages/opentelemetry-resources/src/detectors/platform/node/ProcessDetector.ts, packages/opentelemetry-resources/src/detectors/platform/node/ServiceInstanceIdDetector.ts, packages/opentelemetry-resources/src/semconv.ts
Moved from deprecated to constants that are in incubation.
This PR is part of the Kubecon 2025 Contribfest. I is a simple migration of deprecated constants from ‘@opentelemetry/semantic-conventions‘.
Fixes #5576
I moved deprecated constants in ‘@opentelemetry/semantic-conventions‘ that were moved into ‘@opentelemetry/semantic-conventions/incubating‘ by following the TSdoc of the module.
=> refactor(resources): replace deprecated semconv consts

experimental/packages/exporter-logs-otlp-grpc/test/OTLPLogExporter.test.ts, experimental/packages/exporter-logs-otlp-http/test/browser/OTLPLogExporter.test.ts, experimental/packages/exporter-logs-otlp-http/test/node/OTLPLogExporter.test.ts, experimental/packages/exporter-logs-otlp-proto/test/browser/OTLPLogExporter.test.ts, experimental/packages/exporter-logs-otlp-proto/test/node/OTLPLogExporter.test.ts, experimental/packages/opentelemetry-sdk-node/src/sdk.ts, experimental/packages/sdk-logs/src/LoggerProvider.ts, experimental/packages/sdk-logs/src/internal/LoggerProviderSharedState.ts, experimental/packages/sdk-logs/src/types.ts, experimental/packages/sdk-logs/test/common/LogRecord.test.ts, experimental/packages/sdk-logs/test/common/Logger.test.ts, experimental/packages/sdk-logs/test/common/LoggerProvider.test.ts, experimental/packages/sdk-logs/test/common/MultiLogRecordProcessor.test.ts, experimental/packages/sdk-logs/test/common/export/BatchLogRecordProcessor.test.ts, experimental/packages/sdk-logs/test/common/export/ConsoleLogRecordExporter.test.ts, experimental/packages/sdk-logs/test/common/export/InMemoryLogRecordExporter.test.ts, experimental/packages/sdk-logs/test/common/export/SimpleLogRecordProcessor.test.ts, experimental/packages/web-common/test/SessionLogRecordProcessor.test.ts
Fixes #5559
Moved the "logic" from `LoggerProvider#addLogRecordProcessor()` to the `LoggerProviderSharedState`.
=> feat(@opentelemetry/sdk-logs): align LoggerProvider constructor options with Trace and Metrics SDK

scripts/semconv/changelog-gen.js, scripts/semconv/generate.sh, scripts/semconv/templates/registry/stable/docstring.ts.j2, semantic-conventions/CHANGELOG.md, semantic-conventions/src/experimental_attributes.ts, semantic-conventions/src/experimental_metrics.ts
- Also update "scripts/semconv/changelog-gen.js" to support
*undeprecated* exports. This version includes one such case.
=> feat(semantic-conventions): update semantic conventions to v1.31.0

experimental/packages/opentelemetry-sdk-node/src/sdk.ts
Migrate from old process.env to use new get*FromEnv() function in NodeSDK's metrics setup
Part of Contribfest at KubeCon 2025
Fixes #5564
use new get*FromEnv()
=> refactor(opentelemetry-sdk-node): use new get*FromEnv() function in NodeSDK's metrics setup

.github/ISSUE_TEMPLATE/bug_report.yaml, examples/basic-tracer-node/index.js, examples/esm-http-ts/index.ts, examples/grpc-js/tracer.js, examples/http/tracer.js, examples/https/tracer.js, examples/opentelemetry-web/examples/fetch-proto/index.js, examples/opentelemetry-web/examples/fetch/index.js, examples/opentelemetry-web/examples/fetchXhr/index.js, examples/opentelemetry-web/examples/fetchXhrB3/index.js, examples/opentelemetry-web/examples/xml-http-request/index.js, examples/opentelemetry-web/examples/zipkin/index.js, examples/opentracing-shim/shim.js, examples/otlp-exporter-node/metrics.js, examples/otlp-exporter-node/tracing.js, experimental/examples/opencensus-shim/setup.js, experimental/packages/opentelemetry-browser-detector/README.md, packages/opentelemetry-resources/README.md
This will be one of many PRs updating the semconv pkg exports used for
the 'JS package deprecations'. See
https://github.com/open-telemetry/opentelemetry-js/tree/main/semantic-conventions/#deprecations
This PR is limited to READMEs and examples/ so does no impact any
published code.
=> docs: update from deprecated SEMRESATTRS_SERVICE_NAME to ATTR_SERVICE_NAME

CHANGELOG.md, packages/sdk-metrics/test/export/MetricReader.test.ts, packages/sdk-metrics/test/utils.test.ts
Multiple tests were calling `assertRejects()` without awaiting the result. When/if these assertions fail, mocha does not fail the tests due to unhandled rejections.
It's also worth noting that `assertRejects()` might not be needed anymore. There are multiple copies of this function across the codebase, but `assert.rejects()` is in all supported versions of Node. I would like to open a follow up change to migrate to `assert.rejects()` if it's OK with the maintainers.
Fixes N/A
This commit fixes two tests that were not await'ing `assertRejects()` calls.
=> test(sdk-metrics): fix multiple problematic assertRejects() calls

doc/context.md, doc/metrics.md, doc/sdk-registration.md, doc/tracing.md
The new typedoc version generates the docs a bit differently - so the links have changed. This PR fixes the links.
=> docs: fix api doc links

.github/workflows/publish-to-npm.yml
> [!IMPORTANT]
> This PR targets `v1.x` - keeping as draft until we're ready to release 2.x, until then releases from this branch should still target `latest`
To avoid having releases from `v1.x` end up with the `latest` tag automatically, this PR adds specific dist-tag to publishes from the `v1.x` branch.
The dist-tag chosen:
- `sdk-v1.x` to show that the packages are compatible with `v1.x`
- I did not put another `ts4.4` tag as originally planned as lerna errors when using more than one tag.
=> ci: add sdk-v1.x dist-tag when publishing from v1.x 

experimental/CHANGELOG.md, experimental/packages/opentelemetry-sdk-node/src/utils.ts, experimental/packages/opentelemetry-sdk-node/test/utils.test.ts
The baggage propagator is not instantiated when the env var is set.
Fixes #5633
=> fix(sdk-node): instantiate baggage processor when env var is set

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation-http/src/http.ts, experimental/packages/opentelemetry-instrumentation-http/src/utils.ts, experimental/packages/opentelemetry-instrumentation-http/test/functionals/http-metrics.test.ts
This adds [http.response.status_code](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/attributes-registry/http.md) attributes to client requests when opting in to stable semantic conventions.
Fixes #5624
This records the status code that was received in the response when available when requests end.
=> fix(instrumentation-http): stable client metrics response code

renovate.json
This PR is using [renovate constraints](https://docs.renovatebot.com/configuration-options/#constraints) to tell renovate to use `npm@>10.8.0` which I'm hoping will eliminate the license-field churn in `package-lock.json` during renovate updates.
See also: https://github.com/npm/cli/issues/7384
=> chore: add constraint for renovate to use npm@>10.8.0

doc/frequently-asked-questions.md, doc/upgrade-to-2.x.md
Document that Jest v29.4 or higher is required to support submodule imports as used by several packages.
And I just figured out a workaround! Added that, too.
Resolves #5618 and probably #5557 (pending confirmation from the OP there)
=> [docs] Upgrade note with Jest version requirements and workaround for older versions of Jest

CHANGELOG.md, packages/opentelemetry-core/src/baggage/utils.ts, packages/opentelemetry-core/test/common/baggage/utils.test.ts
Not a problem, but the `parseKeyPairsIntoRecord()` function can be simplified a bit.
Fixes N/A
This commit refactors `parseKeyPairsIntoRecord()` to use a single `forEach()` loop instead of a series of loops using `map()`, `filter()`, and `reduce()`.
=> refactor(opentelemetry-core): simplify `parseKeyPairsIntoRecord()`

scripts/semconv/generate.sh, semantic-conventions/CHANGELOG.md, semantic-conventions/src/experimental_attributes.ts, semantic-conventions/src/experimental_metrics.ts, semantic-conventions/src/stable_attributes.ts, semantic-conventions/src/stable_metrics.ts
Summary of semconv changes in the changelog here: https://github.com/open-telemetry/opentelemetry-js/pull/5654/files#diff-9f239f4331d2856552d1cfd71fb5585d24d9ef409c7cbcce2e0a59a76e631278R12
Highlights: DB semantics are stable; also some stabilized `code.*` constants for stacktraces.
=> feat(semantic-conventions): update semantic conventions to v1.33.0

doc/metrics.md, doc/tracing.md
This also updates these doc examples to closer to modern/stable
HTTP and DB semantics. They are just examples though so I wasn't
extremely careful.
Refs: https://github.com/open-telemetry/opentelemetry-js/issues/4896
=> docs: update old/deprecated 'SemanticAttributes' usage

CHANGELOG.md, package-lock.json, packages/opentelemetry-sdk-trace-web/package.json, packages/opentelemetry-sdk-trace-web/src/semconv.ts, packages/opentelemetry-sdk-trace-web/src/utils.ts, packages/opentelemetry-sdk-trace-web/test/WebTracerProvider.test.ts
This also moves the semantic-conventions dep to a devDep, because
it is no longer used in the runtime code.
Refs: #4896
=> refactor(sdk-trace-web): update semconv usage to ATTR_ exports

CHANGELOG.md, packages/sdk-metrics/src/export/PeriodicExportingMetricReader.ts, packages/sdk-metrics/test/export/PeriodicExportingMetricReader.test.ts
See https://github.com/open-telemetry/opentelemetry-js/pull/5621#issuecomment-2867470770
On a quick initial pass after seeing an approval on the PR I thought this was okay, but I think this has the potential to break a lot of users as it's common to specify just the export interval but not the timeout - which would throw with what's on `main` now if the interval is lower than the timeout. I re-checked the spec and it does not give any guidance on this. Quite a few other implementations seem to skip this check entirely too.
Reopens #5550
=> Revert "fix(sdk-metrics): improve PeriodicExportingMetricReader() constructor input validation (#5621)"

.github/workflows/unit-test.yml, experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation-http/test/functionals/http-package.test.ts, experimental/packages/opentelemetry-instrumentation-http/test/functionals/https-package.test.ts
Testing on the latest version of Node.js
Fixes # N/A
Node.js v24 was recently released. This change adds it to the CI. (Adapted from https://github.com/open-telemetry/opentelemetry-js/commit/34a2dd574c521fa970e2c0cd60c852110823c962)
=> test: test Node.js 24 in CI

scripts/semconv/templates/registry/stable/weaver.yaml
This is preferred to exclude_stability, b/c it is expected to be more
resilient with other stability names used for unstable, e.g. 'development',
'rc', 'beta', etc.
This results in the exact same generated files.
=> refactor(semantic-conventions): weaver 0.13.0 supports a 'stable_only' arg to semconv_attributes

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation/src/semconvStability.ts
Change `SemconvStability` export from `const enum` to `enum` to allow single-file transpilation tooling to work with code that uses `SemconvStability`
Refs: #5691
Refs: https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2671#issuecomment-2886789314
=> fix(instrumentation): change `SemconvStability` export from `const enum` to `enum`

scripts/semconv/generate.sh, scripts/semconv/templates/registry/ts-experimental/attributes.ts.j2, scripts/semconv/templates/registry/ts-stable/attributes.ts.j2, semantic-conventions/CHANGELOG.md, semantic-conventions/src/experimental_attributes.ts, semantic-conventions/src/experimental_metrics.ts
This removes the special-casing of NETWORK_TRANSPORT_VALUE_QUIC
which is now marked stable in semconv.
Refs: https://github.com/open-telemetry/opentelemetry-js/pull/5690
=> feat(semantic-conventions): update semantic conventions to v1.34.0

experimental/CHANGELOG.md, experimental/packages/opentelemetry-exporter-metrics-otlp-proto/.eslintrc.js, experimental/packages/opentelemetry-exporter-metrics-otlp-proto/karma.conf.js, experimental/packages/opentelemetry-exporter-metrics-otlp-proto/package.json, experimental/packages/opentelemetry-exporter-metrics-otlp-proto/src/platform/browser/OTLPMetricExporter.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-proto/src/platform/browser/index.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-proto/src/platform/index.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-proto/src/platform/node/OTLPMetricExporter.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-proto/src/platform/node/index.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-proto/test/browser/OTLPMetricExporter.test.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-proto/test/browser/index-webpack.ts, experimental/packages/opentelemetry-exporter-metrics-otlp-proto/test/node/OTLPMetricExporter.test.ts, package-lock.json
Log, Trace support protobuf properly in browser, but Metric crashes because it references `@opentelemetry/otlp-exporter-base/node-http`.
- Meter Exporter supports protobuf in browser
=> feat(exporter-metrics-otlp-proto): Support to protobuf in browser metrics

e2e-tests/package.json
Fixes the following issues with e2e tests: 
1. collector continues running if tests stop
2. tests fail if collector is already running
3. verification happens before collector finishes writing output to disk
4. local collector container may not actually be latest
=> Improve e2e stability

experimental/packages/exporter-logs-otlp-proto/README.md
The markdown table in the `exporter-logs-otlp-proto` README was slightly unformatted. Example screenshot from [npmjs](http://web.archive.org/web/20250525010947/https://www.npmjs.com/package/@opentelemetry/exporter-logs-otlp-proto):
Here's also a before/after of the file:
=> docs(exporter-logs-otlp-proto): Fixup markdown table

CHANGELOG.md, packages/sdk-metrics/src/aggregator/ExponentialHistogram.ts
Fixes: https://github.com/open-telemetry/opentelemetry-js/issues/5755
=> fix(sdk-metrics): remove invalid default value for 'startTime' param to ExponentialHistogramAccumulation

experimental/CHANGELOG.md, experimental/packages/otlp-exporter-base/src/transport/http-transport-utils.ts
As far as I can tell, this code is never called unless the `req.setTimeout()` callback is called before it on Node.js >=18, so it is safe to drop.
=> refactor(otlp-exporter-base): remove pre-Node.js 14 compatibility code

experimental/CHANGELOG.md, experimental/packages/opentelemetry-instrumentation-http/src/http.ts, experimental/packages/opentelemetry-instrumentation-http/test/functionals/http-metrics.test.ts
This reports the `error.type` attribute on HTTP metrics wherever it is already reported on HTTP spans as [required by the spec](https://github.com/open-telemetry/semantic-conventions/blob/4676c009fa6b8f4ed7d2321c991024373e77428e/docs/http/http-metrics.md?plain=1#L111-L126).
Fixes #5627 
Updates the metrics attributes from the `_on***Error` helpers and uses those wherever appropriate.
I added a test for client metrics but couldn't figure out a way to test server metrics since it involves throwing within the server request handler which is an uncaught exception.
=> fix(instrumentation-http): report error.type metrics attribute

experimental/CHANGELOG.md, experimental/packages/opentelemetry-configuration/src/ConfigProvider.ts, experimental/packages/opentelemetry-configuration/src/FileConfigProvider.ts, experimental/packages/opentelemetry-configuration/test/ConfigProvider.test.ts, experimental/packages/opentelemetry-configuration/test/fixtures/kitchen-sink.yaml
Solves #5814 
This PR creates the structure for a FileConfigProvider. In this PR it only checks if the file exists and is a YAML, returning an error otherwise.
Parse of the file will be done on a following PR
=> feat(opentelemetry-configuration): creation of basic FileConfigProvider 

.github/workflows/publish-to-npm.yml
Nothing has happened to us, but with everything that's been happening recently, this PR does a few things to harden our publishing process:
- switches publishing from token-based to OIDC
- I have already updated all packages to disallow token publish, and set up OIDC for all of the packages published from this repo
- makes use of a new `npm-publish-environment` environment, to lock down who can actually publish to npm
- until recently access was more broad, but additonal maintainer approval will now be required for publishing here and in contrib
- requiring the environment and OIDC will also limit a potential blast radius to one repo, we can set up to require more than one maintainer approval before publishing.
- I have moved `npm ci` to run outside of the deploy environment to further …
=> ci: harden npm publish workflow by switching to OIDC

experimental/packages/opentelemetry-instrumentation/package.json, experimental/packages/shim-opencensus/package.json, package-lock.json
A new version of `require-in-the-middle` has been released which bumps the minimum supported Node version to v8.10.0 and allowed us to remove some dependencies. 
Before they looked like this:
And now it's like this:
=> chore(deps): Update `require-in-the-middle` to v8.0.0

.github/workflows/move-to-emeritus.yml
uses `otelbot-js` over the regular `otelbot` as the regular one is not allowed to create any PRs.
Ref: https://github.com/open-telemetry/opentelemetry-js/actions/runs/18096191118
=> ci(move-to-emeritus): use otelbot-js over regular otelbot

CHANGELOG.md, packages/opentelemetry-shim-opentracing/test/Shim.test.ts
These equality assertions can be flaky due to floating point math.
Fixes: https://github.com/open-telemetry/opentelemetry-js/actions/runs/18082260606/job/51447397928?pr=5962
This commit updates the assertions to allow a small threshold.
=> test(shim-opentracing): add comparison thresholds in flaky assertions
