open-telemetry/opentelemetry-js

README.md

Add SIG meeting information to README

---

packages/opentelemetry-types/src/trace/span.ts

Span: Add setAttributes operation

---

packages/opentelemetry-types/src/resources/Resource.ts

Based on https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/resources-api.md#resource-creation

Add Resource Interface

---

packages/opentelemetry-core/package.json

Remove compile:release script

---

CONTRIBUTING.md
README.md
package.json
packages/opentelemetry-core/package.json
packages/opentelemetry-types/README.md
packages/opentelemetry-types/package.json

Continuation of https://github.com/open-telemetry/opentelemetry-js/issues/20

Rename Node to js

---

README.md
packages/opentelemetry-core/README.md
packages/opentelemetry-types/README.md

https://circleci.com/gh/open-telemetry/opentelemetry-js

Add CircleCI build and badge

---

.circleci/config.yml
packages/opentelemetry-core/package.json
packages/opentelemetry-types/src/index.ts
packages/opentelemetry-types/src/trace/span.ts
packages/opentelemetry-types/src/trace/span_context.ts

This PR contains following minor nits:
- Sort imports
- Fix `yarn` commands
- Use caret (`^`) in package.

💄Minor formatting style

---

packages/opentelemetry-types/src/trace/tracer.ts

Continuation of https://github.com/open-telemetry/opentelemetry-js/pull/85

Improve Tracer API docs

---

packages/opentelemetry-core/src/trace/sampler/ProbabilitySampler.ts
packages/opentelemetry-core/test/trace/ProbabilitySampler.test.ts
packages/opentelemetry-types/src/trace/Sampler.ts

Originates from https://github.com/open-telemetry/opentelemetry-js/pull/48#discussion_r300102206

 Add toString method to Sampler API

---

README.md
packages/opentelemetry-types/README.md

Update links in readme

---

packages/opentelemetry-core/test/trace/spancontext-utils.test.ts

Increase code coverage (**~0.26%**).

Add spancontext-utils tests

---

README.md
packages/opentelemetry-basic-tracer/README.md
packages/opentelemetry-core/README.md
packages/opentelemetry-node-tracer/README.md
packages/opentelemetry-types/README.md

Updates https://github.com/open-telemetry/opentelemetry-js/issues/96
1. Add a license badge
2. Fix minor typo
3. Add Gitter chat badge

docs: improve readme

---

packages/opentelemetry-basic-tracer/src/BasicTracer.ts
packages/opentelemetry-basic-tracer/test/BasicTracer.test.ts
packages/opentelemetry-core/src/trace/NoopSpan.ts
packages/opentelemetry-core/src/trace/NoopTracer.ts
packages/opentelemetry-core/test/trace/NoopTracer.test.ts

fix: add exported const of NoopSpan instance

---

packages/opentelemetry-node-tracer/package.json
packages/opentelemetry-node-tracer/src/NodeTracer.ts
packages/opentelemetry-node-tracer/test/NodeTracer.test.ts

feat: node-tracer initial implementation

---

packages/opentelemetry-basic-tracer/src/BasicTracer.ts
packages/opentelemetry-basic-tracer/test/BasicTracer.test.ts

Updates https://github.com/open-telemetry/opentelemetry-js/issues/90

fix(basic-tracer): use recording/real span

---

packages/opentelemetry-plugin-grpc/.npmignore
packages/opentelemetry-plugin-grpc/LICENSE
packages/opentelemetry-plugin-grpc/README.md
packages/opentelemetry-plugin-grpc/package.json
packages/opentelemetry-plugin-grpc/tsconfig.json
packages/opentelemetry-plugin-http/.npmignore
packages/opentelemetry-plugin-http/LICENSE
packages/opentelemetry-plugin-http/README.md
packages/opentelemetry-plugin-http/package.json
packages/opentelemetry-plugin-http/tsconfig.json

chore(packages): add http and grpc skeletons

---

.github/CODEOWNERS

Based on https://github.com/open-telemetry/community/pull/157

docs: add @bg451 as a code owner

---

packages/opentelemetry-exporter-jaeger/.npmignore
packages/opentelemetry-exporter-jaeger/LICENSE
packages/opentelemetry-exporter-jaeger/README.md
packages/opentelemetry-exporter-jaeger/package.json
packages/opentelemetry-exporter-jaeger/src/index.ts
packages/opentelemetry-exporter-jaeger/tsconfig.json
packages/opentelemetry-exporter-zipkin/.npmignore
packages/opentelemetry-exporter-zipkin/LICENSE
packages/opentelemetry-exporter-zipkin/README.md
packages/opentelemetry-exporter-zipkin/package.json
packages/opentelemetry-exporter-zipkin/src/index.ts
packages/opentelemetry-exporter-zipkin/tsconfig.json

chore(packages): add jaeger and zipkin skeletons

---

packages/opentelemetry-basic-tracer/src/export/ExportResult.ts
packages/opentelemetry-basic-tracer/src/export/SpanExporter.ts

Based on specs: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/sdk-exporter.md#exporter-interface
Split from #149 to unblock Exporter work #173 and #174.

feat(sdk): add SpanExporter interface

---

.github/PULL_REQUEST_TEMPLATE.md

Pull request template is missing from below checklist.

chore: add Pull request template

---

packages/opentelemetry-plugin-http2/.npmignore
packages/opentelemetry-plugin-http2/LICENSE
packages/opentelemetry-plugin-http2/README.md
packages/opentelemetry-plugin-http2/package.json
packages/opentelemetry-plugin-http2/src/index.ts
packages/opentelemetry-plugin-http2/tsconfig.json
packages/opentelemetry-plugin-https/.npmignore
packages/opentelemetry-plugin-https/LICENSE
packages/opentelemetry-plugin-https/README.md
packages/opentelemetry-plugin-https/package.json
packages/opentelemetry-plugin-https/src/index.ts
packages/opentelemetry-plugin-https/tsconfig.json
packages/opentelemetry-plugin-mongodb/.npmignore
packages/opentelemetry-plugin-mongodb/LICENSE
packages/opentelemetry-plugin-mongodb/README.md
packages/opentelemetry-plugin-mongodb/package.json
packages/opentelemetry-plugin-mongodb/src/index.ts
packages/opentelemetry-plugin-mongodb/tsconfig.json
packages/opentelemetry-plugin-redis/.npmignore
packages/opentelemetry-plugin-redis/LICENSE
packages/opentelemetry-plugin-redis/README.md
packages/opentelemetry-plugin-redis/package.json
packages/opentelemetry-plugin-redis/src/index.ts
packages/opentelemetry-plugin-redis/tsconfig.json

Creating all at once since i will try to port them from Census to here before this weekend.

chore(plugin): setup https/http2/redis/mongodb plugin packages

---

packages/opentelemetry-basic-tracer/test/BasicTracer.test.ts
packages/opentelemetry-basic-tracer/test/Span.test.ts

- Fixes #162 
- Adds missing coverage to the basic tracer package

chore(basic-tracer): test coverage

---

packages/opentelemetry-basic-tracer/package.json
packages/opentelemetry-basic-tracer/test/BasicTracer.test.ts
packages/opentelemetry-exporter-jaeger/package.json
packages/opentelemetry-exporter-zipkin/package.json
packages/opentelemetry-node-tracer/package.json
packages/opentelemetry-node-tracer/test/NodeTracer.test.ts
packages/opentelemetry-plugin-grpc/package.json
packages/opentelemetry-plugin-http2/package.json
packages/opentelemetry-plugin-https/package.json
packages/opentelemetry-plugin-mongodb/package.json
packages/opentelemetry-plugin-redis/package.json
packages/opentelemetry-scope-async-hooks/package.json
packages/opentelemetry-scope-base/package.json

- Originates from https://github.com/open-telemetry/opentelemetry-js/pull/232#issuecomment-526708493
- This fix will allow loading test files in deeper folders (recursively).
- Based on https://github.com/mochajs/mocha/issues/3115
- Found and fixed broken test case in `NodeTracer`.
- Also, addressed minor nits.

fix: ts-mocha allow recursively loading files

---

packages/opentelemetry-basic-tracer/src/BasicTracer.ts
packages/opentelemetry-basic-tracer/test/BasicTracer.test.ts
packages/opentelemetry-basic-tracer/test/Span.test.ts

fix: set attributes from SpanOptions

---

packages/opentelemetry-exporter-jaeger/README.md
packages/opentelemetry-exporter-jaeger/package.json
packages/opentelemetry-exporter-jaeger/src/index.ts
packages/opentelemetry-exporter-jaeger/src/jaeger.ts
packages/opentelemetry-exporter-jaeger/src/transform.ts
packages/opentelemetry-exporter-jaeger/src/types.ts
packages/opentelemetry-exporter-jaeger/test/jaeger.test.ts
packages/opentelemetry-exporter-jaeger/test/transform.test.ts

- Resolves #173 
TODO [Update 09/09]:
1. ~Buffer spans (batch based on both time and max number).~ Will be handled by `BatchSpanProcessor`.
2. ~Decide what to do with event `attributes`, during transform into Jaeger `Log`.~ Done.
3. ~Decide how to handle `ThriftReference ` type, OT `Link` doesn't have type.~ Partially done.
~But I think this can happen in separate PR. :)~

feat: add Jaeger exporter

---

packages/opentelemetry-exporter-jaeger/package.json

- Add missing main property - entry point to the Jaeger exporter module.

fix(exporter-jaeger): add main property - entry point to the module

---

packages/opentelemetry-basic-tracer/src/export/ExportResult.ts
packages/opentelemetry-basic-tracer/src/export/InMemorySpanExporter.ts
packages/opentelemetry-basic-tracer/test/export/InMemorySpanExporter.test.ts
packages/opentelemetry-exporter-jaeger/src/jaeger.ts

- Based on https://github.com/open-telemetry/opentelemetry-specification/pull/243

fix: rename FailedNoneRetryable -> FailedNotRetryable

---

packages/opentelemetry-exporter-jaeger/README.md

- Update Jaeger exporter's Readme.

chore: update jaeger readme

---

packages/opentelemetry-core/src/common/time.ts
packages/opentelemetry-core/src/platform/browser/performance.ts
packages/opentelemetry-core/src/platform/node/index.ts
packages/opentelemetry-core/src/platform/node/performance.ts
packages/opentelemetry-core/test/common/time.test.ts
packages/opentelemetry-exporter-jaeger/src/transform.ts
packages/opentelemetry-exporter-jaeger/test/jaeger.test.ts
packages/opentelemetry-exporter-jaeger/test/transform.test.ts
packages/opentelemetry-plugin-grpc/test/utils/assertionUtils.ts
packages/opentelemetry-plugin-http/test/functionals/http-enable.test.ts
packages/opentelemetry-types/src/common/Time.ts

- Fix build and correct time in Jaeger exporter.
- Exported Node and Browser specific `performance` constant.

Continuation of #206 

---

examples/node-basic/index.js

- Add node basic tracer example.

chore: add basic tracer example

---

packages/opentelemetry-basic-tracer/src/Span.ts
packages/opentelemetry-basic-tracer/test/Span.test.ts

feat: enforce TraceParams Limits

---

packages/opentelemetry-basic-tracer/test/Span.test.ts
packages/opentelemetry-core/src/common/time.ts
packages/opentelemetry-core/test/common/time.test.ts
packages/opentelemetry-exporter-jaeger/src/transform.ts
packages/opentelemetry-exporter-jaeger/test/transform.test.ts
packages/opentelemetry-plugin-grpc/test/utils/assertionUtils.ts

- Add `hrTimeToMicroseconds` function.
- Address left over comments from https://github.com/open-telemetry/opentelemetry-js/pull/206#discussion_r322303128

feat: add hrTimeToMicroseconds and fix numberToHrtime func

---

packages/opentelemetry-exporter-zipkin/package.json

- Closes #287 
- Add missing main property - entry point to the Zipkin exporter module.

fix(exporter-zipkin): add main property - entry point to the module

---

packages/opentelemetry-metrics/.npmignore
packages/opentelemetry-metrics/LICENSE
packages/opentelemetry-metrics/README.md
packages/opentelemetry-metrics/package.json
packages/opentelemetry-metrics/src/export/index.ts
packages/opentelemetry-metrics/src/index.ts
packages/opentelemetry-metrics/tsconfig.json
packages/opentelemetry-metrics/tslint.json

Create opentelemetry metrics package

---

packages/opentelemetry-plugin-grpc/package.json
packages/opentelemetry-plugin-http/package.json

chore: add codecov script

---

packages/opentelemetry-exporter-zipkin/README.md

- Update zipkin exporter README.

chore: update zipkin exporter README

---

packages/opentelemetry-core/package.json
packages/opentelemetry-exporter-zipkin/package.json
packages/opentelemetry-plugin-http/package.json
packages/opentelemetry-types/package.json

- Update out-of-date dependencies.

chore: update out-of-date dependencies

---

packages/opentelemetry-node-sdk/package.json
packages/opentelemetry-plugin-grpc/package.json
packages/opentelemetry-plugin-http/package.json

chore: remove unused dependencies

---

packages/opentelemetry-shim-opentracing/LICENSE

- closes #307
- reset placeholders in license for consistency

chore: reset placeholders in license

---

packages/opentelemetry-shim-opentracing/package.json

- closes #242
- remove posttest script.

chore(shim-opentracing): remove posttest script

---

packages/opentelemetry-plugin-grpc/package.json

- https://github.com/open-telemetry/opentelemetry-js/issues/321, testing this out to see if master gets fixed. 
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/open-telemetry/opentelemetry-js/322)

fix: adds node-pre-gyp as dev dependency

---

packages/opentelemetry-node-sdk/package.json
packages/opentelemetry-node-sdk/src/instrumentation/PluginLoader.ts
packages/opentelemetry-node-sdk/src/instrumentation/utils.ts
packages/opentelemetry-node-sdk/test/instrumentation/PluginLoader.test.ts
packages/opentelemetry-node-sdk/test/instrumentation/node_modules/@opentelemetry/plugin-http-module/http-module.js
packages/opentelemetry-node-sdk/test/instrumentation/node_modules/@opentelemetry/plugin-http-module/index.js
packages/opentelemetry-node-sdk/test/instrumentation/node_modules/@opentelemetry/plugin-http-module/package.json
packages/opentelemetry-node-sdk/test/instrumentation/utils.test.ts

- closes #311
needed for https://github.com/open-telemetry/opentelemetry-js/issues/245
- remove one test
- add test in order to not reproduce the bug
- modify hook callback in PluginLoader

fix: pluginLoader for core modules

---

packages/opentelemetry-exporter-jaeger/src/jaeger.ts
packages/opentelemetry-exporter-jaeger/src/types.ts
packages/opentelemetry-exporter-jaeger/test/jaeger.test.ts

feat(exporter-jaeger): add forceFlush and timeout options

---

packages/opentelemetry-exporter-prometheus/package.json
packages/opentelemetry-metrics/package.json

fix: make repos private to mask them from alpha

---

README.md
examples/http/README.md
packages/opentelemetry-plugin-http/README.md

chore: update HTTP Readme

---

doc/development-guide.md

chore: add development guide

---

packages/opentelemetry-basic-tracer/package.json
packages/opentelemetry-core/package.json
packages/opentelemetry-exporter-jaeger/package.json
packages/opentelemetry-exporter-zipkin/package.json
packages/opentelemetry-plugin-http/package.json
packages/opentelemetry-plugin-http2/package.json
packages/opentelemetry-plugin-https/package.json
packages/opentelemetry-plugin-mongodb/package.json
packages/opentelemetry-plugin-redis/package.json
packages/opentelemetry-scope-async-hooks/package.json
packages/opentelemetry-scope-base/package.json
packages/opentelemetry-types/package.json

chore: minor nit

---

examples/grpc/package.json
examples/http/package.json
lerna.json

Closes #359 
Add `examples/*` to `lerna.json`.

chore: add examples folder to lerna

---

packages/opentelemetry-node-sdk/README.md

Closes #362 
Extend `node-sdk` documentation with an explanation of auto instrumentation and sample

Extend documentation for node-sdk

---

README.md
packages/opentelemetry-plugin-http/package.json

- Adds a brief project description
- Adds a quickstart section
- Moves the release schedule up and change `unknown` to `tbd`

Extend main README in preparation for Alpha

---

packages/opentelemetry-plugin-http/test/functionals/http-disable.test.ts
packages/opentelemetry-plugin-http/test/functionals/http-enable.test.ts
packages/opentelemetry-plugin-http/test/functionals/utils.test.ts

test(plugin-http): increase coverage

---

packages/opentelemetry-plugin-http/src/http.ts
packages/opentelemetry-plugin-http/src/utils.ts
packages/opentelemetry-plugin-http/test/functionals/http-enable.test.ts

- closes #364
- handle aborted request
- add 2 tests
- fix flaky test
- sets attributes earlier in case of error

feat(plugin-http): handle aborted request

---

examples/http/client.js
examples/http/setup.js
packages/opentelemetry-exporter-jaeger/src/jaeger.ts

- assign correct scope for flush operation.
- Fix HTTP Example with Jaeger exporter.

fix(jaeger): assign correct scope for flush operation

---

packages/opentelemetry-tracer-basic/test/export/BatchSpanProcessor.test.ts

-  Replace temp. `TestExporter` with `InMemorySpanExporter`.

refactor: replace TestExporter with InMemorySpanExporter

---

packages/opentelemetry-plugin-http/src/http.ts
packages/opentelemetry-plugin-http/src/utils.ts
packages/opentelemetry-plugin-http/test/functionals/http-enable.test.ts
packages/opentelemetry-plugin-http/test/functionals/utils.test.ts
packages/opentelemetry-plugin-http/test/utils/assertSpan.ts

refactor(plugin-http): remove utility class container

---

packages/opentelemetry-tracer-basic/test/BasicTracer.test.ts
packages/opentelemetry-tracer-basic/test/Span.test.ts
packages/opentelemetry-tracer-basic/test/export/BatchSpanProcessor.test.ts
packages/opentelemetry-tracer-basic/test/export/SimpleSpanProcessor.test.ts

- Refactor tests
- Remove `TestExporter` and use `InMemorySpanExporter`.

refactor: basic tracer tests

---

packages/opentelemetry-core/package.json
packages/opentelemetry-plugin-grpc/test/grpc.test.ts
packages/opentelemetry-plugin-http/src/utils.ts
packages/opentelemetry-scope-async-hooks/README.md
packages/opentelemetry-scope-base/package.json
packages/opentelemetry-shim-opentracing/README.md
packages/opentelemetry-shim-opentracing/package.json
packages/opentelemetry-shim-opentracing/test/Shim.test.ts
packages/opentelemetry-types/package.json

- Fix minor typos
- Remove unwanted devDependency
- Add `browser` keyword for supported package.

chore: fix typos and remove unwanted devDependency

---

packages/opentelemetry-exporter-jaeger/README.md

docs(exporter-jaeger): fix jaeger version

---

examples/basic-tracer-node/README.md
examples/basic-tracer-node/package.json
packages/opentelemetry-plugin-http/src/enums/AttributeNames.ts
packages/opentelemetry-plugin-postgres/README.md
packages/opentelemetry-tracing/README.md

- closes #427
- fix broken links
- rename link texts

docs: fix broken links

---

packages/opentelemetry-tracing/src/Span.ts
packages/opentelemetry-tracing/src/config.ts
packages/opentelemetry-tracing/test/Span.test.ts
packages/opentelemetry-types/src/trace/span.ts
packages/opentelemetry-types/src/trace/status.ts

- Please see https://github.com/open-telemetry/opentelemetry-specification/issues/21, https://github.com/open-telemetry/opentelemetry-specification/issues/119 and https://github.com/open-telemetry/opentelemetry-js/issues/19 for a detailed explanation.

chore: TODO cleanup

---

examples/basic-tracer-node/package.json
examples/dns/package.json
examples/grpc/package.json
examples/http/package.json
examples/https/package.json
examples/tracer-web/package.json
lerna.json
package.json
packages/opentelemetry-core/package.json
packages/opentelemetry-exporter-jaeger/package.json
packages/opentelemetry-exporter-prometheus/package.json
packages/opentelemetry-exporter-zipkin/package.json
packages/opentelemetry-metrics/package.json
packages/opentelemetry-node/package.json
packages/opentelemetry-plugin-dns/package.json
packages/opentelemetry-plugin-grpc/package.json
packages/opentelemetry-plugin-http/package.json
packages/opentelemetry-plugin-http2/package.json
packages/opentelemetry-plugin-https/package.json
packages/opentelemetry-plugin-mongodb/package.json
packages/opentelemetry-plugin-postgres/package.json
packages/opentelemetry-plugin-redis/package.json
packages/opentelemetry-scope-async-hooks/package.json
packages/opentelemetry-shim-opentracing/package.json
packages/opentelemetry-tracing/package.json
packages/opentelemetry-web/package.json

- Post release version update.

chore: post release update examples, README

---

packages/opentelemetry-tracing/test/export/BatchSpanProcessor.test.ts

The build fails randomly from time to time for example here
https://circleci.com/gh/open-telemetry/opentelemetry-js/7125?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

chore: fixing flaky test for batch span processor

---

.circleci/config.yml

- Updates #481 
- Merge Lint and Docs jobs to improve (faster) CircleCI build.

chore(CircleCI): merge lint and docs

---

README.md

I haven't been following this project due to other commitments.

Remove yurishkuro as approver

---

packages/opentelemetry-core/test/context/B3Format.test.ts
packages/opentelemetry-exporter-prometheus/src/export/types.ts

- better comments
- fixed two spoted misspelling in comments

fix: typos in comments

---

.github/CODEOWNERS
README.md

As my responsibilities have changed and @dyladan is doing a great job in this SIG, I am nominating him to take over maintainership from me.
@dyladan 
opentelemetry-js
- Make and approve technical design decisions for the subproject.
- Set technical direction and priorities for the subproject.
- Define milestones and releases.
- Mentor and guide approvers, reviewers, and contributors to the subproject.
- Escalate reviewer and maintainer workflow concerns (i.e. responsiveness, availability, and general contributor community health) to the TC.
- Ensure continued health of subproject:
- Adequate test coverage to confidently release
- Tests are passing reliably (i.e. not flaky) and are fixed when they fail
- Ensure a healthy process for discussion and decision making is in place.
- Work with …

Maintainers: Add dyladan, remove danielkhan

---

CHANGELOG.md
packages/opentelemetry-plugin-dns/package.json

- Update CHANGELOG
- Add missing prepare script to compile dns plugin.

chore: post release

---

CHANGELOG.md

- Post Release: update CHANGELOG.md

Post Release: update CHANGELOG.md

---

README.md

- Missing information in main readme about `exporter-collector`

chore: adding missing information about exporter-collector

---

README.md

- Adding information to readme about user interaction plugin

chore: adding information to main readme about user interaction plugin

---

packages/opentelemetry-api/README.md

chore: fix npm img for api package

---

packages/opentelemetry-resources/src/version.ts

missing autogenerated file `version.ts`

chore: leftovers from merge

---

packages/opentelemetry-exporter-prometheus/README.md

- Broken badges: <img width="940" alt="Screen Shot 2020-03-02 at 4 09 57 PM" src="https://user-images.githubusercontent.com/6525361/75729954-4b88ca00-5ca0-11ea-80c3-220ad5d8c091.png">

chore(Prometheus): fix broken badges

---

README.md
packages/opentelemetry-plugin-mysql/src/mysql.ts

Do not multiwrap pool queries

---

packages/opentelemetry-api/src/metrics/NoopMeter.ts

chore: remove getDefaultBound and setCallback from NoopMetric

---

README.md

Screenshot:
Inspired by OpenTelemetry-Collector README.
Feel free to give thumps-down, if you prefer previous version :)

chore: update README top section

---

packages/opentelemetry-plugin-redis/src/enums.ts

- the URL in the `enums.ts` file of the redis plug in was out of date
- Updated the URL to https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/data-database.md

chore: update reference URL in enums.ts

---

packages/opentelemetry-plugin-ioredis/src/enums.ts
packages/opentelemetry-plugin-mysql/src/enums.ts
packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg-pool/src/enums.ts
packages/opentelemetry-plugin-postgres/opentelemetry-plugin-pg/src/enums.ts

Updating the old links

---

packages/opentelemetry-exporter-prometheus/src/prometheus.ts
packages/opentelemetry-exporter-prometheus/test/prometheus.test.ts

chore: adding timestamp for prometheus metric Counter

---

packages/opentelemetry-api/README.md

Adding missing semicolon

---

packages/opentelemetry-exporter-zipkin/package.json
packages/opentelemetry-plugin-http/package.json
packages/opentelemetry-plugin-https/package.json

Removing @types/nock from all package.json files

---

README.md

- OpenTelemetry registry: One place to find all the compatible exporters.

Add link to OpenTelemetry registry for compatible exporters

---

packages/opentelemetry-node/src/instrumentation/PluginLoader.ts

- Fix minor logger typo in plugin loader

fix: pluginloader typo

---

packages/opentelemetry-tracing/src/types.ts

- Small typo in the documentation

Fix typo in opentelemetry-tracing types.js

---

packages/opentelemetry-exporter-prometheus/test/prometheus.test.ts

chore: fix build on latest typings

---

.github/CODEOWNERS
README.md

**Requirements**
-----------------------
- Active >1mo
-  add to CODEOWNERS (done in this pull)
-  Add to README.md (done in this pull)
-  Maintainer nomination
- @mayurkale22  ✔️
- @dyladan  ✔️
-  Add to @open-telemetry/javascript-approvers

Add @mwear as an approver

---

examples/basic-tracer-node/index.js

Fix:Spelling Mistake

---

packages/opentelemetry-exporter-collector/src/transform.ts
packages/opentelemetry-exporter-collector/src/types.ts

-fix:spelling mistakes
-Change COLLETOR_SPAN_KIND_MAPPING to COLLECTOR_SPAN_KIND_MAPPING

Fix:Spelling Mistakes

---

packages/opentelemetry-resources/README.md

chore: add opentelemetry-resources readme

---

packages/opentelemetry-plugin-http/package.json

Originates from https://github.com/open-telemetry/opentelemetry-js/pull/1164#discussion_r437733799

chore(plugin-http): remove unused eslint

---

examples/grpc/helloworld_pb.js

chore: remove double blank lines

---

doc/plugin-guide.md

- Broken link from issue #1268 
- Updated the link to the BasePlugin

Fixed broken link to BasePlugin

---

packages/opentelemetry-metrics/src/Meter.ts

- Removed one unnecessary `new Promise` operation.

refactor: remove unnecessary new Promise operation

---

renovate.json

chore: attempt 2 to fix renovate config

---

getting-started/ts-example/README.md

I noticed some type errors, so fixed those along with a variable name. Also formatted the examples.

docs: update ts-example types and formatting

---

packages/opentelemetry-tracing/src/Span.ts
packages/opentelemetry-tracing/test/Span.test.ts

feat: isRecording return false if span is ended #1633

---

packages/opentelemetry-instrumentation-xml-http-request/src/xhr.ts
packages/opentelemetry-web/src/utils.ts

Fix broken lint build step

---

packages/opentelemetry-exporter-collector/README.md

- Readme typo
- fix `MetricProvider` to `MeterProvider`

docs: fix readme MetricProvider -> MeterProvider

---

CONTRIBUTING.md

chore: make explicit that approvers may merge PRs

---

README.md

Corrects the upgrade guidelines version number for the readme

fix: update readme upgrade guidelines version setting

---

packages/opentelemetry-resource-detector-aws/README.md

- Improves the README file for the `aws-detector`-package 
Adds an explanation how you use the aws detectors

doc: add usage example to aws detector

---

packages/opentelemetry-exporter-collector/README.md

- Small doc fix to update an example which tripped me up earlier
- Update config options to those introduced in https://github.com/open-telemetry/opentelemetry-js/commit/9f965b0c749108df00bbe44eeab84d79b04bb0a4

docs - update BatchSpanProcessor example config

---

packages/opentelemetry-node/README.md

fix docs typo

---

packages/opentelemetry-sdk-node/src/sdk.ts

- This PR fixes lint warnings in `sdk-node` package.

chore(sdk-node): fix lint warnings

---

CHANGELOG.md
experimental/backwards-compatability/node10/package.json
experimental/backwards-compatability/node12/package.json
experimental/backwards-compatability/node8/package.json
integration-tests/propagation-validation-server/package.json
lerna.json
packages/opentelemetry-context-async-hooks/package.json
packages/opentelemetry-context-zone-peer-dep/package.json
packages/opentelemetry-context-zone/package.json
packages/opentelemetry-core/package.json
packages/opentelemetry-exporter-jaeger/package.json
packages/opentelemetry-exporter-zipkin/package.json
packages/opentelemetry-propagator-b3/package.json
packages/opentelemetry-propagator-jaeger/package.json
packages/opentelemetry-resources/package.json
packages/opentelemetry-sdk-trace-base/package.json
packages/opentelemetry-sdk-trace-node/package.json
packages/opentelemetry-sdk-trace-web/package.json
packages/opentelemetry-semantic-conventions/package.json
packages/opentelemetry-shim-opentracing/package.json
packages/template/package.json

This is a precursor to the 1.0 release. It contains all of the large changes which are expected to be in the 1.0 release. If it goes well, the 1.0 release will soon follow it.

chore: v0.26.0 proposal

---

experimental/packages/opentelemetry-sdk-node/src/sdk.ts

Signed-off-by: rickyes <0x19951125@gmail.com>
Remove redundant judgments for `metricExporter`.

refactor(opentelemetry-sdk-node): remove redundant judgments for metric

---

package.json

chore: fix nojekyll in docs command

---

package.json
tsconfig.json

Typedoc updated to properly support multi-package repositories and the configuration needs to be changed to reflect that.

docs: update typedoc config

---

packages/opentelemetry-context-zone/README.md

Just updating `provider` to match defined `const providerWithZone`.

Update example in ContextZone README.md

---

CHANGELOG.md
api/src/metrics/Metric.ts

Fixes https://github.com/open-telemetry/opentelemetry-js/issues/3391

docs(api): fix counter negative value wording

---

api/CHANGELOG.md
api/src/index.ts

Related to https://github.com/open-telemetry/opentelemetry-js/pull/3533#discussion_r1069470064

fix(metrics): export MetricsAPI type

---

api/CHANGELOG.md

Accidentally merged a broken link

Fix changelog link

---

README.md

Welcome @pichlermarc to maintainers. Thanks for the work you've done and let's keep it going

Add pichlermarc to maintainers

---

CHANGELOG.md
README.md
renovate.json

Moving to emeriti as i've not be active since november and i don't think i will be more in the future

chore: move vmarchaud to emeriti

---

experimental/packages/shim-opencensus/package.json
experimental/packages/shim-opencensus/src/ShimSpan.ts
experimental/packages/shim-opencensus/src/ShimTracer.ts
experimental/packages/shim-opencensus/src/index.ts
experimental/packages/shim-opencensus/test/ShimSpan.test.ts
experimental/packages/shim-opencensus/test/ShimTracer.test.ts
experimental/packages/shim-opencensus/test/otel-sandwich.test.ts
experimental/packages/shim-opencensus/test/util.ts
experimental/packages/shim-opencensus/tsconfig.json

Part of https://github.com/open-telemetry/opentelemetry-js/issues/3749 [3 of 5]. Final state of the series of PRs: https://github.com/open-telemetry/opentelemetry-js/pull/3778
Add `ShimTracer` and `ShimSpan` which implement OpenCensus interfaces and bridge to a wrapped OpenTelemetry impl. Added a bunch of tests as well.
The next PR will add a require-in-the-middle hook and register script so users can add in the bridge without modifying OC instrumentation.
- Added a bunch of test cases for each new class

feat(opencensus-shim) add ShimTracer and ShimSpan implementations

---

README.md

Adding @pkanal to the approvers list in recognition of her ongoing work in OpenTelemetry JS.

Add Purvi to approvers

---

tsconfig.json

Added `experimental/packages/shim-opencensus` to `tsconfig.json`

fix: missing `entryPoints` in tsconfig.json

---

README.md

Update my personal info in the README

chore: update blumamir employee name in the README

---

.github/workflows/unit-test.yml

fix(ci): pin nx to 15.9.6 for Node.js v14

---

scripts/generate-protos.js

[next] Execute binaries from root node modules

---

README.md

Getting started link pointed to 404
Updates getting started link

docs: Update getting started link in README

---

examples/README.md

fix a wrong internal link in examples readme

---

experimental/packages/opentelemetry-sdk-node/LICENSE
experimental/packages/otlp-exporter-base/LICENSE
packages/opentelemetry-resources/LICENSE
packages/opentelemetry-semantic-conventions/LICENSE
packages/propagator-aws-xray/LICENSE

See https://github.com/open-telemetry/community/issues/2056 for more details
not applicable
- [n/a] Followed the style guidelines of this project
- [n/a] Unit tests have been added
- [n/a] Documentation has been updated

fix: revert modifications to Apache license

---

README.md

doc: update legendecas affiliation

---

README.md

In recognition of his great work and valuable insights, I propose to add @david-luna to the list of JS approvers. :slightly_smiling_face:

chore: add @david-luna to approvers

---

package-lock.json

#4816 made a change to the package.json but didn't update the package lock

Sync package-lock.json

---

packages/opentelemetry-sdk-trace-base/test/common/export/InMemorySpanExporter.test.ts

In the initial implementation, the reset function of InMemorySpanExporter was not directly tested because it was consistently used in the afterEach setup of tests. This design made a standalone test unnecessary at the time of its addition ([commit c8a37be](https://github.com/open-telemetry/opentelemetry-js/commit/c8a37beebaa362225fb52df141247dea4c90f9dd#diff-a96b8cb364904b6cfd28636122f51764e03068778962eaffcd77bb8ede07967e)).
However, as of [commit b884eec](https://github.com/open-telemetry/opentelemetry-js/commit/b884eeca2e4cd6ff544ea44b8f7e4bd4027ceed0), the reset function was removed from the afterEach setup, leaving it untested directly. This PR addresses this gap by adding a dedicated test to ensure reset functionality works as intended.
Added a unit test specifically for the reset …

add reset function test for InMemorySpanExporter

---

README.md

Compatible versions are not automatically updated in `README.md`. This PR adds the latest few there.

docs: document compatible versions

---

package-lock.json
package.json

Update prettier to the latest version
No one asked for this, I ran into a small issue. (It was small enough that after all of this I forgot what it was, sorry.) Upgrading fixed the issue, and didn't require any changes, so here is the PR.
* Upgrade prettier
* `npm install`
* `npm run lint:fix`/`npm run lint` (no changes)
* `npm run lint:fix`/`npm run lint` (no changes)

chore: update prettier to 3.4.2

---

README.md

post-release ceremony on the v1.x branch

chore: updated v1.x supported versions

---

.github/workflows/survey-on-merged-pr.yml

Fix the repo on the PR merged survey workflow to point to the correct one

chore: fix repo parameter

---

.github/ISSUE_TEMPLATE/bug_report.yaml
examples/basic-tracer-node/index.js
examples/esm-http-ts/index.ts
examples/grpc-js/tracer.js
examples/http/tracer.js
examples/https/tracer.js
examples/opentelemetry-web/examples/fetch-proto/index.js
examples/opentelemetry-web/examples/fetch/index.js
examples/opentelemetry-web/examples/fetchXhr/index.js
examples/opentelemetry-web/examples/fetchXhrB3/index.js
examples/opentelemetry-web/examples/xml-http-request/index.js
examples/opentelemetry-web/examples/zipkin/index.js
examples/opentracing-shim/shim.js
examples/otlp-exporter-node/metrics.js
examples/otlp-exporter-node/tracing.js
experimental/examples/opencensus-shim/setup.js
experimental/packages/exporter-logs-otlp-proto/README.md

Resources docs are out of date in a few places, this PR aligns them with the state on `main`.

docs(resources): align documentation with current state

---

README.md

`SEMRESATTRS_SERVICE_NAME` has been [deprecated](https://github.com/open-telemetry/opentelemetry-js/blob/7fde94081ed141c7d61db269b77d5765887a9665/semantic-conventions/src/resource/SemanticResourceAttributes.ts#L654) in `@opentelemetry/semantic-conventions`.
Update `SEMRESATTRS_SERVICE_NAME` to `ATTR_SERVICE_NAME` in readme.
Not test is needed.

docs: use ATTR_SERVICE_NAME in readme

---

CHANGELOG.md
packages/opentelemetry-resources/src/ResourceImpl.ts
packages/opentelemetry-resources/test/Resource.test.ts
packages/opentelemetry-resources/test/detect-resources.test.ts

Guard async attributes

---

experimental/packages/web-common/README.md

The npm links point to the wrong package

fix: npm links

---

experimental/packages/opentelemetry-exporter-metrics-otlp-grpc/test/OTLPMetricExporter.test.ts
experimental/packages/opentelemetry-exporter-metrics-otlp-http/test/browser/OTLPMetricExporter.test.ts
experimental/packages/opentelemetry-exporter-metrics-otlp-http/test/node/OTLPMetricExporter.test.ts
experimental/packages/opentelemetry-exporter-metrics-otlp-proto/test/OTLPMetricExporter.test.ts

Resolves open-telemetry/opentelemetry-js#5577

fix(exporter-oltp-metrics-*): Remove forceFlush

---

packages/opentelemetry-sdk-trace-web/test/NodeGlobalsFoolProofing.test.ts
packages/opentelemetry-sdk-trace-web/test/StackContextManager.test.ts
packages/opentelemetry-sdk-trace-web/test/WebTracerProvider.test.ts
packages/opentelemetry-sdk-trace-web/test/registration.test.ts
packages/opentelemetry-sdk-trace-web/test/utils.test.ts
packages/opentelemetry-sdk-trace-web/test/window/utils.test.ts

Changelog not updated since only tests are changed.
Resolves open-telemetry/opentelemetry-js#5571

test(@opentelemetry/sdk-trace-web): refactor tests to allow use of mocha context

---

api/test/common/api/api.test.ts
api/test/common/baggage/Baggage.test.ts
api/test/common/context/NoopContextManager.test.ts
api/test/common/diag/ComponentLogger.test.ts
api/test/common/diag/consoleLogger.test.ts
api/test/common/diag/logLevel.test.ts
api/test/common/diag/logger.test.ts
api/test/common/experimental/trace/SugaredTracer.test.ts
api/test/common/internal/global.test.ts
api/test/common/internal/semver.test.ts
api/test/common/metrics/Metric.test.ts
api/test/common/noop-implementations/noop-meter.test.ts
api/test/common/noop-implementations/noop-span.test.ts
api/test/common/noop-implementations/noop-tracer-provider.test.ts
api/test/common/noop-implementations/noop-tracer.test.ts
api/test/common/proxy-implementations/proxy-tracer.test.ts
api/test/common/trace/spancontext-utils.test.ts
api/test/common/trace/tracestate-validators.test.ts
api/test/common/trace/tracestate.test.ts

Resolves open-telemetry/opentelemetry-js#5570

test(@opentelemetry/api): refactor tests to allow use of mocha context

---

packages/opentelemetry-sdk-trace-node/test/NodeTracerProvider.test.ts
packages/opentelemetry-sdk-trace-node/test/registration.test.ts

Changelog not updated since only tests are changed.
Resolves open-telemetry/opentelemetry-js#5573

test(@opentelemetry/sdk-trace-node): refactor tests to allow use of mocha context

---

examples/otlp-exporter-node/package.json
examples/otlp-exporter-node/tracing.js

Fixes #5569
Fix the node tracer provider function in otlp exporter node example

fix(examples): use correct node tracer provider function

---

experimental/packages/opentelemetry-instrumentation/test/common/Instrumentation.test.ts
experimental/packages/opentelemetry-instrumentation/test/common/autoLoader.test.ts
experimental/packages/opentelemetry-instrumentation/test/common/semver.test.ts
experimental/packages/opentelemetry-instrumentation/test/common/utils.test.ts
experimental/packages/opentelemetry-instrumentation/test/node/InstrumentationBase.test.ts
experimental/packages/opentelemetry-instrumentation/test/node/InstrumentationNodeModuleFile.test.ts
experimental/packages/opentelemetry-instrumentation/test/node/ModuleNameTrie.test.ts
experimental/packages/opentelemetry-instrumentation/test/node/RequireInTheMiddleSingleton.test.ts

Fixes #5572
Change tests to allow use of mocha context

refactor(instrumentation): change tests to allow use of mocha context

---

experimental/CHANGELOG.md
experimental/packages/opentelemetry-sdk-node/src/sdk.ts
experimental/packages/opentelemetry-sdk-node/src/utils.ts

Update node SDK to use env var util. This was an issue created for KubeCon EU contribfest.
Fixes #5565

refactor(sdk-node): update node sdk to use env var util

---

README.md

v2.0.0 has been released, so I don't think we should keep the warning around.

fix(docs): remove WIP warning on the README

---

experimental/CHANGELOG.md
experimental/packages/opentelemetry-instrumentation/src/index.ts
experimental/packages/opentelemetry-instrumentation/src/semconvStability.ts
experimental/packages/opentelemetry-instrumentation/test/common/semconvStability.test.ts

Refs: https://github.com/open-telemetry/opentelemetry-js/issues/5646
Refs: https://github.com/open-telemetry/opentelemetry-js/issues/5658

feat(instrumentation): New utilities for semconv stability migration for instrumentations that produce 'http' and 'db' telemetry.

---

CHANGELOG.md
packages/opentelemetry-resources/src/detectors/EnvDetector.ts
packages/opentelemetry-resources/src/semconv.ts
packages/opentelemetry-resources/test/Resource.test.ts
packages/opentelemetry-resources/test/detectors/node/HostDetector.test.ts
packages/opentelemetry-resources/test/detectors/node/OSDetector.test.ts
packages/opentelemetry-resources/test/resource-assertions.test.ts
packages/opentelemetry-resources/test/util/resource-assertions.ts
packages/opentelemetry-resources/test/util/sample-detector.ts

Refs: https://github.com/open-telemetry/opentelemetry-js/issues/4896

refactor(resources): update semconv usage to ATTR_ exports

---

packages/opentelemetry-exporter-zipkin/src/zipkin.ts
packages/opentelemetry-exporter-zipkin/test/common/transform.test.ts
packages/opentelemetry-exporter-zipkin/test/node/zipkin.test.ts

refactor(exporter-zipkin): update semconv usage to ATTR_ exports

---

packages/opentelemetry-shim-opentracing/src/shim.ts
packages/opentelemetry-shim-opentracing/test/Shim.test.ts

refactor(shim-opentracing): update semconv usage to ATTR_ exports

---

experimental/packages/opentelemetry-exporter-prometheus/test/util.ts

refactor(exporter-prometheus): update semconv usage to ATTR_ exports

---

packages/opentelemetry-sdk-trace-node/test/NodeTracerProvider.test.ts

refactor(sdk-trace-node): update semconv usage to ATTR_ exports

---

experimental/CHANGELOG.md
experimental/packages/opentelemetry-sdk-node/test/sdk.test.ts
experimental/packages/opentelemetry-sdk-node/test/semconv.ts
experimental/packages/opentelemetry-sdk-node/test/util/resource-assertions.ts

This also removes a number of exports from
test/util/resource-assertions.ts that were unused.
Refs: #4896

refactor(sdk-node): update semconv usage to ATTR_ exports

---

CHANGELOG.md
packages/opentelemetry-sdk-trace-base/src/Span.ts
packages/opentelemetry-sdk-trace-base/test/common/Span.test.ts

refactor(sdk-trace-base): update semconv usage to ATTR_ exports

---

experimental/packages/opentelemetry-instrumentation-http/src/types.ts

Fixes doc link pointing to limbo
Change link to correctly point to the documentation in the repository
Manually clicked the link

chore(opentelemetry-instrumentation-http): Fix link to docs

---

.github/workflows/codeql-analysis.yml

Related to https://github.com/open-telemetry/sig-security/issues/148#issuecomment-3051569200.
cc @trask

Ensure correct CodeQL workflow permissions

---

.github/workflows/move-to-emeritus.yml

Towards https://github.com/open-telemetry/community/issues/2863
Similar to #5920

More otelbot

---

examples/basic-tracer-node/docker/ot/collector-config.yaml
examples/basic-tracer-node/docker/ot/docker-compose.yaml
examples/opentelemetry-web/docker/collector-config.yaml
examples/otlp-exporter-node/docker/collector-config.yaml

remove processors from config files as requested in #5922 
Fixes #5922 
removed processors from YAML configs, moved to exporters
N/A

chore(examples): remove processors

---

.github/workflows/create-or-update-release-pr.yml
.github/workflows/move-to-emeritus.yml
package.json

The tokens were not correctly supplied everywhere, so the workflows are failing right now. The problem with `.github/workflows/move-to-emeritus.yml` was introduced by my PR #5898, the problem with the release PR was introduced by #5920.

ci: supply correct tokens to workflow steps

---

.github/workflows/move-to-emeritus.yml

In order to push, we also need to checkout using the otelbot-js token.
Ref #5943 
Ref https://github.com/open-telemetry/opentelemetry-js/actions/runs/18135442116

ci(move-to-emeritus): check out using otelbot-js token
